MLIR: lib/Dialect/Arithmetic/Transforms/ExpandOps.cpp File Reference
ExpandOps.cpp File Reference
#include "PassDetail.h"
#include "mlir/Dialect/Arithmetic/IR/Arithmetic.h"
#include "mlir/Dialect/Arithmetic/Transforms/Passes.h"
#include "mlir/Dialect/StandardOps/IR/Ops.h"
#include "mlir/IR/TypeUtilities.h"
#include "mlir/Transforms/DialectConversion.h"
Functions
static Value createConst (Location loc, Type type, int value, PatternRewriter &rewriter)
Create an integer or index constant.
Function Documentation
createConst()
static Value createConst (Location loc, Type type, int value, PatternRewriter & rewriter) static
Create an integer or index constant.
Definition at line 19 of file ExpandOps.cpp.
References mlir::compare(), mlir::OpBuilder::create(), mlir::Builder::getIntegerAttr(), mlir::Value::getType(), mlir::OpRewritePattern< SourceOp >::OpRewritePattern(), mlir::RewriterBase::replaceOpWithNewOp(), and mlir::success().