MLIR: lib/Dialect/Bufferization/Transforms/BufferDeallocation.cpp File Reference
BufferDeallocation.cpp File Reference
#include "PassDetail.h"
#include "mlir/Dialect/Bufferization/IR/AllocationOpInterface.h"
#include "mlir/Dialect/Bufferization/IR/Bufferization.h"
#include "mlir/Dialect/Bufferization/Transforms/BufferUtils.h"
#include "mlir/Dialect/Bufferization/Transforms/Passes.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "llvm/ADT/SetOperations.h"
Functions
static LogicalResult walkReturnOperations (Region *region, llvm::function_ref< LogicalResult(Operation *)> func)
Walks over all immediate return-like terminators in the given region.
static bool validateSupportedControlFlow (Region &region)
Checks if all operations in a given region that have at least one attached region implement the RegionBranchOpInterface.
Function Documentation
validateSupportedControlFlow()
static bool validateSupportedControlFlow (Region & region) static
Checks if all operations in a given region that have at least one attached region implement the RegionBranchOpInterface.
This is not required in edge cases, where we have a single attached region and the parent operation has no results.
Definition at line 84 of file BufferDeallocation.cpp.
References mlir::DialectRegistry::addOpInterface(), mlir::OpBuilder::create(), mlir::Operation::emitError(), mlir::Region::empty(), mlir::failed(), mlir::failure(), mlir::Region::front(), mlir::BlockArgument::getArgNumber(), mlir::Operation::getBlock(), mlir::Value::getDefiningOp(), mlir::LivenessBlockInfo::getEndOperation(), mlir::Value::getLoc(), mlir::getMutableRegionBranchSuccessorOperands(), mlir::Operation::getOperands(), mlir::Block::getOperations(), mlir::BlockArgument::getOwner(), mlir::Block::getParent(), mlir::Value::getParentBlock(), mlir::Region::getParentOp(), mlir::Region::getRegionNumber(), mlir::Operation::getRegions(), mlir::Operation::getResults(), mlir::RegionSuccessor::getSuccessor(), mlir::Operation::getSuccessor(), mlir::RegionSuccessor::getSuccessorInputs(), mlir::Block::getSuccessors(), mlir::DialectRegistry::insert(), mlir::Value::isa(), mlir::Operation::isBeforeInBlock(), mlir::Operation::moveAfter(), mlir::bufferization::None, mlir::Block::pred_begin(), mlir::Block::pred_end(), mlir::Operation::setOperand(), mlir::succeeded(), mlir::success(), value, mlir::Region::walk(), and walkReturnOperations().
walkReturnOperations()
static LogicalResult walkReturnOperations (Region * region, llvm::function_ref< LogicalResult(Operation *)> func) static
Walks over all immediate return-like terminators in the given region.
Definition at line 67 of file BufferDeallocation.cpp.
References mlir::failed(), mlir::failure(), mlir::isRegionReturnLike(), and mlir::success().
Referenced by validateSupportedControlFlow().