MLIR: include/mlir/CAPI/Diagnostics.h File Reference
Diagnostics.h File Reference
#include "mlir-c/Diagnostics.h"
#include <cassert>
Namespaces
mlir
Include the generated interface declarations.
Functions
mlir::Diagnostic & unwrap (MlirDiagnostic diagnostic)
MlirDiagnostic wrap (mlir::Diagnostic &diagnostic)
Function Documentation
unwrap()
mlir::Diagnostic& unwrap (MlirDiagnostic diagnostic) inline
Definition at line 19 of file Diagnostics.h.
References MlirDiagnostic::ptr.
Referenced by llvm::GraphTraits< const mlir::CallGraphNode * >::child_begin(), llvm::GraphTraits< const mlir::CallGraphNode * >::child_end(), getDenseAttribute(), mlirAffineBinaryOpExprGetLHS(), mlirAffineBinaryOpExprGetRHS(), mlirAffineConstantExprGet(), mlirAffineConstantExprGetValue(), mlirAffineDimExprGet(), mlirAffineDimExprGetPosition(), mlirAffineExprCompose(), mlirAffineExprDump(), mlirAffineExprGetContext(), mlirAffineExprGetLargestKnownDivisor(), mlirAffineExprIsAAdd(), mlirAffineExprIsABinary(), mlirAffineExprIsACeilDiv(), mlirAffineExprIsAConstant(), mlirAffineExprIsADim(), mlirAffineExprIsAFloorDiv(), mlirAffineExprIsAMod(), mlirAffineExprIsAMul(), mlirAffineExprIsASymbol(), mlirAffineExprIsFunctionOfDim(), mlirAffineExprIsMultipleOf(), mlirAffineExprIsPureAffine(), mlirAffineExprIsSymbolicOrConstant(), mlirAffineExprPrint(), mlirAffineMapAttrGet(), mlirAffineMapAttrGetValue(), mlirAffineMapConstantGet(), mlirAffineMapDump(), mlirAffineMapEmptyGet(), mlirAffineMapEqual(), mlirAffineMapGet(), mlirAffineMapGetContext(), mlirAffineMapGetMajorSubMap(), mlirAffineMapGetMinorSubMap(), mlirAffineMapGetNumDims(), mlirAffineMapGetNumInputs(), mlirAffineMapGetNumResults(), mlirAffineMapGetNumSymbols(), mlirAffineMapGetResult(), mlirAffineMapGetSingleConstantResult(), mlirAffineMapGetSubMap(), mlirAffineMapIsEmpty(), mlirAffineMapIsIdentity(), mlirAffineMapIsMinorIdentity(), mlirAffineMapIsPermutation(), mlirAffineMapIsProjectedPermutation(), mlirAffineMapIsSingleConstant(), mlirAffineMapMinorIdentityGet(), mlirAffineMapMultiDimIdentityGet(), mlirAffineMapPermutationGet(), mlirAffineMapPrint(), mlirAffineMapReplace(), mlirAffineMapZeroResultGet(), mlirAffineSymbolExprGet(), mlirAffineSymbolExprGetPosition(), mlirAnyQuantizedTypeGet(), mlirArrayAttrGet(), mlirArrayAttrGetElement(), mlirArrayAttrGetNumElements(), mlirAttributeDump(), mlirAttributeEqual(), mlirAttributeGetContext(), mlirAttributeGetType(), mlirAttributeGetTypeID(), mlirAttributeIsAAffineMap(), mlirAttributeIsAArray(), mlirAttributeIsABool(), mlirAttributeIsADenseElements(), mlirAttributeIsADenseFPElements(), mlirAttributeIsADenseIntElements(), mlirAttributeIsADictionary(), mlirAttributeIsAElements(), mlirAttributeIsAFlatSymbolRef(), mlirAttributeIsAFloat(), mlirAttributeIsAInteger(), mlirAttributeIsAIntegerSet(), mlirAttributeIsAOpaque(), mlirAttributeIsAOpaqueElements(), mlirAttributeIsASparseElements(), mlirAttributeIsASparseTensorEncodingAttr(), mlirAttributeIsAString(), mlirAttributeIsASymbolRef(), mlirAttributeIsAType(), mlirAttributeIsAUnit(), mlirAttributeParseGet(), mlirAttributePrint(), mlirBF16TypeGet(), mlirBlockAddArgument(), mlirBlockAppendOwnedOperation(), mlirBlockArgumentGetArgNumber(), mlirBlockArgumentGetOwner(), mlirBlockArgumentSetType(), mlirBlockCreate(), mlirBlockDestroy(), mlirBlockEqual(), mlirBlockGetArgument(), mlirBlockGetFirstOperation(), mlirBlockGetNextInRegion(), mlirBlockGetNumArguments(), mlirBlockGetParentOperation(), mlirBlockGetParentRegion(), mlirBlockGetTerminator(), mlirBlockInsertOwnedOperation(), mlirBlockInsertOwnedOperationAfter(), mlirBlockInsertOwnedOperationBefore(), mlirBlockPrint(), mlirBoolAttrGet(), mlirBoolAttrGetValue(), mlirCalibratedQuantizedTypeGet(), mlirCalibratedQuantizedTypeGetMax(), mlirCalibratedQuantizedTypeGetMin(), mlirComplexTypeGet(), mlirComplexTypeGetElementType(), mlirContextAttachDiagnosticHandler(), mlirContextDestroy(), mlirContextDetachDiagnosticHandler(), mlirContextEnableMultithreading(), mlirContextEqual(), mlirContextGetAllowUnregisteredDialects(), mlirContextGetNumLoadedDialects(), mlirContextGetNumRegisteredDialects(), mlirContextGetOrLoadDialect(), mlirContextIsRegisteredOperation(), mlirContextSetAllowUnregisteredDialects(), mlirDenseElementsAttrBoolGet(), mlirDenseElementsAttrBoolSplatGet(), mlirDenseElementsAttrDoubleSplatGet(), mlirDenseElementsAttrFloatSplatGet(), mlirDenseElementsAttrGet(), mlirDenseElementsAttrGetBoolSplatValue(), mlirDenseElementsAttrGetBoolValue(), mlirDenseElementsAttrGetDoubleSplatValue(), mlirDenseElementsAttrGetDoubleValue(), mlirDenseElementsAttrGetFloatSplatValue(), mlirDenseElementsAttrGetFloatValue(), mlirDenseElementsAttrGetInt16Value(), mlirDenseElementsAttrGetInt32SplatValue(), mlirDenseElementsAttrGetInt32Value(), mlirDenseElementsAttrGetInt64SplatValue(), mlirDenseElementsAttrGetInt64Value(), mlirDenseElementsAttrGetInt8SplatValue(), mlirDenseElementsAttrGetInt8Value(), mlirDenseElementsAttrGetRawData(), mlirDenseElementsAttrGetSplatValue(), mlirDenseElementsAttrGetStringSplatValue(), mlirDenseElementsAttrGetStringValue(), mlirDenseElementsAttrGetUInt16Value(), mlirDenseElementsAttrGetUInt32SplatValue(), mlirDenseElementsAttrGetUInt32Value(), mlirDenseElementsAttrGetUInt64SplatValue(), mlirDenseElementsAttrGetUInt64Value(), mlirDenseElementsAttrGetUInt8SplatValue(), mlirDenseElementsAttrGetUInt8Value(), mlirDenseElementsAttrInt32SplatGet(), mlirDenseElementsAttrInt64SplatGet(), mlirDenseElementsAttrInt8SplatGet(), mlirDenseElementsAttrIsSplat(), mlirDenseElementsAttrRawBufferGet(), mlirDenseElementsAttrReshapeGet(), mlirDenseElementsAttrSplatGet(), mlirDenseElementsAttrStringGet(), mlirDenseElementsAttrUInt32SplatGet(), mlirDenseElementsAttrUInt64SplatGet(), mlirDenseElementsAttrUInt8SplatGet(), mlirDiagnosticGetLocation(), mlirDiagnosticGetNote(), mlirDiagnosticGetNumNotes(), mlirDiagnosticGetSeverity(), mlirDiagnosticPrint(), mlirDialectEqual(), mlirDialectGetContext(), mlirDialectGetNamespace(), mlirDictionaryAttrGet(), mlirDictionaryAttrGetElement(), mlirDictionaryAttrGetElementByName(), mlirDictionaryAttrGetNumElements(), mlirElementsAttrGetNumElements(), mlirElementsAttrGetValue(), mlirElementsAttrIsValidIndex(), mlirEmitError(), mlirExecutionEngineCreate(), mlirExecutionEngineDestroy(), mlirExecutionEngineDumpToObjectFile(), mlirExecutionEngineInvokePacked(), mlirExecutionEngineLookup(), mlirExecutionEngineLookupPacked(), mlirExecutionEngineRegisterSymbol(), mlirF16TypeGet(), mlirF32TypeGet(), mlirF64TypeGet(), mlirFlatSymbolRefAttrGet(), mlirFlatSymbolRefAttrGetValue(), mlirFloatAttrDoubleGet(), mlirFloatAttrDoubleGetChecked(), mlirFloatAttrGetValueDouble(), mlirFunctionTypeGet(), mlirFunctionTypeGetInput(), mlirFunctionTypeGetNumInputs(), mlirFunctionTypeGetNumResults(), mlirFunctionTypeGetResult(), mlirIdentifierEqual(), mlirIdentifierGet(), mlirIdentifierGetContext(), mlirIdentifierStr(), mlirIndexTypeGet(), mlirInferTypeOpInterfaceInferReturnTypes(), mlirIntegerAttrGet(), mlirIntegerAttrGetValueInt(), mlirIntegerSetDump(), mlirIntegerSetEmptyGet(), mlirIntegerSetEqual(), mlirIntegerSetGetConstraint(), mlirIntegerSetGetContext(), mlirIntegerSetGetNumConstraints(), mlirIntegerSetGetNumDims(), mlirIntegerSetGetNumEqualities(), mlirIntegerSetGetNumInequalities(), mlirIntegerSetGetNumInputs(), mlirIntegerSetGetNumSymbols(), mlirIntegerSetIsCanonicalEmpty(), mlirIntegerSetIsConstraintEq(), mlirIntegerSetPrint(), mlirIntegerSetReplaceGet(), mlirIntegerTypeGet(), mlirIntegerTypeGetWidth(), mlirIntegerTypeIsSigned(), mlirIntegerTypeIsSignless(), mlirIntegerTypeIsUnsigned(), mlirIntegerTypeSignedGet(), mlirIntegerTypeUnsignedGet(), mlirLinalgFillBuiltinNamedOpRegion(), mlirLLVMArrayTypeGet(), mlirLLVMFunctionTypeGet(), mlirLLVMPointerTypeGet(), mlirLLVMStructTypeLiteralGet(), mlirLLVMVoidTypeGet(), mlirLocationCallSiteGet(), mlirLocationEqual(), mlirLocationFileLineColGet(), mlirLocationFusedGet(), mlirLocationGetContext(), mlirLocationNameGet(), mlirLocationPrint(), mlirLocationUnknownGet(), mlirMemRefTypeContiguousGet(), mlirMemRefTypeContiguousGetChecked(), mlirMemRefTypeGet(), mlirMemRefTypeGetAffineMap(), mlirMemRefTypeGetChecked(), mlirMemRefTypeGetLayout(), mlirMemRefTypeGetMemorySpace(), mlirModuleCreateEmpty(), mlirModuleCreateParse(), mlirModuleDestroy(), mlirModuleFromOperation(), mlirModuleGetBody(), mlirModuleGetContext(), mlirModuleGetOperation(), mlirNoneTypeGet(), mlirOpaqueAttrGet(), mlirOpaqueAttrGetData(), mlirOpaqueAttrGetDialectNamespace(), mlirOperationClone(), mlirOperationCreate(), mlirOperationDestroy(), mlirOperationDump(), mlirOperationEqual(), mlirOperationGetAttribute(), mlirOperationGetAttributeByName(), mlirOperationGetBlock(), mlirOperationGetContext(), mlirOperationGetFirstRegion(), mlirOperationGetLocation(), mlirOperationGetName(), mlirOperationGetNextInBlock(), mlirOperationGetNumAttributes(), mlirOperationGetNumOperands(), mlirOperationGetNumRegions(), mlirOperationGetNumResults(), mlirOperationGetNumSuccessors(), mlirOperationGetOperand(), mlirOperationGetParentOperation(), mlirOperationGetRegion(), mlirOperationGetResult(), mlirOperationGetSuccessor(), mlirOperationGetTypeID(), mlirOperationImplementsInterface(), mlirOperationImplementsInterfaceStatic(), mlirOperationMoveAfter(), mlirOperationMoveBefore(), mlirOperationPrint(), mlirOperationPrintWithFlags(), mlirOperationRemoveAttributeByName(), mlirOperationRemoveFromParent(), mlirOperationSetAttributeByName(), mlirOperationSetOperand(), mlirOperationVerify(), mlirOpPassManagerAddOwnedPass(), mlirOpPassManagerGetNestedUnder(), mlirOpPrintingFlagsDestroy(), mlirOpPrintingFlagsElideLargeElementsAttrs(), mlirOpPrintingFlagsEnableDebugInfo(), mlirOpPrintingFlagsPrintGenericOpForm(), mlirOpPrintingFlagsUseLocalScope(), mlirOpResultGetOwner(), mlirOpResultGetResultNumber(), mlirParsePassPipeline(), mlirPassManagerAddOwnedPass(), mlirPassManagerCreate(), mlirPassManagerDestroy(), mlirPassManagerEnableIRPrinting(), mlirPassManagerEnableVerifier(), mlirPassManagerGetAsOpPassManager(), mlirPassManagerGetNestedUnder(), mlirPassManagerRun(), mlirPDLAttributeTypeGet(), mlirPDLOperationTypeGet(), mlirPDLRangeTypeGet(), mlirPDLRangeTypeGetElementType(), mlirPDLTypeTypeGet(), mlirPDLValueTypeGet(), mlirPrintPassPipeline(), mlirQuantizedTypeCastExpressedToStorageType(), mlirQuantizedTypeCastFromExpressedType(), mlirQuantizedTypeCastFromStorageType(), mlirQuantizedTypeCastToExpressedType(), mlirQuantizedTypeCastToStorageType(), mlirQuantizedTypeGetExpressedType(), mlirQuantizedTypeGetFlags(), mlirQuantizedTypeGetQuantizedElementType(), mlirQuantizedTypeGetStorageType(), mlirQuantizedTypeGetStorageTypeIntegralWidth(), mlirQuantizedTypeGetStorageTypeMax(), mlirQuantizedTypeGetStorageTypeMin(), mlirQuantizedTypeIsCompatibleExpressedType(), mlirQuantizedTypeIsSigned(), mlirRankedTensorTypeGet(), mlirRankedTensorTypeGetChecked(), mlirRankedTensorTypeGetEncoding(), mlirRegionAppendOwnedBlock(), mlirRegionEqual(), mlirRegionGetFirstBlock(), mlirRegionGetNextInOperation(), mlirRegionInsertOwnedBlock(), mlirRegionInsertOwnedBlockAfter(), mlirRegionInsertOwnedBlockBefore(), mlirRegisterAllDialects(), mlirRegisterAllLLVMTranslations(), mlirShapedTypeGetDimSize(), mlirShapedTypeGetElementType(), mlirShapedTypeGetRank(), mlirShapedTypeHasRank(), mlirShapedTypeHasStaticShape(), mlirShapedTypeIsDynamicDim(), mlirSparseElementsAttrGetIndices(), mlirSparseElementsAttrGetValues(), mlirSparseElementsAttribute(), mlirSparseTensorEncodingAttrGet(), mlirSparseTensorEncodingAttrGetDimLevelType(), mlirSparseTensorEncodingAttrGetDimOrdering(), mlirSparseTensorEncodingAttrGetIndexBitWidth(), mlirSparseTensorEncodingAttrGetPointerBitWidth(), mlirSparseTensorEncodingGetNumDimLevelTypes(), mlirStringAttrGet(), mlirStringAttrGetValue(), mlirStringAttrTypedGet(), mlirSymbolRefAttrGet(), mlirSymbolRefAttrGetLeafReference(), mlirSymbolRefAttrGetNestedReference(), mlirSymbolRefAttrGetNumNestedReferences(), mlirSymbolRefAttrGetRootReference(), mlirSymbolTableCreate(), mlirSymbolTableDestroy(), mlirSymbolTableErase(), mlirSymbolTableInsert(), mlirSymbolTableLookup(), mlirSymbolTableReplaceAllSymbolUses(), mlirSymbolTableWalkSymbolTables(), mlirTupleTypeGet(), mlirTupleTypeGetNumTypes(), mlirTupleTypeGetType(), mlirTypeAttrGet(), mlirTypeAttrGetValue(), mlirTypeDump(), mlirTypeEqual(), mlirTypeGetContext(), mlirTypeGetTypeID(), mlirTypeIDEqual(), mlirTypeIDHashValue(), mlirTypeIsAAnyQuantizedType(), mlirTypeIsABF16(), mlirTypeIsACalibratedQuantizedType(), mlirTypeIsAComplex(), mlirTypeIsAF16(), mlirTypeIsAF32(), mlirTypeIsAF64(), mlirTypeIsAFunction(), mlirTypeIsAIndex(), mlirTypeIsAInteger(), mlirTypeIsAMemRef(), mlirTypeIsANone(), mlirTypeIsAPDLAttributeType(), mlirTypeIsAPDLOperationType(), mlirTypeIsAPDLRangeType(), mlirTypeIsAPDLType(), mlirTypeIsAPDLTypeType(), mlirTypeIsAPDLValueType(), mlirTypeIsAQuantizedType(), mlirTypeIsARankedTensor(), mlirTypeIsAShaped(), mlirTypeIsATensor(), mlirTypeIsATuple(), mlirTypeIsAUniformQuantizedPerAxisType(), mlirTypeIsAUniformQuantizedType(), mlirTypeIsAUnrankedMemRef(), mlirTypeIsAUnrankedTensor(), mlirTypeIsAVector(), mlirTypeParseGet(), mlirTypePrint(), mlirUniformQuantizedPerAxisTypeGet(), mlirUniformQuantizedPerAxisTypeGetNumDims(), mlirUniformQuantizedPerAxisTypeGetQuantizedDimension(), mlirUniformQuantizedPerAxisTypeGetScale(), mlirUniformQuantizedPerAxisTypeGetZeroPoint(), mlirUniformQuantizedPerAxisTypeIsFixedPoint(), mlirUniformQuantizedTypeGet(), mlirUniformQuantizedTypeGetScale(), mlirUniformQuantizedTypeGetZeroPoint(), mlirUniformQuantizedTypeIsFixedPoint(), mlirUnitAttrGet(), mlirUnrankedMemrefGetMemorySpace(), mlirUnrankedMemRefTypeGet(), mlirUnrankedMemRefTypeGetChecked(), mlirUnrankedTensorTypeGet(), mlirUnrankedTensorTypeGetChecked(), mlirValueDump(), mlirValueEqual(), mlirValueGetType(), mlirValueIsABlockArgument(), mlirValueIsAOpResult(), mlirValuePrint(), mlirVectorTypeGet(), mlirVectorTypeGetChecked(), unwrapList(), and mlir::tblgen::Operator::VariableDecoratorIterator::VariableDecoratorIterator().
wrap()
MlirDiagnostic wrap (mlir::Diagnostic & diagnostic) inline
Definition at line 24 of file Diagnostics.h.
Referenced by getDenseAttribute(), mlirAffineBinaryOpExprGetLHS(), mlirAffineBinaryOpExprGetRHS(), mlirAffineConstantExprGet(), mlirAffineDimExprGet(), mlirAffineExprCompose(), mlirAffineExprGetContext(), mlirAffineMapAttrGet(), mlirAffineMapAttrGetValue(), mlirAffineMapConstantGet(), mlirAffineMapEmptyGet(), mlirAffineMapGet(), mlirAffineMapGetContext(), mlirAffineMapGetMajorSubMap(), mlirAffineMapGetMinorSubMap(), mlirAffineMapGetResult(), mlirAffineMapGetSubMap(), mlirAffineMapMinorIdentityGet(), mlirAffineMapMultiDimIdentityGet(), mlirAffineMapPermutationGet(), mlirAffineMapReplace(), mlirAffineMapZeroResultGet(), mlirAffineSymbolExprGet(), mlirAnyQuantizedTypeGet(), mlirArrayAttrGet(), mlirArrayAttrGetElement(), mlirAttributeGetContext(), mlirAttributeGetType(), mlirAttributeGetTypeID(), mlirAttributeParseGet(), mlirBF16TypeGet(), mlirBlockAddArgument(), mlirBlockArgumentGetOwner(), mlirBlockCreate(), mlirBlockGetArgument(), mlirBlockGetFirstOperation(), mlirBlockGetNextInRegion(), mlirBlockGetParentOperation(), mlirBlockGetParentRegion(), mlirBlockGetTerminator(), mlirBoolAttrGet(), mlirCalibratedQuantizedTypeGet(), mlirComplexTypeGet(), mlirComplexTypeGetElementType(), mlirContextAttachDiagnosticHandler(), mlirContextCreate(), mlirContextGetOrLoadDialect(), mlirDenseElementsAttrBoolGet(), mlirDenseElementsAttrBoolSplatGet(), mlirDenseElementsAttrDoubleSplatGet(), mlirDenseElementsAttrFloatSplatGet(), mlirDenseElementsAttrGet(), mlirDenseElementsAttrGetSplatValue(), mlirDenseElementsAttrGetStringSplatValue(), mlirDenseElementsAttrGetStringValue(), mlirDenseElementsAttrInt32SplatGet(), mlirDenseElementsAttrInt64SplatGet(), mlirDenseElementsAttrInt8SplatGet(), mlirDenseElementsAttrRawBufferGet(), mlirDenseElementsAttrReshapeGet(), mlirDenseElementsAttrSplatGet(), mlirDenseElementsAttrStringGet(), mlirDenseElementsAttrUInt32SplatGet(), mlirDenseElementsAttrUInt64SplatGet(), mlirDenseElementsAttrUInt8SplatGet(), mlirDiagnosticGetLocation(), mlirDiagnosticGetNote(), mlirDialectGetContext(), mlirDialectGetNamespace(), mlirDictionaryAttrGet(), mlirDictionaryAttrGetElement(), mlirDictionaryAttrGetElementByName(), mlirElementsAttrGetValue(), mlirExecutionEngineCreate(), mlirExecutionEngineInvokePacked(), mlirF16TypeGet(), mlirF32TypeGet(), mlirF64TypeGet(), mlirFlatSymbolRefAttrGet(), mlirFlatSymbolRefAttrGetValue(), mlirFloatAttrDoubleGet(), mlirFloatAttrDoubleGetChecked(), mlirFunctionTypeGet(), mlirFunctionTypeGetInput(), mlirFunctionTypeGetResult(), mlirIdentifierGet(), mlirIdentifierGetContext(), mlirIdentifierStr(), mlirIndexTypeGet(), mlirInferTypeOpInterfaceInferReturnTypes(), mlirInferTypeOpInterfaceTypeID(), mlirIntegerAttrGet(), mlirIntegerSetEmptyGet(), mlirIntegerSetGet(), mlirIntegerSetGetConstraint(), mlirIntegerSetGetContext(), mlirIntegerSetReplaceGet(), mlirIntegerTypeGet(), mlirIntegerTypeSignedGet(), mlirIntegerTypeUnsignedGet(), mlirLLVMArrayTypeGet(), mlirLLVMFunctionTypeGet(), mlirLLVMPointerTypeGet(), mlirLLVMStructTypeLiteralGet(), mlirLLVMVoidTypeGet(), mlirLocationCallSiteGet(), mlirLocationFileLineColGet(), mlirLocationFusedGet(), mlirLocationGetContext(), mlirLocationNameGet(), mlirLocationUnknownGet(), mlirMemRefTypeContiguousGet(), mlirMemRefTypeContiguousGetChecked(), mlirMemRefTypeGet(), mlirMemRefTypeGetAffineMap(), mlirMemRefTypeGetChecked(), mlirMemRefTypeGetLayout(), mlirMemRefTypeGetMemorySpace(), mlirModuleCreateEmpty(), mlirModuleFromOperation(), mlirModuleGetBody(), mlirModuleGetContext(), mlirModuleGetOperation(), mlirNoneTypeGet(), mlirOpaqueAttrGet(), mlirOpaqueAttrGetData(), mlirOpaqueAttrGetDialectNamespace(), mlirOperationClone(), mlirOperationCreate(), mlirOperationGetAttribute(), mlirOperationGetAttributeByName(), mlirOperationGetBlock(), mlirOperationGetContext(), mlirOperationGetFirstRegion(), mlirOperationGetLocation(), mlirOperationGetName(), mlirOperationGetNextInBlock(), mlirOperationGetOperand(), mlirOperationGetParentOperation(), mlirOperationGetRegion(), mlirOperationGetResult(), mlirOperationGetSuccessor(), mlirOperationGetTypeID(), mlirOpPassManagerGetNestedUnder(), mlirOpPrintingFlagsCreate(), mlirOpResultGetOwner(), mlirParsePassPipeline(), mlirPassManagerCreate(), mlirPassManagerGetAsOpPassManager(), mlirPassManagerGetNestedUnder(), mlirPassManagerRun(), mlirPDLAttributeTypeGet(), mlirPDLOperationTypeGet(), mlirPDLRangeTypeGet(), mlirPDLRangeTypeGetElementType(), mlirPDLTypeTypeGet(), mlirPDLValueTypeGet(), mlirQuantizedTypeCastExpressedToStorageType(), mlirQuantizedTypeCastFromExpressedType(), mlirQuantizedTypeCastFromStorageType(), mlirQuantizedTypeCastToExpressedType(), mlirQuantizedTypeCastToStorageType(), mlirQuantizedTypeGetExpressedType(), mlirQuantizedTypeGetQuantizedElementType(), mlirQuantizedTypeGetStorageType(), mlirRankedTensorTypeGet(), mlirRankedTensorTypeGetChecked(), mlirRankedTensorTypeGetEncoding(), mlirRegionCreate(), mlirRegionGetFirstBlock(), mlirRegionGetNextInOperation(), mlirShapedTypeGetElementType(), mlirSparseElementsAttrGetIndices(), mlirSparseElementsAttrGetValues(), mlirSparseElementsAttribute(), mlirSparseTensorEncodingAttrGet(), mlirSparseTensorEncodingAttrGetDimOrdering(), mlirStringAttrGet(), mlirStringAttrGetValue(), mlirStringAttrTypedGet(), mlirSymbolRefAttrGet(), mlirSymbolRefAttrGetLeafReference(), mlirSymbolRefAttrGetNestedReference(), mlirSymbolRefAttrGetRootReference(), mlirSymbolTableCreate(), mlirSymbolTableGetSymbolAttributeName(), mlirSymbolTableGetVisibilityAttributeName(), mlirSymbolTableInsert(), mlirSymbolTableLookup(), mlirSymbolTableReplaceAllSymbolUses(), mlirSymbolTableWalkSymbolTables(), mlirTupleTypeGet(), mlirTupleTypeGetType(), mlirTypeAttrGet(), mlirTypeAttrGetValue(), mlirTypeGetContext(), mlirTypeGetTypeID(), mlirTypeParseGet(), mlirUniformQuantizedPerAxisTypeGet(), mlirUniformQuantizedTypeGet(), mlirUnitAttrGet(), mlirUnrankedMemrefGetMemorySpace(), mlirUnrankedMemRefTypeGet(), mlirUnrankedMemRefTypeGetChecked(), mlirUnrankedTensorTypeGet(), mlirUnrankedTensorTypeGetChecked(), mlirValueGetType(), mlirVectorTypeGet(), and mlirVectorTypeGetChecked().