MLIR: mlir::SimplexBase Class Reference
mlir::SimplexBase Class Reference
The Simplex class implements a version of the Simplex and Generalized Basis Reduction algorithms, which can perform analysis of integer sets with affine inequalities and equalities.
#include "mlir/Analysis/Presburger/Simplex.h"
Classes
struct Pivot
struct Unknown
An Unknown is either a variable or a constraint.
Public Types
enum Direction { Direction::Up, Direction::Down }
Public Member Functions
SimplexBase ()=delete
SimplexBase (unsigned nVar)
Construct a Simplex object with nVar variables.
SimplexBase (const IntegerPolyhedron &constraints)
bool isEmpty () const
Returns true if the tableau is empty (has conflicting constraints), false otherwise.
void addInequality (ArrayRef< int64_t > coeffs)
Add an inequality to the tableau.
unsigned getNumVariables () const
Returns the number of variables in the tableau.
unsigned getNumConstraints () const
Returns the number of constraints in the tableau.
void addEquality (ArrayRef< int64_t > coeffs)
Add an equality to the tableau.
void appendVariable (unsigned count=1)
Add new variables to the end of the list of variables.
void markEmpty ()
Mark the tableau as being empty.
unsigned getSnapshot () const
Get a snapshot of the current state. This is used for rolling back.
void rollback (unsigned snapshot)
Rollback to a snapshot. This invalidates all later snapshots.
void intersectIntegerPolyhedron (const IntegerPolyhedron &poly)
Add all the constraints from the given IntegerPolyhedron.
Optional< SmallVector< Fraction, 8 > > getRationalSample () const
Returns a rational sample point.
Optional< SmallVector< int64_t, 8 > > getSamplePointIfIntegral () const
Returns the current sample point if it is integral.
void print (raw_ostream &os) const
Print the tableau's internal state.
void dump () const
Protected Types
enum Orientation { Orientation::Row, Orientation::Column }
enum UndoLogEntry { UndoLogEntry::RemoveLastConstraint, UndoLogEntry::RemoveLastVariable, UndoLogEntry::UnmarkEmpty, UndoLogEntry::UnmarkLastRedundant }
Enum to denote operations that need to be undone during rollback.
Protected Member Functions
Optional< Pivot > findPivot (int row, Direction direction) const
Find a pivot to change the sample value of row in the specified direction.
void swapRowWithCol (unsigned row, unsigned col)
Swap the row with the column in the tableau's data structures but not the tableau itself.
void pivot (unsigned row, unsigned col)
Pivot the row with the column.
void pivot (Pivot pair)
const Unknown & unknownFromIndex (int index) const
Returns the unknown associated with index.
const Unknown & unknownFromColumn (unsigned col) const
Returns the unknown associated with col.
const Unknown & unknownFromRow (unsigned row) const
Returns the unknown associated with row.
Unknown & unknownFromIndex (int index)
Returns the unknown associated with index.
Unknown & unknownFromColumn (unsigned col)
Returns the unknown associated with col.
Unknown & unknownFromRow (unsigned row)
Returns the unknown associated with row.
unsigned addRow (ArrayRef< int64_t > coeffs)
Add a new row to the tableau and the associated data structures.
void normalizeRow (unsigned row)
Normalize the given row by removing common factors between the numerator and the denominator.
void swapRows (unsigned i, unsigned j)
Swap the two rows/columns in the tableau and associated data structures.
void swapColumns (unsigned i, unsigned j)
LogicalResult restoreRow (Unknown &u)
Restore the unknown to a non-negative sample value.
void undo (UndoLogEntry entry)
Undo the operation represented by the log entry.
Optional< unsigned > findPivotRow (Optional< unsigned > skipRow, Direction direction, unsigned col) const
Find a row that can be used to pivot the column in the specified direction.
Protected Attributes
unsigned nRow
The number of rows in the tableau.
unsigned nCol
The number of columns in the tableau, including the common denominator and the constant column.
unsigned nRedundant
The number of redundant rows in the tableau.
Matrix tableau
The matrix representing the tableau.
bool empty
This is true if the tableau has been detected to be empty, false otherwise.
SmallVector< UndoLogEntry, 8 > undoLog
Holds a log of operations, used for rolling back to a previous state.
SmallVector< int, 8 > rowUnknown
These hold the indexes of the unknown at a given row or column position.
SmallVector< int, 8 > colUnknown
SmallVector< Unknown, 8 > con
These hold information about each unknown.
SmallVector< Unknown, 8 > var
Detailed Description
The Simplex class implements a version of the Simplex and Generalized Basis Reduction algorithms, which can perform analysis of integer sets with affine inequalities and equalities.
A Simplex can be constructed by specifying the dimensionality of the set. It supports adding affine inequalities and equalities, and can perform emptiness checks, i.e., it can find a solution to the set of constraints if one exists, or say that the set is empty if no solution exists. Currently, this only works for bounded sets. Furthermore, it can find a subset of these constraints that are redundant, i.e. a subset of constraints that doesn't constrain the affine set further after adding the non-redundant constraints. Simplex can also be constructed from an IntegerPolyhedron object.
The implementation of the Simplex and SimplexBase classes, other than the functionality for sampling, is based on the paper "Simplify: A Theorem Prover for Program Checking" by D. Detlefs, G. Nelson, J. B. Saxe.
We define variables, constraints, and unknowns. Consider the example of a two-dimensional set defined by 1 + 2x + 3y >= 0 and 2x - 3y >= 0. Here, x, y, are variables while 1 + 2x + 3y >= 0, 2x - 3y >= 0 are constraints. Unknowns are either variables or constraints, i.e., x, y, 1 + 2x + 3y >= 0, 2x - 3y >= 0 are all unknowns.
The implementation involves a matrix called a tableau, which can be thought of as a 2D matrix of rational numbers having number of rows equal to the number of constraints and number of columns equal to one plus the number of variables. In our implementation, instead of storing rational numbers, we store a common denominator for each row, so it is in fact a matrix of integers with number of rows equal to number of constraints and number of columns equal to two plus the number of variables. For example, instead of storing a row of three rationals [1/2, 2/3, 3], we would store [6, 3, 4, 18] since 3/6 = 1/2, 4/6 = 2/3, and 18/6 = 3.
Every row and column except the first and second columns is associated with an unknown and every unknown is associated with a row or column. The second column represents the constant, explained in more detail below. An unknown associated with a row or column is said to be in row or column position respectively.
The vectors var and con store information about the variables and constraints respectively, namely, whether they are in row or column position, which row or column they are associated with, and whether they correspond to a variable or a constraint.
An unknown is addressed by its index. If the index i is non-negative, then the variable var[i] is being addressed. If the index i is negative, then the constraint con[~i] is being addressed. Effectively this maps 0 -> var[0], 1 -> var[1], -1 -> con[0], -2 -> con[1], etc. rowUnknown[r] and colUnknown[c] are the indexes of the unknowns associated with row r and column c, respectively.
The unknowns in column position are together called the basis. Initially the basis is the set of variables – in our example above, the initial basis is x, y.
The unknowns in row position are represented in terms of the basis unknowns. If the basis unknowns are u_1, u_2, ... u_m, and a row in the tableau is d, c, a_1, a_2, ... a_m, this represents the unknown for that row as (c + a_1*u_1 + a_2*u_2 + ... + a_m*u_m)/d. In our running example, if the basis is the initial basis of x, y, then the constraint 1 + 2x + 3y >= 0 would be represented by the row [1, 1, 2, 3].
The association of unknowns to rows and columns can be changed by a process called pivoting, where a row unknown and a column unknown exchange places and the remaining row variables' representation is changed accordingly by eliminating the old column unknown in favour of the new column unknown. If we had pivoted the column for x with the row for 2x - 3y >= 0, the new row for x would be [2, 1, 3] since x = (1*(2x - 3y) + 3*y)/2. See the documentation for the pivot member function for details.
The association of unknowns to rows and columns is called the tableau configuration. The sample value of an unknown in a particular tableau configuration is its value if all the column unknowns were set to zero. Concretely, for unknowns in column position the sample value is zero and for unknowns in row position the sample value is the constant term divided by the common denominator.
The tableau configuration is called consistent if the sample value of all restricted unknowns is non-negative. Initially there are no constraints, and the tableau is consistent. When a new constraint is added, its sample value in the current tableau configuration may be negative. In that case, we try to find a series of pivots to bring us to a consistent tableau configuration, i.e. we try to make the new constraint's sample value non-negative without making that of any other constraints negative. (See findPivot and findPivotRow for details.) If this is not possible, then the set of constraints is mutually contradictory and the tableau is marked empty, which means the set of constraints has no solution.
The Simplex class supports redundancy checking via detectRedundant and isMarkedRedundant. A redundant constraint is one which is never violated as long as the other constraints are not violated, i.e., removing a redundant constraint does not change the set of solutions to the constraints. As a heuristic, constraints that have been marked redundant can be ignored for most operations. Therefore, these constraints are kept in rows 0 to nRedundant - 1, where nRedundant is a member variable that tracks the number of constraints that have been marked redundant.
This Simplex class also supports taking snapshots of the current state and rolling back to prior snapshots. This works by maintaining an undo log of operations. Snapshots are just pointers to a particular location in the log, and rolling back to a snapshot is done by reverting each log entry's operation from the end until we reach the snapshot's location.
Finding an integer sample is done with the Generalized Basis Reduction algorithm. See the documentation for findIntegerSample and reduceBasis.
The SimplexBase class contains some basic functionality. In the future, lexicographic optimization will be supported by a class inheriting from SimplexBase. Functionality that will not supported by that class is placed in Simplex.
Definition at line 142 of file Simplex.h.
Member Enumeration Documentation
Direction
enum mlir::SimplexBase::Direction strong
Enumerator
Up
Down
Definition at line 144 of file Simplex.h.
Orientation
enum mlir::SimplexBase::Orientation strong protected
Enumerator
Row
Column
Definition at line 198 of file Simplex.h.
UndoLogEntry
enum mlir::SimplexBase::UndoLogEntry strong protected
Enum to denote operations that need to be undone during rollback.
Enumerator
RemoveLastConstraint
RemoveLastVariable
UnmarkEmpty
UnmarkLastRedundant
Definition at line 273 of file Simplex.h.
Constructor & Destructor Documentation
SimplexBase() [1/3]
mlir::SimplexBase::SimplexBase () delete
SimplexBase() [2/3]
mlir::SimplexBase::SimplexBase (unsigned nVar) explicit
Construct a Simplex object with nVar variables.
Definition at line 20 of file Simplex.cpp.
References Column, colUnknown, nCol, and var.
SimplexBase() [3/3]
mlir::SimplexBase::SimplexBase (const IntegerPolyhedron & constraints) explicit
Definition at line 31 of file Simplex.cpp.
References addEquality(), addInequality(), mlir::IntegerPolyhedron::getEquality(), mlir::IntegerPolyhedron::getInequality(), mlir::IntegerPolyhedron::getNumEqualities(), and mlir::IntegerPolyhedron::getNumInequalities().
Member Function Documentation
addEquality()
void mlir::SimplexBase::addEquality (ArrayRef< int64_t > coeffs)
Add an equality to the tableau.
If coeffs is c_0, c_1, ... c_n, where n is the current number of variables, then the corresponding equality is c_n + c_0*x_0 + c_1*x_1 + ... + c_{n-1}*x_{n-1} == 0.
If coeffs is c_0, c_1, ... c_n, where n is the current number of variables, then the corresponding equality is c_n + c_0*x_0 + c_1*x_1 + ... + c_{n-1}*x_{n-1} == 0.
We simply add two opposing inequalities, which force the expression to be zero.
Definition at line 400 of file Simplex.cpp.
References addInequality().
Referenced by mlir::Simplex::findIntegerSample(), intersectIntegerPolyhedron(), and SimplexBase().
addInequality()
void mlir::SimplexBase::addInequality (ArrayRef< int64_t > coeffs)
Add an inequality to the tableau.
If coeffs is c_0, c_1, ... c_n, where n is the current number of variables, then the corresponding inequality is c_n + c_0*x_0 + c_1*x_1 + ... + c_{n-1}*x_{n-1} >= 0.
If coeffs is c_0, c_1, ... c_n, where n is the current number of variables, then the corresponding inequality is c_n + c_0*x_0 + c_1*x_1 + ... + c_{n-1}*x_{n-1} >= 0.
We add the inequality and mark it as restricted. We then try to make its sample value non-negative. If this is not possible, the tableau has become empty and we mark it as such.
Definition at line 385 of file Simplex.cpp.
References addRow(), con, mlir::failed(), markEmpty(), restoreRow(), and mlir::SimplexBase::Unknown::restricted.
Referenced by addEquality(), intersectIntegerPolyhedron(), SimplexBase(), and subtractRecursively().
addRow()
unsigned mlir::SimplexBase::addRow (ArrayRef< int64_t > coeffs) protected
Add a new row to the tableau and the associated data structures.
Add a new row to the tableau corresponding to the given constant term and list of coefficients.
The coefficients are specified as a vector of (variable index, coefficient) pairs.
Definition at line 73 of file Simplex.cpp.
References Column, con, mlir::Matrix::getNumRows(), mlir::lcm(), nCol, normalizeRow(), nRow, RemoveLastConstraint, mlir::Matrix::resizeVertically(), Row, rowUnknown, tableau, undoLog, and var.
Referenced by addInequality(), and mlir::Simplex::computeOptimum().
appendVariable()
void mlir::SimplexBase::appendVariable (unsigned count = 1)
Add new variables to the end of the list of variables.
Definition at line 499 of file Simplex.cpp.
References Column, colUnknown, nCol, RemoveLastVariable, mlir::Matrix::resizeHorizontally(), tableau, undoLog, and var.
Referenced by subtractRecursively().
dump()
void mlir::SimplexBase::dump () const
Definition at line 1297 of file Simplex.cpp.
References print().
findPivot()
Optional< SimplexBase::Pivot > mlir::SimplexBase::findPivot (int row, Direction direction) const protected
Find a pivot to change the sample value of row in the specified direction.
Find a pivot to change the sample value of the row in the specified direction.
The returned pivot row will be row if and only if the unknown is unbounded in the specified direction.
Returns a (row, col) pair denoting a pivot, or an empty Optional if no valid pivot exists.
The returned pivot row will involve row if and only if the unknown is unbounded in the specified direction.
To increase (resp. decrease) the value of a row, we need to find a live column with a non-zero coefficient. If the coefficient is positive, we need to increase (decrease) the value of the column, and if the coefficient is negative, we need to decrease (increase) the value of the column. Also, we cannot decrease the sample value of restricted columns.
If multiple columns are valid, we break ties by considering a lexicographic ordering where we prefer unknowns with lower index.
Definition at line 163 of file Simplex.cpp.
References colUnknown, findPivotRow(), nCol, tableau, and unknownFromColumn().
Referenced by mlir::Simplex::computeRowOptimum(), and restoreRow().
findPivotRow()
Optional< unsigned > mlir::SimplexBase::findPivotRow (Optional< unsigned > skipRow, Direction direction, unsigned col) const protected
Find a row that can be used to pivot the column in the specified direction.
If skipRow is not null, then this row is excluded from consideration. The returned pivot will maintain all constraints except the column itself and skipRow, if it is set. (if these unknowns are restricted).
Returns the row to pivot to, or an empty Optional if the column is unbounded in the specified direction.
This returns an empty optional if and only if the column is unbounded in the specified direction (ignoring skipRow, if skipRow is set).
If skipRow is set, this row is not considered, and (if it is restricted) its restriction may be violated by the returned pivot. Usually, skipRow is set because we don't want to move it to column position unless it is unbounded, and we are either trying to increase the value of skipRow or explicitly trying to make skipRow negative, so we are not concerned about this.
If the direction is up (resp. down) and a restricted row has a negative (positive) coefficient for the column, then this row imposes a bound on how much the sample value of the column can change. Such a row with constant term c and coefficient f for the column imposes a bound of c/|f| on the change in sample value (in the specified direction). (note that c is non-negative here since the row is restricted and the tableau is consistent)
We iterate through the rows and pick the row which imposes the most stringent bound, since pivoting with a row changes the row's sample value to 0 and hence saturates the bound it imposes. We break ties between rows that impose the same bound by considering a lexicographic ordering where we prefer unknowns with lower index value.
Definition at line 307 of file Simplex.cpp.
References nRedundant, nRow, rowUnknown, tableau, and unknownFromRow().
Referenced by mlir::Simplex::computeOptimum(), mlir::Simplex::detectRedundant(), findPivot(), and undo().
getNumConstraints()
unsigned mlir::SimplexBase::getNumConstraints () const
Returns the number of constraints in the tableau.
Definition at line 409 of file Simplex.cpp.
References con.
Referenced by mlir::Simplex::makeProduct(), and subtractRecursively().
getNumVariables()
unsigned mlir::SimplexBase::getNumVariables () const
Returns the number of variables in the tableau.
Definition at line 408 of file Simplex.cpp.
References var.
Referenced by intersectIntegerPolyhedron(), and mlir::Simplex::makeProduct().
getRationalSample()
Optional< SmallVector< Fraction, 8 > > mlir::SimplexBase::getRationalSample () const
Returns a rational sample point.
Returns an empty optional if Simplex is empty.
Definition at line 748 of file Simplex.cpp.
References Column, empty, mlir::SimplexBase::Unknown::orientation, mlir::SimplexBase::Unknown::pos, tableau, and var.
Referenced by mlir::IntegerPolyhedron::findIntegerSample(), and getSamplePointIfIntegral().
getSamplePointIfIntegral()
Optional< SmallVector< int64_t, 8 > > mlir::SimplexBase::getSamplePointIfIntegral () const
Returns the current sample point if it is integral.
Otherwise, returns None.
Definition at line 770 of file Simplex.cpp.
References empty, getRationalSample(), and var.
Referenced by mlir::Simplex::findIntegerSample().
getSnapshot()
unsigned mlir::SimplexBase::getSnapshot () const
Get a snapshot of the current state. This is used for rolling back.
Return a snapshot of the current state.
This is just the current size of the undo log.
Definition at line 413 of file Simplex.cpp.
References undoLog.
Referenced by mlir::Simplex::computeOptimum(), mlir::Simplex::findIntegerSample(), and subtractRecursively().
intersectIntegerPolyhedron()
void mlir::SimplexBase::intersectIntegerPolyhedron (const IntegerPolyhedron & poly)
Add all the constraints from the given IntegerPolyhedron.
Definition at line 515 of file Simplex.cpp.
References addEquality(), addInequality(), mlir::IntegerPolyhedron::getEquality(), mlir::IntegerPolyhedron::getInequality(), mlir::IntegerPolyhedron::getNumEqualities(), mlir::IntegerPolyhedron::getNumIds(), mlir::IntegerPolyhedron::getNumInequalities(), and getNumVariables().
Referenced by subtractRecursively().
isEmpty()
bool mlir::SimplexBase::isEmpty () const
Returns true if the tableau is empty (has conflicting constraints), false otherwise.
Definition at line 346 of file Simplex.cpp.
References empty.
Referenced by mlir::PresburgerSet::coalesce(), mlir::IntegerPolyhedron::findIntegerSample(), mlir::IntegerPolyhedron::getBoundedDirections(), mlir::Simplex::isRationalSubsetOf(), and subtractRecursively().
markEmpty()
void mlir::SimplexBase::markEmpty ()
Mark the tableau as being empty.
Mark this tableau empty and push an entry to the undo stack.
Definition at line 368 of file Simplex.cpp.
References empty, undoLog, and UnmarkEmpty.
Referenced by addInequality().
normalizeRow()
void mlir::SimplexBase::normalizeRow (unsigned row) protected
Normalize the given row by removing common factors between the numerator and the denominator.
Normalize the row by removing factors that are common between the denominator and all the numerator coefficients.
Definition at line 124 of file Simplex.cpp.
References Down, nCol, tableau, and Up.
Referenced by addRow(), and pivot().
pivot() [1/2]
void mlir::SimplexBase::pivot (unsigned pivotRow, unsigned pivotCol) protected
Pivot the row with the column.
Pivot pivotRow and pivotCol.
Let R be the pivot row unknown and let C be the pivot col unknown. Since initially R = a*C + sum b_i * X_i (where the sum is over the other column's unknowns, x_i) C = (R - (sum b_i * X_i))/a
Let u be some other row unknown. u = c*C + sum d_i * X_i So u = c*(R - sum b_i * X_i)/a + sum d_i * X_i
This results in the following transform: pivot col other col pivot col other col pivot row a b -> pivot row 1/a -b/a other row c d other row c/a d - bc/a
Taking into account the common denominators p and q:
       pivot col    other col                    pivot col   other col
pivot row a/p b/p -> pivot row p/a -b/a other row c/q d/q other row cp/aq (da - bc)/aq
The pivot row transform is accomplished be swapping a with the pivot row's common denominator and negating the pivot row except for the pivot column element.
Definition at line 228 of file Simplex.cpp.
References nCol, normalizeRow(), nRow, swapRowWithCol(), and tableau.
Referenced by mlir::Simplex::computeOptimum(), mlir::Simplex::computeRowOptimum(), mlir::Simplex::detectRedundant(), pivot(), restoreRow(), and undo().
pivot() [2/2]
void mlir::SimplexBase::pivot (Pivot pair) protected
Definition at line 201 of file Simplex.cpp.
References mlir::SimplexBase::Pivot::column, pivot(), and mlir::SimplexBase::Pivot::row.
print()
void mlir::SimplexBase::print (raw_ostream & os) const
Print the tableau's internal state.
Definition at line 1262 of file Simplex.cpp.
References colUnknown, con, empty, nCol, nRow, rowUnknown, tableau, and var.
Referenced by dump().
restoreRow()
LogicalResult mlir::SimplexBase::restoreRow (Unknown & u) protected
Restore the unknown to a non-negative sample value.
Perform pivots until the unknown has a non-negative sample value or until no more upward pivots can be performed.
Returns success if the unknown was successfully restored to a non-negative sample value, failure otherwise.
Return success if we were able to bring the row to a non-negative sample value, and failure otherwise.
Definition at line 269 of file Simplex.cpp.
References Column, findPivot(), mlir::SimplexBase::Unknown::orientation, pivot(), mlir::SimplexBase::Unknown::pos, Row, mlir::success(), tableau, and Up.
Referenced by addInequality(), mlir::Simplex::computeOptimum(), and mlir::Simplex::detectRedundant().
rollback()
void mlir::SimplexBase::rollback (unsigned snapshot)
Rollback to a snapshot. This invalidates all later snapshots.
Rollback to the specified snapshot.
We undo all the log entries until the log size when the snapshot was taken is reached.
Definition at line 492 of file Simplex.cpp.
References undo(), and undoLog.
Referenced by mlir::Simplex::computeOptimum(), mlir::Simplex::findIntegerSample(), and subtractRecursively().
swapColumns()
void mlir::SimplexBase::swapColumns (unsigned i, unsigned j) protected
Definition at line 357 of file Simplex.cpp.
References colUnknown, nCol, mlir::SimplexBase::Unknown::pos, mlir::Matrix::swapColumns(), tableau, and unknownFromColumn().
Referenced by undo().
swapRows()
void mlir::SimplexBase::swapRows (unsigned i, unsigned j) protected
Swap the two rows/columns in the tableau and associated data structures.
Definition at line 348 of file Simplex.cpp.
References mlir::SimplexBase::Unknown::pos, rowUnknown, mlir::Matrix::swapRows(), tableau, and unknownFromRow().
Referenced by mlir::Simplex::isMarkedRedundant(), and undo().
swapRowWithCol()
void mlir::SimplexBase::swapRowWithCol (unsigned row, unsigned col) protected
Swap the row with the column in the tableau's data structures but not the tableau itself.
Swap the associated unknowns for the row and the column.
This is used by pivot.
First we swap the index associated with the row and column. Then we update the unknowns to reflect their new position and orientation.
Definition at line 191 of file Simplex.cpp.
References Column, colUnknown, mlir::SimplexBase::Unknown::orientation, mlir::SimplexBase::Unknown::pos, Row, rowUnknown, unknownFromColumn(), and unknownFromRow().
Referenced by pivot().
undo()
void mlir::SimplexBase::undo (UndoLogEntry entry) protected
Undo the operation represented by the log entry.
Definition at line 415 of file Simplex.cpp.
References Column, colUnknown, con, Down, empty, findPivotRow(), nCol, nRedundant, nRow, mlir::SimplexBase::Unknown::orientation, pivot(), mlir::SimplexBase::Unknown::pos, RemoveLastConstraint, RemoveLastVariable, mlir::Matrix::resizeHorizontally(), mlir::Matrix::resizeVertically(), rowUnknown, swapColumns(), swapRows(), tableau, UnmarkEmpty, UnmarkLastRedundant, Up, and var.
Referenced by rollback().
unknownFromColumn() [1/2]
const Simplex::Unknown & mlir::SimplexBase::unknownFromColumn (unsigned col) const protected
Returns the unknown associated with col.
Definition at line 45 of file Simplex.cpp.
References colUnknown, nCol, and unknownFromIndex().
Referenced by findPivot(), swapColumns(), and swapRowWithCol().
unknownFromColumn() [2/2]
Simplex::Unknown & mlir::SimplexBase::unknownFromColumn (unsigned col) protected
Returns the unknown associated with col.
Definition at line 60 of file Simplex.cpp.
References colUnknown, nCol, and unknownFromIndex().
unknownFromIndex() [1/2]
const Simplex::Unknown & mlir::SimplexBase::unknownFromIndex (int index) const protected
Returns the unknown associated with index.
Definition at line 40 of file Simplex.cpp.
References con, and var.
Referenced by mlir::Simplex::makeProduct(), unknownFromColumn(), and unknownFromRow().
unknownFromIndex() [2/2]
Simplex::Unknown & mlir::SimplexBase::unknownFromIndex (int index) protected
Returns the unknown associated with index.
Definition at line 55 of file Simplex.cpp.
References con, and var.
unknownFromRow() [1/2]
const Simplex::Unknown & mlir::SimplexBase::unknownFromRow (unsigned row) const protected
Returns the unknown associated with row.
Definition at line 50 of file Simplex.cpp.
References nRow, rowUnknown, and unknownFromIndex().
Referenced by findPivotRow(), swapRows(), and swapRowWithCol().
unknownFromRow() [2/2]
Simplex::Unknown & mlir::SimplexBase::unknownFromRow (unsigned row) protected
Returns the unknown associated with row.
Definition at line 65 of file Simplex.cpp.
References nRow, rowUnknown, and unknownFromIndex().
Member Data Documentation
colUnknown
SmallVector<int, 8> mlir::SimplexBase::colUnknown protected
Definition at line 322 of file Simplex.h.
Referenced by appendVariable(), findPivot(), mlir::Simplex::makeProduct(), print(), SimplexBase(), swapColumns(), swapRowWithCol(), undo(), and unknownFromColumn().
con
SmallVector<Unknown, 8> mlir::SimplexBase::con protected
These hold information about each unknown.
Definition at line 325 of file Simplex.h.
Referenced by addInequality(), addRow(), mlir::Simplex::computeOptimum(), mlir::Simplex::detectRedundant(), getNumConstraints(), mlir::Simplex::isBoundedAlongConstraint(), mlir::Simplex::isMarkedRedundant(), mlir::Simplex::makeProduct(), print(), undo(), and unknownFromIndex().
empty
bool mlir::SimplexBase::empty protected
This is true if the tableau has been detected to be empty, false otherwise.
Definition at line 310 of file Simplex.h.
Referenced by mlir::Simplex::computeOptimum(), mlir::Simplex::detectRedundant(), mlir::Simplex::findIntegerSample(), getRationalSample(), getSamplePointIfIntegral(), mlir::Simplex::isBoundedAlongConstraint(), isEmpty(), mlir::Simplex::isUnbounded(), mlir::Simplex::makeProduct(), markEmpty(), print(), and undo().
nCol
unsigned mlir::SimplexBase::nCol protected
The number of columns in the tableau, including the common denominator and the constant column.
Definition at line 299 of file Simplex.h.
Referenced by addRow(), appendVariable(), findPivot(), mlir::Simplex::makeProduct(), normalizeRow(), pivot(), print(), SimplexBase(), swapColumns(), undo(), and unknownFromColumn().
nRedundant
unsigned mlir::SimplexBase::nRedundant protected
The number of redundant rows in the tableau.
These are the first nRedundant rows.
Definition at line 303 of file Simplex.h.
Referenced by findPivotRow(), mlir::Simplex::isMarkedRedundant(), mlir::Simplex::makeProduct(), and undo().
nRow
unsigned mlir::SimplexBase::nRow protected
The number of rows in the tableau.
Definition at line 295 of file Simplex.h.
Referenced by addRow(), findPivotRow(), mlir::Simplex::makeProduct(), pivot(), print(), undo(), and unknownFromRow().
rowUnknown
SmallVector<int, 8> mlir::SimplexBase::rowUnknown protected
These hold the indexes of the unknown at a given row or column position.
We keep these as signed integers since that makes it convenient to check if an index corresponds to a variable or a constraint by checking the sign.
colUnknown is padded with two null indexes at the front since the first two columns don't correspond to any unknowns.
Definition at line 322 of file Simplex.h.
Referenced by addRow(), findPivotRow(), mlir::Simplex::makeProduct(), print(), swapRows(), swapRowWithCol(), undo(), and unknownFromRow().
tableau
Matrix mlir::SimplexBase::tableau protected
The matrix representing the tableau.
Definition at line 306 of file Simplex.h.
Referenced by addRow(), appendVariable(), mlir::Simplex::computeRowOptimum(), findPivot(), findPivotRow(), getRationalSample(), mlir::Simplex::makeProduct(), normalizeRow(), pivot(), print(), restoreRow(), swapColumns(), swapRows(), and undo().
undoLog
SmallVector<UndoLogEntry, 8> mlir::SimplexBase::undoLog protected
Holds a log of operations, used for rolling back to a previous state.
Definition at line 313 of file Simplex.h.
Referenced by addRow(), appendVariable(), getSnapshot(), mlir::Simplex::isMarkedRedundant(), markEmpty(), and rollback().
var
SmallVector<Unknown, 8> mlir::SimplexBase::var protected
Definition at line 325 of file Simplex.h.
Referenced by addRow(), appendVariable(), mlir::Simplex::findIntegerSample(), getNumVariables(), getRationalSample(), getSamplePointIfIntegral(), mlir::Simplex::isUnbounded(), mlir::Simplex::makeProduct(), print(), SimplexBase(), undo(), and unknownFromIndex().
The documentation for this class was generated from the following files:
include/mlir/Analysis/Presburger/Simplex.h
lib/Analysis/Presburger/Simplex.cpp