MLIR: mlir::pdll::ast::OperationExpr Class Reference
mlir::pdll::ast::OperationExpr Class Reference final
This expression represents the structural form of an MLIR Operation.
#include "mlir/Tools/PDLL/AST/Nodes.h"
Public Member Functions
Optional< StringRef > getName () const
Return the name of the operation, or None if there isn't one.
const OpNameDecl * getNameDecl () const
Return the declaration of the operation name.
llvm::SMRange getNameLoc () const
Return the location of the name of the operation expression, or an invalid location if there isn't a name.
MutableArrayRef< Expr * > getOperands ()
Return the operands of this operation.
ArrayRef< Expr * > getOperands () const
MutableArrayRef< Expr * > getResultTypes ()
Return the result types of this operation.
MutableArrayRef< Expr * > getResultTypes () const
MutableArrayRef< NamedAttributeDecl * > getAttributes ()
Return the attributes of this operation.
MutableArrayRef< NamedAttributeDecl * > getAttributes () const
Public Member Functions inherited from mlir::pdll::ast::Expr
Type getType () const
Return the type of this expression.
Public Member Functions inherited from mlir::pdll::ast::Node
TypeID getTypeID () const
Return the type identifier of this node.
llvm::SMRange getLoc () const
Return the location of this node.
void print (raw_ostream &os) const
Print this node to the given stream.
Static Public Member Functions
static OperationExpr * create (Context &ctx, llvm::SMRange loc, const OpNameDecl *nameDecl, ArrayRef< Expr *> operands, ArrayRef< Expr *> resultTypes, ArrayRef< NamedAttributeDecl *> attributes)
Static Public Member Functions inherited from mlir::pdll::ast::Node::NodeBase< OperationExpr, Expr >
static bool classof (const Node *node)
Provide type casting support.
Static Public Member Functions inherited from mlir::pdll::ast::Expr
static bool classof (const Node *node)
Provide type casting support.
Static Public Member Functions inherited from mlir::pdll::ast::Stmt
static bool classof (const Node *node)
Provide type casting support.
Additional Inherited Members
Public Types inherited from mlir::pdll::ast::Node::NodeBase< OperationExpr, Expr >
using Base = NodeBase< OperationExpr, Expr >
Protected Member Functions inherited from mlir::pdll::ast::Node::NodeBase< OperationExpr, Expr >
NodeBase (llvm::SMRange loc, Args &&...args)
Protected Member Functions inherited from mlir::pdll::ast::Expr
Expr (TypeID typeID, llvm::SMRange loc, Type type)
Protected Member Functions inherited from mlir::pdll::ast::Node
Node (TypeID typeID, llvm::SMRange loc)
Detailed Description
This expression represents the structural form of an MLIR Operation.
It represents either an input operation to match, or an operation to create within a rewrite.
Definition at line 429 of file Nodes.h.
Member Function Documentation
create()
OperationExpr * OperationExpr::create (Context & ctx, llvm::SMRange loc, const OpNameDecl * nameDecl, ArrayRef< Expr *> operands, ArrayRef< Expr *> resultTypes, ArrayRef< NamedAttributeDecl *> attributes) static
Definition at line 146 of file Nodes.cpp.
References mlir::pdll::ast::OperationType::get(), mlir::pdll::ast::Context::getAllocator(), mlir::pdll::ast::Node::getLoc(), and mlir::pdll::ast::OpNameDecl::getName().
getAttributes() [1/2]
MutableArrayRef<NamedAttributeDecl *> mlir::pdll::ast::OperationExpr::getAttributes () inline
Return the attributes of this operation.
Definition at line 467 of file Nodes.h.
getAttributes() [2/2]
MutableArrayRef<NamedAttributeDecl *> mlir::pdll::ast::OperationExpr::getAttributes () const inline
Definition at line 470 of file Nodes.h.
getName()
Optional< StringRef > OperationExpr::getName () const
Return the name of the operation, or None if there isn't one.
Definition at line 169 of file Nodes.cpp.
getNameDecl()
const OpNameDecl* mlir::pdll::ast::OperationExpr::getNameDecl () const inline
Return the declaration of the operation name.
Definition at line 444 of file Nodes.h.
getNameLoc()
llvm::SMRange mlir::pdll::ast::OperationExpr::getNameLoc () const inline
Return the location of the name of the operation expression, or an invalid location if there isn't a name.
Definition at line 448 of file Nodes.h.
getOperands() [1/2]
MutableArrayRef<Expr *> mlir::pdll::ast::OperationExpr::getOperands () inline
Return the operands of this operation.
Definition at line 451 of file Nodes.h.
getOperands() [2/2]
ArrayRef<Expr *> mlir::pdll::ast::OperationExpr::getOperands () const inline
Definition at line 454 of file Nodes.h.
getResultTypes() [1/2]
MutableArrayRef<Expr *> mlir::pdll::ast::OperationExpr::getResultTypes () inline
Return the result types of this operation.
Definition at line 459 of file Nodes.h.
getResultTypes() [2/2]
MutableArrayRef<Expr *> mlir::pdll::ast::OperationExpr::getResultTypes () const inline
Definition at line 462 of file Nodes.h.
The documentation for this class was generated from the following files:
include/mlir/Tools/PDLL/AST/Nodes.h
lib/Tools/PDLL/AST/Nodes.cpp