MLIR: mlir::FlatAffineRelation Class Reference
mlir::FlatAffineRelation Class Reference
A FlatAffineRelation represents a set of ordered pairs (domain -> range) where "domain" and "range" are tuples of identifiers.
#include "mlir/Dialect/Affine/Analysis/AffineStructures.h"
Public Member Functions
FlatAffineRelation (unsigned numReservedInequalities, unsigned numReservedEqualities, unsigned numReservedCols, unsigned numDomainDims, unsigned numRangeDims, unsigned numSymbols, unsigned numLocals, ArrayRef< Optional< Value >> valArgs={})
FlatAffineRelation (unsigned numDomainDims=0, unsigned numRangeDims=0, unsigned numSymbols=0, unsigned numLocals=0)
FlatAffineRelation (unsigned numDomainDims, unsigned numRangeDims, FlatAffineValueConstraints &fac)
FlatAffineRelation (unsigned numDomainDims, unsigned numRangeDims, FlatAffineConstraints &fac)
FlatAffineValueConstraints getDomainSet () const
Returns a set corresponding to the domain/range of the affine relation.
FlatAffineValueConstraints getRangeSet () const
unsigned getNumDomainDims () const
Returns the number of identifiers corresponding to domain/range of relation.
unsigned getNumRangeDims () const
void compose (const FlatAffineRelation &other)
Given affine relation other: (domainOther -> rangeOther), this operation takes the composition of other on this: (domainThis -> rangeThis).
void inverse ()
Swap domain and range of the relation.
void insertDomainId (unsigned pos, unsigned num=1)
Insert num identifiers of the specified kind after the pos identifier of that kind.
void insertRangeId (unsigned pos, unsigned num=1)
void appendDomainId (unsigned num=1)
Append num identifiers of the specified kind after the last identifier of that kind.
void appendRangeId (unsigned num=1)
Public Member Functions inherited from mlir::FlatAffineValueConstraints
FlatAffineValueConstraints (unsigned numReservedInequalities, unsigned numReservedEqualities, unsigned numReservedCols, unsigned numDims, unsigned numSymbols, unsigned numLocals, ArrayRef< Optional< Value >> valArgs={})
Constructs a constraint system reserving memory for the specified number of constraints and identifiers.
FlatAffineValueConstraints (unsigned numDims=0, unsigned numSymbols=0, unsigned numLocals=0, ArrayRef< Optional< Value >> valArgs={})
Constructs a constraint system with the specified number of dimensions and symbols.
FlatAffineValueConstraints (const FlatAffineConstraints &fac, ArrayRef< Optional< Value >> valArgs={})
FlatAffineValueConstraints (const AffineValueMap &avm)
Create a flat affine constraint system from an AffineValueMap or a list of these.
FlatAffineValueConstraints (ArrayRef< const AffineValueMap *> avmRef)
FlatAffineValueConstraints (IntegerSet set)
Creates an affine constraint system from an IntegerSet.
FlatAffineValueConstraints (ArrayRef< const AffineValueMap *> avmRef, IntegerSet set)
Kind getKind () const override
Return the kind of this FlatAffineConstraints.
void reset (unsigned numReservedInequalities, unsigned numReservedEqualities, unsigned numReservedCols, unsigned numDims, unsigned numSymbols, unsigned numLocals=0) override
Clears any existing data and reserves memory for the specified constraints.
void reset (unsigned numReservedInequalities, unsigned numReservedEqualities, unsigned numReservedCols, unsigned numDims, unsigned numSymbols, unsigned numLocals, ArrayRef< Value > valArgs)
void reset (unsigned numDims, unsigned numSymbols, unsigned numLocals, ArrayRef< Value > valArgs)
std::unique_ptr< FlatAffineValueConstraints > clone () const
Clones this object.
LogicalResult addAffineForOpDomain (AffineForOp forOp)
Adds constraints (lower and upper bounds) for the specified 'affine.for' operation's Value using IR information stored in its bound maps.
LogicalResult addDomainFromSliceMaps (ArrayRef< AffineMap > lbMaps, ArrayRef< AffineMap > ubMaps, ArrayRef< Value > operands)
Adds constraints (lower and upper bounds) for each loop in the loop nest described by the bound maps lbMaps and ubMaps of a computation slice.
void addAffineIfOpDomain (AffineIfOp ifOp)
Adds constraints imposed by the affine.if operation.
LogicalResult addBound (BoundType type, unsigned pos, AffineMap boundMap, ValueRange operands)
Adds a bound for the identifier at the specified position with constraints being drawn from the specified bound map and operands.
void addBound (BoundType type, Value val, int64_t value)
Adds a constant bound for the identifier associated with the given Value.
void getIneqAsAffineValueMap (unsigned pos, unsigned ineqPos, AffineValueMap &vmap, MLIRContext *context) const
Returns the bound for the identifier at pos from the inequality at ineqPos as a 1-d affine value map (affine map + operands).
LogicalResult addSliceBounds (ArrayRef< Value > values, ArrayRef< AffineMap > lbMaps, ArrayRef< AffineMap > ubMaps, ArrayRef< Value > operands)
Adds slice lower bounds represented by lower bounds in lbMaps and upper bounds in ubMaps to each identifier in the constraint system which has a value in values.
bool findId (Value val, unsigned *pos) const
Looks up the position of the identifier with the specified Value.
bool containsId (Value val) const
Returns true if an identifier with the specified Value exists, false otherwise.
void swapId (unsigned posA, unsigned posB) override
Swap the posA^th identifier with the posB^th identifier.
unsigned insertDimId (unsigned pos, ValueRange vals)
Insert identifiers of the specified kind at position pos.
unsigned insertSymbolId (unsigned pos, ValueRange vals)
unsigned insertId (IdKind kind, unsigned pos, unsigned num=1) override
unsigned insertId (IdKind kind, unsigned pos, ValueRange vals)
unsigned appendDimId (ValueRange vals)
Append identifiers of the specified kind after the last identifier of that kind.
unsigned appendSymbolId (ValueRange vals)
void addInductionVarOrTerminalSymbol (Value val)
Add the specified values as a dim or symbol id depending on its nature, if it already doesn't exist in the system.
AffineMap computeAlignedMap (AffineMap map, ValueRange operands) const
Align map with this constraint system based on operands.
LogicalResult composeMap (const AffineValueMap *vMap)
Composes the affine value map with this FlatAffineValueConstrains, adding the results of the map as dimensions at the front [0, vMap->getNumResults()) and with the dimensions set to the equalities specified by the value map.
void projectOut (Value val)
Projects out the identifier that is associate with Value.
void convertLoopIVSymbolsToDims ()
Changes all symbol identifiers which are loop IVs to dim identifiers.
LogicalResult unionBoundingBox (const FlatAffineValueConstraints &other)
Updates the constraints to be the smallest bounding (enclosing) box that contains the points of this set and that of other, with the symbols being treated specially.
void mergeAndAlignIdsWithOther (unsigned offset, FlatAffineValueConstraints *other)
Merge and align the identifiers of this and other starting at offset, so that both constraint systems get the union of the contained identifiers that is dimension-wise and symbol-wise unique; both constraint systems are updated so that they have the union of all identifiers, with this's original identifiers appearing first followed by any of other's identifiers that didn't appear in this.
bool areIdsAlignedWithOther (const FlatAffineValueConstraints &other)
Returns true if this constraint system and other are in the same space, i.e., if they are associated with the same set of identifiers, appearing in the same order.
void clearAndCopyFrom (const IntegerPolyhedron &other) override
Replaces the contents of this FlatAffineValueConstraints with other.
Value getValue (unsigned pos) const
Returns the Value associated with the pos^th identifier.
bool hasValue (unsigned pos) const
Returns true if the pos^th identifier has an associated Value.
bool hasValues () const
Returns true if at least one identifier has an associated Value.
void getValues (unsigned start, unsigned end, SmallVectorImpl< Value > *values) const
Returns the Values associated with identifiers in range [start, end).
void getAllValues (SmallVectorImpl< Value > *values) const
ArrayRef< Optional< Value > > getMaybeValues () const
ArrayRef< Optional< Value > > getMaybeDimValues () const
ArrayRef< Optional< Value > > getMaybeSymbolValues () const
ArrayRef< Optional< Value > > getMaybeDimAndSymbolValues () const
void setValue (unsigned pos, Value val)
Sets the Value associated with the pos^th identifier.
void setValues (unsigned start, unsigned end, ArrayRef< Value > values)
Sets the Values associated with the identifiers in the range [start, end).
void mergeSymbolIds (FlatAffineValueConstraints &other)
Merge and align symbols of this and other such that both get union of of symbols that are unique.
Public Member Functions inherited from mlir::FlatAffineConstraints
FlatAffineConstraints (unsigned numReservedInequalities, unsigned numReservedEqualities, unsigned numReservedCols, unsigned numDims, unsigned numSymbols, unsigned numLocals)
Constructs a constraint system reserving memory for the specified number of constraints and identifiers.
FlatAffineConstraints (unsigned numDims=0, unsigned numSymbols=0, unsigned numLocals=0)
Constructs a constraint system with the specified number of dimensions and symbols.
FlatAffineConstraints (const IntegerPolyhedron &poly)
FlatAffineConstraints (IntegerSet set)
Creates an affine constraint system from an IntegerSet.
FlatAffineConstraints (const MutableAffineMap &map)
~FlatAffineConstraints () override=default
std::unique_ptr< FlatAffineConstraints > clone () const
LogicalResult addBound (BoundType type, unsigned pos, AffineMap boundMap)
Adds a bound for the identifier at the specified position with constraints being drawn from the specified bound map.
IntegerSet getAsIntegerSet (MLIRContext *context) const
Returns the constraint system as an integer set.
void getSliceBounds (unsigned offset, unsigned num, MLIRContext *context, SmallVectorImpl< AffineMap > *lbMaps, SmallVectorImpl< AffineMap > *ubMaps)
Computes the lower and upper bounds of the first num dimensional identifiers (starting at offset) as an affine map of the remaining identifiers (dimensional and symbolic).
LogicalResult composeMatchingMap (AffineMap other)
Composes an affine map whose dimensions and symbols match one to one with the dimensions and symbols of this FlatAffineConstraints.
std::pair< AffineMap, AffineMap > getLowerAndUpperBound (unsigned pos, unsigned offset, unsigned num, unsigned symStartPos, ArrayRef< AffineExpr > localExprs, MLIRContext *context) const
Gets the lower and upper bound of the offset + posth identifier treating [0, offset) U [offset + num, symStartPos) as dimensions and [symStartPos, getNumDimAndSymbolIds) as symbols, and pos lies in [0, num).
Public Member Functions inherited from mlir::IntegerPolyhedron
IntegerPolyhedron (unsigned numReservedInequalities, unsigned numReservedEqualities, unsigned numReservedCols, unsigned numDims, unsigned numSymbols, unsigned numLocals)
Constructs a constraint system reserving memory for the specified number of constraints and identifiers.
IntegerPolyhedron (unsigned numDims=0, unsigned numSymbols=0, unsigned numLocals=0)
Constructs a constraint system with the specified number of dimensions and symbols.
virtual ~IntegerPolyhedron ()=default
std::unique_ptr< IntegerPolyhedron > clone () const
void reset (unsigned numDims=0, unsigned numSymbols=0, unsigned numLocals=0)
void append (const IntegerPolyhedron &other)
Appends constraints from other into this.
int64_t atEq (unsigned i, unsigned j) const
Returns the value at the specified equality row and column.
int64_t & atEq (unsigned i, unsigned j)
int64_t atIneq (unsigned i, unsigned j) const
Returns the value at the specified inequality row and column.
int64_t & atIneq (unsigned i, unsigned j)
unsigned getNumConstraints () const
unsigned getNumIds () const
unsigned getNumDimIds () const
unsigned getNumSymbolIds () const
unsigned getNumDimAndSymbolIds () const
unsigned getNumLocalIds () const
unsigned getNumCols () const
Returns the number of columns in the constraint system.
unsigned getNumEqualities () const
unsigned getNumInequalities () const
unsigned getNumReservedEqualities () const
unsigned getNumReservedInequalities () const
ArrayRef< int64_t > getEquality (unsigned idx) const
ArrayRef< int64_t > getInequality (unsigned idx) const
unsigned insertDimId (unsigned pos, unsigned num=1)
Insert num identifiers of the specified kind at position pos.
unsigned insertSymbolId (unsigned pos, unsigned num=1)
unsigned insertLocalId (unsigned pos, unsigned num=1)
unsigned appendDimId (unsigned num=1)
Append num identifiers of the specified kind after the last identifier.
unsigned appendSymbolId (unsigned num=1)
unsigned appendLocalId (unsigned num=1)
void addInequality (ArrayRef< int64_t > inEq)
Adds an inequality (>= 0) from the coefficients specified in inEq.
void addEquality (ArrayRef< int64_t > eq)
Adds an equality from the coefficients specified in eq.
void removeId (IdKind kind, unsigned pos)
Removes identifiers of the specified kind with the specified pos (or within the specified range) from the system.
void removeIdRange (IdKind kind, unsigned idStart, unsigned idLimit)
void removeId (unsigned pos)
Removes the specified identifier from the system.
void removeEquality (unsigned pos)
void removeInequality (unsigned pos)
void removeEqualityRange (unsigned start, unsigned end)
Remove the (in)equalities at positions [start, end).
void removeInequalityRange (unsigned start, unsigned end)
void clearConstraints ()
Removes all equalities and inequalities.
void setAndEliminate (unsigned pos, ArrayRef< int64_t > values)
Sets the values.size() identifiers starting at pos to the specified values and removes them.
void getLowerAndUpperBoundIndices (unsigned pos, SmallVectorImpl< unsigned > *lbIndices, SmallVectorImpl< unsigned > *ubIndices, SmallVectorImpl< unsigned > *eqIndices=nullptr, unsigned offset=0, unsigned num=0) const
Gather positions of all lower and upper bounds of the identifier at pos, and optionally any equalities on it.
bool isEmpty () const
Checks for emptiness by performing variable elimination on all identifiers, running the GCD test on each equality constraint, and checking for invalid constraints.
bool isEmptyByGCDTest () const
Runs the GCD test on all equality constraints.
bool isIntegerEmpty () const
Returns true if the set of constraints is found to have no solution, false if a solution exists.
Matrix getBoundedDirections () const
Returns a matrix where each row is a vector along which the polytope is bounded.
Optional< SmallVector< int64_t, 8 > > findIntegerSample () const
Find an integer sample point satisfying the constraints using a branch and bound algorithm with generalized basis reduction, with some additional processing using Simplex for unbounded sets.
bool containsPoint (ArrayRef< int64_t > point) const
Returns true if the given point satisfies the constraints, or false otherwise.
void getLocalReprs (std::vector< SmallVector< int64_t, 8 >> &dividends, SmallVector< unsigned, 4 > &denominators, std::vector< presburger_utils::MaybeLocalRepr > &repr) const
Find pairs of inequalities identified by their position indices, using which an explicit representation for each local variable can be computed.
void getLocalReprs (std::vector< presburger_utils::MaybeLocalRepr > &repr) const
void getLocalReprs (std::vector< SmallVector< int64_t, 8 >> &dividends, SmallVector< unsigned, 4 > &denominators) const
void addBound (BoundType type, unsigned pos, int64_t value)
Adds a constant bound for the specified identifier.
void addBound (BoundType type, ArrayRef< int64_t > expr, int64_t value)
Adds a constant bound for the specified expression.
void addLocalFloorDiv (ArrayRef< int64_t > dividend, int64_t divisor)
Adds a new local identifier as the floordiv of an affine function of other identifiers, the coefficients of which are provided in dividend and with respect to a positive constant divisor.
void projectOut (unsigned pos, unsigned num)
Projects out (aka eliminates) num identifiers starting at position pos.
void projectOut (unsigned pos)
void setDimSymbolSeparation (unsigned newSymbolCount)
Changes the partition between dimensions and symbols.
LogicalResult constantFoldId (unsigned pos)
Tries to fold the specified identifier to a constant using a trivial equality detection; if successful, the constant is substituted for the identifier everywhere in the constraint system and then removed from the system.
void constantFoldIdRange (unsigned pos, unsigned num)
This method calls constantFoldId for the specified range of identifiers, num identifiers starting at position pos.
LogicalResult unionBoundingBox (const IntegerPolyhedron &other)
Updates the constraints to be the smallest bounding (enclosing) box that contains the points of this set and that of other, with the symbols being treated specially.
Optional< int64_t > getConstantBoundOnDimSize (unsigned pos, SmallVectorImpl< int64_t > *lb=nullptr, int64_t *boundFloorDivisor=nullptr, SmallVectorImpl< int64_t > *ub=nullptr, unsigned *minLbPos=nullptr, unsigned *minUbPos=nullptr) const
Returns the smallest known constant bound for the extent of the specified identifier (pos^th), i.e., the smallest known constant that is greater than or equal to 'exclusive upper bound' - 'lower bound' of the identifier.
Optional< int64_t > getConstantBound (BoundType type, unsigned pos) const
Returns the constant bound for the pos^th identifier if there is one; None otherwise.
void removeIndependentConstraints (unsigned pos, unsigned num)
Removes constraints that are independent of (i.e., do not have a coefficient) identifiers in the range [pos, pos + num).
bool isHyperRectangular (unsigned pos, unsigned num) const
Returns true if the set can be trivially detected as being hyper-rectangular on the specified contiguous set of identifiers.
void removeTrivialRedundancy ()
Removes duplicate constraints, trivially true constraints, and constraints that can be detected as redundant as a result of differing only in their constant term part.
void removeRedundantInequalities ()
A more expensive check than removeTrivialRedundancy to detect redundant inequalities.
void removeRedundantConstraints ()
Removes redundant constraints using Simplex.
void convertDimToLocal (unsigned dimStart, unsigned dimLimit)
Converts identifiers in the column range [idStart, idLimit) to local variables.
void mergeLocalIds (IntegerPolyhedron &other)
Adds additional local ids to the sets such that they both have the union of the local ids in each set, without changing the set of points that lie in this and other.
void print (raw_ostream &os) const
void dump () const
Protected Member Functions
void removeIdRange (unsigned idStart, unsigned idLimit) override
Removes identifiers in the column range [idStart, idLimit), and copies any remaining valid data into place, updates member variables, and resizes arrays as needed.
Protected Member Functions inherited from mlir::FlatAffineValueConstraints
bool hasConsistentState () const override
Returns false if the fields corresponding to various identifier counts, or equality/inequality buffer sizes aren't consistent; true otherwise.
void fourierMotzkinEliminate (unsigned pos, bool darkShadow=false, bool *isResultIntegerExact=nullptr) override
Eliminates the identifier at the specified position using Fourier-Motzkin variable elimination, but uses Gaussian elimination if there is an equality involving that identifier.
Protected Member Functions inherited from mlir::FlatAffineConstraints
LogicalResult flattenAlignedMapAndMergeLocals (AffineMap map, std::vector< SmallVector< int64_t, 8 >> *flattenedExprs)
Given an affine map that is aligned with this constraint system:
void printSpace (raw_ostream &os) const override
Prints the number of constraints, dimensions, symbols and locals in the FlatAffineConstraints.
Protected Member Functions inherited from mlir::IntegerPolyhedron
bool hasInvalidConstraint () const
Checks all rows of equality/inequality constraints for trivial contradictions (for example: 1 == 0, 0 >= 1), which may have surfaced after elimination.
template<bool isLower>
Optional< int64_t > computeConstantLowerOrUpperBound (unsigned pos)
Returns the constant lower bound bound if isLower is true, and the upper bound if isLower is false.
LogicalResult gaussianEliminateId (unsigned position)
Eliminates a single identifier at position from equality and inequality constraints.
void removeRedundantLocalVars ()
Removes local variables using equalities.
unsigned gaussianEliminateIds (unsigned posStart, unsigned posLimit)
Eliminates identifiers from equality and inequality constraints in column range [posStart, posLimit).
void gcdTightenInequalities ()
Tightens inequalities given that we are dealing with integer spaces.
void normalizeConstraintsByGCD ()
Normalized each constraints by the GCD of its coefficients.
bool findConstraintWithNonZeroAt (unsigned colIdx, bool isEq, unsigned *rowIdx) const
Searches for a constraint with a non-zero coefficient at colIdx in equality (isEq=true) or inequality (isEq=false) constraints.
bool isColZero (unsigned pos) const
Returns true if the pos^th column is all zero for both inequalities and equalities.
unsigned getIdKindOffset (IdKind kind) const
Return the index at which the specified kind of id starts.
unsigned getNumIdKind (IdKind kind) const
Get the number of ids of the specified kind.
Protected Attributes
unsigned numDomainDims
unsigned numRangeDims
Protected Attributes inherited from mlir::FlatAffineValueConstraints
SmallVector< Optional< Value >, 8 > values
Values corresponding to the (column) identifiers of this constraint system appearing in the order the identifiers correspond to columns.
Protected Attributes inherited from mlir::IntegerPolyhedron
unsigned numIds
Total number of identifiers.
unsigned numDims
Number of identifiers corresponding to real dimensions.
unsigned numSymbols
Number of identifiers corresponding to symbols (unknown but constant for analysis).
Matrix equalities
Coefficients of affine equalities (in == 0 form).
Matrix inequalities
Coefficients of affine inequalities (in >= 0 form).
Additional Inherited Members
Public Types inherited from mlir::IntegerPolyhedron
enum Kind { Kind::FlatAffineConstraints, Kind::FlatAffineValueConstraints, Kind::IntegerPolyhedron }
All derived classes of IntegerPolyhedron.
enum IdKind { Dimension, Symbol, Local }
Kind of identifier (column).
enum BoundType { EQ, LB, UB }
The type of bound: equal, lower bound or upper bound.
Static Public Member Functions inherited from mlir::FlatAffineValueConstraints
static FlatAffineValueConstraints getHyperrectangular (ValueRange ivs, ValueRange lbs, ValueRange ubs)
static bool classof (const IntegerPolyhedron *cst)
Static Public Member Functions inherited from mlir::FlatAffineConstraints
static FlatAffineConstraints getUniverse (unsigned numDims=0, unsigned numSymbols=0)
Return a system with no constraints, i.e., one which is satisfied by all points.
static bool classof (const IntegerPolyhedron *cst)
Static Public Member Functions inherited from mlir::IntegerPolyhedron
static IntegerPolyhedron getUniverse (unsigned numDims=0, unsigned numSymbols=0)
Return a system with no constraints, i.e., one which is satisfied by all points.
static bool classof (const IntegerPolyhedron *cst)
Static Protected Attributes inherited from mlir::IntegerPolyhedron
static constexpr unsigned kExplosionFactor = 32
A parameter that controls detection of an unrealistic number of constraints.
Detailed Description
A FlatAffineRelation represents a set of ordered pairs (domain -> range) where "domain" and "range" are tuples of identifiers.
The relation is represented as a FlatAffineValueConstraints with separation of dimension identifiers into domain and range. The identifiers are stored as: [domainIds, rangeIds, symbolIds, localIds, constant].
Definition at line 547 of file AffineStructures.h.
Constructor & Destructor Documentation
FlatAffineRelation() [1/4]
mlir::FlatAffineRelation::FlatAffineRelation (unsigned numReservedInequalities, unsigned numReservedEqualities, unsigned numReservedCols, unsigned numDomainDims, unsigned numRangeDims, unsigned numSymbols, unsigned numLocals, ArrayRef< Optional< Value >> valArgs = {}) inline
Definition at line 549 of file AffineStructures.h.
FlatAffineRelation() [2/4]
mlir::FlatAffineRelation::FlatAffineRelation (unsigned numDomainDims = 0, unsigned numRangeDims = 0, unsigned numSymbols = 0, unsigned numLocals = 0) inline
Definition at line 559 of file AffineStructures.h.
FlatAffineRelation() [3/4]
mlir::FlatAffineRelation::FlatAffineRelation (unsigned numDomainDims, unsigned numRangeDims, FlatAffineValueConstraints & fac) inline
Definition at line 565 of file AffineStructures.h.
FlatAffineRelation() [4/4]
mlir::FlatAffineRelation::FlatAffineRelation (unsigned numDomainDims, unsigned numRangeDims, FlatAffineConstraints & fac) inline
Definition at line 570 of file AffineStructures.h.
Member Function Documentation
appendDomainId()
void FlatAffineRelation::appendDomainId (unsigned num = 1)
Append num identifiers of the specified kind after the last identifier of that kind.
The coefficient columns corresponding to the added identifiers are initialized to zero.
Definition at line 1694 of file AffineStructures.cpp.
References mlir::FlatAffineValueConstraints::insertDimId().
appendRangeId()
void FlatAffineRelation::appendRangeId (unsigned num = 1)
Definition at line 1699 of file AffineStructures.cpp.
References mlir::IntegerPolyhedron::getNumDimIds(), and mlir::FlatAffineValueConstraints::insertDimId().
Referenced by compose().
compose()
void FlatAffineRelation::compose (const FlatAffineRelation & other)
Given affine relation other: (domainOther -> rangeOther), this operation takes the composition of other on this: (domainThis -> rangeThis).
The resulting relation represents tuples of the form: domainOther -> rangeThis.
Definition at line 1609 of file AffineStructures.cpp.
References mlir::IntegerPolyhedron::append(), appendRangeId(), mlir::IntegerPolyhedron::convertDimToLocal(), mlir::FlatAffineValueConstraints::getMaybeDimValues(), getNumDomainDims(), getNumRangeDims(), mlir::FlatAffineValueConstraints::getValue(), mlir::FlatAffineValueConstraints::hasValue(), mlir::IntegerPolyhedron::mergeLocalIds(), mlir::FlatAffineValueConstraints::mergeSymbolIds(), mlir::IntegerPolyhedron::removeRedundantLocalVars(), mlir::FlatAffineValueConstraints::setValue(), and mlir::FlatAffineValueConstraints::values.
Referenced by mlir::checkMemrefAccessDependence().
getDomainSet()
FlatAffineValueConstraints FlatAffineRelation::getDomainSet () const
Returns a set corresponding to the domain/range of the affine relation.
Definition at line 1594 of file AffineStructures.cpp.
References mlir::IntegerPolyhedron::convertDimToLocal().
Referenced by mlir::checkMemrefAccessDependence().
getNumDomainDims()
unsigned mlir::FlatAffineRelation::getNumDomainDims () const inline
Returns the number of identifiers corresponding to domain/range of relation.
Definition at line 581 of file AffineStructures.h.
Referenced by compose(), mlir::MemRefAccess::getAccessRelation(), and mlir::getRelationFromMap().
getNumRangeDims()
unsigned mlir::FlatAffineRelation::getNumRangeDims () const inline
Definition at line 582 of file AffineStructures.h.
Referenced by compose(), mlir::MemRefAccess::getAccessRelation(), and mlir::getRelationFromMap().
getRangeSet()
FlatAffineValueConstraints FlatAffineRelation::getRangeSet () const
Definition at line 1602 of file AffineStructures.cpp.
References mlir::IntegerPolyhedron::convertDimToLocal().
insertDomainId()
void FlatAffineRelation::insertDomainId (unsigned pos, unsigned num = 1)
Insert num identifiers of the specified kind after the pos identifier of that kind.
The coefficient columns corresponding to the added identifiers are initialized to zero.
Definition at line 1680 of file AffineStructures.cpp.
References mlir::FlatAffineValueConstraints::insertDimId().
Referenced by mlir::MemRefAccess::getAccessRelation().
insertRangeId()
void FlatAffineRelation::insertRangeId (unsigned pos, unsigned num = 1)
Definition at line 1687 of file AffineStructures.cpp.
References mlir::FlatAffineValueConstraints::insertDimId().
inverse()
void FlatAffineRelation::inverse ()
Swap domain and range of the relation.
(domain -> range) is converted to (range -> domain).
Definition at line 1665 of file AffineStructures.cpp.
References mlir::FlatAffineValueConstraints::removeIdRange(), and mlir::FlatAffineValueConstraints::swapId().
Referenced by mlir::checkMemrefAccessDependence().
removeIdRange()
void FlatAffineRelation::removeIdRange (unsigned idStart, unsigned idLimit) override protected virtual
Removes identifiers in the column range [idStart, idLimit), and copies any remaining valid data into place, updates member variables, and resizes arrays as needed.
Reimplemented from mlir::FlatAffineValueConstraints.
Definition at line 1704 of file AffineStructures.cpp.
References mlir::IntegerPolyhedron::getNumDimIds(), max(), min(), and mlir::FlatAffineValueConstraints::removeIdRange().
Member Data Documentation
numDomainDims
unsigned mlir::FlatAffineRelation::numDomainDims protected
Definition at line 608 of file AffineStructures.h.
numRangeDims
unsigned mlir::FlatAffineRelation::numRangeDims protected
Definition at line 611 of file AffineStructures.h.
The documentation for this class was generated from the following files:
include/mlir/Dialect/Affine/Analysis/AffineStructures.h
lib/Dialect/Affine/Analysis/AffineStructures.cpp