MLIR: mlir::bufferization::AnalysisBufferizationState Class Reference
mlir::bufferization::AnalysisBufferizationState Class Reference
State for analysis-enabled bufferization.
#include "mlir/Dialect/Bufferization/Transforms/OneShotAnalysis.h"
Public Member Functions
AnalysisBufferizationState (Operation *op, const AnalysisBufferizationOptions &options)
AnalysisBufferizationState (const AnalysisBufferizationState &)=delete
virtual ~AnalysisBufferizationState ()=default
BufferizationAliasInfo & getAliasInfo ()
Return a reference to the BufferizationAliasInfo.
bool isInPlace (OpOperand &opOperand) const override
Return true if the given OpResult has been decided to bufferize inplace.
bool areEquivalentBufferizedValues (Value v1, Value v2) const override
Return true if v1 and v2 bufferize to equivalent buffers.
Public Member Functions inherited from mlir::bufferization::BufferizationState
SmallVector< OpOperand * > getAliasingOpOperand (OpResult result) const
Determine which OpOperand* will alias with result if the op is bufferized in place.
OpResult getAliasingOpResult (OpOperand &opOperand) const
Determine which OpResult will alias with opOperand if the op is bufferized in place.
bool bufferizesToMemoryRead (OpOperand &opOperand) const
Return true if opOperand bufferizes to a memory read.
bool bufferizesToMemoryWrite (OpOperand &opOperand) const
Return true if opOperand bufferizes to a memory write.
bool bufferizesToAliasOnly (OpOperand &opOperand) const
Return true if opOperand does neither read nor write but bufferizes to an alias.
bool isValueRead (Value value) const
Return true if the given value is read by an op that bufferizes to a memory read.
SetVector< Value > findValueInReverseUseDefChain (Value value, llvm::function_ref< bool(Value)> condition) const
Starting from value, follow the use-def chain in reverse, always selecting the aliasing OpOperands.
SetVector< Value > findLastPrecedingWrite (Value value) const
Find the Values of the last preceding write of a given Value.
FailureOr< Value > getBuffer (RewriterBase &rewriter, OpOperand &opOperand, bool forceInPlace=false, Optional< Operation *> customCopyInsertionPoint=None) const
Return the buffer (memref) for a given OpOperand (tensor).
template<typename StateT >
Optional< const StateT * > getDialectState (StringRef name) const
Return dialect-specific bufferization state.
template<typename StateT >
StateT & getOrCreateDialectState (StringRef name)
Return dialect-specific bufferization state or create one if none exists.
const BufferizationOptions & getOptions () const
Return a reference to the BufferizationOptions.
Additional Inherited Members
Protected Member Functions inherited from mlir::bufferization::BufferizationState
BufferizationState (const BufferizationOptions &options)
BufferizationState (const BufferizationState &)=delete
~BufferizationState ()=default
Detailed Description
State for analysis-enabled bufferization.
This class keeps track of alias (via BufferizationAliasInfo) to decide if tensor OpOperands should bufferize in-place.
Definition at line 148 of file OneShotAnalysis.h.
Constructor & Destructor Documentation
AnalysisBufferizationState() [1/2]
AnalysisBufferizationState::AnalysisBufferizationState (Operation * op, const AnalysisBufferizationOptions & options)
Definition at line 188 of file OneShotAnalysis.cpp.
References mlir::WalkResult::advance(), mlir::bufferization::BufferizationOptions::isOpAllowed(), mlir::bufferization::BufferizationAliasInfo::markInPlace(), mlir::WalkResult::skip(), mlir::bufferization::BufferizationAliasInfo::unionAliasSets(), and mlir::Operation::walk().
AnalysisBufferizationState() [2/2]
mlir::bufferization::AnalysisBufferizationState::AnalysisBufferizationState (const AnalysisBufferizationState &) delete
~AnalysisBufferizationState()
virtual mlir::bufferization::AnalysisBufferizationState::~AnalysisBufferizationState () virtual default
Member Function Documentation
areEquivalentBufferizedValues()
bool AnalysisBufferizationState::areEquivalentBufferizedValues (Value v1, Value v2) const override virtual
Return true if v1 and v2 bufferize to equivalent buffers.
Implements mlir::bufferization::BufferizationState.
Definition at line 213 of file OneShotAnalysis.cpp.
References mlir::bufferization::BufferizationAliasInfo::areEquivalentBufferizedValues().
getAliasInfo()
BufferizationAliasInfo& mlir::bufferization::AnalysisBufferizationState::getAliasInfo () inline
Return a reference to the BufferizationAliasInfo.
Definition at line 158 of file OneShotAnalysis.h.
References mlir::bufferization::analyzeOp(), isInPlace(), options, and mlir::bufferization::runOneShotBufferize().
Referenced by mlir::bufferization::analyzeOp().
isInPlace()
bool AnalysisBufferizationState::isInPlace (OpOperand & opOperand) const override virtual
Return true if the given OpResult has been decided to bufferize inplace.
Implements mlir::bufferization::BufferizationState.
Definition at line 209 of file OneShotAnalysis.cpp.
References mlir::bufferization::BufferizationAliasInfo::isInPlace().
The documentation for this class was generated from the following files:
include/mlir/Dialect/Bufferization/Transforms/OneShotAnalysis.h
lib/Dialect/Bufferization/Transforms/OneShotAnalysis.cpp