MLIR: mlir::IntegerPolyhedron Class Reference
mlir::IntegerPolyhedron Class Reference
An integer polyhedron is the set of solutions to a list of affine constraints over n integer-valued variables/identifiers.
#include "mlir/Analysis/Presburger/IntegerPolyhedron.h"
Public Types
enum Kind { Kind::FlatAffineConstraints, Kind::FlatAffineValueConstraints, Kind::IntegerPolyhedron }
All derived classes of IntegerPolyhedron.
enum IdKind { Dimension, Symbol, Local }
Kind of identifier (column).
enum BoundType { EQ, LB, UB }
The type of bound: equal, lower bound or upper bound.
Public Member Functions
IntegerPolyhedron (unsigned numReservedInequalities, unsigned numReservedEqualities, unsigned numReservedCols, unsigned numDims, unsigned numSymbols, unsigned numLocals)
Constructs a constraint system reserving memory for the specified number of constraints and identifiers.
IntegerPolyhedron (unsigned numDims=0, unsigned numSymbols=0, unsigned numLocals=0)
Constructs a constraint system with the specified number of dimensions and symbols.
virtual ~IntegerPolyhedron ()=default
virtual Kind getKind () const
Return the kind of this IntegerPolyhedron.
std::unique_ptr< IntegerPolyhedron > clone () const
virtual void reset (unsigned numReservedInequalities, unsigned numReservedEqualities, unsigned numReservedCols, unsigned numDims, unsigned numSymbols, unsigned numLocals=0)
Clears any existing data and reserves memory for the specified constraints.
void reset (unsigned numDims=0, unsigned numSymbols=0, unsigned numLocals=0)
void append (const IntegerPolyhedron &other)
Appends constraints from other into this.
int64_t atEq (unsigned i, unsigned j) const
Returns the value at the specified equality row and column.
int64_t & atEq (unsigned i, unsigned j)
int64_t atIneq (unsigned i, unsigned j) const
Returns the value at the specified inequality row and column.
int64_t & atIneq (unsigned i, unsigned j)
unsigned getNumConstraints () const
unsigned getNumIds () const
unsigned getNumDimIds () const
unsigned getNumSymbolIds () const
unsigned getNumDimAndSymbolIds () const
unsigned getNumLocalIds () const
unsigned getNumCols () const
Returns the number of columns in the constraint system.
unsigned getNumEqualities () const
unsigned getNumInequalities () const
unsigned getNumReservedEqualities () const
unsigned getNumReservedInequalities () const
ArrayRef< int64_t > getEquality (unsigned idx) const
ArrayRef< int64_t > getInequality (unsigned idx) const
unsigned insertDimId (unsigned pos, unsigned num=1)
Insert num identifiers of the specified kind at position pos.
unsigned insertSymbolId (unsigned pos, unsigned num=1)
unsigned insertLocalId (unsigned pos, unsigned num=1)
virtual unsigned insertId (IdKind kind, unsigned pos, unsigned num=1)
unsigned appendDimId (unsigned num=1)
Append num identifiers of the specified kind after the last identifier.
unsigned appendSymbolId (unsigned num=1)
unsigned appendLocalId (unsigned num=1)
void addInequality (ArrayRef< int64_t > inEq)
Adds an inequality (>= 0) from the coefficients specified in inEq.
void addEquality (ArrayRef< int64_t > eq)
Adds an equality from the coefficients specified in eq.
void removeId (IdKind kind, unsigned pos)
Removes identifiers of the specified kind with the specified pos (or within the specified range) from the system.
void removeIdRange (IdKind kind, unsigned idStart, unsigned idLimit)
void removeId (unsigned pos)
Removes the specified identifier from the system.
void removeEquality (unsigned pos)
void removeInequality (unsigned pos)
void removeEqualityRange (unsigned start, unsigned end)
Remove the (in)equalities at positions [start, end).
void removeInequalityRange (unsigned start, unsigned end)
virtual void swapId (unsigned posA, unsigned posB)
Swap the posA^th identifier with the posB^th identifier.
void clearConstraints ()
Removes all equalities and inequalities.
void setAndEliminate (unsigned pos, ArrayRef< int64_t > values)
Sets the values.size() identifiers starting at pos to the specified values and removes them.
virtual void clearAndCopyFrom (const IntegerPolyhedron &other)
Replaces the contents of this IntegerPolyhedron with other.
void getLowerAndUpperBoundIndices (unsigned pos, SmallVectorImpl< unsigned > *lbIndices, SmallVectorImpl< unsigned > *ubIndices, SmallVectorImpl< unsigned > *eqIndices=nullptr, unsigned offset=0, unsigned num=0) const
Gather positions of all lower and upper bounds of the identifier at pos, and optionally any equalities on it.
bool isEmpty () const
Checks for emptiness by performing variable elimination on all identifiers, running the GCD test on each equality constraint, and checking for invalid constraints.
bool isEmptyByGCDTest () const
Runs the GCD test on all equality constraints.
bool isIntegerEmpty () const
Returns true if the set of constraints is found to have no solution, false if a solution exists.
Matrix getBoundedDirections () const
Returns a matrix where each row is a vector along which the polytope is bounded.
Optional< SmallVector< int64_t, 8 > > findIntegerSample () const
Find an integer sample point satisfying the constraints using a branch and bound algorithm with generalized basis reduction, with some additional processing using Simplex for unbounded sets.
bool containsPoint (ArrayRef< int64_t > point) const
Returns true if the given point satisfies the constraints, or false otherwise.
void getLocalReprs (std::vector< SmallVector< int64_t, 8 >> &dividends, SmallVector< unsigned, 4 > &denominators, std::vector< presburger_utils::MaybeLocalRepr > &repr) const
Find pairs of inequalities identified by their position indices, using which an explicit representation for each local variable can be computed.
void getLocalReprs (std::vector< presburger_utils::MaybeLocalRepr > &repr) const
void getLocalReprs (std::vector< SmallVector< int64_t, 8 >> &dividends, SmallVector< unsigned, 4 > &denominators) const
void addBound (BoundType type, unsigned pos, int64_t value)
Adds a constant bound for the specified identifier.
void addBound (BoundType type, ArrayRef< int64_t > expr, int64_t value)
Adds a constant bound for the specified expression.
void addLocalFloorDiv (ArrayRef< int64_t > dividend, int64_t divisor)
Adds a new local identifier as the floordiv of an affine function of other identifiers, the coefficients of which are provided in dividend and with respect to a positive constant divisor.
void projectOut (unsigned pos, unsigned num)
Projects out (aka eliminates) num identifiers starting at position pos.
void projectOut (unsigned pos)
void setDimSymbolSeparation (unsigned newSymbolCount)
Changes the partition between dimensions and symbols.
LogicalResult constantFoldId (unsigned pos)
Tries to fold the specified identifier to a constant using a trivial equality detection; if successful, the constant is substituted for the identifier everywhere in the constraint system and then removed from the system.
void constantFoldIdRange (unsigned pos, unsigned num)
This method calls constantFoldId for the specified range of identifiers, num identifiers starting at position pos.
LogicalResult unionBoundingBox (const IntegerPolyhedron &other)
Updates the constraints to be the smallest bounding (enclosing) box that contains the points of this set and that of other, with the symbols being treated specially.
Optional< int64_t > getConstantBoundOnDimSize (unsigned pos, SmallVectorImpl< int64_t > *lb=nullptr, int64_t *boundFloorDivisor=nullptr, SmallVectorImpl< int64_t > *ub=nullptr, unsigned *minLbPos=nullptr, unsigned *minUbPos=nullptr) const
Returns the smallest known constant bound for the extent of the specified identifier (pos^th), i.e., the smallest known constant that is greater than or equal to 'exclusive upper bound' - 'lower bound' of the identifier.
Optional< int64_t > getConstantBound (BoundType type, unsigned pos) const
Returns the constant bound for the pos^th identifier if there is one; None otherwise.
void removeIndependentConstraints (unsigned pos, unsigned num)
Removes constraints that are independent of (i.e., do not have a coefficient) identifiers in the range [pos, pos + num).
bool isHyperRectangular (unsigned pos, unsigned num) const
Returns true if the set can be trivially detected as being hyper-rectangular on the specified contiguous set of identifiers.
void removeTrivialRedundancy ()
Removes duplicate constraints, trivially true constraints, and constraints that can be detected as redundant as a result of differing only in their constant term part.
void removeRedundantInequalities ()
A more expensive check than removeTrivialRedundancy to detect redundant inequalities.
void removeRedundantConstraints ()
Removes redundant constraints using Simplex.
void convertDimToLocal (unsigned dimStart, unsigned dimLimit)
Converts identifiers in the column range [idStart, idLimit) to local variables.
void mergeLocalIds (IntegerPolyhedron &other)
Adds additional local ids to the sets such that they both have the union of the local ids in each set, without changing the set of points that lie in this and other.
void print (raw_ostream &os) const
void dump () const
Static Public Member Functions
static IntegerPolyhedron getUniverse (unsigned numDims=0, unsigned numSymbols=0)
Return a system with no constraints, i.e., one which is satisfied by all points.
static bool classof (const IntegerPolyhedron *cst)
Protected Member Functions
bool hasInvalidConstraint () const
Checks all rows of equality/inequality constraints for trivial contradictions (for example: 1 == 0, 0 >= 1), which may have surfaced after elimination.
template<bool isLower>
Optional< int64_t > computeConstantLowerOrUpperBound (unsigned pos)
Returns the constant lower bound bound if isLower is true, and the upper bound if isLower is false.
LogicalResult gaussianEliminateId (unsigned position)
Eliminates a single identifier at position from equality and inequality constraints.
void removeRedundantLocalVars ()
Removes local variables using equalities.
unsigned gaussianEliminateIds (unsigned posStart, unsigned posLimit)
Eliminates identifiers from equality and inequality constraints in column range [posStart, posLimit).
virtual void fourierMotzkinEliminate (unsigned pos, bool darkShadow=false, bool *isResultIntegerExact=nullptr)
Eliminates the identifier at the specified position using Fourier-Motzkin variable elimination, but uses Gaussian elimination if there is an equality involving that identifier.
void gcdTightenInequalities ()
Tightens inequalities given that we are dealing with integer spaces.
void normalizeConstraintsByGCD ()
Normalized each constraints by the GCD of its coefficients.
bool findConstraintWithNonZeroAt (unsigned colIdx, bool isEq, unsigned *rowIdx) const
Searches for a constraint with a non-zero coefficient at colIdx in equality (isEq=true) or inequality (isEq=false) constraints.
bool isColZero (unsigned pos) const
Returns true if the pos^th column is all zero for both inequalities and equalities.
virtual bool hasConsistentState () const
Returns false if the fields corresponding to various identifier counts, or equality/inequality buffer sizes aren't consistent; true otherwise.
virtual void printSpace (raw_ostream &os) const
Prints the number of constraints, dimensions, symbols and locals in the IntegerPolyhedron.
unsigned getIdKindOffset (IdKind kind) const
Return the index at which the specified kind of id starts.
unsigned getNumIdKind (IdKind kind) const
Get the number of ids of the specified kind.
virtual void removeIdRange (unsigned idStart, unsigned idLimit)
Removes identifiers in the column range [idStart, idLimit), and copies any remaining valid data into place, updates member variables, and resizes arrays as needed.
Protected Attributes
unsigned numIds
Total number of identifiers.
unsigned numDims
Number of identifiers corresponding to real dimensions.
unsigned numSymbols
Number of identifiers corresponding to symbols (unknown but constant for analysis).
Matrix equalities
Coefficients of affine equalities (in == 0 form).
Matrix inequalities
Coefficients of affine inequalities (in >= 0 form).
Static Protected Attributes
static constexpr unsigned kExplosionFactor = 32
A parameter that controls detection of an unrealistic number of constraints.
Detailed Description
An integer polyhedron is the set of solutions to a list of affine constraints over n integer-valued variables/identifiers.
Affine constraints can be inequalities or equalities in the form:
Inequality: c_0*x_0 + c_1*x_1 + .... + c_{n-1}*x_{n-1} + c_n >= 0 Equality : c_0*x_0 + c_1*x_1 + .... + c_{n-1}*x_{n-1} + c_n == 0
where c_0, c_1, ..., c_n are integers.
Such a set corresponds to the set of integer points lying in a convex polyhedron. For example, consider the set: (x, y) : (1 <= x <= 7, x = 2y). This set contains the points (2, 1), (4, 2), and (6, 3).
The integer-valued variables are distinguished into 3 types of:
Dimension: Ordinary variables over which the set is represented.
Symbol: Symbol variables correspond to fixed but unknown values. Mathematically, an integer polyhedron with symbolic variables is like a family of integer polyhedra indexed by the symbolic variables.
Local: Local variables correspond to existentially quantified variables. For example, consider the set: (x) : (exists q : 1 <= x <= 7, x = 2q). An assignment to symbolic and dimension variables is valid if there exists some assignment to the local variable q satisfying these constraints. For this example, the set is equivalent to {2, 4, 6}. Mathematically, existential quantification can be thought of as the result of projection. In this example, q is existentially quantified. This can be thought of as the result of projecting out q from the previous example, i.e. we obtained {2, 4, 6} by projecting out the second dimension from {(2, 1), (4, 2), (6, 2)}.
Definition at line 53 of file IntegerPolyhedron.h.
Member Enumeration Documentation
BoundType
enum mlir::IntegerPolyhedron::BoundType
The type of bound: equal, lower bound or upper bound.
Enumerator
EQ
LB
UB
Definition at line 279 of file IntegerPolyhedron.h.
IdKind
enum mlir::IntegerPolyhedron::IdKind
Kind of identifier (column).
Enumerator
Dimension
Symbol
Local
Definition at line 63 of file IntegerPolyhedron.h.
Kind
enum mlir::IntegerPolyhedron::Kind strong
All derived classes of IntegerPolyhedron.
Enumerator
FlatAffineConstraints
FlatAffineValueConstraints
IntegerPolyhedron
Definition at line 56 of file IntegerPolyhedron.h.
Constructor & Destructor Documentation
IntegerPolyhedron() [1/2]
mlir::IntegerPolyhedron::IntegerPolyhedron (unsigned numReservedInequalities, unsigned numReservedEqualities, unsigned numReservedCols, unsigned numDims, unsigned numSymbols, unsigned numLocals) inline
Constructs a constraint system reserving memory for the specified number of constraints and identifiers.
Definition at line 67 of file IntegerPolyhedron.h.
References numIds.
IntegerPolyhedron() [2/2]
mlir::IntegerPolyhedron::IntegerPolyhedron (unsigned numDims = 0, unsigned numSymbols = 0, unsigned numLocals = 0) inline
Constructs a constraint system with the specified number of dimensions and symbols.
Definition at line 79 of file IntegerPolyhedron.h.
~IntegerPolyhedron()
virtual mlir::IntegerPolyhedron::~IntegerPolyhedron () virtual default
Referenced by getUniverse().
Member Function Documentation
addBound() [1/2]
void IntegerPolyhedron::addBound (BoundType type, unsigned pos, int64_t value)
Adds a constant bound for the specified identifier.
Definition at line 1174 of file IntegerPolyhedron.cpp.
References value.
Referenced by mlir::FlatAffineConstraints::classof().
addBound() [2/2]
void IntegerPolyhedron::addBound (BoundType type, ArrayRef< int64_t > expr, int64_t value)
Adds a constant bound for the specified expression.
Definition at line 1188 of file IntegerPolyhedron.cpp.
addEquality()
void IntegerPolyhedron::addEquality (ArrayRef< int64_t > eq)
Adds an equality from the coefficients specified in eq.
Definition at line 112 of file IntegerPolyhedron.cpp.
Referenced by mlir::FlatAffineValueConstraints::addAffineForOpDomain(), mlir::FlatAffineConstraints::addBound(), addOrderingConstraints(), mlir::FlatAffineConstraints::composeMatchingMap(), computeDirectionVector(), mlir::FlatAffineConstraints::FlatAffineConstraints(), getCommonConstraints(), and mlir::getRelationFromMap().
addInequality()
void IntegerPolyhedron::addInequality (ArrayRef< int64_t > inEq)
Adds an inequality (>= 0) from the coefficients specified in inEq.
Definition at line 119 of file IntegerPolyhedron.cpp.
Referenced by mlir::FlatAffineConstraints::addBound(), addLoopRangeConstraints(), addOrderingConstraints(), canonicalizeMinMaxOp(), mlir::FlatAffineConstraints::FlatAffineConstraints(), getCommonConstraints(), mlir::scf::rewritePeeledMinMaxOp(), and subtractRecursively().
addLocalFloorDiv()
void IntegerPolyhedron::addLocalFloorDiv (ArrayRef< int64_t > dividend, int64_t divisor)
Adds a new local identifier as the floordiv of an affine function of other identifiers, the coefficients of which are provided in dividend and with respect to a positive constant divisor.
Adds a new local identifier as the floordiv of an affine function of other identifiers, the coefficients of which are provided in 'dividend' and with respect to a positive constant 'divisor'.
Two constraints are added to the system to capture equivalence with the floordiv: q = dividend floordiv c <=> c*q <= dividend <= c*q + c - 1.
Two constraints are added to the system to capture equivalence with the floordiv. q = expr floordiv c <=> c*q <= expr <= c*q + c - 1.
Definition at line 1204 of file IntegerPolyhedron.cpp.
References copy().
Referenced by mlir::FlatAffineValueConstraints::addAffineForOpDomain().
append()
void IntegerPolyhedron::append (const IntegerPolyhedron & other)
Appends constraints from other into this.
This is equivalent to an intersection with no simplification of any sort attempted.
Definition at line 49 of file IntegerPolyhedron.cpp.
References getEquality(), getInequality(), getNumCols(), getNumDimIds(), getNumEqualities(), getNumInequalities(), and getNumSymbolIds().
Referenced by mlir::FlatAffineValueConstraints::addAffineIfOpDomain(), classof(), mlir::FlatAffineRelation::compose(), mlir::FlatAffineConstraints::FlatAffineConstraints(), mlir::FlatAffineConstraints::flattenAlignedMapAndMergeLocals(), mlir::MemRefAccess::getAccessRelation(), and mlir::PresburgerSet::intersect().
appendDimId()
unsigned IntegerPolyhedron::appendDimId (unsigned num = 1)
Append num identifiers of the specified kind after the last identifier.
of that kind. Return the position of the first appended column. The coefficient columns corresponding to the added identifiers are initialized to zero.
Definition at line 94 of file IntegerPolyhedron.cpp.
Referenced by mlir::getRelationFromMap().
appendLocalId()
unsigned IntegerPolyhedron::appendLocalId (unsigned num = 1)
Definition at line 106 of file IntegerPolyhedron.cpp.
Referenced by mlir::FlatAffineConstraints::FlatAffineConstraints(), and mlir::FlatAffineConstraints::flattenAlignedMapAndMergeLocals().
appendSymbolId()
unsigned IntegerPolyhedron::appendSymbolId (unsigned num = 1)
Definition at line 100 of file IntegerPolyhedron.cpp.
atEq() [1/2]
int64_t mlir::IntegerPolyhedron::atEq (unsigned i, unsigned j) const inline
Returns the value at the specified equality row and column.
Definition at line 119 of file IntegerPolyhedron.h.
References equalities.
Referenced by detectAsMod(), eliminateFromConstraint(), eliminateRedundantLocalId(), eqInvolvesSuffixDims(), findEqualityToConstant(), getIndependentConstraints(), mlir::FlatAffineConstraints::getSliceBounds(), and normalizeConstraintByGCD().
atEq() [2/2]
int64_t& mlir::IntegerPolyhedron::atEq (unsigned i, unsigned j) inline
Definition at line 120 of file IntegerPolyhedron.h.
References equalities.
atIneq() [1/2]
int64_t mlir::IntegerPolyhedron::atIneq (unsigned i, unsigned j) const inline
Returns the value at the specified inequality row and column.
Definition at line 123 of file IntegerPolyhedron.h.
References inequalities.
Referenced by createSeparationCondition(), eliminateFromConstraint(), eliminateRedundantLocalId(), fillInequality(), findIntegerSample(), getBestIdToEliminate(), getDivRepr(), getIndependentConstraints(), ineqInvolvesSuffixDims(), negateInequality(), normalizeConstraintByGCD(), and removeRedundantInequalities().
atIneq() [2/2]
int64_t& mlir::IntegerPolyhedron::atIneq (unsigned i, unsigned j) inline
Definition at line 126 of file IntegerPolyhedron.h.
References inequalities.
classof()
static bool mlir::IntegerPolyhedron::classof (const IntegerPolyhedron * cst) inline static
Definition at line 99 of file IntegerPolyhedron.h.
References append(), clone(), numDims, numSymbols, and reset().
clearAndCopyFrom()
void IntegerPolyhedron::clearAndCopyFrom (const IntegerPolyhedron & other) virtual
Replaces the contents of this IntegerPolyhedron with other.
Reimplemented in mlir::FlatAffineValueConstraints, and mlir::FlatAffineConstraints.
Definition at line 317 of file IntegerPolyhedron.cpp.
clearConstraints()
void IntegerPolyhedron::clearConstraints ()
Removes all equalities and inequalities.
Definition at line 227 of file IntegerPolyhedron.cpp.
clone()
std::unique_ptr< IntegerPolyhedron > IntegerPolyhedron::clone () const
Definition at line 28 of file IntegerPolyhedron.cpp.
Referenced by classof().
computeConstantLowerOrUpperBound()
template<bool isLower> Optional< int64_t > IntegerPolyhedron::computeConstantLowerOrUpperBound (unsigned pos) protected
Returns the constant lower bound bound if isLower is true, and the upper bound if isLower is false.
Definition at line 1427 of file IntegerPolyhedron.cpp.
References mlir::ceilDiv(), findEqualityToConstant(), mlir::floorDiv(), and mlir::presburger_utils::None.
Referenced by getConstantBound(), and projectOut().
constantFoldId()
LogicalResult IntegerPolyhedron::constantFoldId (unsigned pos)
Tries to fold the specified identifier to a constant using a trivial equality detection; if successful, the constant is substituted for the identifier everywhere in the constraint system and then removed from the system.
Definition at line 1265 of file IntegerPolyhedron.cpp.
References mlir::failure(), findEqualityToConstant(), and mlir::success().
Referenced by projectOut().
constantFoldIdRange()
void IntegerPolyhedron::constantFoldIdRange (unsigned pos, unsigned num)
This method calls constantFoldId for the specified range of identifiers, num identifiers starting at position pos.
Definition at line 1278 of file IntegerPolyhedron.cpp.
References mlir::failed().
Referenced by projectOut().
containsPoint()
bool IntegerPolyhedron::containsPoint (ArrayRef< int64_t > point) const
Returns true if the given point satisfies the constraints, or false otherwise.
A point satisfies an equality iff the value of the equality at the expression is zero, and it satisfies an inequality iff the value of the inequality at that point is non-negative.
Definition at line 791 of file IntegerPolyhedron.cpp.
References getLocalReprs(), and valueAt().
Referenced by mlir::PresburgerSet::containsPoint(), and findIntegerSample().
convertDimToLocal()
void IntegerPolyhedron::convertDimToLocal (unsigned dimStart, unsigned dimLimit)
Converts identifiers in the column range [idStart, idLimit) to local variables.
Definition at line 1154 of file IntegerPolyhedron.cpp.
Referenced by mlir::FlatAffineRelation::compose(), mlir::FlatAffineRelation::getDomainSet(), mlir::FlatAffineRelation::getRangeSet(), and projectOut().
dump()
void IntegerPolyhedron::dump () const
Definition at line 2089 of file IntegerPolyhedron.cpp.
References print().
Referenced by mlir::checkMemrefAccessDependence(), mlir::FlatAffineConstraints::getAsIntegerSet(), mlir::FlatAffineConstraints::getSliceBounds(), mlir::ComputationSliceState::isSliceValid(), and projectOut().
findConstraintWithNonZeroAt()
bool IntegerPolyhedron::findConstraintWithNonZeroAt (unsigned colIdx, bool isEq, unsigned * rowIdx) const protected
Searches for a constraint with a non-zero coefficient at colIdx in equality (isEq=true) or inequality (isEq=false) constraints.
Returns true and sets row found in search in rowIdx, false otherwise.
Definition at line 324 of file IntegerPolyhedron.cpp.
Referenced by gaussianEliminateId(), and mlir::FlatAffineConstraints::getSliceBounds().
findIntegerSample()
Optional< SmallVector< int64_t, 8 > > IntegerPolyhedron::findIntegerSample () const
Find an integer sample point satisfying the constraints using a branch and bound algorithm with generalized basis reduction, with some additional processing using Simplex for unbounded sets.
Let this set be S.
Returns an integer sample point if one exists, or an empty Optional otherwise.
If S is bounded then we directly call into the GBR sampling algorithm. Otherwise, there are some unbounded directions, i.e., vectors v such that S extends to infinity along v or -v. In this case we use an algorithm described in the integer set library (isl) manual and used by the isl_set_sample function in that library. The algorithm is:
1) Apply a unimodular transform T to S to obtain S*T, such that all dimensions in which S*T is bounded lie in the linear span of a prefix of the dimensions.
2) Construct a set B by removing all constraints that involve the unbounded dimensions and then deleting the unbounded dimensions. Note that B is a Bounded set.
3) Try to obtain a sample from B using the GBR sampling algorithm. If no sample is found, return that S is empty.
4) Otherwise, substitute the obtained sample into S*T to obtain a set C. C is a full-dimensional Cone and always contains a sample.
5) Obtain an integer sample from C.
6) Return T*v, where v is the concatenation of the samples from B and C.
The following is a sketch of a proof that a) If the algorithm returns empty, then S is empty. b) If the algorithm returns a sample, it is a valid sample in S.
The algorithm returns empty only if B is empty, in which case S*T is certainly empty since B was obtained by removing constraints and then deleting unconstrained dimensions from S*T. Since T is unimodular, a vector v is in S*T iff T*v is in S. So in this case, since S*T is empty, S is empty too.
Otherwise, the algorithm substitutes the sample from B into S*T. All the constraints of S*T that did not involve unbounded dimensions are satisfied by this substitution. All dimensions in the linear span of the dimensions outside the prefix are unbounded in S*T (step 1). Substituting values for the bounded dimensions cannot make these dimensions bounded, and these are the only remaining dimensions in C, so C is unbounded along every vector (in the positive or negative direction, or both). C is hence a full-dimensional cone and therefore always contains an integer point.
Concatenating the samples from B and C gives a sample v in S*T, so the returned sample T*v is a sample in S.
Definition at line 674 of file IntegerPolyhedron.cpp.
References mlir::LinearTransform::applyTo(), atIneq(), mlir::ceil(), containsPoint(), mlir::Simplex::findIntegerSample(), getNumIds(), getNumInequalities(), mlir::SimplexBase::getRationalSample(), mlir::SimplexBase::isEmpty(), mlir::Simplex::isUnbounded(), mlir::LinearTransform::makeTransformToColumnEchelon(), mlir::LinearTransform::postMultiplyWithColumn(), removeConstraintsInvolvingSuffixDims(), removeIdRange(), and setAndEliminate().
Referenced by mlir::PresburgerSet::findIntegerSample().
fourierMotzkinEliminate()
void IntegerPolyhedron::fourierMotzkinEliminate (unsigned pos, bool darkShadow = false, bool * isResultIntegerExact = nullptr) protected virtual
Eliminates the identifier at the specified position using Fourier-Motzkin variable elimination, but uses Gaussian elimination if there is an equality involving that identifier.
If the result of the elimination is integer exact, *isResultIntegerExact is set to true. If darkShadow is set to true, a potential under approximation (subset) of the rational shadow / exact integer shadow is computed.
Create the new system which has one identifier less.
Reimplemented in mlir::FlatAffineValueConstraints.
Definition at line 1653 of file IntegerPolyhedron.cpp.
References getNewNumDimsSymbols(), mlir::lcm(), and mlir::succeeded().
Referenced by mlir::FlatAffineValueConstraints::fourierMotzkinEliminate(), gaussianEliminateId(), isEmpty(), and mlir::FlatAffineValueConstraints::setValues().
gaussianEliminateId()
LogicalResult mlir::IntegerPolyhedron::gaussianEliminateId (unsigned position) inline protected
Eliminates a single identifier at position from equality and inequality constraints.
Returns success if the identifier was eliminated, and failure otherwise.
Definition at line 424 of file IntegerPolyhedron.h.
References findConstraintWithNonZeroAt(), fourierMotzkinEliminate(), gaussianEliminateIds(), gcdTightenInequalities(), getIdKindOffset(), getNumIdKind(), hasConsistentState(), isColZero(), normalizeConstraintsByGCD(), printSpace(), removeIdRange(), removeRedundantLocalVars(), and mlir::success().
gaussianEliminateIds()
unsigned IntegerPolyhedron::gaussianEliminateIds (unsigned posStart, unsigned posLimit) protected
Eliminates identifiers from equality and inequality constraints in column range [posStart, posLimit).
Returns the number of variables eliminated.
Definition at line 884 of file IntegerPolyhedron.cpp.
References eliminateFromConstraint(), and normalizeConstraintByGCD().
Referenced by gaussianEliminateId(), and isEmpty().
gcdTightenInequalities()
void IntegerPolyhedron::gcdTightenInequalities () protected
Tightens inequalities given that we are dealing with integer spaces.
This is similar to the GCD test but applied to inequalities. The constant term can be reduced to the preceding multiple of the GCD of the coefficients, i.e., 64*i - 100 >= 0 => 64*i - 128 >= 0 (since 'i' is an integer). This is a fast method (linear in the number of coefficients).
This is analogous to the GCD test but applied to inequalities. The constant term can be reduced to the preceding multiple of the GCD of the coefficients, i.e., 64*i - 100 >= 0 => 64*i - 128 >= 0 (since 'i' is an integer). This is a fast method - linear in the number of coefficients.
Definition at line 865 of file IntegerPolyhedron.cpp.
References mlir::floorDiv().
Referenced by gaussianEliminateId().
getBoundedDirections()
Matrix IntegerPolyhedron::getBoundedDirections () const
Returns a matrix where each row is a vector along which the polytope is bounded.
The span of the returned vectors is guaranteed to contain all such vectors. The returned vectors are NOT guaranteed to be linearly independent. This function should not be called on empty sets.
Definition at line 557 of file IntegerPolyhedron.cpp.
References mlir::Simplex::isBoundedAlongConstraint(), and mlir::SimplexBase::isEmpty().
getConstantBound()
Optional< int64_t > IntegerPolyhedron::getConstantBound (BoundType type, unsigned pos) const
Returns the constant bound for the pos^th identifier if there is one; None otherwise.
Definition at line 1483 of file IntegerPolyhedron.cpp.
References computeConstantLowerOrUpperBound().
Referenced by computeDirectionVector(), detectAsMod(), mlir::FlatAffineConstraints::getSliceBounds(), mlir::normalizeMemRefType(), and projectOut().
getConstantBoundOnDimSize()
Optional< int64_t > IntegerPolyhedron::getConstantBoundOnDimSize (unsigned pos, SmallVectorImpl< int64_t > * lb = nullptr, int64_t * boundFloorDivisor = nullptr, SmallVectorImpl< int64_t > * ub = nullptr, unsigned * minLbPos = nullptr, unsigned * minUbPos = nullptr) const
Returns the smallest known constant bound for the extent of the specified identifier (pos^th), i.e., the smallest known constant that is greater than or equal to 'exclusive upper bound' - 'lower bound' of the identifier.
Returns a non-negative constant bound on the extent (upper bound - lower bound) of the specified identifier if it is found to be a constant; returns None if it's not a constant.
This constant bound is guaranteed to be non-negative. Returns None if it's not a constant. This method employs trivial (low complexity / cost) checks and detection. Symbolic identifiers are treated specially, i.e., it looks for constant differences between affine expressions involving only the symbolic identifiers. lb and ub (along with the boundFloorDivisor) are set to represent the lower and upper bound associated with the constant difference: lb, ub have the coefficients, and boundFloorDivisor, their divisor. minLbPos and minUbPos if non-null are set to the position of the constant lower bound and upper bound respectively (to the same if they are from an equality). Ex: if the lower bound is [(s0 + s2 - 1) floordiv 32] for a system with three symbolic identifiers, *lb = [1, 0, 1], lbDivisor = 32. See comments at function definition for examples.
This methods treats symbolic identifiers specially, i.e., it looks for constant differences between affine expressions involving only the symbolic identifiers. See comments at function definition for example. 'lb', if provided, is set to the lower bound associated with the constant difference. Note that 'lb' is purely symbolic and thus will contain the coefficients of the symbolic identifiers and the constant coefficient.
Definition at line 1299 of file IntegerPolyhedron.cpp.
References mlir::ceilDiv(), findEqualityToConstant(), and mlir::presburger_utils::None.
Referenced by createFullTiles(), createSeparationCondition(), projectOut(), and unionBoundingBox().
getEquality()
ArrayRef<int64_t> mlir::IntegerPolyhedron::getEquality (unsigned idx) const inline
Definition at line 156 of file IntegerPolyhedron.h.
References equalities, and mlir::Matrix::getRow().
Referenced by append(), mlir::LinearTransform::applyTo(), mlir::FlatAffineConstraints::getAsIntegerSet(), getCommonConstraints(), mlir::FlatAffineConstraints::getLowerAndUpperBound(), mlir::SimplexBase::intersectIntegerPolyhedron(), mlir::Simplex::isRationalSubsetOf(), mlir::SimplexBase::SimplexBase(), and subtractRecursively().
getIdKindOffset()
unsigned IntegerPolyhedron::getIdKindOffset (IdKind kind) const protected
Return the index at which the specified kind of id starts.
Definition at line 207 of file IntegerPolyhedron.cpp.
Referenced by gaussianEliminateId().
getInequality()
ArrayRef<int64_t> mlir::IntegerPolyhedron::getInequality (unsigned idx) const inline
Definition at line 160 of file IntegerPolyhedron.h.
References mlir::Matrix::getRow(), inequalities, insertDimId(), insertId(), insertLocalId(), and insertSymbolId().
Referenced by append(), mlir::LinearTransform::applyTo(), createSeparationCondition(), mlir::FlatAffineConstraints::getAsIntegerSet(), getCommonConstraints(), mlir::FlatAffineValueConstraints::getIneqAsAffineValueMap(), mlir::FlatAffineConstraints::getLowerAndUpperBound(), mlir::SimplexBase::intersectIntegerPolyhedron(), mlir::Simplex::isRationalSubsetOf(), mlir::SimplexBase::SimplexBase(), and subtractRecursively().
getKind()
virtual Kind mlir::IntegerPolyhedron::getKind () const inline virtual
Return the kind of this IntegerPolyhedron.
Reimplemented in mlir::FlatAffineValueConstraints, and mlir::FlatAffineConstraints.
Definition at line 97 of file IntegerPolyhedron.h.
References IntegerPolyhedron.
Referenced by mlir::FlatAffineConstraints::classof(), and mlir::FlatAffineValueConstraints::classof().
getLocalReprs() [1/3]
void mlir::IntegerPolyhedron::getLocalReprs (std::vector< SmallVector< int64_t, 8 >> & dividends, SmallVector< unsigned, 4 > & denominators, std::vector< presburger_utils::MaybeLocalRepr > & repr) const
Find pairs of inequalities identified by their position indices, using which an explicit representation for each local variable can be computed.
The pairs are stored as indices of upperbound, lowerbound inequalities. If no such pair can be found, it is stored as llvm::None.
The dividends of the explicit representations are stored in dividends and the denominators in denominators. If no explicit representation could be found for the i^th local identifier, denominators[i] is set to 0.
Referenced by containsPoint(), getLocalReprs(), mergeLocalIds(), and subtractRecursively().
getLocalReprs() [2/3]
void mlir::IntegerPolyhedron::getLocalReprs (std::vector< presburger_utils::MaybeLocalRepr > & repr) const
getLocalReprs() [3/3]
void IntegerPolyhedron::getLocalReprs (std::vector< SmallVector< int64_t, 8 >> & dividends, SmallVector< unsigned, 4 > & denominators) const
Definition at line 809 of file IntegerPolyhedron.cpp.
References getLocalReprs().
getLowerAndUpperBoundIndices()
void IntegerPolyhedron::getLowerAndUpperBoundIndices (unsigned pos, SmallVectorImpl< unsigned > * lbIndices, SmallVectorImpl< unsigned > * ubIndices, SmallVectorImpl< unsigned > * eqIndices = nullptr, unsigned offset = 0, unsigned num = 0) const
Gather positions of all lower and upper bounds of the identifier at pos, and optionally any equalities on it.
Gather all lower and upper bounds of the identifier at pos, and optionally any equalities on it.
In addition, the bounds are to be independent of identifiers in position range [offset, offset + num).
Definition at line 235 of file IntegerPolyhedron.cpp.
Referenced by mlir::presburger_utils::computeSingleVarRepr(), createSeparationCondition(), and mlir::FlatAffineConstraints::getLowerAndUpperBound().
getNumCols()
unsigned mlir::IntegerPolyhedron::getNumCols () const inline
Returns the number of columns in the constraint system.
Definition at line 140 of file IntegerPolyhedron.h.
References numIds.
Referenced by mlir::FlatAffineValueConstraints::addAffineForOpDomain(), mlir::FlatAffineConstraints::addBound(), addLoopRangeConstraints(), addOrderingConstraints(), append(), canonicalizeMinMaxOp(), mlir::FlatAffineConstraints::composeMatchingMap(), computeDirectionVector(), createSeparationCondition(), detectAsMod(), eliminateFromConstraint(), fillInequality(), mlir::FlatAffineConstraints::FlatAffineConstraints(), generateCopy(), getDivRepr(), mlir::FlatAffineValueConstraints::getIneqAsAffineValueMap(), mlir::getRelationFromMap(), negateInequality(), normalizeConstraintByGCD(), and removeRedundantInequalities().
getNumConstraints()
unsigned mlir::IntegerPolyhedron::getNumConstraints () const inline
Definition at line 128 of file IntegerPolyhedron.h.
References getNumEqualities(), and getNumInequalities().
Referenced by mlir::FlatAffineConstraints::getAsIntegerSet(), and isEmpty().
getNumDimAndSymbolIds()
unsigned mlir::IntegerPolyhedron::getNumDimAndSymbolIds () const inline
Definition at line 134 of file IntegerPolyhedron.h.
References numSymbols.
Referenced by mlir::FlatAffineConstraints::addBound(), mlir::computeSliceUnion(), mlir::FlatAffineValueConstraints::convertLoopIVSymbolsToDims(), createFullTiles(), createSeparationCondition(), detectAsMod(), eliminateRedundantLocalId(), mlir::FlatAffineConstraints::getAsIntegerSet(), mlir::getComputationSliceState(), mlir::FlatAffineValueConstraints::getIneqAsAffineValueMap(), mlir::FlatAffineConstraints::getLowerAndUpperBound(), mlir::getRelationFromMap(), mlir::FlatAffineConstraints::getSliceBounds(), mergeAndAlignIds(), mlir::FlatAffineValueConstraints::mergeSymbolIds(), and turnSymbolIntoDim().
getNumDimIds()
unsigned mlir::IntegerPolyhedron::getNumDimIds () const inline
Definition at line 132 of file IntegerPolyhedron.h.
References numDims.
Referenced by mlir::FlatAffineConstraints::addBound(), mlir::FlatAffineValueConstraints::addDomainFromSliceMaps(), addLoopRangeConstraints(), addMissingLoopIVBounds(), addOrderingConstraints(), append(), mlir::FlatAffineValueConstraints::appendDimId(), mlir::FlatAffineRelation::appendRangeId(), areIdsAligned(), assertDimensionsCompatible(), mlir::FlatAffineConstraints::composeMatchingMap(), computeDirectionVector(), computeLocalVars(), mlir::computeSliceUnion(), mlir::FlatAffineValueConstraints::convertLoopIVSymbolsToDims(), detectAsMod(), findEqualityToConstant(), generateCopy(), mlir::MemRefAccess::getAccessRelation(), mlir::FlatAffineConstraints::getAsIntegerSet(), getCommonConstraints(), mlir::FlatAffineValueConstraints::getIneqAsAffineValueMap(), mlir::FlatAffineConstraints::getLowerAndUpperBound(), mlir::FlatAffineValueConstraints::getMaybeDimAndSymbolValues(), mlir::FlatAffineValueConstraints::getMaybeDimValues(), mlir::FlatAffineValueConstraints::getMaybeSymbolValues(), getNewNumDimsSymbols(), getNumCommonLoops(), mlir::getRelationFromMap(), mlir::FlatAffineConstraints::getSliceBounds(), mlir::linalg::getUpperBoundForIndex(), mlir::ComputationSliceState::isMaximal(), mergeAndAlignIds(), mergeLocalIds(), mlir::FlatAffineValueConstraints::mergeSymbolIds(), mlir::FlatAffineRelation::removeIdRange(), subtractRecursively(), turnSymbolIntoDim(), unionBoundingBox(), and mlir::FlatAffineValueConstraints::unionBoundingBox().
getNumEqualities()
unsigned mlir::IntegerPolyhedron::getNumEqualities () const inline
Definition at line 142 of file IntegerPolyhedron.h.
References equalities, and mlir::Matrix::getNumRows().
Referenced by append(), mlir::LinearTransform::applyTo(), detectAsMod(), eliminateRedundantLocalId(), findEqualityToConstant(), mlir::FlatAffineConstraints::getAsIntegerSet(), getCommonConstraints(), getIndependentConstraints(), getNumConstraints(), mlir::SimplexBase::intersectIntegerPolyhedron(), mlir::Simplex::isRationalSubsetOf(), removeConstraintsInvolvingSuffixDims(), mlir::SimplexBase::SimplexBase(), and subtractRecursively().
getNumIdKind()
unsigned IntegerPolyhedron::getNumIdKind (IdKind kind) const protected
Get the number of ids of the specified kind.
Definition at line 217 of file IntegerPolyhedron.cpp.
Referenced by gaussianEliminateId().
getNumIds()
unsigned mlir::IntegerPolyhedron::getNumIds () const inline
Definition at line 131 of file IntegerPolyhedron.h.
References numIds.
Referenced by mlir::LinearTransform::applyTo(), areIdsAligned(), areIdsUnique(), computeDirectionVector(), mlir::presburger_utils::computeSingleVarRepr(), detectAsFloorDiv(), detectAsMod(), eqInvolvesSuffixDims(), findEqualityToConstant(), findIntegerSample(), mlir::FlatAffineValueConstraints::fourierMotzkinEliminate(), generateCopy(), mlir::FlatAffineConstraints::getAsIntegerSet(), getBestIdToEliminate(), getDivRepr(), getIndependentConstraints(), mlir::FlatAffineValueConstraints::getIneqAsAffineValueMap(), mlir::FlatAffineConstraints::getSliceBounds(), mlir::FlatAffineValueConstraints::hasConsistentState(), ineqInvolvesSuffixDims(), mlir::SimplexBase::intersectIntegerPolyhedron(), isEmpty(), mlir::ComputationSliceState::isSliceValid(), mlir::normalizeMemRefType(), and mlir::FlatAffineConstraints::printSpace().
getNumInequalities()
unsigned mlir::IntegerPolyhedron::getNumInequalities () const inline
Definition at line 144 of file IntegerPolyhedron.h.
References mlir::Matrix::getNumRows(), and inequalities.
Referenced by append(), mlir::LinearTransform::applyTo(), eliminateRedundantLocalId(), findIntegerSample(), mlir::FlatAffineConstraints::getAsIntegerSet(), getBestIdToEliminate(), getCommonConstraints(), getDivRepr(), getIndependentConstraints(), mlir::FlatAffineValueConstraints::getIneqAsAffineValueMap(), getNumConstraints(), mlir::SimplexBase::intersectIntegerPolyhedron(), mlir::Simplex::isRationalSubsetOf(), removeConstraintsInvolvingSuffixDims(), mlir::SimplexBase::SimplexBase(), and subtractRecursively().
getNumLocalIds()
unsigned mlir::IntegerPolyhedron::getNumLocalIds () const inline
Definition at line 135 of file IntegerPolyhedron.h.
References numIds, and numSymbols.
Referenced by computeLocalVars(), mlir::computeSliceUnion(), eliminateRedundantLocalId(), mlir::FlatAffineConstraints::FlatAffineConstraints(), mlir::FlatAffineConstraints::flattenAlignedMapAndMergeLocals(), mlir::FlatAffineConstraints::getAsIntegerSet(), getCommonConstraints(), mlir::FlatAffineValueConstraints::getIneqAsAffineValueMap(), mlir::FlatAffineConstraints::getLowerAndUpperBound(), mlir::FlatAffineConstraints::getSliceBounds(), mlir::ComputationSliceState::isSliceValid(), mergeLocalIds(), mlir::normalizeMemRefType(), subtractRecursively(), unionBoundingBox(), and mlir::FlatAffineValueConstraints::unionBoundingBox().
getNumReservedEqualities()
unsigned mlir::IntegerPolyhedron::getNumReservedEqualities () const inline
Definition at line 148 of file IntegerPolyhedron.h.
References equalities, and mlir::Matrix::getNumReservedRows().
getNumReservedInequalities()
unsigned mlir::IntegerPolyhedron::getNumReservedInequalities () const inline
Definition at line 152 of file IntegerPolyhedron.h.
References mlir::Matrix::getNumReservedRows(), and inequalities.
getNumSymbolIds()
unsigned mlir::IntegerPolyhedron::getNumSymbolIds () const inline
Definition at line 133 of file IntegerPolyhedron.h.
References numSymbols.
Referenced by mlir::FlatAffineConstraints::addBound(), addLoopRangeConstraints(), append(), mlir::FlatAffineValueConstraints::appendSymbolId(), areIdsAligned(), assertDimensionsCompatible(), mlir::FlatAffineConstraints::composeMatchingMap(), computeLocalVars(), detectAsMod(), generateCopy(), mlir::FlatAffineConstraints::getAsIntegerSet(), getCommonConstraints(), mlir::FlatAffineValueConstraints::getIneqAsAffineValueMap(), mlir::FlatAffineValueConstraints::getMaybeDimAndSymbolValues(), mlir::FlatAffineValueConstraints::getMaybeSymbolValues(), getNewNumDimsSymbols(), mlir::FlatAffineConstraints::getSliceBounds(), mlir::ComputationSliceState::isSliceValid(), mergeLocalIds(), mlir::FlatAffineValueConstraints::mergeSymbolIds(), subtractRecursively(), and turnSymbolIntoDim().
getUniverse()
static IntegerPolyhedron mlir::IntegerPolyhedron::getUniverse (unsigned numDims = 0, unsigned numSymbols = 0) inline static
Return a system with no constraints, i.e., one which is satisfied by all points.
Definition at line 89 of file IntegerPolyhedron.h.
References IntegerPolyhedron, numDims, numSymbols, and ~IntegerPolyhedron().
Referenced by mlir::PresburgerSet::complement(), and mlir::PresburgerSet::getUniverse().
hasConsistentState()
bool IntegerPolyhedron::hasConsistentState () const protected virtual
Returns false if the fields corresponding to various identifier counts, or equality/inequality buffer sizes aren't consistent; true otherwise.
This is meant to be used within an assert internally.
Reimplemented in mlir::FlatAffineValueConstraints.
Definition at line 286 of file IntegerPolyhedron.cpp.
Referenced by gaussianEliminateId(), mlir::FlatAffineValueConstraints::hasConsistentState(), and mlir::FlatAffineValueConstraints::setValues().
hasInvalidConstraint()
bool IntegerPolyhedron::hasInvalidConstraint () const protected
Checks all rows of equality/inequality constraints for trivial contradictions (for example: 1 == 0, 0 >= 1), which may have surfaced after elimination.
Returns true if an invalid constraint is found; false otherwise.
Definition at line 370 of file IntegerPolyhedron.cpp.
Referenced by isEmpty(), and projectOut().
insertDimId()
unsigned IntegerPolyhedron::insertDimId (unsigned pos, unsigned num = 1)
Insert num identifiers of the specified kind at position pos.
Positions are relative to the kind of identifier. The coefficient columns corresponding to the added identifiers are initialized to zero. Return the absolute column position (i.e., not relative to the kind of identifier) of the first added identifier.
Definition at line 66 of file IntegerPolyhedron.cpp.
Referenced by mlir::FlatAffineValueConstraints::classof(), and getInequality().
insertId()
unsigned IntegerPolyhedron::insertId (IdKind kind, unsigned pos, unsigned num = 1) virtual
Reimplemented in mlir::FlatAffineValueConstraints.
Definition at line 78 of file IntegerPolyhedron.cpp.
Referenced by mlir::FlatAffineValueConstraints::classof(), and getInequality().
insertLocalId()
unsigned IntegerPolyhedron::insertLocalId (unsigned pos, unsigned num = 1)
Definition at line 74 of file IntegerPolyhedron.cpp.
Referenced by mlir::FlatAffineConstraints::flattenAlignedMapAndMergeLocals(), getInequality(), and mergeLocalIds().
insertSymbolId()
unsigned IntegerPolyhedron::insertSymbolId (unsigned pos, unsigned num = 1)
Definition at line 70 of file IntegerPolyhedron.cpp.
Referenced by mlir::FlatAffineValueConstraints::classof(), and getInequality().
isColZero()
bool IntegerPolyhedron::isColZero (unsigned pos) const protected
Returns true if the pos^th column is all zero for both inequalities and equalities.
Definition at line 2010 of file IntegerPolyhedron.cpp.
Referenced by gaussianEliminateId(), and mlir::FlatAffineConstraints::getAsIntegerSet().
isEmpty()
bool IntegerPolyhedron::isEmpty () const
Checks for emptiness by performing variable elimination on all identifiers, running the GCD test on each equality constraint, and checking for invalid constraints.
Returns true if the GCD test fails for any equality, or if any invalid constraints are discovered on any row. Returns false otherwise.
Definition at line 473 of file IntegerPolyhedron.cpp.
References fourierMotzkinEliminate(), gaussianEliminateIds(), getBestIdToEliminate(), getNumConstraints(), getNumIds(), hasInvalidConstraint(), isEmptyByGCDTest(), and removeRedundantLocalVars().
Referenced by canonicalizeMinMaxOp(), mlir::checkMemrefAccessDependence(), mlir::PresburgerSet::intersect(), removeRedundantInequalities(), and mlir::simplifyIntegerSet().
isEmptyByGCDTest()
bool IntegerPolyhedron::isEmptyByGCDTest () const
Runs the GCD test on all equality constraints.
Returns true if this test fails on any equality. Returns false otherwise. This test can be used to disprove the existence of a solution. If it returns true, no integer solution to the equality constraints can exist.
Definition at line 534 of file IntegerPolyhedron.cpp.
Referenced by isEmpty(), and subtractRecursively().
isHyperRectangular()
bool IntegerPolyhedron::isHyperRectangular (unsigned pos, unsigned num) const
Returns true if the set can be trivially detected as being hyper-rectangular on the specified contiguous set of identifiers.
Definition at line 1493 of file IntegerPolyhedron.cpp.
Referenced by checkIfHyperRectangular(), and projectOut().
isIntegerEmpty()
bool IntegerPolyhedron::isIntegerEmpty () const
Returns true if the set of constraints is found to have no solution, false if a solution exists.
Uses the same algorithm as findIntegerSample.
Definition at line 625 of file IntegerPolyhedron.cpp.
Referenced by mlir::PresburgerSet::isIntegerEmpty().
mergeLocalIds()
void IntegerPolyhedron::mergeLocalIds (IntegerPolyhedron & other)
Adds additional local ids to the sets such that they both have the union of the local ids in each set, without changing the set of points that lie in this and other.
The ordering of the local ids in the sets may also be changed. After merging, if the i^th local variable in one set has a known division representation, then the i^th local variable in the other set either has the same division representation or no known division representation.
The number of dimensions and symbol ids in this and other should match.
To detect local ids that always take the same in both sets, each local id is represented as a floordiv with constant denominator in terms of other ids. After extracting these divisions, local ids with the same division representation are considered duplicate and are merged. It is possible that division representation for some local id cannot be obtained, and thus these local ids are not considered for detecting duplicates.
Definition at line 1062 of file IntegerPolyhedron.cpp.
References copy(), eliminateRedundantLocalId(), getLocalReprs(), getNumDimIds(), getNumLocalIds(), getNumSymbolIds(), insertLocalId(), and mlir::presburger_utils::removeDuplicateDivs().
Referenced by mlir::FlatAffineRelation::compose(), mlir::PresburgerSet::intersect(), mergeAndAlignIds(), projectOut(), and subtractRecursively().
normalizeConstraintsByGCD()
void IntegerPolyhedron::normalizeConstraintsByGCD () protected
Normalized each constraints by the GCD of its coefficients.
Definition at line 361 of file IntegerPolyhedron.cpp.
References normalizeConstraintByGCD().
Referenced by gaussianEliminateId(), and mlir::FlatAffineConstraints::getSliceBounds().
print()
void IntegerPolyhedron::print (raw_ostream & os) const
Definition at line 2071 of file IntegerPolyhedron.cpp.
References impl::printSpace().
Referenced by mlir::PresburgerSet::print(), and projectOut().
printSpace()
void IntegerPolyhedron::printSpace (raw_ostream & os) const protected virtual
Prints the number of constraints, dimensions, symbols and locals in the IntegerPolyhedron.
Reimplemented in mlir::FlatAffineConstraints.
Definition at line 2065 of file IntegerPolyhedron.cpp.
Referenced by gaussianEliminateId(), and mlir::FlatAffineConstraints::printSpace().
projectOut() [1/2]
void IntegerPolyhedron::projectOut (unsigned pos, unsigned num)
Projects out (aka eliminates) num identifiers starting at position pos.
The resulting constraint system is the shadow along the dimensions that still exist. This method may not always be integer exact.
Definition at line 1814 of file IntegerPolyhedron.cpp.
References getBestIdToEliminate().
Referenced by mlir::normalizeMemRefType().
projectOut() [2/2]
void mlir::IntegerPolyhedron::projectOut (unsigned pos) inline
Definition at line 300 of file IntegerPolyhedron.h.
References computeConstantLowerOrUpperBound(), constantFoldId(), constantFoldIdRange(), convertDimToLocal(), dump(), getConstantBound(), getConstantBoundOnDimSize(), hasInvalidConstraint(), isHyperRectangular(), mergeLocalIds(), print(), projectOut(), removeIndependentConstraints(), removeRedundantConstraints(), removeRedundantInequalities(), removeTrivialRedundancy(), setDimSymbolSeparation(), and unionBoundingBox().
Referenced by projectOut().
removeEquality()
void IntegerPolyhedron::removeEquality (unsigned pos)
Definition at line 174 of file IntegerPolyhedron.cpp.
Referenced by removeConstraintsInvolvingSuffixDims().
removeEqualityRange()
void IntegerPolyhedron::removeEqualityRange (unsigned start, unsigned end)
Remove the (in)equalities at positions [start, end).
Definition at line 182 of file IntegerPolyhedron.cpp.
Referenced by subtractRecursively().
removeId() [1/2]
void IntegerPolyhedron::removeId (IdKind kind, unsigned pos)
Removes identifiers of the specified kind with the specified pos (or within the specified range) from the system.
The specified location is relative to the first identifier of the specified kind.
Definition at line 126 of file IntegerPolyhedron.cpp.
Referenced by createSeparationCondition(), and eliminateRedundantLocalId().
removeId() [2/2]
void IntegerPolyhedron::removeId (unsigned pos)
Removes the specified identifier from the system.
Definition at line 130 of file IntegerPolyhedron.cpp.
removeIdRange() [1/2]
void IntegerPolyhedron::removeIdRange (IdKind kind, unsigned idStart, unsigned idLimit)
Definition at line 132 of file IntegerPolyhedron.cpp.
Referenced by findIntegerSample(), gaussianEliminateId(), mlir::FlatAffineValueConstraints::removeIdRange(), mlir::FlatAffineValueConstraints::setValues(), and subtractRecursively().
removeIdRange() [2/2]
void IntegerPolyhedron::removeIdRange (unsigned idStart, unsigned idLimit) protected virtual
Removes identifiers in the column range [idStart, idLimit), and copies any remaining valid data into place, updates member variables, and resizes arrays as needed.
Reimplemented in mlir::FlatAffineRelation, and mlir::FlatAffineValueConstraints.
Definition at line 139 of file IntegerPolyhedron.cpp.
References max(), and min().
removeIndependentConstraints()
void IntegerPolyhedron::removeIndependentConstraints (unsigned pos, unsigned num)
Removes constraints that are independent of (i.e., do not have a coefficient) identifiers in the range [pos, pos + num).
Definition at line 2048 of file IntegerPolyhedron.cpp.
References getIndependentConstraints().
Referenced by createSeparationCondition(), and projectOut().
removeInequality()
void IntegerPolyhedron::removeInequality (unsigned pos)
Definition at line 178 of file IntegerPolyhedron.cpp.
Referenced by removeConstraintsInvolvingSuffixDims(), and subtractRecursively().
removeInequalityRange()
void IntegerPolyhedron::removeInequalityRange (unsigned start, unsigned end)
Definition at line 188 of file IntegerPolyhedron.cpp.
Referenced by subtractRecursively().
removeRedundantConstraints()
void IntegerPolyhedron::removeRedundantConstraints ()
Removes redundant constraints using Simplex.
Although the algorithm can theoretically take exponential time in the worst case (rare), it is known to perform much better in the average case. If V is the number of vertices in the polytope and C is the number of constraints, the algorithm takes O(VC) time.
Definition at line 989 of file IntegerPolyhedron.cpp.
References mlir::Simplex::detectRedundant(), and mlir::Simplex::isMarkedRedundant().
Referenced by projectOut().
removeRedundantInequalities()
void IntegerPolyhedron::removeRedundantInequalities ()
A more expensive check than removeTrivialRedundancy to detect redundant inequalities.
Definition at line 949 of file IntegerPolyhedron.cpp.
References atIneq(), fillInequality(), getNumCols(), isEmpty(), and negateInequality().
Referenced by projectOut().
removeRedundantLocalVars()
void IntegerPolyhedron::removeRedundantLocalVars () protected
Removes local variables using equalities.
Each equality is checked if it can be reduced to the form: e = affine-expr, where e is a local variable and affine-expr is an affine expression not containing e. If an equality satisfies this form, the local variable is replaced in each constraint and then removed. The equality used to replace this local variable is also removed.
Definition at line 1112 of file IntegerPolyhedron.cpp.
References eliminateFromConstraint(), and normalizeConstraintByGCD().
Referenced by mlir::FlatAffineRelation::compose(), gaussianEliminateId(), and isEmpty().
removeTrivialRedundancy()
void IntegerPolyhedron::removeTrivialRedundancy ()
Removes duplicate constraints, trivially true constraints, and constraints that can be detected as redundant as a result of differing only in their constant term part.
A constraint of the form <non-negative constant> >= 0 is considered trivially true. This method is a linear time method on the constraints, does a single scan, and updates in place. It also normalizes constraints by their GCD and performs GCD tightening on inequalities.
A constraint of the form <non-negative constant> >= 0 is considered trivially true.
Definition at line 1523 of file IntegerPolyhedron.cpp.
Referenced by createSeparationCondition(), projectOut(), and mlir::simplifyIntegerSet().
reset() [1/2]
void IntegerPolyhedron::reset (unsigned numReservedInequalities, unsigned numReservedEqualities, unsigned numReservedCols, unsigned numDims, unsigned numSymbols, unsigned numLocals = 0) virtual
Clears any existing data and reserves memory for the specified constraints.
Reimplemented in mlir::FlatAffineValueConstraints.
Definition at line 32 of file IntegerPolyhedron.cpp.
Referenced by classof(), mlir::FlatAffineValueConstraints::classof(), getCommonConstraints(), getFlattenedAffineExprs(), and mlir::getFlattenedAffineExprs().
reset() [2/2]
void IntegerPolyhedron::reset (unsigned numDims = 0, unsigned numSymbols = 0, unsigned numLocals = 0)
Definition at line 43 of file IntegerPolyhedron.cpp.
setAndEliminate()
void IntegerPolyhedron::setAndEliminate (unsigned pos, ArrayRef< int64_t > values)
Sets the values.size() identifiers starting at pos to the specified values and removes them.
Definition at line 299 of file IntegerPolyhedron.cpp.
Referenced by findIntegerSample().
setDimSymbolSeparation()
void IntegerPolyhedron::setDimSymbolSeparation (unsigned newSymbolCount)
Changes the partition between dimensions and symbols.
Depending on the new symbol count, either a chunk of trailing dimensional identifiers becomes symbols, or some of the leading symbols become dimensions.
Definition at line 1228 of file IntegerPolyhedron.cpp.
Referenced by createFullTiles(), createSeparationCondition(), projectOut(), and turnSymbolIntoDim().
swapId()
void IntegerPolyhedron::swapId (unsigned posA, unsigned posB) virtual
Swap the posA^th identifier with the posB^th identifier.
Reimplemented in mlir::FlatAffineValueConstraints.
Definition at line 194 of file IntegerPolyhedron.cpp.
Referenced by mlir::FlatAffineValueConstraints::classof(), and mlir::FlatAffineValueConstraints::swapId().
unionBoundingBox()
LogicalResult IntegerPolyhedron::unionBoundingBox (const IntegerPolyhedron & other)
Updates the constraints to be the smallest bounding (enclosing) box that contains the points of this set and that of other, with the symbols being treated specially.
For each of the dimensions, the min of the lower bounds (symbolic) and the max of the upper bounds (symbolic) is computed to determine such a bounding box. other is expected to have the same dimensional identifiers as this constraint system (in the same order).
E.g.: 1) this = {0 <= d0 <= 127}, other = {16 <= d0 <= 192}, output = {0 <= d0 <= 192} 2) this = {s0 + 5 <= d0 <= s0 + 20}, other = {s0 + 1 <= d0 <= s0 + 9}, output = {s0 + 1 <= d0 <= s0 + 20} 3) this = {0 <= d0 <= 5, 1 <= d1 <= 9} other = {2 <= d0 <= 6, 5 <= d1 <= 15}, output = {0 <= d0 <= 6, 1 <= d1 <= 15}
Definition at line 1899 of file IntegerPolyhedron.cpp.
References mlir::failure(), getCommonConstraints(), getConstantBoundOnDimSize(), getNumDimIds(), and getNumLocalIds().
Referenced by projectOut(), and mlir::FlatAffineValueConstraints::unionBoundingBox().
Member Data Documentation
equalities
Matrix mlir::IntegerPolyhedron::equalities protected
Coefficients of affine equalities (in == 0 form).
Definition at line 515 of file IntegerPolyhedron.h.
Referenced by atEq(), getEquality(), getNumEqualities(), and getNumReservedEqualities().
inequalities
Matrix mlir::IntegerPolyhedron::inequalities protected
Coefficients of affine inequalities (in >= 0 form).
Definition at line 518 of file IntegerPolyhedron.h.
Referenced by atIneq(), getInequality(), getNumInequalities(), and getNumReservedInequalities().
kExplosionFactor
constexpr unsigned mlir::IntegerPolyhedron::kExplosionFactor = 32 static protected
A parameter that controls detection of an unrealistic number of constraints.
If the number of constraints is this many times the number of variables, we consider such a system out of line with the intended use case of IntegerPolyhedron.
Definition at line 502 of file IntegerPolyhedron.h.
numDims
unsigned mlir::IntegerPolyhedron::numDims protected
Number of identifiers corresponding to real dimensions.
Definition at line 508 of file IntegerPolyhedron.h.
Referenced by classof(), mlir::FlatAffineValueConstraints::computeAlignedMap(), computeLocalVars(), mlir::FlatAffineConstraints::getAsIntegerSet(), mlir::FlatAffineValueConstraints::getIneqAsAffineValueMap(), getNumDimIds(), mlir::FlatAffineConstraints::getUniverse(), getUniverse(), and mlir::FlatAffineValueConstraints::unionBoundingBox().
numIds
unsigned mlir::IntegerPolyhedron::numIds protected
Total number of identifiers.
Definition at line 505 of file IntegerPolyhedron.h.
Referenced by mlir::FlatAffineValueConstraints::clearAndCopyFrom(), mlir::FlatAffineValueConstraints::FlatAffineValueConstraints(), mlir::FlatAffineValueConstraints::fourierMotzkinEliminate(), mlir::FlatAffineValueConstraints::getAllValues(), getNumCols(), getNumIds(), getNumLocalIds(), mlir::FlatAffineValueConstraints::getValues(), IntegerPolyhedron(), mlir::FlatAffineValueConstraints::setValue(), and mlir::FlatAffineValueConstraints::setValues().
numSymbols
unsigned mlir::IntegerPolyhedron::numSymbols protected
Number of identifiers corresponding to symbols (unknown but constant for analysis).
Definition at line 512 of file IntegerPolyhedron.h.
Referenced by mlir::alignAffineMapWithValues(), classof(), mlir::FlatAffineValueConstraints::computeAlignedMap(), getNumDimAndSymbolIds(), getNumLocalIds(), getNumSymbolIds(), mlir::FlatAffineConstraints::getUniverse(), and getUniverse().
The documentation for this class was generated from the following files:
include/mlir/Analysis/Presburger/IntegerPolyhedron.h
lib/Analysis/Presburger/IntegerPolyhedron.cpp