MLIR: mlir::FlatAffineConstraints Class Reference
mlir::FlatAffineConstraints Class Reference
A flat list of affine equalities and inequalities in the form.
#include "mlir/Dialect/Affine/Analysis/AffineStructures.h"
Public Member Functions
FlatAffineConstraints (unsigned numReservedInequalities, unsigned numReservedEqualities, unsigned numReservedCols, unsigned numDims, unsigned numSymbols, unsigned numLocals)
Constructs a constraint system reserving memory for the specified number of constraints and identifiers.
FlatAffineConstraints (unsigned numDims=0, unsigned numSymbols=0, unsigned numLocals=0)
Constructs a constraint system with the specified number of dimensions and symbols.
FlatAffineConstraints (const IntegerPolyhedron &poly)
FlatAffineConstraints (IntegerSet set)
Creates an affine constraint system from an IntegerSet.
FlatAffineConstraints (const MutableAffineMap &map)
~FlatAffineConstraints () override=default
Kind getKind () const override
Return the kind of this FlatAffineConstraints.
std::unique_ptr< FlatAffineConstraints > clone () const
LogicalResult addBound (BoundType type, unsigned pos, AffineMap boundMap)
Adds a bound for the identifier at the specified position with constraints being drawn from the specified bound map.
IntegerSet getAsIntegerSet (MLIRContext *context) const
Returns the constraint system as an integer set.
void getSliceBounds (unsigned offset, unsigned num, MLIRContext *context, SmallVectorImpl< AffineMap > *lbMaps, SmallVectorImpl< AffineMap > *ubMaps)
Computes the lower and upper bounds of the first num dimensional identifiers (starting at offset) as an affine map of the remaining identifiers (dimensional and symbolic).
LogicalResult composeMatchingMap (AffineMap other)
Composes an affine map whose dimensions and symbols match one to one with the dimensions and symbols of this FlatAffineConstraints.
void clearAndCopyFrom (const IntegerPolyhedron &other) override
Replaces the contents of this FlatAffineConstraints with other.
std::pair< AffineMap, AffineMap > getLowerAndUpperBound (unsigned pos, unsigned offset, unsigned num, unsigned symStartPos, ArrayRef< AffineExpr > localExprs, MLIRContext *context) const
Gets the lower and upper bound of the offset + posth identifier treating [0, offset) U [offset + num, symStartPos) as dimensions and [symStartPos, getNumDimAndSymbolIds) as symbols, and pos lies in [0, num).
Public Member Functions inherited from mlir::IntegerPolyhedron
IntegerPolyhedron (unsigned numReservedInequalities, unsigned numReservedEqualities, unsigned numReservedCols, unsigned numDims, unsigned numSymbols, unsigned numLocals)
Constructs a constraint system reserving memory for the specified number of constraints and identifiers.
IntegerPolyhedron (unsigned numDims=0, unsigned numSymbols=0, unsigned numLocals=0)
Constructs a constraint system with the specified number of dimensions and symbols.
virtual ~IntegerPolyhedron ()=default
std::unique_ptr< IntegerPolyhedron > clone () const
virtual void reset (unsigned numReservedInequalities, unsigned numReservedEqualities, unsigned numReservedCols, unsigned numDims, unsigned numSymbols, unsigned numLocals=0)
Clears any existing data and reserves memory for the specified constraints.
void reset (unsigned numDims=0, unsigned numSymbols=0, unsigned numLocals=0)
void append (const IntegerPolyhedron &other)
Appends constraints from other into this.
int64_t atEq (unsigned i, unsigned j) const
Returns the value at the specified equality row and column.
int64_t & atEq (unsigned i, unsigned j)
int64_t atIneq (unsigned i, unsigned j) const
Returns the value at the specified inequality row and column.
int64_t & atIneq (unsigned i, unsigned j)
unsigned getNumConstraints () const
unsigned getNumIds () const
unsigned getNumDimIds () const
unsigned getNumSymbolIds () const
unsigned getNumDimAndSymbolIds () const
unsigned getNumLocalIds () const
unsigned getNumCols () const
Returns the number of columns in the constraint system.
unsigned getNumEqualities () const
unsigned getNumInequalities () const
unsigned getNumReservedEqualities () const
unsigned getNumReservedInequalities () const
ArrayRef< int64_t > getEquality (unsigned idx) const
ArrayRef< int64_t > getInequality (unsigned idx) const
unsigned insertDimId (unsigned pos, unsigned num=1)
Insert num identifiers of the specified kind at position pos.
unsigned insertSymbolId (unsigned pos, unsigned num=1)
unsigned insertLocalId (unsigned pos, unsigned num=1)
virtual unsigned insertId (IdKind kind, unsigned pos, unsigned num=1)
unsigned appendDimId (unsigned num=1)
Append num identifiers of the specified kind after the last identifier.
unsigned appendSymbolId (unsigned num=1)
unsigned appendLocalId (unsigned num=1)
void addInequality (ArrayRef< int64_t > inEq)
Adds an inequality (>= 0) from the coefficients specified in inEq.
void addEquality (ArrayRef< int64_t > eq)
Adds an equality from the coefficients specified in eq.
void removeId (IdKind kind, unsigned pos)
Removes identifiers of the specified kind with the specified pos (or within the specified range) from the system.
void removeIdRange (IdKind kind, unsigned idStart, unsigned idLimit)
void removeId (unsigned pos)
Removes the specified identifier from the system.
void removeEquality (unsigned pos)
void removeInequality (unsigned pos)
void removeEqualityRange (unsigned start, unsigned end)
Remove the (in)equalities at positions [start, end).
void removeInequalityRange (unsigned start, unsigned end)
virtual void swapId (unsigned posA, unsigned posB)
Swap the posA^th identifier with the posB^th identifier.
void clearConstraints ()
Removes all equalities and inequalities.
void setAndEliminate (unsigned pos, ArrayRef< int64_t > values)
Sets the values.size() identifiers starting at pos to the specified values and removes them.
void getLowerAndUpperBoundIndices (unsigned pos, SmallVectorImpl< unsigned > *lbIndices, SmallVectorImpl< unsigned > *ubIndices, SmallVectorImpl< unsigned > *eqIndices=nullptr, unsigned offset=0, unsigned num=0) const
Gather positions of all lower and upper bounds of the identifier at pos, and optionally any equalities on it.
bool isEmpty () const
Checks for emptiness by performing variable elimination on all identifiers, running the GCD test on each equality constraint, and checking for invalid constraints.
bool isEmptyByGCDTest () const
Runs the GCD test on all equality constraints.
bool isIntegerEmpty () const
Returns true if the set of constraints is found to have no solution, false if a solution exists.
Matrix getBoundedDirections () const
Returns a matrix where each row is a vector along which the polytope is bounded.
Optional< SmallVector< int64_t, 8 > > findIntegerSample () const
Find an integer sample point satisfying the constraints using a branch and bound algorithm with generalized basis reduction, with some additional processing using Simplex for unbounded sets.
bool containsPoint (ArrayRef< int64_t > point) const
Returns true if the given point satisfies the constraints, or false otherwise.
void getLocalReprs (std::vector< SmallVector< int64_t, 8 >> &dividends, SmallVector< unsigned, 4 > &denominators, std::vector< presburger_utils::MaybeLocalRepr > &repr) const
Find pairs of inequalities identified by their position indices, using which an explicit representation for each local variable can be computed.
void getLocalReprs (std::vector< presburger_utils::MaybeLocalRepr > &repr) const
void getLocalReprs (std::vector< SmallVector< int64_t, 8 >> &dividends, SmallVector< unsigned, 4 > &denominators) const
void addBound (BoundType type, unsigned pos, int64_t value)
Adds a constant bound for the specified identifier.
void addBound (BoundType type, ArrayRef< int64_t > expr, int64_t value)
Adds a constant bound for the specified expression.
void addLocalFloorDiv (ArrayRef< int64_t > dividend, int64_t divisor)
Adds a new local identifier as the floordiv of an affine function of other identifiers, the coefficients of which are provided in dividend and with respect to a positive constant divisor.
void projectOut (unsigned pos, unsigned num)
Projects out (aka eliminates) num identifiers starting at position pos.
void projectOut (unsigned pos)
void setDimSymbolSeparation (unsigned newSymbolCount)
Changes the partition between dimensions and symbols.
LogicalResult constantFoldId (unsigned pos)
Tries to fold the specified identifier to a constant using a trivial equality detection; if successful, the constant is substituted for the identifier everywhere in the constraint system and then removed from the system.
void constantFoldIdRange (unsigned pos, unsigned num)
This method calls constantFoldId for the specified range of identifiers, num identifiers starting at position pos.
LogicalResult unionBoundingBox (const IntegerPolyhedron &other)
Updates the constraints to be the smallest bounding (enclosing) box that contains the points of this set and that of other, with the symbols being treated specially.
Optional< int64_t > getConstantBoundOnDimSize (unsigned pos, SmallVectorImpl< int64_t > *lb=nullptr, int64_t *boundFloorDivisor=nullptr, SmallVectorImpl< int64_t > *ub=nullptr, unsigned *minLbPos=nullptr, unsigned *minUbPos=nullptr) const
Returns the smallest known constant bound for the extent of the specified identifier (pos^th), i.e., the smallest known constant that is greater than or equal to 'exclusive upper bound' - 'lower bound' of the identifier.
Optional< int64_t > getConstantBound (BoundType type, unsigned pos) const
Returns the constant bound for the pos^th identifier if there is one; None otherwise.
void removeIndependentConstraints (unsigned pos, unsigned num)
Removes constraints that are independent of (i.e., do not have a coefficient) identifiers in the range [pos, pos + num).
bool isHyperRectangular (unsigned pos, unsigned num) const
Returns true if the set can be trivially detected as being hyper-rectangular on the specified contiguous set of identifiers.
void removeTrivialRedundancy ()
Removes duplicate constraints, trivially true constraints, and constraints that can be detected as redundant as a result of differing only in their constant term part.
void removeRedundantInequalities ()
A more expensive check than removeTrivialRedundancy to detect redundant inequalities.
void removeRedundantConstraints ()
Removes redundant constraints using Simplex.
void convertDimToLocal (unsigned dimStart, unsigned dimLimit)
Converts identifiers in the column range [idStart, idLimit) to local variables.
void mergeLocalIds (IntegerPolyhedron &other)
Adds additional local ids to the sets such that they both have the union of the local ids in each set, without changing the set of points that lie in this and other.
void print (raw_ostream &os) const
void dump () const
Static Public Member Functions
static FlatAffineConstraints getUniverse (unsigned numDims=0, unsigned numSymbols=0)
Return a system with no constraints, i.e., one which is satisfied by all points.
static bool classof (const IntegerPolyhedron *cst)
Static Public Member Functions inherited from mlir::IntegerPolyhedron
static IntegerPolyhedron getUniverse (unsigned numDims=0, unsigned numSymbols=0)
Return a system with no constraints, i.e., one which is satisfied by all points.
static bool classof (const IntegerPolyhedron *cst)
Protected Member Functions
LogicalResult flattenAlignedMapAndMergeLocals (AffineMap map, std::vector< SmallVector< int64_t, 8 >> *flattenedExprs)
Given an affine map that is aligned with this constraint system:
void printSpace (raw_ostream &os) const override
Prints the number of constraints, dimensions, symbols and locals in the FlatAffineConstraints.
Protected Member Functions inherited from mlir::IntegerPolyhedron
bool hasInvalidConstraint () const
Checks all rows of equality/inequality constraints for trivial contradictions (for example: 1 == 0, 0 >= 1), which may have surfaced after elimination.
template<bool isLower>
Optional< int64_t > computeConstantLowerOrUpperBound (unsigned pos)
Returns the constant lower bound bound if isLower is true, and the upper bound if isLower is false.
LogicalResult gaussianEliminateId (unsigned position)
Eliminates a single identifier at position from equality and inequality constraints.
void removeRedundantLocalVars ()
Removes local variables using equalities.
unsigned gaussianEliminateIds (unsigned posStart, unsigned posLimit)
Eliminates identifiers from equality and inequality constraints in column range [posStart, posLimit).
virtual void fourierMotzkinEliminate (unsigned pos, bool darkShadow=false, bool *isResultIntegerExact=nullptr)
Eliminates the identifier at the specified position using Fourier-Motzkin variable elimination, but uses Gaussian elimination if there is an equality involving that identifier.
void gcdTightenInequalities ()
Tightens inequalities given that we are dealing with integer spaces.
void normalizeConstraintsByGCD ()
Normalized each constraints by the GCD of its coefficients.
bool findConstraintWithNonZeroAt (unsigned colIdx, bool isEq, unsigned *rowIdx) const
Searches for a constraint with a non-zero coefficient at colIdx in equality (isEq=true) or inequality (isEq=false) constraints.
bool isColZero (unsigned pos) const
Returns true if the pos^th column is all zero for both inequalities and equalities.
virtual bool hasConsistentState () const
Returns false if the fields corresponding to various identifier counts, or equality/inequality buffer sizes aren't consistent; true otherwise.
unsigned getIdKindOffset (IdKind kind) const
Return the index at which the specified kind of id starts.
unsigned getNumIdKind (IdKind kind) const
Get the number of ids of the specified kind.
virtual void removeIdRange (unsigned idStart, unsigned idLimit)
Removes identifiers in the column range [idStart, idLimit), and copies any remaining valid data into place, updates member variables, and resizes arrays as needed.
Additional Inherited Members
Public Types inherited from mlir::IntegerPolyhedron
enum Kind { Kind::FlatAffineConstraints, Kind::FlatAffineValueConstraints, Kind::IntegerPolyhedron }
All derived classes of IntegerPolyhedron.
enum IdKind { Dimension, Symbol, Local }
Kind of identifier (column).
enum BoundType { EQ, LB, UB }
The type of bound: equal, lower bound or upper bound.
Protected Attributes inherited from mlir::IntegerPolyhedron
unsigned numIds
Total number of identifiers.
unsigned numDims
Number of identifiers corresponding to real dimensions.
unsigned numSymbols
Number of identifiers corresponding to symbols (unknown but constant for analysis).
Matrix equalities
Coefficients of affine equalities (in == 0 form).
Matrix inequalities
Coefficients of affine inequalities (in >= 0 form).
Static Protected Attributes inherited from mlir::IntegerPolyhedron
static constexpr unsigned kExplosionFactor = 32
A parameter that controls detection of an unrealistic number of constraints.
Detailed Description
A flat list of affine equalities and inequalities in the form.
Inequality: c_0*x_0 + c_1*x_1 + .... + c_{n-1}*x_{n-1} >= 0 Equality: c_0*x_0 + c_1*x_1 + .... + c_{n-1}*x_{n-1} == 0
FlatAffineConstraints stores coefficients in a contiguous buffer (one buffer for equalities and one for inequalities). The size of each buffer is numReservedCols * number of inequalities (or equalities). The reserved size is numReservedCols * numReservedInequalities (or numReservedEqualities). A coefficient (r, c) lives at the location numReservedCols * r + c in the buffer. The extra space between getNumCols() and numReservedCols exists to prevent frequent movement of data when adding columns, especially at the end.
The identifiers x_0, x_1, ... appear in the order: dimensional identifiers, symbolic identifiers, and local identifiers. The local identifiers correspond to local/internal variables created when converting from AffineExpr's containing mod's and div's; they are thus needed to increase representational power. Each local identifier is always (by construction) a floordiv of a pure add/mul affine function of dimensional, symbolic, and other local identifiers, in a non-mutually recursive way. Hence, every local identifier can ultimately always be recovered as an affine function of dimensional and symbolic identifiers (involving floordiv's); note however that some floordiv combinations are converted to mod's by AffineExpr construction.
Definition at line 60 of file AffineStructures.h.
Constructor & Destructor Documentation
FlatAffineConstraints() [1/5]
mlir::FlatAffineConstraints::FlatAffineConstraints (unsigned numReservedInequalities, unsigned numReservedEqualities, unsigned numReservedCols, unsigned numDims, unsigned numSymbols, unsigned numLocals) inline
Constructs a constraint system reserving memory for the specified number of constraints and identifiers.
Definition at line 64 of file AffineStructures.h.
Referenced by mlir::FlatAffineValueConstraints::FlatAffineValueConstraints(), getSliceBounds(), and getUniverse().
FlatAffineConstraints() [2/5]
mlir::FlatAffineConstraints::FlatAffineConstraints (unsigned numDims = 0, unsigned numSymbols = 0, unsigned numLocals = 0) inline
Constructs a constraint system with the specified number of dimensions and symbols.
Definition at line 73 of file AffineStructures.h.
FlatAffineConstraints() [3/5]
mlir::FlatAffineConstraints::FlatAffineConstraints (const IntegerPolyhedron & poly) inline explicit
Definition at line 81 of file AffineStructures.h.
FlatAffineConstraints() [4/5]
FlatAffineConstraints::FlatAffineConstraints (IntegerSet set) explicit
Creates an affine constraint system from an IntegerSet.
Definition at line 159 of file AffineStructures.cpp.
References mlir::IntegerPolyhedron::addEquality(), mlir::IntegerPolyhedron::addInequality(), mlir::IntegerPolyhedron::append(), mlir::IntegerPolyhedron::appendLocalId(), mlir::failed(), mlir::getFlattenedAffineExprs(), mlir::IntegerPolyhedron::getNumCols(), and mlir::IntegerPolyhedron::getNumLocalIds().
FlatAffineConstraints() [5/5]
mlir::FlatAffineConstraints::FlatAffineConstraints (const MutableAffineMap & map)
~FlatAffineConstraints()
mlir::FlatAffineConstraints::~FlatAffineConstraints () override default
Referenced by getUniverse().
Member Function Documentation
addBound()
LogicalResult FlatAffineConstraints::addBound (BoundType type, unsigned pos, AffineMap boundMap)
Adds a bound for the identifier at the specified position with constraints being drawn from the specified bound map.
In case of an EQ bound, the bound map is expected to have exactly one result. In case of a LB/UB, the bound map may have more than one result, for each of which an inequality is added. Note: The dimensions/symbols of this FlatAffineConstraints must match the dimensions/symbols of the affine map.
Definition at line 1155 of file AffineStructures.cpp.
References mlir::IntegerPolyhedron::addEquality(), mlir::IntegerPolyhedron::addInequality(), mlir::failed(), mlir::failure(), flattenAlignedMapAndMergeLocals(), mlir::IntegerPolyhedron::getNumCols(), mlir::IntegerPolyhedron::getNumDimAndSymbolIds(), mlir::IntegerPolyhedron::getNumDimIds(), mlir::AffineMap::getNumDims(), mlir::AffineMap::getNumInputs(), mlir::AffineMap::getNumResults(), mlir::IntegerPolyhedron::getNumSymbolIds(), mlir::AffineMap::getNumSymbols(), and mlir::success().
Referenced by classof(), mlir::FlatAffineValueConstraints::classof(), mlir::getMemRefSizeInBytes(), and mlir::normalizeMemRefType().
classof()
static bool mlir::FlatAffineConstraints::classof (const IntegerPolyhedron * cst) inline static
Definition at line 101 of file AffineStructures.h.
References addBound(), mlir::IntegerPolyhedron::addBound(), clearAndCopyFrom(), clone(), composeMatchingMap(), mlir::IntegerPolyhedron::FlatAffineConstraints, flattenAlignedMapAndMergeLocals(), getAsIntegerSet(), mlir::IntegerPolyhedron::getKind(), getLowerAndUpperBound(), getSliceBounds(), and printSpace().
clearAndCopyFrom()
void FlatAffineConstraints::clearAndCopyFrom (const IntegerPolyhedron & other) override virtual
Replaces the contents of this FlatAffineConstraints with other.
Reimplemented from mlir::IntegerPolyhedron.
Reimplemented in mlir::FlatAffineValueConstraints.
Definition at line 1346 of file AffineStructures.cpp.
Referenced by classof(), and getFlattenedAffineExprs().
clone()
std::unique_ptr< FlatAffineConstraints > FlatAffineConstraints::clone () const
Definition at line 149 of file AffineStructures.cpp.
Referenced by classof(), and mlir::FlatAffineValueConstraints::classof().
composeMatchingMap()
LogicalResult FlatAffineConstraints::composeMatchingMap (AffineMap other)
Composes an affine map whose dimensions and symbols match one to one with the dimensions and symbols of this FlatAffineConstraints.
The results of the map other are added as the leading dimensions of this constraint system. Returns failure if other is a semi-affine map.
Definition at line 450 of file AffineStructures.cpp.
References mlir::IntegerPolyhedron::addEquality(), mlir::failed(), mlir::failure(), flattenAlignedMapAndMergeLocals(), mlir::IntegerPolyhedron::getNumCols(), mlir::IntegerPolyhedron::getNumDimIds(), mlir::AffineMap::getNumDims(), mlir::AffineMap::getNumInputs(), mlir::AffineMap::getNumResults(), mlir::IntegerPolyhedron::getNumSymbolIds(), mlir::AffineMap::getNumSymbols(), mlir::FlatAffineValueConstraints::insertDimId(), and mlir::success().
Referenced by classof(), mlir::FlatAffineValueConstraints::composeMap(), and mlir::normalizeMemRefType().
flattenAlignedMapAndMergeLocals()
LogicalResult FlatAffineConstraints::flattenAlignedMapAndMergeLocals (AffineMap map, std::vector< SmallVector< int64_t, 8 >> * flattenedExprs) protected
Given an affine map that is aligned with this constraint system:
Flatten the map.
Add newly introduced local columns at the beginning of this constraint system (local column pos 0).
Add equalities that define the new local columns to this constraint system.
Return the flattened expressions via flattenedExprs.
Note: This is a shared helper function of addLowerOrUpperBound and composeMatchingMap.
Definition at line 1131 of file AffineStructures.cpp.
References mlir::IntegerPolyhedron::append(), mlir::IntegerPolyhedron::appendLocalId(), mlir::failed(), mlir::failure(), mlir::getFlattenedAffineExprs(), mlir::IntegerPolyhedron::getNumLocalIds(), mlir::IntegerPolyhedron::insertLocalId(), and mlir::success().
Referenced by addBound(), classof(), and composeMatchingMap().
getAsIntegerSet()
IntegerSet FlatAffineConstraints::getAsIntegerSet (MLIRContext * context) const
Returns the constraint system as an integer set.
Returns a null integer set if the system has no constraints, or if an integer set couldn't be constructed as a result of a local variable's explicit representation not being known and such a local variable appearing in any of the constraints.
Definition at line 1496 of file AffineStructures.cpp.
References computeLocalVars(), mlir::IntegerPolyhedron::dump(), mlir::failed(), mlir::IntegerSet::get(), mlir::getAffineConstantExpr(), mlir::getAffineExprFromFlatForm(), mlir::IntegerPolyhedron::getEquality(), mlir::IntegerPolyhedron::getInequality(), mlir::IntegerPolyhedron::getNumConstraints(), mlir::IntegerPolyhedron::getNumDimAndSymbolIds(), mlir::IntegerPolyhedron::getNumDimIds(), mlir::IntegerPolyhedron::getNumEqualities(), mlir::IntegerPolyhedron::getNumIds(), mlir::IntegerPolyhedron::getNumInequalities(), mlir::IntegerPolyhedron::getNumLocalIds(), mlir::IntegerPolyhedron::getNumSymbolIds(), mlir::IntegerPolyhedron::isColZero(), and mlir::IntegerPolyhedron::numDims.
Referenced by classof(), createSeparationCondition(), and mlir::simplifyIntegerSet().
getKind()
Kind mlir::FlatAffineConstraints::getKind () const inline override virtual
Return the kind of this FlatAffineConstraints.
Reimplemented from mlir::IntegerPolyhedron.
Reimplemented in mlir::FlatAffineValueConstraints.
Definition at line 99 of file AffineStructures.h.
References mlir::IntegerPolyhedron::FlatAffineConstraints.
getLowerAndUpperBound()
std::pair< AffineMap, AffineMap > FlatAffineConstraints::getLowerAndUpperBound (unsigned pos, unsigned offset, unsigned num, unsigned symStartPos, ArrayRef< AffineExpr > localExprs, MLIRContext * context) const
Gets the lower and upper bound of the offset + posth identifier treating [0, offset) U [offset + num, symStartPos) as dimensions and [symStartPos, getNumDimAndSymbolIds) as symbols, and pos lies in [0, num).
The multi-dimensional maps in the returned pair represent the max and min of potentially multiple affine expressions. The upper bound is exclusive. localExprs holds pre-computed AffineExpr's for all local identifiers in the system.
Add to 'b' from 'a' in set [0, offset) U [offset + num, symbStartPos).
Definition at line 872 of file AffineStructures.cpp.
References mlir::floorDiv(), mlir::AffineMap::get(), mlir::getAffineExprFromFlatForm(), mlir::IntegerPolyhedron::getEquality(), mlir::IntegerPolyhedron::getInequality(), mlir::IntegerPolyhedron::getLowerAndUpperBoundIndices(), mlir::IntegerPolyhedron::getNumDimAndSymbolIds(), mlir::IntegerPolyhedron::getNumDimIds(), and mlir::IntegerPolyhedron::getNumLocalIds().
Referenced by classof().
getSliceBounds()
void FlatAffineConstraints::getSliceBounds (unsigned offset, unsigned num, MLIRContext * context, SmallVectorImpl< AffineMap > * lbMaps, SmallVectorImpl< AffineMap > * ubMaps)
Computes the lower and upper bounds of the first num dimensional identifiers (starting at offset) as an affine map of the remaining identifiers (dimensional and symbolic).
Computes the lower and upper bounds of the first 'num' dimensional identifiers (starting at 'offset') as affine maps of the remaining identifiers (dimensional and symbolic identifiers).
This method is able to detect identifiers as floordiv's and mod's of affine expressions of other identifiers with respect to (positive) constants. Sets bound map to a null AffineMap if such a bound can't be found (or yet unimplemented).
Local identifiers are themselves explicitly computed as affine functions of other identifiers in this process if needed.
Definition at line 960 of file AffineStructures.cpp.
References mlir::IntegerPolyhedron::atEq(), detectAsFloorDiv(), detectAsMod(), mlir::AffineMap::dump(), mlir::IntegerPolyhedron::dump(), mlir::IntegerPolyhedron::findConstraintWithNonZeroAt(), FlatAffineConstraints(), mlir::floorDiv(), mlir::AffineMap::get(), mlir::getAffineConstantExpr(), mlir::getAffineDimExpr(), mlir::getAffineSymbolExpr(), mlir::IntegerPolyhedron::getConstantBound(), mlir::IntegerPolyhedron::getNumDimAndSymbolIds(), mlir::IntegerPolyhedron::getNumDimIds(), mlir::IntegerPolyhedron::getNumIds(), mlir::IntegerPolyhedron::getNumLocalIds(), mlir::AffineMap::getNumResults(), mlir::IntegerPolyhedron::getNumSymbolIds(), mlir::IntegerPolyhedron::normalizeConstraintsByGCD(), and mlir::simplifyAffineExpr().
Referenced by canonicalizeMinMaxOp(), classof(), mlir::computeSliceUnion(), mlir::getComputationSliceState(), and mlir::linalg::getUpperBoundForIndex().
getUniverse()
static FlatAffineConstraints mlir::FlatAffineConstraints::getUniverse (unsigned numDims = 0, unsigned numSymbols = 0) inline static
Return a system with no constraints, i.e., one which is satisfied by all points.
Definition at line 86 of file AffineStructures.h.
References FlatAffineConstraints(), mlir::IntegerPolyhedron::numDims, mlir::IntegerPolyhedron::numSymbols, and ~FlatAffineConstraints().
printSpace()
void FlatAffineConstraints::printSpace (raw_ostream & os) const override protected virtual
Prints the number of constraints, dimensions, symbols and locals in the FlatAffineConstraints.
Also, prints for each identifier whether there is an SSA Value attached to it.
Reimplemented from mlir::IntegerPolyhedron.
Definition at line 1330 of file AffineStructures.cpp.
References mlir::IntegerPolyhedron::getNumIds(), and mlir::IntegerPolyhedron::printSpace().
Referenced by classof().
The documentation for this class was generated from the following files:
include/mlir/Dialect/Affine/Analysis/AffineStructures.h
lib/Dialect/Affine/Analysis/AffineStructures.cpp