MLIR: mlir::bufferization::BufferizationState Class Reference
mlir::bufferization::BufferizationState Class Reference abstract
BufferizationState provides a variety of helper functions for dealing with tensor values and memref buffers.
#include "mlir/Dialect/Bufferization/IR/BufferizableOpInterface.h"
Public Member Functions
SmallVector< OpOperand * > getAliasingOpOperand (OpResult result) const
Determine which OpOperand* will alias with result if the op is bufferized in place.
OpResult getAliasingOpResult (OpOperand &opOperand) const
Determine which OpResult will alias with opOperand if the op is bufferized in place.
bool bufferizesToMemoryRead (OpOperand &opOperand) const
Return true if opOperand bufferizes to a memory read.
bool bufferizesToMemoryWrite (OpOperand &opOperand) const
Return true if opOperand bufferizes to a memory write.
bool bufferizesToAliasOnly (OpOperand &opOperand) const
Return true if opOperand does neither read nor write but bufferizes to an alias.
bool isValueRead (Value value) const
Return true if the given value is read by an op that bufferizes to a memory read.
SetVector< Value > findValueInReverseUseDefChain (Value value, llvm::function_ref< bool(Value)> condition) const
Starting from value, follow the use-def chain in reverse, always selecting the aliasing OpOperands.
SetVector< Value > findLastPrecedingWrite (Value value) const
Find the Values of the last preceding write of a given Value.
virtual bool isInPlace (OpOperand &opOperand) const =0
Return true if the given OpResult has been decided to bufferize inplace.
virtual bool areEquivalentBufferizedValues (Value v1, Value v2) const =0
Return true if v1 and v2 bufferize to equivalent buffers.
FailureOr< Value > getBuffer (RewriterBase &rewriter, OpOperand &opOperand, bool forceInPlace=false, Optional< Operation *> customCopyInsertionPoint=None) const
Return the buffer (memref) for a given OpOperand (tensor).
template<typename StateT >
Optional< const StateT * > getDialectState (StringRef name) const
Return dialect-specific bufferization state.
template<typename StateT >
StateT & getOrCreateDialectState (StringRef name)
Return dialect-specific bufferization state or create one if none exists.
const BufferizationOptions & getOptions () const
Return a reference to the BufferizationOptions.
Protected Member Functions
BufferizationState (const BufferizationOptions &options)
BufferizationState (const BufferizationState &)=delete
~BufferizationState ()=default
Detailed Description
BufferizationState provides a variety of helper functions for dealing with tensor values and memref buffers.
Definition at line 158 of file BufferizableOpInterface.h.
Constructor & Destructor Documentation
BufferizationState() [1/2]
BufferizationState::BufferizationState (const BufferizationOptions & options) protected
Definition at line 200 of file BufferizableOpInterface.cpp.
BufferizationState() [2/2]
mlir::bufferization::BufferizationState::BufferizationState (const BufferizationState &) protected delete
~BufferizationState()
mlir::bufferization::BufferizationState::~BufferizationState () protected default
Member Function Documentation
areEquivalentBufferizedValues()
virtual bool mlir::bufferization::BufferizationState::areEquivalentBufferizedValues (Value v1, Value v2) const pure virtual
Return true if v1 and v2 bufferize to equivalent buffers.
Implemented in mlir::bufferization::AnalysisBufferizationState.
Referenced by mlir::linalg::comprehensive_bufferize::scf_ext::IfOpInterface::bufferRelation(), and mlir::linalg::comprehensive_bufferize::scf_ext::ForOpInterface::bufferRelation().
bufferizesToAliasOnly()
bool BufferizationState::bufferizesToAliasOnly (OpOperand & opOperand) const
Return true if opOperand does neither read nor write but bufferizes to an alias.
Return false if the op is not bufferizable.
Definition at line 124 of file BufferizableOpInterface.cpp.
References mlir::detail::IROperandBase::getOwner().
bufferizesToMemoryRead()
bool BufferizationState::bufferizesToMemoryRead (OpOperand & opOperand) const
Return true if opOperand bufferizes to a memory read.
Return true if the op is not bufferizable.
Definition at line 100 of file BufferizableOpInterface.cpp.
References mlir::detail::IROperandBase::getOwner().
Referenced by getBuffer().
bufferizesToMemoryWrite()
bool BufferizationState::bufferizesToMemoryWrite (OpOperand & opOperand) const
Return true if opOperand bufferizes to a memory write.
Return true` if the op is not bufferizable.
Return true if the op is not bufferizable.
Definition at line 112 of file BufferizableOpInterface.cpp.
References mlir::detail::IROperandBase::getOwner().
Referenced by getAssumedUniqueReturnOp(), getBuffer(), isInplaceMemoryWrite(), and wouldCreateWriteToNonWritableBuffer().
findLastPrecedingWrite()
llvm::SetVector< Value > BufferizationState::findLastPrecedingWrite (Value value) const
Find the Values of the last preceding write of a given Value.
Note: Unknown ops are handled conservatively and assumed to be writes. Furthermore, BlockArguments are also assumed to be writes. There is no analysis across block boundaries.
Note: When reaching an end of the reverse SSA use-def chain, that value is returned regardless of whether it is a memory write or not.
Definition at line 188 of file BufferizableOpInterface.cpp.
References mlir::Value::cast(), mlir::Value::getDefiningOp(), and options.
Referenced by getBuffer(), and hasReadAfterWriteInterference().
findValueInReverseUseDefChain()
llvm::SetVector< Value > BufferizationState::findValueInReverseUseDefChain (Value value, llvm::function_ref< bool(Value)> condition) const
Starting from value, follow the use-def chain in reverse, always selecting the aliasing OpOperands.
Find and return Values for which condition evaluates to true. OpOperands of such matching Values are not traversed any further.
When reaching the end of a chain (BlockArgument or Value without aliasing OpOperands), also return the last Value of that chain.
Example:
                          8
                          |
6* 7* +--—+-—+ | | | | 2* 3 4* 5 | | | | +-------—+-------—+-------—+ | 1
In the above example, Values with a star satisfy the condition. When starting the traversal from Value 1, the resulting SetVector is: { 2, 7, 8, 5 }
Definition at line 160 of file BufferizableOpInterface.cpp.
References mlir::Value::cast(), mlir::Value::getDefiningOp(), mlir::Value::isa(), and options.
Referenced by mlir::linalg::comprehensive_bufferize::linalg_ext::InitTensorEliminationStep::eliminateInitTensors().
getAliasingOpOperand()
SmallVector< OpOperand * > BufferizationState::getAliasingOpOperand (OpResult result) const
Determine which OpOperand* will alias with result if the op is bufferized in place.
Return an empty vector if the op is not bufferizable.
Definition at line 82 of file BufferizableOpInterface.cpp.
References mlir::Value::getDefiningOp().
Referenced by mlir::linalg::comprehensive_bufferize::linalg_ext::InitTensorEliminationStep::eliminateInitTensors().
getAliasingOpResult()
OpResult BufferizationState::getAliasingOpResult (OpOperand & opOperand) const
Determine which OpResult will alias with opOperand if the op is bufferized in place.
Return an empty OpResult if the op is not bufferizable.
Definition at line 91 of file BufferizableOpInterface.cpp.
References mlir::detail::IROperandBase::getOwner().
Referenced by mlir::bufferization::BufferizationAliasInfo::bufferizeInPlace(), getBuffer(), hasReadAfterWriteInterference(), and wouldCreateWriteToNonWritableBuffer().
getBuffer()
FailureOr< Value > BufferizationState::getBuffer (RewriterBase & rewriter, OpOperand & opOperand, bool forceInPlace = false, Optional< Operation *> customCopyInsertionPoint = None) const
Return the buffer (memref) for a given OpOperand (tensor).
Return the result buffer (memref) for a given OpResult (tensor).
Allocate a new buffer and copy over data from the existing buffer if out-of-place bufferization was decided.
Allocate a new buffer and copy over data from the existing buffer if out-of-place bufferization is necessary.
Definition at line 234 of file BufferizableOpInterface.cpp.
References bufferizesToMemoryRead(), bufferizesToMemoryWrite(), mlir::Value::cast(), mlir::bufferization::createAlloc(), mlir::bufferization::BufferizationOptions::createDeallocs, mlir::bufferization::createMemCpy(), mlir::bufferization::BufferizationOptions::dynCastBufferizableOp(), mlir::failed(), mlir::failure(), findLastPrecedingWrite(), mlir::IROperand< DerivedT, IRValueT >::get(), getAliasingOpResult(), mlir::Operation::getLoc(), mlir::detail::IROperandBase::getOwner(), isInPlace(), isValueRead(), lookupBuffer(), mlir::OpBuilder::setInsertionPoint(), and setInsertionPointAfter().
Referenced by mlir::linalg::comprehensive_bufferize::vector_ext::TransferReadOpInterface::bufferize(), mlir::linalg::comprehensive_bufferize::std_ext::SelectOpInterface::bufferize(), mlir::linalg::comprehensive_bufferize::vector_ext::TransferWriteOpInterface::bufferize(), mlir::linalg::comprehensive_bufferize::scf_ext::ForOpInterface::bufferize(), mlir::linalg::comprehensive_bufferize::std_ext::CallOpInterface::bufferize(), and bufferizeFuncOpBoundary().
getDialectState()
template<typename StateT > Optional<const StateT *> mlir::bufferization::BufferizationState::getDialectState (StringRef name) const inline
Return dialect-specific bufferization state.
Definition at line 238 of file BufferizableOpInterface.h.
References mlir::bufferization::None.
Referenced by getModuleBufferizationState().
getOptions()
const BufferizationOptions& mlir::bufferization::BufferizationState::getOptions () const inline
Return a reference to the BufferizationOptions.
Definition at line 255 of file BufferizableOpInterface.h.
References options, and mlir::bufferization::replaceOpWithBufferizedValues().
Referenced by aliasesNonWritableBuffer(), mlir::bufferization::analyzeOp(), annotateOpsWithBufferizationMarkers(), mlir::linalg::comprehensive_bufferize::scf_ext::ExecuteRegionOpInterface::bufferize(), mlir::linalg::comprehensive_bufferize::scf_ext::IfOpInterface::bufferize(), mlir::linalg::comprehensive_bufferize::std_ext::CallOpInterface::bufferize(), bufferizeFuncOpBoundary(), mlir::bufferization::bufferizeOp(), checkAliasInfoConsistency(), equivalenceAnalysis(), getAssumedUniqueReturnOp(), hasReadAfterWriteInterference(), and inPlaceAnalysis().
getOrCreateDialectState()
template<typename StateT > StateT& mlir::bufferization::BufferizationState::getOrCreateDialectState (StringRef name) inline
Return dialect-specific bufferization state or create one if none exists.
Definition at line 247 of file BufferizableOpInterface.h.
Referenced by getModuleBufferizationState().
isInPlace()
virtual bool mlir::bufferization::BufferizationState::isInPlace (OpOperand & opOperand) const pure virtual
Return true if the given OpResult has been decided to bufferize inplace.
Implemented in mlir::bufferization::AnalysisBufferizationState.
Referenced by equivalenceAnalysis(), getAssumedUniqueReturnOp(), and getBuffer().
isValueRead()
bool BufferizationState::isValueRead (Value value) const
Return true if the given value is read by an op that bufferizes to a memory read.
Also takes into account ops that create an alias but do not read by themselves (e.g., ExtractSliceOp).
Definition at line 137 of file BufferizableOpInterface.cpp.
References mlir::Value::getType(), mlir::Value::getUses(), and mlir::Type::isa().
Referenced by mlir::linalg::comprehensive_bufferize::scf_ext::ForOpInterface::bufferizesToMemoryRead(), getAssumedUniqueReturnOp(), and getBuffer().
The documentation for this class was generated from the following files:
include/mlir/Dialect/Bufferization/IR/BufferizableOpInterface.h
lib/Dialect/Bufferization/IR/BufferizableOpInterface.cpp