MLIR: mlir::pdll::ast::Node Class Reference
mlir::pdll::ast::Node Class Reference
This class represents a base AST node.
#include "mlir/Tools/PDLL/AST/Nodes.h"
Classes
class NodeBase
This CRTP class provides several utilies when defining new AST nodes.
Public Member Functions
TypeID getTypeID () const
Return the type identifier of this node.
llvm::SMRange getLoc () const
Return the location of this node.
void print (raw_ostream &os) const
Print this node to the given stream.
Protected Member Functions
Node (TypeID typeID, llvm::SMRange loc)
Detailed Description
This class represents a base AST node.
All AST nodes are derived from this class, and it contains many of the base functionality for interacting with nodes.
Definition at line 107 of file Nodes.h.
Constructor & Destructor Documentation
Node()
mlir::pdll::ast::Node::Node (TypeID typeID, llvm::SMRange loc) inline protected
Definition at line 135 of file Nodes.h.
Member Function Documentation
getLoc()
llvm::SMRange mlir::pdll::ast::Node::getLoc () const inline
Return the location of this node.
Definition at line 129 of file Nodes.h.
References print().
Referenced by mlir::pdll::ast::OperationExpr::create().
getTypeID()
TypeID mlir::pdll::ast::Node::getTypeID () const inline
Return the type identifier of this node.
Definition at line 126 of file Nodes.h.
Referenced by mlir::pdll::ast::Node::NodeBase< CompoundStmt, Stmt >::classof().
print()
void Node::print (raw_ostream & os) const
Print this node to the given stream.
Definition at line 329 of file NodePrinter.cpp.
References mlir::pdll::ast::Type::print().
The documentation for this class was generated from the following files:
include/mlir/Tools/PDLL/AST/Nodes.h
lib/Tools/PDLL/AST/NodePrinter.cpp