MLIR: mlir::bufferization::BufferizationAliasInfo Class Reference
mlir::bufferization::BufferizationAliasInfo Class Reference
The BufferizationAliasInfo class maintains a list of buffer aliases and equivalence classes to support bufferization.
#include "mlir/Dialect/Bufferization/Transforms/OneShotAnalysis.h"
Public Member Functions
BufferizationAliasInfo (Operation *rootOp)
BufferizationAliasInfo (const BufferizationAliasInfo &)=delete
void createAliasInfoEntry (Value v)
Add a new entry for v in the aliasInfo and equivalentInfo.
void insertNewBufferAlias (Value newValue, Value alias)
Insert an info entry for newValue and merge its alias set with that of alias.
void insertNewBufferEquivalence (Value newValue, Value alias)
Insert an info entry for newValue and merge its alias set with that of alias.
void bufferizeInPlace (OpOperand &operand, BufferizationState &state)
Set the inPlace bufferization spec to true.
void bufferizeOutOfPlace (OpOperand &operand)
Set the inPlace bufferization spec to false.
bool areEquivalentBufferizedValues (Value v1, Value v2) const
Return true if v1 and v2 bufferize to equivalent buffers.
void unionAliasSets (Value v1, Value v2)
Union the alias sets of v1 and v2.
void unionEquivalenceClasses (Value v1, Value v2)
Union the equivalence classes of v1 and v2.
void applyOnEquivalenceClass (Value v, function_ref< void(Value)> fun) const
Apply fun to all the members of the equivalence class of v.
void applyOnAliases (Value v, function_ref< void(Value)> fun) const
Apply fun to all aliases of v.
void markInPlace (OpOperand &o)
Mark a value as in-place bufferized.
bool isInPlace (OpOperand &opOperand) const
Return true if a value was marked as in-place bufferized.
Detailed Description
The BufferizationAliasInfo class maintains a list of buffer aliases and equivalence classes to support bufferization.
Definition at line 60 of file OneShotAnalysis.h.
Constructor & Destructor Documentation
BufferizationAliasInfo() [1/2]
BufferizationAliasInfo::BufferizationAliasInfo (Operation * rootOp) explicit
Definition at line 99 of file OneShotAnalysis.cpp.
References createAliasInfoEntry(), mlir::Operation::getRegions(), mlir::Operation::getResults(), and mlir::Operation::walk().
BufferizationAliasInfo() [2/2]
mlir::bufferization::BufferizationAliasInfo::BufferizationAliasInfo (const BufferizationAliasInfo &) delete
Member Function Documentation
applyOnAliases()
void BufferizationAliasInfo::applyOnAliases (Value v, function_ref< void(Value)> fun) const
Apply fun to all aliases of v.
Definition at line 164 of file OneShotAnalysis.cpp.
Referenced by aliasesInPlaceWrite(), aliasesNonWritableBuffer(), and getAssumedUniqueReturnOp().
applyOnEquivalenceClass()
void BufferizationAliasInfo::applyOnEquivalenceClass (Value v, function_ref< void(Value)> fun) const
Apply fun to all the members of the equivalence class of v.
Definition at line 154 of file OneShotAnalysis.cpp.
Referenced by AssertDestinationPassingStyle::run().
areEquivalentBufferizedValues()
bool mlir::bufferization::BufferizationAliasInfo::areEquivalentBufferizedValues (Value v1, Value v2) const inline
Return true if v1 and v2 bufferize to equivalent buffers.
Definition at line 87 of file OneShotAnalysis.h.
Referenced by mlir::bufferization::AnalysisBufferizationState::areEquivalentBufferizedValues(), mlir::linalg::comprehensive_bufferize::linalg_ext::InitTensorEliminationStep::eliminateInitTensors(), getAssumedUniqueReturnOp(), and mlir::linalg::comprehensive_bufferize::scf_ext::AssertScfForAliasingProperties::run().
bufferizeInPlace()
void BufferizationAliasInfo::bufferizeInPlace (OpOperand & operand, BufferizationState & state)
Set the inPlace bufferization spec to true.
Merge result's and operand's aliasing sets and iterate to a fixed point.
Definition at line 140 of file OneShotAnalysis.cpp.
References mlir::IROperand< DerivedT, IRValueT >::get(), mlir::bufferization::BufferizationState::getAliasingOpResult(), and markInPlace().
Referenced by bufferizableInPlaceAnalysisImpl().
bufferizeOutOfPlace()
void BufferizationAliasInfo::bufferizeOutOfPlace (OpOperand & operand)
Set the inPlace bufferization spec to false.
Definition at line 148 of file OneShotAnalysis.cpp.
Referenced by bufferizableInPlaceAnalysisImpl().
createAliasInfoEntry()
void BufferizationAliasInfo::createAliasInfoEntry (Value v)
Add a new entry for v in the aliasInfo and equivalentInfo.
In the beginning the alias and equivalence sets only contain v itself.
Definition at line 114 of file OneShotAnalysis.cpp.
Referenced by BufferizationAliasInfo(), mlir::linalg::comprehensive_bufferize::linalg_ext::InitTensorEliminationStep::eliminateInitTensors(), and insertNewBufferAlias().
insertNewBufferAlias()
void BufferizationAliasInfo::insertNewBufferAlias (Value newValue, Value alias)
Insert an info entry for newValue and merge its alias set with that of alias.
Definition at line 121 of file OneShotAnalysis.cpp.
References createAliasInfoEntry().
Referenced by insertNewBufferEquivalence().
insertNewBufferEquivalence()
void BufferizationAliasInfo::insertNewBufferEquivalence (Value newValue, Value alias)
Insert an info entry for newValue and merge its alias set with that of alias.
Additionally, merge their equivalence classes.
Definition at line 128 of file OneShotAnalysis.cpp.
References insertNewBufferAlias().
isInPlace()
bool BufferizationAliasInfo::isInPlace (OpOperand & opOperand) const
Return true if a value was marked as in-place bufferized.
Definition at line 135 of file OneShotAnalysis.cpp.
Referenced by annotateOpsWithBufferizationMarkers(), mlir::linalg::comprehensive_bufferize::linalg_ext::InitTensorEliminationStep::eliminateInitTensors(), mlir::bufferization::AnalysisBufferizationState::isInPlace(), isInplaceMemoryWrite(), and mlir::linalg::comprehensive_bufferize::linalg_ext::InsertSliceAnchoredInitTensorEliminationStep::run().
markInPlace()
void mlir::bufferization::BufferizationAliasInfo::markInPlace (OpOperand & o) inline
Mark a value as in-place bufferized.
Definition at line 106 of file OneShotAnalysis.h.
References isInPlace().
Referenced by mlir::bufferization::AnalysisBufferizationState::AnalysisBufferizationState(), and bufferizeInPlace().
unionAliasSets()
void mlir::bufferization::BufferizationAliasInfo::unionAliasSets (Value v1, Value v2) inline
Union the alias sets of v1 and v2.
Definition at line 92 of file OneShotAnalysis.h.
Referenced by mlir::bufferization::AnalysisBufferizationState::AnalysisBufferizationState(), and mlir::linalg::comprehensive_bufferize::linalg_ext::InitTensorEliminationStep::eliminateInitTensors().
unionEquivalenceClasses()
void mlir::bufferization::BufferizationAliasInfo::unionEquivalenceClasses (Value v1, Value v2) inline
Union the equivalence classes of v1 and v2.
Definition at line 95 of file OneShotAnalysis.h.
Referenced by mlir::linalg::comprehensive_bufferize::linalg_ext::InitTensorEliminationStep::eliminateInitTensors(), and equivalenceAnalysis().
The documentation for this class was generated from the following files:
include/mlir/Dialect/Bufferization/Transforms/OneShotAnalysis.h
lib/Dialect/Bufferization/Transforms/OneShotAnalysis.cpp