MLIR: lib/Dialect/Linalg/Transforms/ComprehensiveBufferizePass.cpp File Reference
ComprehensiveBufferizePass.cpp File Reference
#include "PassDetail.h"
#include "mlir/Dialect/Bufferization/IR/BufferizableOpInterface.h"
#include "mlir/Dialect/Bufferization/IR/Bufferization.h"
#include "mlir/Dialect/Bufferization/Transforms/OneShotAnalysis.h"
#include "mlir/Dialect/Linalg/ComprehensiveBufferize/AffineInterfaceImpl.h"
#include "mlir/Dialect/Linalg/ComprehensiveBufferize/ArithInterfaceImpl.h"
#include "mlir/Dialect/Linalg/ComprehensiveBufferize/LinalgInterfaceImpl.h"
#include "mlir/Dialect/Linalg/ComprehensiveBufferize/ModuleBufferization.h"
#include "mlir/Dialect/Linalg/ComprehensiveBufferize/SCFInterfaceImpl.h"
#include "mlir/Dialect/Linalg/ComprehensiveBufferize/StdInterfaceImpl.h"
#include "mlir/Dialect/Linalg/ComprehensiveBufferize/VectorInterfaceImpl.h"
#include "mlir/Dialect/Linalg/Passes.h"
#include "mlir/Dialect/Tensor/Transforms/BufferizableOpInterfaceImpl.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Pass/PassManager.h"
#include "mlir/Transforms/GreedyPatternRewriteDriver.h"
#include "mlir/Transforms/Passes.h"
Functions
static void applyEnablingTransformations (ModuleOp moduleOp)
static FailureOr< Value > allocationFnUsingAlloca (OpBuilder &b, Location loc, MemRefType type, ValueRange dynShape)
static LogicalResult createLinalgCopyOp (OpBuilder &b, Location loc, Value from, Value to)
Create a linalg::GenericOp version of an n-D copy that can further tile, lower to loops or vectorize, unlike the current implementation of memref::CopyOp.
Function Documentation
allocationFnUsingAlloca()
static FailureOr<Value> allocationFnUsingAlloca (OpBuilder & b, Location loc, MemRefType type, ValueRange dynShape) static
Definition at line 72 of file ComprehensiveBufferizePass.cpp.
References mlir::OpBuilder::create(), mlir::Builder::getI64IntegerAttr(), and mlir::bufferization::kBufferAlignments.
Referenced by createLinalgCopyOp().
applyEnablingTransformations()
static void applyEnablingTransformations (ModuleOp moduleOp) static
Definition at line 66 of file ComprehensiveBufferizePass.cpp.
References mlir::RewritePatternSet::add(), and mlir::applyPatternsAndFoldGreedily().
Referenced by createLinalgCopyOp().
createLinalgCopyOp()
static LogicalResult createLinalgCopyOp (OpBuilder & b, Location loc, Value from, Value to) static
Create a linalg::GenericOp version of an n-D copy that can further tile, lower to loops or vectorize, unlike the current implementation of memref::CopyOp.
Do not depend on linalg::CopyOp that is getting deprecated.
Definition at line 84 of file ComprehensiveBufferizePass.cpp.
References mlir::OpPassManager::addPass(), allocationFnUsingAlloca(), applyEnablingTransformations(), mlir::Type::cast(), mlir::OpBuilder::create(), mlir::createCanonicalizerPass(), mlir::createCSEPass(), mlir::createLoopInvariantCodeMotionPass(), mlir::failed(), mlir::failure(), mlir::Builder::getContext(), mlir::AffineMap::getMultiDimIdentityMap(), mlir::getParallelIteratorTypeName(), mlir::Value::getType(), options, mlir::linalg::comprehensive_bufferize::runComprehensiveBufferize(), and mlir::success().