MLIR: lib/Transforms/ControlFlowSink.cpp File Reference
ControlFlowSink.cpp File Reference
#include "PassDetail.h"
#include "mlir/IR/Dominance.h"
#include "mlir/Interfaces/ControlFlowInterfaces.h"
#include "mlir/Transforms/ControlFlowSinkUtils.h"
#include "mlir/Transforms/Passes.h"
Functions
static bool isSideEffectFree (Operation *op)
Returns true if the given operation is side-effect free as are all of its nested operations.
Function Documentation
isSideEffectFree()
static bool isSideEffectFree (Operation * op) static
Returns true if the given operation is side-effect free as are all of its nested operations.
Definition at line 33 of file ControlFlowSink.cpp.
References mlir::controlFlowSink(), mlir::Operation::getRegions(), mlir::getSinglyExecutedRegionsToSink(), and mlir::Operation::hasTrait().