MLIR: lib/Analysis/Presburger/IntegerPolyhedron.cpp File Reference
IntegerPolyhedron.cpp File Reference
#include "mlir/Analysis/Presburger/IntegerPolyhedron.h"
#include "mlir/Analysis/Presburger/LinearTransform.h"
#include "mlir/Analysis/Presburger/Simplex.h"
#include "mlir/Analysis/Presburger/Utils.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/DenseSet.h"
#include "llvm/Support/Debug.h"
Macros
#define DEBUG_TYPE "presburger"
#define DEBUG_TYPE "fm"
#define DEBUG_TYPE "presburger"
Enumerations
enum BoundCmpResult
Functions
template<bool isEq>
static void normalizeConstraintByGCD (IntegerPolyhedron *constraints, unsigned rowIdx)
static void eliminateFromConstraint (IntegerPolyhedron *constraints, unsigned rowIdx, unsigned pivotRow, unsigned pivotCol, unsigned elimColStart, bool isEq)
Eliminate identifier from constraint at rowIdx based on coefficient at pivotRow, pivotCol.
static unsigned getBestIdToEliminate (const IntegerPolyhedron &cst, unsigned start, unsigned end)
Returns the position of the identifier that has the minimum <number of="" lower="" bounds>=""> times <number of="" upper="" bounds>=""> from the specified range of identifiers [start, end).
bool eqInvolvesSuffixDims (const IntegerPolyhedron &poly, unsigned eqIndex, unsigned numDims)
bool ineqInvolvesSuffixDims (const IntegerPolyhedron &poly, unsigned ineqIndex, unsigned numDims)
void removeConstraintsInvolvingSuffixDims (IntegerPolyhedron &poly, unsigned unboundedDims)
static int64_t valueAt (ArrayRef< int64_t > expr, ArrayRef< int64_t > point)
Helper to evaluate an affine expression at a point.
static void fillInequality (IntegerPolyhedron *cst, unsigned r, int64_t val)
static void negateInequality (IntegerPolyhedron *cst, unsigned r)
static void eliminateRedundantLocalId (IntegerPolyhedron &poly, unsigned pos1, unsigned pos2)
Eliminate pos2^th local identifier, replacing its every instance with pos1^th local identifier.
static int findEqualityToConstant (const IntegerPolyhedron &cst, unsigned pos, bool symbolic=false)
Finds an equality that equates the specified identifier to a constant.
static std::pair< unsigned, unsigned > getNewNumDimsSymbols (unsigned pos, const IntegerPolyhedron &cst)
static void getCommonConstraints (const IntegerPolyhedron &a, const IntegerPolyhedron &b, IntegerPolyhedron &c)
static void getIndependentConstraints (const IntegerPolyhedron &cst, unsigned pos, unsigned num, SmallVectorImpl< unsigned > &nbIneqIndices, SmallVectorImpl< unsigned > &nbEqIndices)
Find positions of inequalities and equalities that do not have a coefficient for [pos, pos + num) identifiers.
Macro Definition Documentation
DEBUG_TYPE [1/3]
#define DEBUG_TYPE "presburger"
Definition at line 1812 of file IntegerPolyhedron.cpp.
DEBUG_TYPE [2/3]
#define DEBUG_TYPE "fm"
Definition at line 1812 of file IntegerPolyhedron.cpp.
DEBUG_TYPE [3/3]
#define DEBUG_TYPE "presburger"
Definition at line 1812 of file IntegerPolyhedron.cpp.
Enumeration Type Documentation
BoundCmpResult
enum BoundCmpResult
Definition at line 1851 of file IntegerPolyhedron.cpp.
Function Documentation
eliminateFromConstraint()
static void eliminateFromConstraint (IntegerPolyhedron * constraints, unsigned rowIdx, unsigned pivotRow, unsigned pivotCol, unsigned elimColStart, bool isEq) static
Eliminate identifier from constraint at rowIdx based on coefficient at pivotRow, pivotCol.
Columns in range [elimColStart, pivotCol) will not be updated as they have already been eliminated.
Definition at line 403 of file IntegerPolyhedron.cpp.
References mlir::IntegerPolyhedron::atEq(), mlir::IntegerPolyhedron::atIneq(), mlir::IntegerPolyhedron::getNumCols(), and mlir::lcm().
Referenced by mlir::IntegerPolyhedron::gaussianEliminateIds(), and mlir::IntegerPolyhedron::removeRedundantLocalVars().
eliminateRedundantLocalId()
static void eliminateRedundantLocalId (IntegerPolyhedron & poly, unsigned pos1, unsigned pos2) static
Eliminate pos2^th local identifier, replacing its every instance with pos1^th local identifier.
This function is intended to be used to remove redundancy when local variables at position pos1 and pos2 are restricted to have the same value.
Definition at line 1036 of file IntegerPolyhedron.cpp.
References mlir::IntegerPolyhedron::atEq(), mlir::IntegerPolyhedron::atIneq(), mlir::IntegerPolyhedron::getNumDimAndSymbolIds(), mlir::IntegerPolyhedron::getNumEqualities(), mlir::IntegerPolyhedron::getNumInequalities(), mlir::IntegerPolyhedron::getNumLocalIds(), and mlir::IntegerPolyhedron::removeId().
Referenced by mlir::IntegerPolyhedron::mergeLocalIds().
eqInvolvesSuffixDims()
bool eqInvolvesSuffixDims (const IntegerPolyhedron & poly, unsigned eqIndex, unsigned numDims)
Definition at line 598 of file IntegerPolyhedron.cpp.
References mlir::IntegerPolyhedron::atEq(), and mlir::IntegerPolyhedron::getNumIds().
Referenced by removeConstraintsInvolvingSuffixDims().
fillInequality()
static void fillInequality (IntegerPolyhedron * cst, unsigned r, int64_t val) inline static
Definition at line 933 of file IntegerPolyhedron.cpp.
References mlir::IntegerPolyhedron::atIneq(), and mlir::IntegerPolyhedron::getNumCols().
Referenced by mlir::IntegerPolyhedron::removeRedundantInequalities().
findEqualityToConstant()
static int findEqualityToConstant (const IntegerPolyhedron & cst, unsigned pos, bool symbolic = false) static
Finds an equality that equates the specified identifier to a constant.
Returns the position of the equality row. If 'symbolic' is set to true, symbols are also treated like a constant, i.e., an affine function of the symbols is also treated like a constant. Returns -1 if such an equality could not be found.
Definition at line 1240 of file IntegerPolyhedron.cpp.
References mlir::IntegerPolyhedron::atEq(), mlir::IntegerPolyhedron::getNumDimIds(), mlir::IntegerPolyhedron::getNumEqualities(), and mlir::IntegerPolyhedron::getNumIds().
Referenced by mlir::IntegerPolyhedron::computeConstantLowerOrUpperBound(), mlir::IntegerPolyhedron::constantFoldId(), and mlir::IntegerPolyhedron::getConstantBoundOnDimSize().
getBestIdToEliminate()
static unsigned getBestIdToEliminate (const IntegerPolyhedron & cst, unsigned start, unsigned end) static
Returns the position of the identifier that has the minimum <number of="" lower="" bounds>=""> times <number of="" upper="" bounds>=""> from the specified range of identifiers [start, end).
It is often best to eliminate in the increasing order of these counts when doing Fourier-Motzkin elimination since FM adds that many new constraints.
Definition at line 440 of file IntegerPolyhedron.cpp.
References mlir::IntegerPolyhedron::atIneq(), mlir::IntegerPolyhedron::getNumIds(), mlir::IntegerPolyhedron::getNumInequalities(), and min().
Referenced by mlir::IntegerPolyhedron::isEmpty(), and mlir::IntegerPolyhedron::projectOut().
getCommonConstraints()
static void getCommonConstraints (const IntegerPolyhedron & a, const IntegerPolyhedron & b, IntegerPolyhedron & c) static
Definition at line 1873 of file IntegerPolyhedron.cpp.
References mlir::IntegerPolyhedron::addEquality(), mlir::IntegerPolyhedron::addInequality(), mlir::IntegerPolyhedron::getEquality(), mlir::IntegerPolyhedron::getInequality(), mlir::IntegerPolyhedron::getNumDimIds(), mlir::IntegerPolyhedron::getNumEqualities(), mlir::IntegerPolyhedron::getNumInequalities(), mlir::IntegerPolyhedron::getNumLocalIds(), mlir::IntegerPolyhedron::getNumSymbolIds(), and mlir::IntegerPolyhedron::reset().
Referenced by mlir::IntegerPolyhedron::unionBoundingBox().
getIndependentConstraints()
static void getIndependentConstraints (const IntegerPolyhedron & cst, unsigned pos, unsigned num, SmallVectorImpl< unsigned > & nbIneqIndices, SmallVectorImpl< unsigned > & nbEqIndices) static
Find positions of inequalities and equalities that do not have a coefficient for [pos, pos + num) identifiers.
Definition at line 2018 of file IntegerPolyhedron.cpp.
References mlir::IntegerPolyhedron::atEq(), mlir::IntegerPolyhedron::atIneq(), mlir::IntegerPolyhedron::getNumEqualities(), mlir::IntegerPolyhedron::getNumIds(), and mlir::IntegerPolyhedron::getNumInequalities().
Referenced by mlir::IntegerPolyhedron::removeIndependentConstraints().
getNewNumDimsSymbols()
static std::pair<unsigned, unsigned> getNewNumDimsSymbols (unsigned pos, const IntegerPolyhedron & cst) static
Definition at line 1589 of file IntegerPolyhedron.cpp.
References mlir::IntegerPolyhedron::getNumDimIds(), and mlir::IntegerPolyhedron::getNumSymbolIds().
Referenced by mlir::IntegerPolyhedron::fourierMotzkinEliminate().
ineqInvolvesSuffixDims()
bool ineqInvolvesSuffixDims (const IntegerPolyhedron & poly, unsigned ineqIndex, unsigned numDims)
Definition at line 605 of file IntegerPolyhedron.cpp.
References mlir::IntegerPolyhedron::atIneq(), and mlir::IntegerPolyhedron::getNumIds().
Referenced by removeConstraintsInvolvingSuffixDims().
negateInequality()
static void negateInequality (IntegerPolyhedron * cst, unsigned r) inline static
Definition at line 941 of file IntegerPolyhedron.cpp.
References mlir::IntegerPolyhedron::atIneq(), and mlir::IntegerPolyhedron::getNumCols().
Referenced by mlir::IntegerPolyhedron::removeRedundantInequalities().
normalizeConstraintByGCD()
template<bool isEq> static void normalizeConstraintByGCD (IntegerPolyhedron * constraints, unsigned rowIdx) static
Definition at line 342 of file IntegerPolyhedron.cpp.
References mlir::IntegerPolyhedron::atEq(), mlir::IntegerPolyhedron::atIneq(), and mlir::IntegerPolyhedron::getNumCols().
Referenced by mlir::IntegerPolyhedron::gaussianEliminateIds(), mlir::IntegerPolyhedron::normalizeConstraintsByGCD(), and mlir::IntegerPolyhedron::removeRedundantLocalVars().
removeConstraintsInvolvingSuffixDims()
void removeConstraintsInvolvingSuffixDims (IntegerPolyhedron & poly, unsigned unboundedDims)
Definition at line 613 of file IntegerPolyhedron.cpp.
References eqInvolvesSuffixDims(), mlir::IntegerPolyhedron::getNumEqualities(), mlir::IntegerPolyhedron::getNumInequalities(), ineqInvolvesSuffixDims(), mlir::IntegerPolyhedron::removeEquality(), and mlir::IntegerPolyhedron::removeInequality().
Referenced by mlir::IntegerPolyhedron::findIntegerSample().
valueAt()
static int64_t valueAt (ArrayRef< int64_t > expr, ArrayRef< int64_t > point) static
Helper to evaluate an affine expression at a point.
The expression is a list of coefficients for the dimensions followed by the constant term.
Definition at line 779 of file IntegerPolyhedron.cpp.
References value.
Referenced by mlir::IntegerPolyhedron::containsPoint().