MLIR: lib/Dialect/LLVMIR/IR/LLVMDialect.cpp File Reference
LLVMDialect.cpp File Reference
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "TypeDetail.h"
#include "mlir/Dialect/LLVMIR/LLVMTypes.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/DialectImplementation.h"
#include "mlir/IR/FunctionImplementation.h"
#include "mlir/IR/MLIRContext.h"
#include "mlir/IR/Matchers.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/ADT/TypeSwitch.h"
#include "llvm/AsmParser/Parser.h"
#include "llvm/Bitcode/BitcodeReader.h"
#include "llvm/Bitcode/BitcodeWriter.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/Type.h"
#include "llvm/Support/Mutex.h"
#include "llvm/Support/SourceMgr.h"
#include <iostream>
#include <numeric>
#include "mlir/Dialect/LLVMIR/LLVMOpsDialect.cpp.inc"
#include "mlir/Dialect/LLVMIR/LLVMOpsEnums.cpp.inc"
#include "mlir/Dialect/LLVMIR/LLVMOpsInterfaces.cpp.inc"
#include "mlir/Dialect/LLVMIR/LLVMOpsAttrDefs.cpp.inc"
#include "mlir/Dialect/LLVMIR/LLVMOps.cpp.inc"
Macros
#define GET_ATTRDEF_CLASSES
#define REGISTER_ENUM_TYPE(Ty)
#define GET_OP_LIST
#define GET_OP_CLASSES
Functions
static auto processFMFAttr (ArrayRef< NamedAttribute > attrs)
static ParseResult parseLLVMOpAttrs (OpAsmParser &parser, NamedAttrList &result)
static void printLLVMOpAttrs (OpAsmPrinter &printer, Operation *op, DictionaryAttr attrs)
static LogicalResult verifySymbolAttrUse (FlatSymbolRefAttr symbol, Operation *op, SymbolTableCollection &symbolTable)
Verifies symbol's use in op to ensure the symbol is a valid and fully defined llvm.func.
static void printICmpOp (OpAsmPrinter &p, ICmpOp &op)
static void printFCmpOp (OpAsmPrinter &p, FCmpOp &op)
template<typename CmpPredicateType >
static ParseResult parseCmpOp (OpAsmParser &parser, OperationState &result)
static void printAllocaOp (OpAsmPrinter &p, AllocaOp &op)
static ParseResult parseAllocaOp (OpAsmParser &parser, OperationState &result)
static ParseResult parseSwitchOpCases (OpAsmParser &parser, Type flagType, ElementsAttr &caseValues, SmallVectorImpl< Block *> &caseDestinations, SmallVectorImpl< SmallVector< OpAsmParser::OperandType >> &caseOperands, SmallVectorImpl< SmallVector< Type >> &caseOperandTypes)
<cases> ::= integer : bb-id ((ssa-use-and-type-list))? (, integer : bb-id ((ssa-use-and-type-list))?)?
static void printSwitchOpCases (OpAsmPrinter &p, SwitchOp op, Type flagType, ElementsAttr caseValues, SuccessorRange caseDestinations, OperandRangeRange caseOperands, const TypeRangeRange &caseOperandTypes)
static LogicalResult verify (SwitchOp op)
static void recordStructIndices (Type type, unsigned currentIndex, SmallVectorImpl< unsigned > &indices, SmallVectorImpl< unsigned > *structSizes, SmallPtrSet< Type, 4 > &visited)
Populates indices with positions of GEP indices that would correspond to LLVMStructTypes potentially nested in the given type.
static void findKnownStructIndices (Type baseGEPType, SmallVectorImpl< unsigned > &indices, SmallVectorImpl< unsigned > *structSizes=nullptr)
Populates indices with positions of GEP indices that correspond to LLVMStructTypes potentially nested in the given baseGEPType, which must be either an LLVMPointer type or a vector thereof.
static ParseResult parseGEPIndices (OpAsmParser &parser, SmallVectorImpl< OpAsmParser::OperandType > &indices, DenseIntElementsAttr &structIndices)
static void printGEPIndices (OpAsmPrinter &printer, LLVM::GEPOp gepOp, OperandRange indices, DenseIntElementsAttr structIndices)
LogicalResult verify (LLVM::GEPOp gepOp)
LogicalResult verifySymbolAttribute (Operation *op, StringRef attributeName, llvm::function_ref< LogicalResult(Operation *, SymbolRefAttr)> verifySymbolType)
template<typename OpTy >
static LogicalResult verifyOpMetadata (Operation *op, StringRef attributeName)
static LogicalResult verifyMemoryOpMetadata (Operation *op)
static LogicalResult verify (LoadOp op)
static void printLoadOp (OpAsmPrinter &p, LoadOp &op)
static Type getLoadStoreElementType (OpAsmParser &parser, Type type, llvm::SMLoc trailingTypeLoc)
static ParseResult parseLoadOp (OpAsmParser &parser, OperationState &result)
static LogicalResult verify (StoreOp op)
static void printStoreOp (OpAsmPrinter &p, StoreOp &op)
static ParseResult parseStoreOp (OpAsmParser &parser, OperationState &result)
static LogicalResult verify (InvokeOp op)
static void printInvokeOp (OpAsmPrinter &p, InvokeOp op)
static ParseResult parseInvokeOp (OpAsmParser &parser, OperationState &result)
<operation> ::= llvm.invoke (function-id | ssa-use) (ssa-use-list) to bb-id ([ ssa-use-and-type-list ])? unwind bb-id ([ ssa-use-and-type-list ])? attribute-dict? : function-type
static LogicalResult verify (LandingpadOp op)
===-------------------------------------------------------------------—===// Verifying/Printing/Parsing for LLVM::LandingpadOp.
static void printLandingpadOp (OpAsmPrinter &p, LandingpadOp &op)
static ParseResult parseLandingpadOp (OpAsmParser &parser, OperationState &result)
<operation> ::= llvm.landingpad cleanup? ((catch | filter) operand-type ssa-use)* attribute-dict?
static LogicalResult verify (CallOp &op)
static void printCallOp (OpAsmPrinter &p, CallOp &op)
static ParseResult parseCallOp (OpAsmParser &parser, OperationState &result)
static void printExtractElementOp (OpAsmPrinter &p, ExtractElementOp &op)
static ParseResult parseExtractElementOp (OpAsmParser &parser, OperationState &result)
static LogicalResult verify (ExtractElementOp op)
static void printExtractValueOp (OpAsmPrinter &p, ExtractValueOp &op)
static Type getInsertExtractValueElementType (OpAsmParser &parser, Type containerType, ArrayAttr positionAttr, llvm::SMLoc attributeLoc, llvm::SMLoc typeLoc)
static Type getInsertExtractValueElementType (Type containerType, ArrayAttr positionAttr, Operation *op)
static ParseResult parseExtractValueOp (OpAsmParser &parser, OperationState &result)
static LogicalResult verify (ExtractValueOp op)
static void printInsertElementOp (OpAsmPrinter &p, InsertElementOp &op)
static ParseResult parseInsertElementOp (OpAsmParser &parser, OperationState &result)
static LogicalResult verify (InsertElementOp op)
static void printInsertValueOp (OpAsmPrinter &p, InsertValueOp &op)
static ParseResult parseInsertValueOp (OpAsmParser &parser, OperationState &result)
static LogicalResult verify (InsertValueOp op)
static void printReturnOp (OpAsmPrinter &p, ReturnOp op)
static ParseResult parseReturnOp (OpAsmParser &parser, OperationState &result)
static LogicalResult verify (ReturnOp op)
template<typename OpTy >
static OpTy lookupSymbolInModule (Operation *parent, StringRef name)
static LogicalResult verify (AddressOfOp op)
static StringRef getLinkageAttrName ()
Returns the name used for the linkage attribute.
static StringRef getUnnamedAddrAttrName ()
Returns the name used for the unnamed_addr attribute.
static void printGlobalOp (OpAsmPrinter &p, GlobalOp op)
static int parseOptionalKeywordAlternative (OpAsmParser &parser, ArrayRef< StringRef > keywords)
template<typename EnumTy , typename RetTy = EnumTy>
static RetTy parseOptionalLLVMKeyword (OpAsmParser &parser, OperationState &result, EnumTy defaultValue)
Parse an enum from the keyword, or default to the provided default value.
static ParseResult parseGlobalOp (OpAsmParser &parser, OperationState &result)
static bool isZeroAttribute (Attribute value)
static LogicalResult verify (GlobalOp op)
static LogicalResult verify (GlobalCtorsOp op)
static LogicalResult verify (GlobalDtorsOp op)
static void printShuffleVectorOp (OpAsmPrinter &p, ShuffleVectorOp &op)
static ParseResult parseShuffleVectorOp (OpAsmParser &parser, OperationState &result)
static Type buildLLVMFunctionType (OpAsmParser &parser, llvm::SMLoc loc, ArrayRef< Type > inputs, ArrayRef< Type > outputs, function_interface_impl::VariadicFlag variadicFlag)
static ParseResult parseLLVMFuncOp (OpAsmParser &parser, OperationState &result)
static void printLLVMFuncOp (OpAsmPrinter &p, LLVMFuncOp op)
static LogicalResult verify (LLVMFuncOp op)
static LogicalResult verify (LLVM::ConstantOp op)
static ParseResult parseAtomicBinOp (OpAsmParser &parser, OperationState &result, StringRef attrName)
static ParseResult parseAtomicOrdering (OpAsmParser &parser, OperationState &result, StringRef attrName)
static void printAtomicRMWOp (OpAsmPrinter &p, AtomicRMWOp &op)
static ParseResult parseAtomicRMWOp (OpAsmParser &parser, OperationState &result)
static LogicalResult verify (AtomicRMWOp op)
static void printAtomicCmpXchgOp (OpAsmPrinter &p, AtomicCmpXchgOp &op)
static ParseResult parseAtomicCmpXchgOp (OpAsmParser &parser, OperationState &result)
static LogicalResult verify (AtomicCmpXchgOp op)
static ParseResult parseFenceOp (OpAsmParser &parser, OperationState &result)
static void printFenceOp (OpAsmPrinter &p, FenceOp &op)
static LogicalResult verify (FenceOp &op)
template<typename T >
static Optional< T > getOption (ArrayRef< std::pair< LoopOptionCase, int64_t >> options, LoopOptionCase option)
Variables
static constexpr const char kVolatileAttrName [] = "volatile_"
static constexpr const char kNonTemporalAttrName [] = "nontemporal"
static constexpr const FastmathFlags fastmathFlagsList []
Macro Definition Documentation
GET_ATTRDEF_CLASSES
#define GET_ATTRDEF_CLASSES
Definition at line 49 of file LLVMDialect.cpp.
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 2516 of file LLVMDialect.cpp.
GET_OP_LIST
#define GET_OP_LIST
REGISTER_ENUM_TYPE
#define REGISTER_ENUM_TYPE (Ty)
Value:
template <>                                                                  \
  struct EnumTraits<Ty> {                                                      \
    static StringRef stringify(Ty value) { return stringify##Ty(value); }      \
    static unsigned getMaxEnumVal() { return getMaxEnumValFor##Ty(); }         \
  }
Definition at line 1686 of file LLVMDialect.cpp.
Function Documentation
buildLLVMFunctionType()
static Type buildLLVMFunctionType (OpAsmParser & parser, llvm::SMLoc loc, ArrayRef< Type > inputs, ArrayRef< Type > outputs, function_interface_impl::VariadicFlag variadicFlag) static
Definition at line 1988 of file LLVMDialect.cpp.
References mlir::AsmParser::emitError(), mlir::LLVM::LLVMFunctionType::get(), mlir::AsmParser::getBuilder(), mlir::Builder::getContext(), mlir::LLVM::isCompatibleType(), and mlir::function_interface_impl::VariadicFlag::isVariadic().
Referenced by parseLLVMFuncOp().
findKnownStructIndices()
static void findKnownStructIndices (Type baseGEPType, SmallVectorImpl< unsigned > & indices, SmallVectorImpl< unsigned > * structSizes = nullptr) static
Populates indices with positions of GEP indices that correspond to LLVMStructTypes potentially nested in the given baseGEPType, which must be either an LLVMPointer type or a vector thereof.
If structSizes is provided, it is populated with sizes of the indexed structs for bounds verification purposes.
Definition at line 401 of file LLVMDialect.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::addAttributes(), mlir::OperationState::addOperands(), mlir::OperationState::addTypes(), mlir::Type::cast(), mlir::Type::dyn_cast(), getElementType(), mlir::Builder::getI32TensorAttr(), mlir::Value::getType(), mlir::m_ConstantInt(), mlir::matchPattern(), recordStructIndices(), and vectorType().
Referenced by verify().
getInsertExtractValueElementType() [1/2]
static Type getInsertExtractValueElementType (OpAsmParser & parser, Type containerType, ArrayAttr positionAttr, llvm::SMLoc attributeLoc, llvm::SMLoc typeLoc) static
Definition at line 1231 of file LLVMDialect.cpp.
References mlir::Type::dyn_cast(), mlir::AsmParser::emitError(), and mlir::LLVM::isCompatibleType().
Referenced by parseExtractValueOp(), parseInsertValueOp(), and verify().
getInsertExtractValueElementType() [2/2]
static Type getInsertExtractValueElementType (Type containerType, ArrayAttr positionAttr, Operation * op) static
Definition at line 1273 of file LLVMDialect.cpp.
References mlir::Type::dyn_cast(), mlir::Operation::emitError(), mlir::Operation::emitOpError(), and mlir::LLVM::isCompatibleType().
getLinkageAttrName()
static StringRef getLinkageAttrName () static
Returns the name used for the linkage attribute.
This must correspond to the name of the attribute in ODS.
Definition at line 1602 of file LLVMDialect.cpp.
Referenced by getUnnamedAddrAttrName(), parseGlobalOp(), parseLLVMFuncOp(), parseShuffleVectorOp(), printGlobalOp(), and printLLVMFuncOp().
getLoadStoreElementType()
static Type getLoadStoreElementType (OpAsmParser & parser, Type type, llvm::SMLoc trailingTypeLoc) static
Definition at line 644 of file LLVMDialect.cpp.
References mlir::Type::dyn_cast(), and mlir::AsmParser::emitError().
Referenced by parseLoadOp(), and parseStoreOp().
getOption()
template<typename T > static Optional<T> getOption (ArrayRef< std::pair< LoopOptionCase, int64_t >> options, LoopOptionCase option) static
Definition at line 2790 of file LLVMDialect.cpp.
References mlir::AsmParser::emitError(), mlir::failed(), mlir::AsmParser::getContext(), mlir::AsmParser::getNameLoc(), mlir::LLVM::LoopOptionsAttrBuilder::LoopOptionsAttr, mlir::AsmParser::parseEqual(), mlir::AsmParser::parseGreater(), mlir::AsmParser::parseInteger(), mlir::AsmParser::parseKeyword(), mlir::AsmParser::parseLess(), mlir::AsmParser::parseOptionalComma(), mlir::AsmParser::parseOptionalKeyword(), print(), mlir::succeeded(), and value.
Referenced by mlir::detail::PassOptions::ListOption< DataType, OptionParser >::operator*(), and mlir::detail::PassOptions::Option< DataType, OptionParser >::operator=().
getUnnamedAddrAttrName()
static StringRef getUnnamedAddrAttrName () static
Returns the name used for the unnamed_addr attribute.
This must correspond to the name of the attribute in ODS.
Definition at line 1606 of file LLVMDialect.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::addRegion(), mlir::NamedAttrList::append(), mlir::OperationState::attributes, mlir::Builder::getContext(), mlir::Builder::getI32IntegerAttr(), mlir::Builder::getI64IntegerAttr(), getLinkageAttrName(), mlir::Builder::getStringAttr(), mlir::SymbolTable::getSymbolAttrName(), and mlir::Builder::getUnitAttr().
Referenced by parseGlobalOp(), and printGlobalOp().
isZeroAttribute()
static bool isZeroAttribute (Attribute value) static
Definition at line 1780 of file LLVMDialect.cpp.
References mlir::Attribute::dyn_cast().
Referenced by verify().
lookupSymbolInModule()
template<typename OpTy > static OpTy lookupSymbolInModule (Operation * parent, StringRef name) static
Definition at line 1556 of file LLVMDialect.cpp.
References mlir::Operation::getParentOp(), mlir::SymbolTable::lookupSymbolIn(), and mlir::LLVM::satisfiesLLVMModule().
parseAllocaOp()
static ParseResult parseAllocaOp (OpAsmParser & parser, OperationState & result) static
Definition at line 194 of file LLVMDialect.cpp.
References mlir::OperationState::addTypes(), mlir::OperationState::attributes, mlir::Type::dyn_cast(), mlir::AsmParser::emitError(), mlir::NamedAttrList::erase(), mlir::failure(), mlir::AsmParser::getCurrentLocation(), mlir::Builder::getI32VectorAttr(), mlir::NamedAttrList::getNamed(), mlir::AsmParser::getNameLoc(), mlir::OperationState::operands, mlir::AsmParser::parseColon(), mlir::AsmParser::parseKeyword(), mlir::OpAsmParser::parseOperand(), mlir::AsmParser::parseOptionalAttrDict(), mlir::AsmParser::parseType(), mlir::OpAsmParser::resolveOperand(), mlir::success(), and value.
parseAtomicBinOp()
static ParseResult parseAtomicBinOp (OpAsmParser & parser, OperationState & result, StringRef attrName) static
Definition at line 2217 of file LLVMDialect.cpp.
References mlir::failure(), mlir::AsmParser::getCurrentLocation(), and mlir::AsmParser::parseKeyword().
Referenced by parseAtomicRMWOp().
parseAtomicCmpXchgOp()
static ParseResult parseAtomicCmpXchgOp (OpAsmParser & parser, OperationState & result) static
Definition at line 2352 of file LLVMDialect.cpp.
References mlir::OperationState::addTypes(), mlir::OperationState::attributes, mlir::failure(), mlir::LLVM::LLVMPointerType::get(), mlir::AsmParser::getBuilder(), mlir::Builder::getContext(), mlir::LLVM::LLVMStructType::getLiteral(), mlir::OperationState::operands, parseAtomicOrdering(), mlir::AsmParser::parseColonType(), mlir::AsmParser::parseComma(), mlir::OpAsmParser::parseOperand(), mlir::AsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::resolveOperand(), and mlir::success().
parseAtomicOrdering()
static ParseResult parseAtomicOrdering (OpAsmParser & parser, OperationState & result, StringRef attrName) static
Definition at line 2243 of file LLVMDialect.cpp.
References mlir::failure(), mlir::AsmParser::getCurrentLocation(), and mlir::AsmParser::parseKeyword().
Referenced by parseAtomicCmpXchgOp(), parseAtomicRMWOp(), and parseFenceOp().
parseAtomicRMWOp()
static ParseResult parseAtomicRMWOp (OpAsmParser & parser, OperationState & result) static
Definition at line 2279 of file LLVMDialect.cpp.
References mlir::OperationState::addTypes(), mlir::OperationState::attributes, mlir::failure(), mlir::LLVM::LLVMPointerType::get(), mlir::OperationState::operands, parseAtomicBinOp(), parseAtomicOrdering(), mlir::AsmParser::parseColonType(), mlir::AsmParser::parseComma(), mlir::OpAsmParser::parseOperand(), mlir::AsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::resolveOperand(), and mlir::success().
parseCallOp()
static ParseResult parseCallOp (OpAsmParser & parser, OperationState & result) static
Definition at line 1080 of file LLVMDialect.cpp.
References mlir::OperationState::addAttributes(), mlir::OperationState::addTypes(), mlir::OperationState::attributes, mlir::Type::dyn_cast(), mlir::AsmParser::emitError(), mlir::failure(), mlir::LLVM::LLVMFunctionType::get(), mlir::LLVM::LLVMPointerType::get(), mlir::AsmParser::getBuilder(), mlir::Builder::getContext(), mlir::AsmParser::getCurrentLocation(), mlir::AsmParser::getNameLoc(), mlir::Value::getType(), mlir::LLVM::getVectorElementType(), mlir::Type::isa(), mlir::LLVM::isCompatibleType(), mlir::OperationState::operands, mlir::AsmParser::Paren, mlir::AsmParser::parseAttribute(), mlir::AsmParser::parseColon(), mlir::OpAsmParser::parseOperandList(), mlir::AsmParser::parseOptionalAttrDict(), mlir::AsmParser::parseType(), mlir::OpAsmParser::resolveOperand(), mlir::OpAsmParser::resolveOperands(), mlir::success(), and vectorType().
parseCmpOp()
template<typename CmpPredicateType > static ParseResult parseCmpOp (OpAsmParser & parser, OperationState & result) static
Definition at line 112 of file LLVMDialect.cpp.
References mlir::AsmParser::getBuilder().
parseExtractElementOp()
static ParseResult parseExtractElementOp (OpAsmParser & parser, OperationState & result) static
Definition at line 1183 of file LLVMDialect.cpp.
References mlir::OperationState::addTypes(), mlir::OperationState::attributes, mlir::AsmParser::emitError(), mlir::failure(), mlir::AsmParser::getCurrentLocation(), mlir::LLVM::getVectorElementType(), mlir::LLVM::isCompatibleVectorType(), mlir::OperationState::operands, mlir::AsmParser::parseColonType(), mlir::AsmParser::parseLSquare(), mlir::OpAsmParser::parseOperand(), mlir::AsmParser::parseOptionalAttrDict(), mlir::AsmParser::parseRSquare(), mlir::OpAsmParser::resolveOperand(), and mlir::success().
parseExtractValueOp()
static ParseResult parseExtractValueOp (OpAsmParser & parser, OperationState & result) static
Definition at line 1320 of file LLVMDialect.cpp.
References mlir::OperationState::addTypes(), mlir::OperationState::attributes, mlir::failure(), mlir::AsmParser::getCurrentLocation(), mlir::Value::getDefiningOp(), getInsertExtractValueElementType(), min(), mlir::OperationState::operands, mlir::AsmParser::parseAttribute(), mlir::AsmParser::parseColon(), mlir::OpAsmParser::parseOperand(), mlir::AsmParser::parseOptionalAttrDict(), mlir::AsmParser::parseType(), mlir::OpAsmParser::resolveOperand(), and mlir::success().
parseFenceOp()
static ParseResult parseFenceOp (OpAsmParser & parser, OperationState & result) static
Definition at line 2409 of file LLVMDialect.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::attributes, mlir::failed(), mlir::failure(), mlir::AsmParser::getBuilder(), mlir::Builder::getStringAttr(), parseAtomicOrdering(), mlir::AsmParser::parseAttribute(), mlir::AsmParser::parseLParen(), mlir::AsmParser::parseOptionalAttrDict(), mlir::AsmParser::parseOptionalKeyword(), mlir::AsmParser::parseRParen(), and mlir::success().
parseGEPIndices()
static ParseResult parseGEPIndices (OpAsmParser & parser, SmallVectorImpl< OpAsmParser::OperandType > & indices, DenseIntElementsAttr & structIndices) static
Definition at line 484 of file LLVMDialect.cpp.
References mlir::sparse_tensor::constantIndex(), mlir::failed(), mlir::failure(), mlir::AsmParser::getBuilder(), mlir::Builder::getI32TensorAttr(), mlir::OptionalParseResult::getValue(), mlir::OptionalParseResult::hasValue(), mlir::OpAsmParser::parseOperand(), mlir::AsmParser::parseOptionalComma(), mlir::AsmParser::parseOptionalInteger(), mlir::succeeded(), and mlir::success().
parseGlobalOp()
static ParseResult parseGlobalOp (OpAsmParser & parser, OperationState & result) static
Definition at line 1720 of file LLVMDialect.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::addRegion(), mlir::OperationState::attributes, mlir::Attribute::dyn_cast_or_null(), mlir::AsmParser::emitError(), mlir::failed(), mlir::failure(), mlir::LLVM::LLVMArrayType::get(), mlir::AsmParser::getBuilder(), mlir::AsmParser::getContext(), mlir::Builder::getI64IntegerAttr(), getLinkageAttrName(), mlir::AsmParser::getNameLoc(), mlir::SymbolTable::getSymbolAttrName(), mlir::Builder::getUnitAttr(), getUnnamedAddrAttrName(), mlir::OptionalParseResult::hasValue(), mlir::AsmParser::parseAttribute(), mlir::AsmParser::parseLParen(), mlir::AsmParser::parseOptionalAttrDict(), mlir::AsmParser::parseOptionalColonTypeList(), mlir::AsmParser::parseOptionalKeyword(), mlir::OpAsmParser::parseOptionalRegion(), mlir::AsmParser::parseOptionalRParen(), mlir::AsmParser::parseRParen(), mlir::AsmParser::parseSymbolName(), mlir::succeeded(), mlir::success(), and value.
parseInsertElementOp()
static ParseResult parseInsertElementOp (OpAsmParser & parser, OperationState & result) static
Definition at line 1397 of file LLVMDialect.cpp.
References mlir::OperationState::addTypes(), mlir::OperationState::attributes, mlir::AsmParser::emitError(), mlir::failure(), mlir::AsmParser::getCurrentLocation(), mlir::LLVM::getVectorElementType(), mlir::LLVM::isCompatibleVectorType(), mlir::OperationState::operands, mlir::AsmParser::parseColonType(), mlir::AsmParser::parseComma(), mlir::AsmParser::parseLSquare(), mlir::OpAsmParser::parseOperand(), mlir::AsmParser::parseOptionalAttrDict(), mlir::AsmParser::parseRSquare(), mlir::OpAsmParser::resolveOperand(), mlir::success(), value, and vectorType().
parseInsertValueOp()
static ParseResult parseInsertValueOp (OpAsmParser & parser, OperationState & result) static
Definition at line 1447 of file LLVMDialect.cpp.
References mlir::OperationState::addTypes(), mlir::OperationState::attributes, mlir::failure(), mlir::AsmParser::getCurrentLocation(), getInsertExtractValueElementType(), mlir::OperationState::operands, mlir::AsmParser::parseAttribute(), mlir::AsmParser::parseColon(), mlir::AsmParser::parseComma(), mlir::OpAsmParser::parseOperand(), mlir::AsmParser::parseOptionalAttrDict(), mlir::AsmParser::parseType(), mlir::OpAsmParser::resolveOperand(), mlir::success(), and value.
parseInvokeOp()
static ParseResult parseInvokeOp (OpAsmParser & parser, OperationState & result) static
<operation> ::= llvm.invoke (function-id | ssa-use) (ssa-use-list) to bb-id ([ ssa-use-and-type-list ])? unwind bb-id ([ ssa-use-and-type-list ])? attribute-dict? : function-type
Definition at line 789 of file LLVMDialect.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::addOperands(), mlir::OperationState::addSuccessors(), mlir::OperationState::addTypes(), mlir::OperationState::attributes, mlir::AsmParser::emitError(), mlir::failure(), mlir::LLVM::LLVMFunctionType::get(), mlir::LLVM::LLVMPointerType::get(), mlir::AsmParser::getBuilder(), mlir::Builder::getContext(), mlir::AsmParser::getCurrentLocation(), mlir::Builder::getI32VectorAttr(), mlir::AsmParser::getNameLoc(), mlir::LLVM::isCompatibleType(), mlir::OperationState::operands, mlir::AsmParser::Paren, mlir::AsmParser::parseAttribute(), mlir::AsmParser::parseColon(), mlir::AsmParser::parseKeyword(), mlir::OpAsmParser::parseOperandList(), mlir::AsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::parseSuccessorAndUseList(), mlir::AsmParser::parseType(), mlir::OpAsmParser::resolveOperand(), mlir::OpAsmParser::resolveOperands(), and mlir::success().
parseLandingpadOp()
static ParseResult parseLandingpadOp (OpAsmParser & parser, OperationState & result) static
<operation> ::= llvm.landingpad cleanup? ((catch | filter) operand-type ssa-use)* attribute-dict?
Definition at line 942 of file LLVMDialect.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::addTypes(), mlir::failure(), mlir::AsmParser::getBuilder(), mlir::Builder::getUnitAttr(), mlir::OperationState::operands, mlir::AsmParser::parseColon(), mlir::OpAsmParser::parseOperand(), mlir::AsmParser::parseOptionalKeyword(), mlir::AsmParser::parseOptionalLParen(), mlir::AsmParser::parseRParen(), mlir::AsmParser::parseType(), mlir::OpAsmParser::resolveOperand(), mlir::succeeded(), and mlir::success().
parseLLVMFuncOp()
static ParseResult parseLLVMFuncOp (OpAsmParser & parser, OperationState & result) static
Definition at line 2027 of file LLVMDialect.cpp.
References mlir::function_interface_impl::addArgAndResultAttrs(), mlir::OperationState::addAttribute(), buildLLVMFunctionType(), mlir::failed(), mlir::failure(), mlir::AsmParser::getContext(), getLinkageAttrName(), mlir::SymbolTable::getSymbolAttrName(), mlir::function_interface_impl::getTypeAttrName(), mlir::OptionalParseResult::hasValue(), and mlir::function_interface_impl::parseFunctionSignature().
parseLLVMOpAttrs()
static ParseResult parseLLVMOpAttrs (OpAsmParser & parser, NamedAttrList & result) static
Definition at line 64 of file LLVMDialect.cpp.
References mlir::AsmParser::parseOptionalAttrDict().
parseLoadOp()
static ParseResult parseLoadOp (OpAsmParser & parser, OperationState & result) static
Definition at line 654 of file LLVMDialect.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::addTypes(), mlir::OperationState::attributes, mlir::failure(), mlir::AsmParser::getBuilder(), mlir::AsmParser::getCurrentLocation(), getLoadStoreElementType(), mlir::Builder::getUnitAttr(), kVolatileAttrName, mlir::OperationState::operands, mlir::AsmParser::parseColon(), mlir::OpAsmParser::parseOperand(), mlir::AsmParser::parseOptionalAttrDict(), mlir::AsmParser::parseOptionalKeyword(), mlir::AsmParser::parseType(), mlir::OpAsmParser::resolveOperand(), mlir::succeeded(), and mlir::success().
parseOptionalKeywordAlternative()
static int parseOptionalKeywordAlternative (OpAsmParser & parser, ArrayRef< StringRef > keywords) static
Definition at line 1673 of file LLVMDialect.cpp.
References mlir::detail::enumerate(), mlir::AsmParser::parseOptionalKeyword(), and mlir::succeeded().
Referenced by parseOptionalLLVMKeyword().
parseOptionalLLVMKeyword()
template<typename EnumTy , typename RetTy = EnumTy> static RetTy parseOptionalLLVMKeyword (OpAsmParser & parser, OperationState & result, EnumTy defaultValue) static
Parse an enum from the keyword, or default to the provided default value.
The return type is the enum type by default, unless overriden with the second template argument.
Definition at line 1701 of file LLVMDialect.cpp.
References parseOptionalKeywordAlternative(), and mlir::tblgen::stringify().
parseReturnOp()
static ParseResult parseReturnOp (OpAsmParser & parser, OperationState & result) static
Definition at line 1506 of file LLVMDialect.cpp.
References mlir::OperationState::attributes, mlir::failure(), mlir::OperationState::operands, mlir::AsmParser::parseColonType(), mlir::OpAsmParser::parseOperandList(), mlir::AsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::resolveOperand(), and mlir::success().
parseShuffleVectorOp()
static ParseResult parseShuffleVectorOp (OpAsmParser & parser, OperationState & result) static
Definition at line 1919 of file LLVMDialect.cpp.
References mlir::function_interface_impl::addArgAndResultAttrs(), mlir::OperationState::addAttribute(), mlir::OperationState::addRegion(), mlir::OperationState::addTypes(), mlir::NamedAttrList::append(), mlir::OperationState::attributes, mlir::Type::cast(), mlir::AsmParser::emitError(), mlir::failure(), mlir::Builder::getContext(), mlir::AsmParser::getCurrentLocation(), mlir::LLVM::getFixedVectorType(), getLinkageAttrName(), mlir::LLVM::LLVMFunctionType::getNumParams(), mlir::LLVM::LLVMFunctionType::getParamType(), mlir::Builder::getStringAttr(), mlir::SymbolTable::getSymbolAttrName(), mlir::Builder::getUnitAttr(), mlir::LLVM::getVectorElementType(), mlir::LLVM::isCompatibleVectorType(), mlir::OperationState::operands, mlir::AsmParser::parseAttribute(), mlir::AsmParser::parseColonType(), mlir::AsmParser::parseComma(), mlir::OpAsmParser::parseOperand(), mlir::AsmParser::parseOptionalAttrDict(), mlir::AsmParser::parseType(), mlir::OpAsmParser::resolveOperand(), and mlir::success().
parseStoreOp()
static ParseResult parseStoreOp (OpAsmParser & parser, OperationState & result) static
Definition at line 706 of file LLVMDialect.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::attributes, mlir::failure(), mlir::AsmParser::getBuilder(), mlir::AsmParser::getCurrentLocation(), getLoadStoreElementType(), mlir::Builder::getUnitAttr(), kVolatileAttrName, mlir::OperationState::operands, mlir::AsmParser::parseColon(), mlir::AsmParser::parseComma(), mlir::OpAsmParser::parseOperand(), mlir::AsmParser::parseOptionalAttrDict(), mlir::AsmParser::parseOptionalKeyword(), mlir::AsmParser::parseType(), mlir::OpAsmParser::resolveOperand(), mlir::succeeded(), mlir::success(), and value.
parseSwitchOpCases()
static ParseResult parseSwitchOpCases (OpAsmParser & parser, Type flagType, ElementsAttr & caseValues, SmallVectorImpl< Block *> & caseDestinations, SmallVectorImpl< SmallVector< OpAsmParser::OperandType >> & caseOperands, SmallVectorImpl< SmallVector< Type >> & caseOperandTypes) static
<cases> ::= integer : bb-id ((ssa-use-and-type-list))? (, integer : bb-id ((ssa-use-and-type-list))?)?
Definition at line 275 of file LLVMDialect.cpp.
References mlir::failure(), mlir::DenseIntElementsAttr::get(), mlir::Type::getIntOrFloatBitWidth(), mlir::OptionalParseResult::getValue(), mlir::OptionalParseResult::hasValue(), mlir::AsmParser::parseColon(), mlir::AsmParser::parseColonTypeList(), mlir::AsmParser::parseOptionalComma(), mlir::AsmParser::parseOptionalInteger(), mlir::AsmParser::parseOptionalLParen(), mlir::OpAsmParser::parseRegionArgumentList(), mlir::AsmParser::parseRParen(), mlir::OpAsmParser::parseSuccessor(), and mlir::success().
printAllocaOp()
static void printAllocaOp (OpAsmPrinter & p, AllocaOp & op) static
Definition at line 178 of file LLVMDialect.cpp.
References getElementType(), and mlir::OpAsmPrinter::printOptionalAttrDict().
printAtomicCmpXchgOp()
static void printAtomicCmpXchgOp (OpAsmPrinter & p, AtomicCmpXchgOp & op) static
Definition at line 2341 of file LLVMDialect.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict().
printAtomicRMWOp()
static void printAtomicRMWOp (OpAsmPrinter & p, AtomicRMWOp & op) static
Definition at line 2270 of file LLVMDialect.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict().
printCallOp()
static void printCallOp (OpAsmPrinter & p, CallOp & op) static
Definition at line 1057 of file LLVMDialect.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict(), mlir::AsmPrinter::printSymbolName(), and processFMFAttr().
printExtractElementOp()
static void printExtractElementOp (OpAsmPrinter & p, ExtractElementOp & op) static
Definition at line 1174 of file LLVMDialect.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict().
printExtractValueOp()
static void printExtractValueOp (OpAsmPrinter & p, ExtractValueOp & op) static
Definition at line 1221 of file LLVMDialect.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict().
printFCmpOp()
static void printFCmpOp (OpAsmPrinter & p, FCmpOp & op) static
Definition at line 100 of file LLVMDialect.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict(), and processFMFAttr().
printFenceOp()
static void printFenceOp (OpAsmPrinter & p, FenceOp & op) static
Definition at line 2427 of file LLVMDialect.cpp.
printGEPIndices()
static void printGEPIndices (OpAsmPrinter & printer, LLVM::GEPOp gepOp, OperandRange indices, DenseIntElementsAttr structIndices) static
Definition at line 508 of file LLVMDialect.cpp.
printGlobalOp()
static void printGlobalOp (OpAsmPrinter & p, GlobalOp op) static
Definition at line 1636 of file LLVMDialect.cpp.
References mlir::Region::empty(), getLinkageAttrName(), mlir::SymbolTable::getSymbolAttrName(), getUnnamedAddrAttrName(), mlir::AsmPrinter::printAttribute(), mlir::OpAsmPrinter::printOptionalAttrDict(), mlir::OpAsmPrinter::printRegion(), and mlir::AsmPrinter::printSymbolName().
printICmpOp()
static void printICmpOp (OpAsmPrinter & p, ICmpOp & op) static
Definition at line 93 of file LLVMDialect.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict().
printInsertElementOp()
static void printInsertElementOp (OpAsmPrinter & p, InsertElementOp & op) static
Definition at line 1388 of file LLVMDialect.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict().
printInsertValueOp()
static void printInsertValueOp (OpAsmPrinter & p, InsertValueOp & op) static
Definition at line 1438 of file LLVMDialect.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict().
printInvokeOp()
static void printInvokeOp (OpAsmPrinter & p, InvokeOp op) static
Definition at line 759 of file LLVMDialect.cpp.
References mlir::OpAsmPrinter::printFunctionalType(), mlir::OpAsmPrinter::printOptionalAttrDict(), mlir::OpAsmPrinter::printSuccessorAndUseList(), and mlir::AsmPrinter::printSymbolName().
printLandingpadOp()
static void printLandingpadOp (OpAsmPrinter & p, LandingpadOp & op) static
Definition at line 923 of file LLVMDialect.cpp.
References mlir::Value::getType(), mlir::Type::isa(), and mlir::OpAsmPrinter::printOptionalAttrDict().
printLLVMFuncOp()
static void printLLVMFuncOp (OpAsmPrinter & p, LLVMFuncOp op) static
Definition at line 2075 of file LLVMDialect.cpp.
References getLinkageAttrName(), mlir::LLVM::LLVMFunctionType::getNumParams(), mlir::LLVM::LLVMFunctionType::getParamType(), mlir::LLVM::LLVMFunctionType::getReturnType(), mlir::function_interface_impl::getTypeAttrName(), mlir::Type::isa(), mlir::function_interface_impl::printFunctionAttributes(), mlir::function_interface_impl::printFunctionSignature(), mlir::OpAsmPrinter::printRegion(), mlir::AsmPrinter::printSymbolName(), and mlir::success().
printLLVMOpAttrs()
static void printLLVMOpAttrs (OpAsmPrinter & printer, Operation * op, DictionaryAttr attrs) static
Definition at line 69 of file LLVMDialect.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict(), and processFMFAttr().
printLoadOp()
static void printLoadOp (OpAsmPrinter & p, LoadOp & op) static
Definition at line 633 of file LLVMDialect.cpp.
References kVolatileAttrName, and mlir::OpAsmPrinter::printOptionalAttrDict().
printReturnOp()
static void printReturnOp (OpAsmPrinter & p, ReturnOp op) static
Definition at line 1494 of file LLVMDialect.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict().
printShuffleVectorOp()
static void printShuffleVectorOp (OpAsmPrinter & p, ShuffleVectorOp & op) static
Definition at line 1910 of file LLVMDialect.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict().
printStoreOp()
static void printStoreOp (OpAsmPrinter & p, StoreOp & op) static
Definition at line 695 of file LLVMDialect.cpp.
References kVolatileAttrName, and mlir::OpAsmPrinter::printOptionalAttrDict().
printSwitchOpCases()
static void printSwitchOpCases (OpAsmPrinter & p, SwitchOp op, Type flagType, ElementsAttr caseValues, SuccessorRange caseDestinations, OperandRangeRange caseOperands, const TypeRangeRange & caseOperandTypes) static
Definition at line 313 of file LLVMDialect.cpp.
References mlir::OpAsmPrinter::printNewline().
processFMFAttr()
static auto processFMFAttr (ArrayRef< NamedAttribute > attrs) static
Definition at line 52 of file LLVMDialect.cpp.
References mlir::Attribute::getContext(), mlir::NamedAttribute::getName(), and mlir::NamedAttribute::getValue().
Referenced by printCallOp(), printFCmpOp(), and printLLVMOpAttrs().
recordStructIndices()
static void recordStructIndices (Type type, unsigned currentIndex, SmallVectorImpl< unsigned > & indices, SmallVectorImpl< unsigned > * structSizes, SmallPtrSet< Type, 4 > & visited) static
Populates indices with positions of GEP indices that would correspond to LLVMStructTypes potentially nested in the given type.
The type currently visited gets currentIndex and LLVM container types are visited recursively. The recursion is bounded and takes care of recursive types by means of the visited set.
Definition at line 370 of file LLVMDialect.cpp.
References mlir::LLVM::LLVMStructType::getBody().
Referenced by findKnownStructIndices().
verify() [1/21]
static LogicalResult verify (SwitchOp op) static
Definition at line 337 of file LLVMDialect.cpp.
References mlir::success().
verify() [2/21]
LogicalResult verify (LLVM::GEPOp gepOp)
Definition at line 521 of file LLVMDialect.cpp.
References findKnownStructIndices(), and mlir::success().
verify() [3/21]
static LogicalResult verify (LoadOp op) static
Definition at line 616 of file LLVMDialect.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::addOperands(), mlir::OperationState::addTypes(), mlir::Builder::getI64IntegerAttr(), mlir::Builder::getUnitAttr(), kNonTemporalAttrName, kVolatileAttrName, and verifyMemoryOpMetadata().
verify() [4/21]
static LogicalResult verify (StoreOp op) static
Definition at line 678 of file LLVMDialect.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::addOperands(), mlir::OperationState::addTypes(), mlir::Builder::getI64IntegerAttr(), mlir::Builder::getUnitAttr(), kNonTemporalAttrName, kVolatileAttrName, value, and verifyMemoryOpMetadata().
verify() [5/21]
static LogicalResult verify (InvokeOp op) static
Definition at line 742 of file LLVMDialect.cpp.
References mlir::Block::empty(), mlir::Block::front(), and mlir::success().
verify() [6/21]
static LogicalResult verify (LandingpadOp op) static
===-------------------------------------------------------------------—===// Verifying/Printing/Parsing for LLVM::LandingpadOp.
===-------------------------------------------------------------------—===//
Definition at line 883 of file LLVMDialect.cpp.
References mlir::Value::getDefiningOp(), mlir::Value::getType(), mlir::Type::isa(), mlir::success(), and value.
verify() [7/21]
static LogicalResult verify (CallOp & op) static
Definition at line 973 of file LLVMDialect.cpp.
References mlir::Type::dyn_cast(), mlir::Operation::emitOpError(), mlir::FlatSymbolRefAttr::getAttr(), mlir::LLVM::LLVMFunctionType::getNumParams(), mlir::LLVM::LLVMFunctionType::getParamType(), mlir::LLVM::LLVMFunctionType::getReturnType(), mlir::FlatSymbolRefAttr::getValue(), mlir::Type::isa(), mlir::LLVM::LLVMFunctionType::isVarArg(), mlir::SymbolTable::lookupNearestSymbolFrom(), and mlir::success().
verify() [8/21]
static LogicalResult verify (ExtractElementOp op) static
Definition at line 1203 of file LLVMDialect.cpp.
References mlir::LLVM::getVectorElementType(), mlir::LLVM::isCompatibleVectorType(), mlir::success(), and vectorType().
verify() [9/21]
static LogicalResult verify (ExtractValueOp op) static
Definition at line 1370 of file LLVMDialect.cpp.
References mlir::failure(), getInsertExtractValueElementType(), and mlir::success().
verify() [10/21]
static LogicalResult verify (InsertElementOp op) static
Definition at line 1426 of file LLVMDialect.cpp.
References mlir::LLVM::getVectorElementType(), and mlir::success().
verify() [11/21]
static LogicalResult verify (InsertValueOp op) static
Definition at line 1476 of file LLVMDialect.cpp.
References mlir::failure(), getInsertExtractValueElementType(), and mlir::success().
verify() [12/21]
static LogicalResult verify (ReturnOp op) static
Definition at line 1522 of file LLVMDialect.cpp.
References mlir::InFlightDiagnostic::attachNote(), diag(), mlir::Type::isa(), and mlir::success().
verify() [13/21]
static LogicalResult verify (AddressOfOp op) static
Definition at line 1575 of file LLVMDialect.cpp.
References mlir::LLVM::LLVMPointerType::get(), and mlir::success().
verify() [14/21]
static LogicalResult verify (GlobalOp op) static
Definition at line 1794 of file LLVMDialect.cpp.
References mlir::Type::dyn_cast(), mlir::failed(), mlir::failure(), mlir::LLVM::LLVMPointerType::isValidElementType(), isZeroAttribute(), mlir::LLVM::satisfiesLLVMModule(), mlir::success(), and verifySymbolAttrUse().
verify() [15/21]
static LogicalResult verify (GlobalCtorsOp op) static
Definition at line 1867 of file LLVMDialect.cpp.
References mlir::failed(), mlir::failure(), mlir::success(), and verifySymbolAttrUse().
verify() [16/21]
static LogicalResult verify (GlobalDtorsOp op) static
Definition at line 1888 of file LLVMDialect.cpp.
References mlir::OperationState::addAttributes(), mlir::LLVM::getFixedVectorType(), mlir::Value::getType(), mlir::LLVM::getVectorElementType(), and mlir::success().
verify() [17/21]
static LogicalResult verify (LLVMFuncOp op) static
Definition at line 2120 of file LLVMDialect.cpp.
References mlir::Block::front(), mlir::Block::getArgument(), mlir::Value::getType(), mlir::LLVM::isCompatibleType(), and mlir::success().
verify() [18/21]
static LogicalResult verify (LLVM::ConstantOp op) static
Definition at line 2166 of file LLVMDialect.cpp.
References mlir::success().
verify() [19/21]
static LogicalResult verify (AtomicRMWOp op) static
Definition at line 2297 of file LLVMDialect.cpp.
References mlir::LLVM::LLVMPointerType::getElementType(), mlir::LLVM::isCompatibleFloatingPointType(), and mlir::success().
verify() [20/21]
static LogicalResult verify (AtomicCmpXchgOp op) static
Definition at line 2378 of file LLVMDialect.cpp.
References mlir::success().
verify() [21/21]
static LogicalResult verify (FenceOp & op) static
Definition at line 2435 of file LLVMDialect.cpp.
References mlir::m_Zero(), mlir::matchPattern(), and mlir::success().
verifyMemoryOpMetadata()
static LogicalResult verifyMemoryOpMetadata (Operation * op) static
Definition at line 597 of file LLVMDialect.cpp.
References mlir::failed(), mlir::failure(), and mlir::success().
Referenced by verify().
verifyOpMetadata()
template<typename OpTy > static LogicalResult verifyOpMetadata (Operation * op, StringRef attributeName) static
Definition at line 583 of file LLVMDialect.cpp.
References mlir::Operation::emitOpError(), mlir::success(), and verifySymbolAttribute().
verifySymbolAttribute()
LogicalResult verifySymbolAttribute (Operation * op, StringRef attributeName, llvm::function_ref< LogicalResult(Operation *, SymbolRefAttr)> verifySymbolType)
Definition at line 547 of file LLVMDialect.cpp.
References mlir::Operation::emitOpError(), mlir::failed(), mlir::failure(), mlir::Operation::getAttr(), mlir::Operation::getParentOp(), mlir::SymbolTable::lookupNearestSymbolFrom(), and mlir::success().
Referenced by verifyOpMetadata().
verifySymbolAttrUse()
static LogicalResult verifySymbolAttrUse (FlatSymbolRefAttr symbol, Operation * op, SymbolTableCollection & symbolTable) static
Verifies symbol's use in op to ensure the symbol is a valid and fully defined llvm.func.
Definition at line 76 of file LLVMDialect.cpp.
References mlir::Operation::emitOpError(), mlir::FlatSymbolRefAttr::getAttr(), mlir::FlatSymbolRefAttr::getValue(), mlir::SymbolTableCollection::lookupNearestSymbolFrom(), and mlir::success().
Referenced by verify().
Variable Documentation
fastmathFlagsList
constexpr const FastmathFlags fastmathFlagsList[] static
Initial value:
= {
    FastmathFlags::nnan,
    FastmathFlags::ninf,
    FastmathFlags::nsz,
    FastmathFlags::arcp,
    FastmathFlags::contract,
    FastmathFlags::afn,
    FastmathFlags::reassoc,
    FastmathFlags::fast,
}
Definition at line 2662 of file LLVMDialect.cpp.
kNonTemporalAttrName
constexpr const char kNonTemporalAttrName[] = "nontemporal" static
Definition at line 45 of file LLVMDialect.cpp.
Referenced by verify().
kVolatileAttrName
constexpr const char kVolatileAttrName[] = "volatile_" static
Definition at line 44 of file LLVMDialect.cpp.
Referenced by parseLoadOp(), parseStoreOp(), printLoadOp(), printStoreOp(), and verify().