MLIR: lib/Interfaces/LoopLikeInterface.cpp File Reference
LoopLikeInterface.cpp File Reference
#include "mlir/Interfaces/LoopLikeInterface.h"
#include "mlir/Interfaces/SideEffectInterfaces.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/Support/Debug.h"
#include "mlir/Interfaces/LoopLikeInterface.cpp.inc"
Macros
#define DEBUG_TYPE "loop-like"
Functions
static bool canBeHoisted (Operation *op, function_ref< bool(Value)> definedOutside)
Include the definitions of the loop-like interfaces.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "loop-like"
Definition at line 16 of file LoopLikeInterface.cpp.
Function Documentation
canBeHoisted()
static bool canBeHoisted (Operation * op, function_ref< bool(Value)> definedOutside) static
Include the definitions of the loop-like interfaces.
Definition at line 34 of file LoopLikeInterface.cpp.
References mlir::Operation::getOperands(), mlir::Operation::getRegions(), and mlir::Operation::hasTrait().
Referenced by mlir::moveLoopInvariantCode().