MLIR: lib/Dialect/Affine/Transforms/LoopUnroll.cpp File Reference
LoopUnroll.cpp File Reference
#include "PassDetail.h"
#include "mlir/Dialect/Affine/Analysis/LoopAnalysis.h"
#include "mlir/Dialect/Affine/IR/AffineOps.h"
#include "mlir/Dialect/Affine/LoopUtils.h"
#include "mlir/Dialect/Affine/Passes.h"
#include "mlir/IR/AffineExpr.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/IR/Builders.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
Macros
#define DEBUG_TYPE "affine-loop-unroll"
Functions
static bool isInnermostAffineForOp (AffineForOp forOp)
Returns true if no other affine.for ops are nested within.
static void gatherInnermostLoops (FuncOp f, SmallVectorImpl< AffineForOp > &loops)
Gathers loops that have no affine.for's nested within.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "affine-loop-unroll"
Definition at line 26 of file LoopUnroll.cpp.
Function Documentation
gatherInnermostLoops()
static void gatherInnermostLoops (FuncOp f, SmallVectorImpl< AffineForOp > & loops) static
Gathers loops that have no affine.for's nested within.
Definition at line 77 of file LoopUnroll.cpp.
References mlir::getConstantTripCount(), isInnermostAffineForOp(), mlir::loopUnrollByFactor(), mlir::loopUnrollFull(), mlir::loopUnrollUpToFactor(), and mlir::succeeded().
isInnermostAffineForOp()
static bool isInnermostAffineForOp (AffineForOp forOp) static
Returns true if no other affine.for ops are nested within.
Definition at line 65 of file LoopUnroll.cpp.
References mlir::WalkResult::interrupt().
Referenced by gatherInnermostLoops().