MLIR: lib/Dialect/MemRef/IR/MemRefOps.cpp File Reference
MemRefOps.cpp File Reference
#include "mlir/Dialect/Arithmetic/IR/Arithmetic.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/MemRef/Utils/MemRefUtils.h"
#include "mlir/Dialect/StandardOps/IR/Ops.h"
#include "mlir/Dialect/StandardOps/Utils/Utils.h"
#include "mlir/Dialect/Utils/StaticValueUtils.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/Matchers.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/IR/TypeUtilities.h"
#include "mlir/Interfaces/InferTypeOpInterface.h"
#include "mlir/Interfaces/ViewLikeInterface.h"
#include "llvm/ADT/STLExtras.h"
#include "mlir/Dialect/MemRef/IR/MemRefOps.cpp.inc"
Classes
struct CollapseShapeOpMemRefCastFolder
struct SubViewReturnTypeCanonicalizer
Return the canonical type of the result of a subview.
struct SubViewCanonicalizer
A canonicalizer wrapper to replace SubViewOps.
Namespaces
saturated_arith
Helpers to write more idiomatic operations.
Macros
#define GET_OP_CLASSES
Functions
template<typename AllocLikeOp >
static LogicalResult verifyAllocLikeOp (AllocLikeOp op)
static LogicalResult verify (AllocOp op)
static LogicalResult verify (AllocaOp op)
static void print (OpAsmPrinter &p, AllocaScopeOp &op)
static ParseResult parseAllocaScopeOp (OpAsmParser &parser, OperationState &result)
static LogicalResult verify (AllocaScopeOp op)
static LogicalResult verify (AssumeAlignmentOp op)
static LogicalResult verify (DimOp op)
static std::map< int64_t, unsigned > getNumOccurences (ArrayRef< int64_t > vals)
Return a map with key being elements in vals and data being number of occurences of it.
static llvm::Optional< llvm::SmallDenseSet< unsigned > > computeMemRefRankReductionMask (MemRefType originalType, MemRefType reducedType, ArrayRef< OpFoldResult > sizes)
Given the originalType and a candidateReducedType whose shape is assumed to be a subset of originalType with some 1 entries erased, return the set of indices that specifies which of the entries of originalShape are dropped to obtain reducedShape.
static void print (OpAsmPrinter &p, DmaStartOp op)
static ParseResult parseDmaStartOp (OpAsmParser &parser, OperationState &result)
static LogicalResult verify (DmaStartOp op)
static LogicalResult verify (DmaWaitOp op)
static LogicalResult verify (GenericAtomicRMWOp op)
static ParseResult parseGenericAtomicRMWOp (OpAsmParser &parser, OperationState &result)
static void print (OpAsmPrinter &p, GenericAtomicRMWOp op)
static LogicalResult verify (AtomicYieldOp op)
static void printGlobalMemrefOpTypeAndInitialValue (OpAsmPrinter &p, GlobalOp op, TypeAttr type, Attribute initialValue)
static ParseResult parseGlobalMemrefOpTypeAndInitialValue (OpAsmParser &parser, TypeAttr &typeAttr, Attribute &initialValue)
static LogicalResult verify (GlobalOp op)
static LogicalResult verify (LoadOp op)
static void print (OpAsmPrinter &p, PrefetchOp op)
static ParseResult parsePrefetchOp (OpAsmParser &parser, OperationState &result)
static LogicalResult verify (PrefetchOp op)
static LogicalResult verify (ReinterpretCastOp op)
static void print (OpAsmPrinter &p, ExpandShapeOp op)
static void print (OpAsmPrinter &p, CollapseShapeOp op)
static bool isReshapableDimBand (unsigned dim, unsigned extent, ArrayRef< int64_t > sizes, ArrayRef< AffineExpr > strides)
Detect whether memref dims [dim, dim + extent) can be reshaped without copies.
static MemRefType computeReshapeCollapsedType (MemRefType type, ArrayRef< AffineMap > reassociation)
Compute the MemRefType obtained by applying the reassociation (which is expected to be valid) to type.
template<typename ReshapeOp , bool isExpansion = std::is_same<ReshapeOp, ExpandShapeOp>::value>
static LogicalResult verifyReshapeOp (ReshapeOp op, MemRefType expandedType, MemRefType collapsedType)
static LogicalResult verify (ExpandShapeOp op)
static LogicalResult verify (CollapseShapeOp op)
static LogicalResult verify (ReshapeOp op)
static LogicalResult verify (StoreOp op)
static bool haveCompatibleOffsets (MemRefType t1, MemRefType t2)
Return true if t1 and t2 have equal offsets (both dynamic or of same static value).
static SliceVerificationResult isRankReducedMemRefType (MemRefType originalType, MemRefType candidateRankReducedType, ArrayRef< OpFoldResult > sizes)
Checks if original Type type can be rank reduced to reduced type.
template<typename OpTy >
static LogicalResult produceSubViewErrorMsg (SliceVerificationResult result, OpTy op, Type expectedType)
static LogicalResult verify (SubViewOp op)
Verifier for SubViewOp.
static MemRefType getCanonicalSubViewResultType (MemRefType currentResultType, MemRefType currentSourceType, MemRefType sourceType, ArrayRef< OpFoldResult > mixedOffsets, ArrayRef< OpFoldResult > mixedSizes, ArrayRef< OpFoldResult > mixedStrides)
Compute the canonical result type of a SubViewOp.
static MemRefType getCanonicalSubViewResultType (MemRefType currentResultType, MemRefType sourceType, ArrayRef< OpFoldResult > mixedOffsets, ArrayRef< OpFoldResult > mixedSizes, ArrayRef< OpFoldResult > mixedStrides)
Compute the canonical result type of a SubViewOp.
static bool isTrivialSubViewOp (SubViewOp subViewOp)
Helper method to check if a subview operation is trivially a no-op.
static MemRefType inferTransposeResultType (MemRefType memRefType, AffineMap permutationMap)
Build a strided memref type by applying permutationMap tp memRefType.
static void print (OpAsmPrinter &p, TransposeOp op)
static ParseResult parseTransposeOp (OpAsmParser &parser, OperationState &result)
static LogicalResult verify (TransposeOp op)
static ParseResult parseViewOp (OpAsmParser &parser, OperationState &result)
static void print (OpAsmPrinter &p, ViewOp op)
static LogicalResult verify (ViewOp op)
static LogicalResult verify (AtomicRMWOp op)
Macro Definition Documentation
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 2499 of file MemRefOps.cpp.
Function Documentation
computeMemRefRankReductionMask()
static llvm::Optional<llvm::SmallDenseSet<unsigned> > computeMemRefRankReductionMask (MemRefType originalType, MemRefType reducedType, ArrayRef< OpFoldResult > sizes) static
Given the originalType and a candidateReducedType whose shape is assumed to be a subset of originalType with some 1 entries erased, return the set of indices that specifies which of the entries of originalShape are dropped to obtain reducedShape.
This accounts for cases where there are multiple unit-dims, but only a subset of those are dropped. For MemRefTypes these can be disambiguated using the strides. If a dimension is dropped the stride must be dropped too.
Definition at line 582 of file MemRefOps.cpp.
References mlir::RewritePatternSet::add(), mlir::OperationState::addOperands(), mlir::OpBuilder::create(), mlir::Type::dyn_cast(), mlir::detail::enumerate(), mlir::failed(), mlir::failure(), mlir::memref::foldMemRefCast(), mlir::Value::getDefiningOp(), mlir::Builder::getIndexAttr(), mlir::getMixedSizes(), getNumOccurences(), mlir::getStridesAndOffset(), mlir::Value::getType(), mlir::RewriterBase::replaceOp(), resultIndex(), mlir::OpBuilder::setInsertionPointAfter(), mlir::succeeded(), and mlir::success().
Referenced by getCanonicalSubViewResultType(), and isRankReducedMemRefType().
computeReshapeCollapsedType()
static MemRefType computeReshapeCollapsedType (MemRefType type, ArrayRef< AffineMap > reassociation) static
Compute the MemRefType obtained by applying the reassociation (which is expected to be valid) to type.
If type is Contiguous MemRefType, this always produce a contiguous MemRefType.
Definition at line 1414 of file MemRefOps.cpp.
References mlir::OperationState::addAttribute(), mlir::canonicalizeStridedLayout(), mlir::Type::cast(), mlir::convertReassociationIndicesToExprs(), mlir::AffineExpr::dyn_cast(), mlir::Value::dyn_cast_or_null(), mlir::Builder::getContext(), mlir::getReassociationAttrName(), mlir::getReassociationIndicesAttribute(), mlir::getStridesAndOffset(), mlir::getSymbolLessAffineMaps(), mlir::Value::getType(), mlir::isReassociationValid(), isReshapableDimBand(), mlir::makeStridedLinearLayoutMap(), mlir::MemRefType::Builder::setLayout(), mlir::MemRefType::Builder::setShape(), mlir::succeeded(), and value.
Referenced by CollapseShapeOpMemRefCastFolder::matchAndRewrite(), and verifyReshapeOp().
getCanonicalSubViewResultType() [1/2]
static MemRefType getCanonicalSubViewResultType (MemRefType currentResultType, MemRefType currentSourceType, MemRefType sourceType, ArrayRef< OpFoldResult > mixedOffsets, ArrayRef< OpFoldResult > mixedSizes, ArrayRef< OpFoldResult > mixedStrides) static
Compute the canonical result type of a SubViewOp.
Call inferResultType to deduce the result type for the given sourceType. Additionally, reduce the rank of the inferred result type if currentResultType is lower rank than currentSourceType. Use this signature if sourceType is updated together with the result type. In this case, it is important to compute the dropped dimensions using currentSourceType whose strides align with currentResultType.
Definition at line 2005 of file MemRefOps.cpp.
References computeMemRefRankReductionMask(), mlir::detail::enumerate(), mlir::getProjectedMap(), and mlir::AffineMap::isIdentity().
Referenced by getCanonicalSubViewResultType(), isTrivialSubViewOp(), and SubViewReturnTypeCanonicalizer::operator()().
getCanonicalSubViewResultType() [2/2]
static MemRefType getCanonicalSubViewResultType (MemRefType currentResultType, MemRefType sourceType, ArrayRef< OpFoldResult > mixedOffsets, ArrayRef< OpFoldResult > mixedSizes, ArrayRef< OpFoldResult > mixedStrides) static
Compute the canonical result type of a SubViewOp.
Call inferResultType to deduce the result type. Additionally, reduce the rank of the inferred result type if currentResultType is lower rank than sourceType.
Definition at line 2034 of file MemRefOps.cpp.
References getCanonicalSubViewResultType().
getNumOccurences()
static std::map<int64_t, unsigned> getNumOccurences (ArrayRef< int64_t > vals) static
Return a map with key being elements in vals and data being number of occurences of it.
Use std::map, since the vals here are strides and the dynamic stride value is the same as the tombstone value for DenseMap<int64_t>.
Definition at line 567 of file MemRefOps.cpp.
Referenced by computeMemRefRankReductionMask().
haveCompatibleOffsets()
static bool haveCompatibleOffsets (MemRefType t1, MemRefType t2) static
Return true if t1 and t2 have equal offsets (both dynamic or of same static value).
Definition at line 1874 of file MemRefOps.cpp.
References mlir::getStridesAndOffset(), and mlir::succeeded().
Referenced by isRankReducedMemRefType().
inferTransposeResultType()
static MemRefType inferTransposeResultType (MemRefType memRefType, AffineMap permutationMap) static
Build a strided memref type by applying permutationMap tp memRefType.
Definition at line 2202 of file MemRefOps.cpp.
References mlir::detail::enumerate(), and mlir::AffineMap::getResults().
Referenced by verify().
isRankReducedMemRefType()
static SliceVerificationResult isRankReducedMemRefType (MemRefType originalType, MemRefType candidateRankReducedType, ArrayRef< OpFoldResult > sizes) static
Checks if original Type type can be rank reduced to reduced type.
This function is slight variant of is subsequence algorithm where not matching dimension must be 1.
Definition at line 1886 of file MemRefOps.cpp.
References computeMemRefRankReductionMask(), haveCompatibleOffsets(), mlir::isRankReducedType(), mlir::LayoutMismatch, mlir::MemSpaceMismatch, and mlir::Success.
Referenced by verify().
isReshapableDimBand()
static bool isReshapableDimBand (unsigned dim, unsigned extent, ArrayRef< int64_t > sizes, ArrayRef< AffineExpr > strides) static
Detect whether memref dims [dim, dim + extent) can be reshaped without copies.
Definition at line 1382 of file MemRefOps.cpp.
Referenced by computeReshapeCollapsedType().
isTrivialSubViewOp()
static bool isTrivialSubViewOp (SubViewOp subViewOp) static
Helper method to check if a subview operation is trivially a no-op.
This is the case if the all offsets are zero, all strides are 1, and the source shape is same as the size of the subview. In such cases, the subview can be folded into its source.
Definition at line 2047 of file MemRefOps.cpp.
References mlir::tensor::canFoldIntoConsumerOp(), mlir::OpBuilder::create(), mlir::detail::enumerate(), mlir::failure(), getCanonicalSubViewResultType(), mlir::getConstantIntValue(), mlir::matchConstantIndex(), mlir::matchPattern(), mlir::RewriterBase::replaceOp(), mlir::RewriterBase::replaceOpWithNewOp(), and mlir::success().
parseAllocaScopeOp()
static ParseResult parseAllocaScopeOp (OpAsmParser & parser, OperationState & result) static
Definition at line 226 of file MemRefOps.cpp.
References mlir::OperationState::addRegion(), mlir::OperationState::attributes, mlir::failure(), mlir::AsmParser::getBuilder(), mlir::OperationState::location, mlir::AsmParser::parseOptionalArrowTypeList(), mlir::AsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::parseRegion(), mlir::OperationState::regions, mlir::success(), and mlir::OperationState::types.
parseDmaStartOp()
static ParseResult parseDmaStartOp (OpAsmParser & parser, OperationState & result) static
Definition at line 793 of file MemRefOps.cpp.
References mlir::AsmParser::emitError(), mlir::failure(), mlir::AsmParser::getBuilder(), mlir::Builder::getIndexType(), mlir::AsmParser::getNameLoc(), mlir::isStrided(), mlir::OperationState::operands, mlir::AsmParser::parseColonTypeList(), mlir::AsmParser::parseComma(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOperandList(), mlir::OpAsmParser::parseTrailingOperandList(), mlir::OpAsmParser::resolveOperand(), mlir::OpAsmParser::resolveOperands(), mlir::AsmParser::Square, and mlir::success().
parseGenericAtomicRMWOp()
static ParseResult parseGenericAtomicRMWOp (OpAsmParser & parser, OperationState & result) static
Definition at line 989 of file MemRefOps.cpp.
References mlir::OperationState::addRegion(), mlir::OperationState::attributes, mlir::Type::cast(), mlir::failure(), mlir::AsmParser::getBuilder(), mlir::Builder::getIndexType(), mlir::OperationState::operands, mlir::AsmParser::parseColonType(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOperandList(), mlir::AsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::parseRegion(), mlir::OpAsmParser::resolveOperand(), mlir::OpAsmParser::resolveOperands(), mlir::AsmParser::Square, mlir::success(), and mlir::OperationState::types.
parseGlobalMemrefOpTypeAndInitialValue()
static ParseResult parseGlobalMemrefOpTypeAndInitialValue (OpAsmParser & parser, TypeAttr & typeAttr, Attribute & initialValue) static
Definition at line 1049 of file MemRefOps.cpp.
References mlir::Type::dyn_cast(), mlir::AsmParser::emitError(), mlir::failure(), mlir::AsmParser::getContext(), mlir::AsmParser::getNameLoc(), mlir::memref::getTensorTypeFromMemRefType(), mlir::Attribute::isa(), mlir::AsmParser::parseAttribute(), mlir::AsmParser::parseOptionalEqual(), mlir::AsmParser::parseOptionalKeyword(), mlir::AsmParser::parseType(), mlir::succeeded(), and mlir::success().
parsePrefetchOp()
static ParseResult parsePrefetchOp (OpAsmParser & parser, OperationState & result) static
Definition at line 1171 of file MemRefOps.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::attributes, mlir::AsmParser::emitError(), mlir::failure(), mlir::Builder::getBoolAttr(), mlir::AsmParser::getBuilder(), mlir::Builder::getIndexType(), mlir::Builder::getIntegerType(), mlir::AsmParser::getNameLoc(), mlir::OperationState::operands, mlir::AsmParser::parseAttribute(), mlir::AsmParser::parseColonType(), mlir::AsmParser::parseComma(), mlir::AsmParser::parseGreater(), mlir::AsmParser::parseKeyword(), mlir::AsmParser::parseLess(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOperandList(), mlir::OpAsmParser::resolveOperand(), mlir::OpAsmParser::resolveOperands(), mlir::AsmParser::Square, and mlir::success().
parseTransposeOp()
static ParseResult parseTransposeOp (OpAsmParser & parser, OperationState & result) static
Definition at line 2248 of file MemRefOps.cpp.
References mlir::OperationState::addAttribute(), mlir::AsmParser::addTypeToList(), mlir::OperationState::attributes, mlir::failure(), mlir::OperationState::operands, mlir::AsmParser::parseAffineMap(), mlir::AsmParser::parseColonType(), mlir::AsmParser::parseKeywordType(), mlir::OpAsmParser::parseOperand(), mlir::AsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::resolveOperand(), mlir::success(), and mlir::OperationState::types.
parseViewOp()
static ParseResult parseViewOp (OpAsmParser & parser, OperationState & result) static
Definition at line 2293 of file MemRefOps.cpp.
References mlir::AsmParser::addTypeToList(), mlir::OperationState::attributes, mlir::AsmParser::emitError(), mlir::failure(), mlir::AsmParser::getBuilder(), mlir::AsmParser::getCurrentLocation(), mlir::Builder::getIndexType(), mlir::OperationState::operands, mlir::AsmParser::parseColonType(), mlir::AsmParser::parseKeywordType(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOperandList(), mlir::AsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::resolveOperand(), mlir::OpAsmParser::resolveOperands(), mlir::AsmParser::Square, and mlir::OperationState::types.
print() [1/8]
static void print (OpAsmPrinter & p, AllocaScopeOp & op) static
Definition at line 211 of file MemRefOps.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict(), and mlir::OpAsmPrinter::printRegion().
print() [2/8]
static void print (OpAsmPrinter & p, DmaStartOp op) static
Definition at line 772 of file MemRefOps.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict().
print() [3/8]
static void print (OpAsmPrinter & p, GenericAtomicRMWOp op) static
Definition at line 1011 of file MemRefOps.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict(), and mlir::OpAsmPrinter::printRegion().
print() [4/8]
static void print (OpAsmPrinter & p, PrefetchOp op) static
Definition at line 1159 of file MemRefOps.cpp.
References mlir::OpAsmPrinter::printOperands(), and mlir::OpAsmPrinter::printOptionalAttrDict().
print() [5/8]
static void print (OpAsmPrinter & p, ExpandShapeOp op) static
Definition at line 1372 of file MemRefOps.cpp.
print() [6/8]
static void print (OpAsmPrinter & p, CollapseShapeOp op) static
Definition at line 1376 of file MemRefOps.cpp.
print() [7/8]
static void print (OpAsmPrinter & p, TransposeOp op) static
Definition at line 2241 of file MemRefOps.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict().
print() [8/8]
static void print (OpAsmPrinter & p, ViewOp op) static
Definition at line 2318 of file MemRefOps.cpp.
References mlir::OpAsmPrinter::printOperand(), and mlir::OpAsmPrinter::printOptionalAttrDict().
printGlobalMemrefOpTypeAndInitialValue()
static void printGlobalMemrefOpTypeAndInitialValue (OpAsmPrinter & p, GlobalOp op, TypeAttr type, Attribute initialValue) static
Definition at line 1035 of file MemRefOps.cpp.
References mlir::AsmPrinter::printAttributeWithoutType().
produceSubViewErrorMsg()
template<typename OpTy > static LogicalResult produceSubViewErrorMsg (SliceVerificationResult result, OpTy op, Type expectedType) static
Definition at line 1912 of file MemRefOps.cpp.
References mlir::Type::cast(), mlir::ElemTypeMismatch, mlir::LayoutMismatch, mlir::MemSpaceMismatch, mlir::RankTooLarge, mlir::SizeMismatch, mlir::success(), and mlir::Success.
Referenced by verify().
verify() [1/21]
static LogicalResult verify (AllocOp op) static
Definition at line 98 of file MemRefOps.cpp.
References verifyAllocLikeOp().
verify() [2/21]
static LogicalResult verify (AllocaOp op) static
Definition at line 100 of file MemRefOps.cpp.
References mlir::RewritePatternSet::add(), mlir::OpBuilder::create(), mlir::RewriterBase::eraseOp(), mlir::failure(), mlir::matchConstantIndex(), mlir::matchPattern(), mlir::RewriterBase::replaceOp(), mlir::MemRefType::Builder::setShape(), mlir::success(), and verifyAllocLikeOp().
verify() [3/21]
static LogicalResult verify (AllocaScopeOp op) static
Definition at line 249 of file MemRefOps.cpp.
References mlir::failed(), mlir::failure(), and mlir::success().
verify() [4/21]
static LogicalResult verify (AssumeAlignmentOp op) static
Definition at line 271 of file MemRefOps.cpp.
References mlir::RewritePatternSet::add(), mlir::tensor::canFoldIntoConsumerOp(), mlir::OpBuilder::create(), mlir::Type::dyn_cast(), mlir::detail::enumerate(), mlir::RewriterBase::eraseOp(), mlir::failed(), mlir::failure(), mlir::memref::foldMemRefCast(), mlir::Builder::getIndexType(), mlir::getStridesAndOffset(), mlir::OperationState::location, mlir::succeeded(), mlir::success(), and mlir::RewriterBase::updateRootInPlace().
verify() [5/21]
static LogicalResult verify (DimOp op) static
Definition at line 544 of file MemRefOps.cpp.
References mlir::Type::dyn_cast(), mlir::Type::isa(), and mlir::success().
verify() [6/21]
static LogicalResult verify (DmaStartOp op) static
Definition at line 854 of file MemRefOps.cpp.
References mlir::memref::foldMemRefCast(), and mlir::success().
verify() [7/21]
static LogicalResult verify (DmaWaitOp op) static
Definition at line 937 of file MemRefOps.cpp.
References mlir::Region::addArgument(), mlir::OperationState::addOperands(), mlir::OperationState::addRegion(), mlir::OperationState::addTypes(), mlir::Type::dyn_cast(), mlir::Value::getLoc(), mlir::Value::getType(), mlir::Region::push_back(), and mlir::success().
verify() [8/21]
static LogicalResult verify (GenericAtomicRMWOp op) static
Definition at line 967 of file MemRefOps.cpp.
References mlir::WalkResult::advance(), mlir::Operation::emitError(), mlir::failure(), hasSideEffects(), mlir::WalkResult::interrupt(), and mlir::success().
verify() [9/21]
static LogicalResult verify (AtomicYieldOp op) static
Definition at line 1022 of file MemRefOps.cpp.
References mlir::success().
verify() [10/21]
static LogicalResult verify (GlobalOp op) static
Definition at line 1078 of file MemRefOps.cpp.
References mlir::memref::getTensorTypeFromMemRefType(), mlir::Attribute::getType(), mlir::Attribute::isa(), mlir::SymbolTableCollection::lookupNearestSymbolFrom(), and mlir::success().
verify() [11/21]
static LogicalResult verify (LoadOp op) static
Definition at line 1142 of file MemRefOps.cpp.
References mlir::memref::foldMemRefCast(), mlir::succeeded(), and mlir::success().
verify() [12/21]
static LogicalResult verify (PrefetchOp op) static
Definition at line 1212 of file MemRefOps.cpp.
References mlir::OperationState::addAttributes(), mlir::dispatchIndexOpFoldResults(), mlir::Type::dyn_cast(), mlir::memref::foldMemRefCast(), mlir::Builder::getI64ArrayAttr(), mlir::Builder::getI64IntegerAttr(), and mlir::success().
verify() [13/21]
static LogicalResult verify (ReinterpretCastOp op) static
Definition at line 1294 of file MemRefOps.cpp.
References mlir::Type::cast(), mlir::convertReassociationIndicesToExprs(), mlir::detail::enumerate(), mlir::extractFromI64ArrayAttr(), mlir::failed(), mlir::BaseMemRefType::getMemorySpace(), mlir::getStridesAndOffset(), mlir::getSymbolLessAffineMaps(), and mlir::success().
verify() [14/21]
static LogicalResult verify (ExpandShapeOp op) static
Definition at line 1520 of file MemRefOps.cpp.
References mlir::RewritePatternSet::add(), and verifyReshapeOp().
verify() [15/21]
static LogicalResult verify (CollapseShapeOp op) static
Definition at line 1530 of file MemRefOps.cpp.
References verifyReshapeOp().
verify() [16/21]
static LogicalResult verify (ReshapeOp op) static
Definition at line 1581 of file MemRefOps.cpp.
References mlir::Type::cast(), mlir::Type::dyn_cast(), getElementType(), and mlir::success().
verify() [17/21]
static LogicalResult verify (StoreOp op) static
Definition at line 1616 of file MemRefOps.cpp.
References mlir::memref::foldMemRefCast(), and mlir::success().
verify() [18/21]
static LogicalResult verify (SubViewOp op) static
Verifier for SubViewOp.
Definition at line 1939 of file MemRefOps.cpp.
References mlir::extractFromI64ArrayAttr(), isRankReducedMemRefType(), mlir::isStrided(), and produceSubViewErrorMsg().
verify() [19/21]
static LogicalResult verify (TransposeOp op) static
Definition at line 2266 of file MemRefOps.cpp.
References mlir::memref::foldMemRefCast(), inferTransposeResultType(), mlir::succeeded(), and mlir::success().
verify() [20/21]
static LogicalResult verify (ViewOp op) static
Definition at line 2326 of file MemRefOps.cpp.
References mlir::RewritePatternSet::add(), mlir::OpBuilder::create(), mlir::failed(), mlir::failure(), mlir::Value::getDefiningOp(), mlir::getStridesAndOffset(), mlir::matchConstantIndex(), mlir::matchPattern(), mlir::RewriterBase::replaceOpWithNewOp(), mlir::MemRefType::Builder::setShape(), and mlir::success().
verify() [21/21]
static LogicalResult verify (AtomicRMWOp op) static
Definition at line 2455 of file MemRefOps.cpp.
References mlir::memref::foldMemRefCast(), mlir::succeeded(), mlir::success(), and value.
verifyAllocLikeOp()
template<typename AllocLikeOp > static LogicalResult verifyAllocLikeOp (AllocLikeOp op) static
Definition at line 75 of file MemRefOps.cpp.
References mlir::success(), and value.
Referenced by verify().
verifyReshapeOp()
template<typename ReshapeOp , bool isExpansion = std::is_same<ReshapeOp, ExpandShapeOp>::value> static LogicalResult verifyReshapeOp (ReshapeOp op, MemRefType expandedType, MemRefType collapsedType) static
Definition at line 1507 of file MemRefOps.cpp.
References computeReshapeCollapsedType(), mlir::failed(), mlir::failure(), mlir::success(), and mlir::verifyReshapeLikeTypes().
Referenced by verify().