MLIR: lib/Dialect/Linalg/ComprehensiveBufferize/ModuleBufferization.cpp File Reference
ModuleBufferization.cpp File Reference
#include "mlir/Dialect/Linalg/ComprehensiveBufferize/ModuleBufferization.h"
#include "mlir/Dialect/Bufferization/IR/BufferizableOpInterface.h"
#include "mlir/Dialect/Bufferization/IR/Bufferization.h"
#include "mlir/Dialect/Bufferization/Transforms/Bufferize.h"
#include "mlir/Dialect/Bufferization/Transforms/OneShotAnalysis.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/StandardOps/IR/Ops.h"
#include "mlir/IR/Operation.h"
Classes
struct mlir::linalg::comprehensive_bufferize::std_ext::CallOpInterface
struct mlir::linalg::comprehensive_bufferize::std_ext::ReturnOpInterface
struct mlir::linalg::comprehensive_bufferize::std_ext::FuncOpInterface
Namespaces
mlir
Include the generated interface declarations.
mlir::linalg
mlir::linalg::comprehensive_bufferize
mlir::linalg::comprehensive_bufferize::std_ext
Enumerations
enum FuncOpAnalysisState
The state of analysis of a FuncOp.
Functions
static const ModuleBufferizationState & getModuleBufferizationState (const BufferizationState &state)
Get ModuleBufferizationState.
static ModuleBufferizationState & getModuleBufferizationState (BufferizationState &state)
Get or create ModuleBufferizationState.
static FuncOpAnalysisState getFuncOpAnalysisState (const BufferizationState &state, FuncOp funcOp)
Return the state (phase) of analysis of the FuncOp.
static ReturnOp getAssumedUniqueReturnOp (FuncOp funcOp)
Return the unique ReturnOp that terminates funcOp.
static bool isaTensor (Type t)
static Value getNonCastedValue (Value value)
If value is a memref::CastOp, return its source.
static void removeBufferizationFuncArguments (BlockArgument bbArg)
Remove the attribute that triggers inplace bufferization on a FuncOp argument bbArg.
static FuncOp getCalledFunction (CallOpInterface callOp)
Return the FuncOp called by callOp.
static FunctionType getBufferizedFunctionType (MLIRContext *ctx, TypeRange argumentTypes, TypeRange resultTypes, const BufferizationOptions &options)
Return the FunctionType with argumentTypes and resultTypes where each tensor is replaced by the corresponding buffer type.
static void equivalenceAnalysis (FuncOp funcOp, BufferizationAliasInfo &aliasInfo, ModuleBufferizationState &moduleState)
Gather equivalence info of CallOps.
static LogicalResult bufferizeFuncOpBoundary (FuncOp funcOp, RewriterBase &rewriter, BufferizationState &state)
Rewrite the funcOp arguments analysis return values and terminator into buffer form (using the canonical memref layout for now), according to the inPlace-bufferizable information of the function arguments.
static LogicalResult getFuncOpsOrderedByCalls (ModuleOp moduleOp, SmallVectorImpl< FuncOp > &orderedFuncOps, DenseMap< FuncOp, DenseSet< Operation *>> &callerMap)
Store all functions of the moduleOp in orderedFuncOps, sorted by callee-caller order (i.e.
static void foreachCaller (const DenseMap< FuncOp, DenseSet< Operation *>> &callerMap, FuncOp callee, llvm::function_ref< void(Operation *)> doit)
static void layoutPostProcessing (ModuleOp moduleOp)
Postprocess the linalg.buffer_layout annotation across function boundaries.
static Optional< int64_t > mlir::linalg::comprehensive_bufferize::std_ext::getEquivalentFuncArgIdx (FuncOp funcOp, const ModuleBufferizationState &state, int64_t returnValIdx)
Return the index of the bbArg in the given FuncOp that is equivalent to the specified return value (if any).
static void setInPlaceFuncArgument (BlockArgument bbArg, bool inPlace)
Set the attribute that triggers inplace bufferization on a FuncOp argument bbArg.
static void annotateOpsWithBufferizationMarkers (FuncOp funcOp, const BufferizationState &state)
Annotate the IR with the result of the analysis. For testing/debugging only.
Enumeration Type Documentation
FuncOpAnalysisState
enum FuncOpAnalysisState strong
The state of analysis of a FuncOp.
Definition at line 90 of file ModuleBufferization.cpp.
Function Documentation
annotateOpsWithBufferizationMarkers()
static void annotateOpsWithBufferizationMarkers (FuncOp funcOp, const BufferizationState & state) static
Annotate the IR with the result of the analysis. For testing/debugging only.
Definition at line 966 of file ModuleBufferization.cpp.
References mlir::bufferization::analyzeOp(), bufferizeFuncOpBoundary(), mlir::bufferization::bufferizeOp(), equivalenceAnalysis(), mlir::failed(), mlir::failure(), getFuncOpsOrderedByCalls(), getModuleBufferizationState(), layoutPostProcessing(), options, removeBufferizationFuncArguments(), mlir::linalg::comprehensive_bufferize::runComprehensiveBufferize(), setInPlaceFuncArgument(), and mlir::success().
bufferizeFuncOpBoundary()
static LogicalResult bufferizeFuncOpBoundary (FuncOp funcOp, RewriterBase & rewriter, BufferizationState & state) static
Rewrite the funcOp arguments analysis return values and terminator into buffer form (using the canonical memref layout for now), according to the inPlace-bufferizable information of the function arguments.
This relies on a buffer equivalence analysis of each return operand. When a result buffer is equivalent to a BlockArgument of funcOp, it can be dropped from the return values and becomes inplaceable at all callers. This assumes all CallOp perform the necessary work to clone operands so as to make them inplaceable. Reliance on this logic will need to be relaxed in the future.
Note: Returning a memref currently fails bufferization. If such memrefs originate from an op with an Alloc effect, they could be hoisted in the future.
Definition at line 367 of file ModuleBufferization.cpp.
References mlir::Block::addArgument(), mlir::Type::dyn_cast(), mlir::Block::eraseArgument(), mlir::Block::front(), mlir::Block::getArgument(), mlir::Block::getArguments(), getAssumedUniqueReturnOp(), mlir::bufferization::BufferizationState::getBuffer(), getBufferizedFunctionType(), getModuleBufferizationState(), getNonCastedValue(), mlir::Block::getNumArguments(), mlir::bufferization::BufferizationState::getOptions(), mlir::Value::getType(), mlir::Type::isa(), isaTensor(), mlir::Value::replaceAllUsesWith(), mlir::OpBuilder::setInsertionPointToStart(), and mlir::success().
Referenced by annotateOpsWithBufferizationMarkers().
equivalenceAnalysis()
static void equivalenceAnalysis (FuncOp funcOp, BufferizationAliasInfo & aliasInfo, ModuleBufferizationState & moduleState) static
Gather equivalence info of CallOps.
Note: This only adds new equivalence info if funcOp was already analyzed.
Definition at line 330 of file ModuleBufferization.cpp.
References mlir::WalkResult::advance(), getCalledFunction(), mlir::WalkResult::skip(), and mlir::bufferization::BufferizationAliasInfo::unionEquivalenceClasses().
Referenced by annotateOpsWithBufferizationMarkers().
foreachCaller()
static void foreachCaller (const DenseMap< FuncOp, DenseSet< Operation *>> & callerMap, FuncOp callee, llvm::function_ref< void(Operation *)> doit) static
Definition at line 553 of file ModuleBufferization.cpp.
getAssumedUniqueReturnOp()
static ReturnOp getAssumedUniqueReturnOp (FuncOp funcOp) static
Return the unique ReturnOp that terminates funcOp.
Return nullptr if there is no such unique ReturnOp.
Definition at line 149 of file ModuleBufferization.cpp.
References mlir::bufferization::BufferizationAliasInfo::applyOnAliases(), mlir::bufferization::BufferizationAliasInfo::areEquivalentBufferizedValues(), mlir::bufferization::BufferizationState::bufferizesToMemoryWrite(), mlir::Attribute::cast(), mlir::Value::dyn_cast(), mlir::IROperand< DerivedT, IRValueT >::get(), mlir::BlockArgument::getArgNumber(), mlir::Operation::getAttr(), mlir::Operation::getContext(), mlir::Value::getDefiningOp(), getFuncOpAnalysisState(), getModuleBufferizationState(), mlir::Operation::getNumOperands(), mlir::OpOperand::getOperandNumber(), mlir::bufferization::BufferizationState::getOptions(), mlir::detail::IROperandBase::getOwner(), mlir::Operation::getParentOfType(), mlir::Operation::getParentOp(), mlir::Value::getType(), mlir::Value::getUses(), mlir::Operation::hasAttr(), mlir::Type::isa(), mlir::bufferization::BufferizationState::isInPlace(), mlir::bufferization::BufferizationState::isValueRead(), mlir::Operation::setAttr(), mlir::success(), mlir::bufferization::BufferizationOptions::testAnalysisOnly, and value.
Referenced by bufferizeFuncOpBoundary().
getBufferizedFunctionType()
static FunctionType getBufferizedFunctionType (MLIRContext * ctx, TypeRange argumentTypes, TypeRange resultTypes, const BufferizationOptions & options) static
Return the FunctionType with argumentTypes and resultTypes where each tensor is replaced by the corresponding buffer type.
In order for all the callers to agree, this must bufferize to the most dynamic buffer type supported. A later pass across all CallOps in the module can decide whether to simplify the types of to version according to some cost model.
Definition at line 312 of file ModuleBufferization.cpp.
References mlir::bufferization::getMemRefType(), and rewrite().
Referenced by mlir::linalg::comprehensive_bufferize::std_ext::CallOpInterface::bufferize(), and bufferizeFuncOpBoundary().
getCalledFunction()
static FuncOp getCalledFunction (CallOpInterface callOp) static
Return the FuncOp called by callOp.
Definition at line 297 of file ModuleBufferization.cpp.
References mlir::SymbolTable::lookupNearestSymbolFrom().
Referenced by mlir::linalg::comprehensive_bufferize::std_ext::CallOpInterface::bufferize(), mlir::linalg::comprehensive_bufferize::std_ext::CallOpInterface::bufferizesToMemoryRead(), mlir::linalg::comprehensive_bufferize::std_ext::CallOpInterface::bufferizesToMemoryWrite(), equivalenceAnalysis(), mlir::linalg::comprehensive_bufferize::std_ext::CallOpInterface::getAliasingOpOperand(), and mlir::linalg::comprehensive_bufferize::std_ext::CallOpInterface::getAliasingOpResult().
getFuncOpAnalysisState()
static FuncOpAnalysisState getFuncOpAnalysisState (const BufferizationState & state, FuncOp funcOp) static
Return the state (phase) of analysis of the FuncOp.
Definition at line 138 of file ModuleBufferization.cpp.
References getModuleBufferizationState().
Referenced by mlir::linalg::comprehensive_bufferize::std_ext::CallOpInterface::bufferizesToMemoryRead(), mlir::linalg::comprehensive_bufferize::std_ext::CallOpInterface::bufferizesToMemoryWrite(), and getAssumedUniqueReturnOp().
getFuncOpsOrderedByCalls()
static LogicalResult getFuncOpsOrderedByCalls (ModuleOp moduleOp, SmallVectorImpl< FuncOp > & orderedFuncOps, DenseMap< FuncOp, DenseSet< Operation *>> & callerMap) static
Store all functions of the moduleOp in orderedFuncOps, sorted by callee-caller order (i.e.
callees without callers first). Store the map of FuncOp to all its callers in callerMap. Return failure() if a cycle of calls is detected or if we are unable to retrieve the called FuncOp from any CallOpInterface.
Definition at line 501 of file ModuleBufferization.cpp.
Referenced by annotateOpsWithBufferizationMarkers().
getModuleBufferizationState() [1/2]
static const ModuleBufferizationState& getModuleBufferizationState (const BufferizationState & state) static
Get ModuleBufferizationState.
Definition at line 121 of file ModuleBufferization.cpp.
References mlir::bufferization::BufferizationState::getDialectState().
Referenced by annotateOpsWithBufferizationMarkers(), mlir::linalg::comprehensive_bufferize::std_ext::CallOpInterface::bufferize(), bufferizeFuncOpBoundary(), mlir::linalg::comprehensive_bufferize::std_ext::CallOpInterface::bufferizesToMemoryRead(), mlir::linalg::comprehensive_bufferize::std_ext::CallOpInterface::bufferizesToMemoryWrite(), mlir::linalg::comprehensive_bufferize::std_ext::CallOpInterface::getAliasingOpOperand(), mlir::linalg::comprehensive_bufferize::std_ext::CallOpInterface::getAliasingOpResult(), getAssumedUniqueReturnOp(), and getFuncOpAnalysisState().
getModuleBufferizationState() [2/2]
static ModuleBufferizationState& getModuleBufferizationState (BufferizationState & state) static
Get or create ModuleBufferizationState.
Definition at line 131 of file ModuleBufferization.cpp.
References mlir::bufferization::BufferizationState::getOrCreateDialectState().
getNonCastedValue()
static Value getNonCastedValue (Value value) static
If value is a memref::CastOp, return its source.
Otherwise, return value directly.
Definition at line 280 of file ModuleBufferization.cpp.
References mlir::Value::getDefiningOp(), and value.
Referenced by bufferizeFuncOpBoundary().
isaTensor()
static bool isaTensor (Type t) static
Definition at line 276 of file ModuleBufferization.cpp.
References mlir::Type::isa().
Referenced by mlir::linalg::comprehensive_bufferize::std_ext::CallOpInterface::bufferize(), and bufferizeFuncOpBoundary().
layoutPostProcessing()
static void layoutPostProcessing (ModuleOp moduleOp) static
Postprocess the linalg.buffer_layout annotation across function boundaries.
This is a purely mechanical process that may later become part of a separate pass with its own layout assignment heuristic.
Definition at line 565 of file ModuleBufferization.cpp.
Referenced by annotateOpsWithBufferizationMarkers().
removeBufferizationFuncArguments()
static void removeBufferizationFuncArguments (BlockArgument bbArg) static
Remove the attribute that triggers inplace bufferization on a FuncOp argument bbArg.
Definition at line 288 of file ModuleBufferization.cpp.
References mlir::BlockArgument::getArgNumber(), mlir::BlockArgument::getOwner(), and mlir::Block::getParentOp().
Referenced by annotateOpsWithBufferizationMarkers().
setInPlaceFuncArgument()
static void setInPlaceFuncArgument (BlockArgument bbArg, bool inPlace) static
Set the attribute that triggers inplace bufferization on a FuncOp argument bbArg.
Definition at line 957 of file ModuleBufferization.cpp.
References mlir::BoolAttr::get(), mlir::BlockArgument::getArgNumber(), mlir::Value::getContext(), mlir::BlockArgument::getOwner(), and mlir::Block::getParentOp().
Referenced by annotateOpsWithBufferizationMarkers().