MLIR: mlir::presburger_utils Namespace Reference
mlir::presburger_utils Namespace Reference
Classes
struct MaybeLocalRepr
MaybeLocalRepr contains the indices of the contraints that can be expressed as a floordiv of an affine function.
Enumerations
enum ReprKind { ReprKind::Inequality, ReprKind::Equality, ReprKind::None }
ReprKind enum is used to set the constraint type in MaybeLocalRepr.
Functions
MaybeLocalRepr computeSingleVarRepr (const IntegerPolyhedron &cst, ArrayRef< bool > foundRepr, unsigned pos, SmallVector< int64_t, 8 > &dividend, unsigned &divisor)
Check if the pos^th identifier can be expressed as a floordiv of an affine function of other identifiers (where the divisor is a positive constant).
void removeDuplicateDivs (std::vector< SmallVector< int64_t, 8 >> &divs, SmallVectorImpl< unsigned > &denoms, unsigned localOffset, llvm::function_ref< bool(unsigned i, unsigned j)> merge)
Given dividends of divisions divs and denominators denoms, detects and removes duplicate divisions.
Enumeration Type Documentation
ReprKind
enum mlir::presburger_utils::ReprKind strong
ReprKind enum is used to set the constraint type in MaybeLocalRepr.
Enumerator
Inequality
Equality
None
Definition at line 26 of file Utils.h.
Function Documentation
computeSingleVarRepr()
MaybeLocalRepr mlir::presburger_utils::computeSingleVarRepr (const IntegerPolyhedron & cst, ArrayRef< bool > foundRepr, unsigned pos, SmallVector< int64_t, 8 > & dividend, unsigned & divisor)
Check if the pos^th identifier can be expressed as a floordiv of an affine function of other identifiers (where the divisor is a positive constant).
foundRepr contains a boolean for each identifier indicating if the explicit representation for that identifier has already been computed. Returns the upper and lower bound inequalities using which the floordiv can be computed. If the representation could be computed, dividend and denominator are set. If the representation could not be computed, llvm::None is returned.
Definition at line 151 of file Utils.cpp.
References mlir::failed(), getDivRepr(), mlir::IntegerPolyhedron::getLowerAndUpperBoundIndices(), mlir::IntegerPolyhedron::getNumIds(), Inequality, mlir::presburger_utils::MaybeLocalRepr::inEqualityPair, mlir::presburger_utils::MaybeLocalRepr::kind, and mlir::presburger_utils::MaybeLocalRepr::repr.
Referenced by detectAsFloorDiv().
removeDuplicateDivs()
void mlir::presburger_utils::removeDuplicateDivs (std::vector< SmallVector< int64_t, 8 >> & divs, SmallVectorImpl< unsigned > & denoms, unsigned localOffset, llvm::function_ref< bool(unsigned i, unsigned j)> merge)
Given dividends of divisions divs and denominators denoms, detects and removes duplicate divisions.
localOffset is the offset in dividend of a division from where local identifiers start.
On every possible duplicate division found, merge(i, j), where i, j are current index of the duplicate divisions, is called and division at index j is merged into division at index i. If merge(i, j) returns true, the divisions are merged i.e. j^th division gets eliminated and it's each instance is replaced by i^th division. If it returns false, the divisions are not merged. merge can also do side effects, For example it can merge the local identifiers in IntegerPolyhedron.
Definition at line 194 of file Utils.cpp.
Referenced by mlir::IntegerPolyhedron::mergeLocalIds().