MLIR: lib/Target/LLVMIR/Dialect/OpenMP/OpenMPToLLVMIRTranslation.cpp File Reference
OpenMPToLLVMIRTranslation.cpp File Reference
#include "mlir/Target/LLVMIR/Dialect/OpenMP/OpenMPToLLVMIRTranslation.h"
#include "mlir/Dialect/OpenMP/OpenMPDialect.h"
#include "mlir/IR/BlockAndValueMapping.h"
#include "mlir/IR/Operation.h"
#include "mlir/Support/LLVM.h"
#include "mlir/Target/LLVMIR/ModuleTranslation.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/TypeSwitch.h"
#include "llvm/Frontend/OpenMP/OMPIRBuilder.h"
#include "llvm/IR/IRBuilder.h"
Functions
static llvm::OpenMPIRBuilder::InsertPointTy findAllocaInsertPoint (llvm::IRBuilderBase &builder, const LLVM::ModuleTranslation &moduleTranslation)
Find the insertion point for allocas given the current insertion point for normal operations in the builder.
static void convertOmpOpRegions (Region &region, StringRef blockName, llvm::BasicBlock &sourceBlock, llvm::BasicBlock &continuationBlock, llvm::IRBuilderBase &builder, LLVM::ModuleTranslation &moduleTranslation, LogicalResult &bodyGenStatus, SmallVectorImpl< llvm::PHINode *> *continuationBlockPHIs=nullptr)
Converts the given region that appears within an OpenMP dialect operation to LLVM IR, creating a branch from the sourceBlock to the entry block of the region, and a branch from any block with an successor-less OpenMP terminator to continuationBlock.
static llvm::omp::ProcBindKind getProcBindKind (omp::ClauseProcBindKind kind)
Convert ProcBindKind from MLIR-generated enum to LLVM enum.
static LogicalResult convertOmpParallel (omp::ParallelOp opInst, llvm::IRBuilderBase &builder, LLVM::ModuleTranslation &moduleTranslation)
Converts the OpenMP parallel operation to LLVM IR.
static LogicalResult convertOmpMaster (Operation &opInst, llvm::IRBuilderBase &builder, LLVM::ModuleTranslation &moduleTranslation)
Converts an OpenMP 'master' operation into LLVM IR using OpenMPIRBuilder.
static LogicalResult convertOmpCritical (Operation &opInst, llvm::IRBuilderBase &builder, LLVM::ModuleTranslation &moduleTranslation)
Converts an OpenMP 'critical' operation into LLVM IR using OpenMPIRBuilder.
static omp::ReductionDeclareOp findReductionDecl (omp::WsLoopOp container, omp::ReductionOp reduction)
Returns a reduction declaration that corresponds to the given reduction operation in the given container.
static void collectReductionDecls (omp::WsLoopOp loop, SmallVectorImpl< omp::ReductionDeclareOp > &reductions)
Populates reductions with reduction declarations used in the given loop.
static LogicalResult inlineConvertOmpRegions (Region &region, StringRef blockName, llvm::IRBuilderBase &builder, LLVM::ModuleTranslation &moduleTranslation, SmallVectorImpl< llvm::Value *> *continuationBlockArgs=nullptr)
Translates the blocks contained in the given region and appends them to at the current insertion point of builder.
static OwningReductionGen makeReductionGen (omp::ReductionDeclareOp decl, llvm::IRBuilderBase &builder, LLVM::ModuleTranslation &moduleTranslation)
Create an OpenMPIRBuilder-compatible reduction generator for the given reduction declaration.
static OwningAtomicReductionGen makeAtomicReductionGen (omp::ReductionDeclareOp decl, llvm::IRBuilderBase &builder, LLVM::ModuleTranslation &moduleTranslation)
Create an OpenMPIRBuilder-compatible atomic reduction generator for the given reduction declaration.
static LogicalResult convertOmpOrdered (Operation &opInst, llvm::IRBuilderBase &builder, LLVM::ModuleTranslation &moduleTranslation)
Converts an OpenMP 'ordered' operation into LLVM IR using OpenMPIRBuilder.
static LogicalResult convertOmpOrderedRegion (Operation &opInst, llvm::IRBuilderBase &builder, LLVM::ModuleTranslation &moduleTranslation)
Converts an OpenMP 'ordered_region' operation into LLVM IR using OpenMPIRBuilder.
static LogicalResult convertOmpSections (Operation &opInst, llvm::IRBuilderBase &builder, LLVM::ModuleTranslation &moduleTranslation)
static LogicalResult convertOmpWsLoop (Operation &opInst, llvm::IRBuilderBase &builder, LLVM::ModuleTranslation &moduleTranslation)
Converts an OpenMP workshare loop into LLVM IR using OpenMPIRBuilder.
llvm::AtomicOrdering convertAtomicOrdering (Optional< omp::ClauseMemoryOrderKind > ao)
Convert an Atomic Ordering attribute to llvm::AtomicOrdering.
static LogicalResult convertOmpAtomicRead (Operation &opInst, llvm::IRBuilderBase &builder, LLVM::ModuleTranslation &moduleTranslation)
Convert omp.atomic.read operation to LLVM IR.
static LogicalResult convertOmpAtomicWrite (Operation &opInst, llvm::IRBuilderBase &builder, LLVM::ModuleTranslation &moduleTranslation)
Converts an omp.atomic.write operation to LLVM IR.
static LogicalResult convertOmpReductionOp (omp::ReductionOp reductionOp, llvm::IRBuilderBase &builder, LLVM::ModuleTranslation &moduleTranslation)
Converts an OpenMP reduction operation using OpenMPIRBuilder.
Function Documentation
collectReductionDecls()
static void collectReductionDecls (omp::WsLoopOp loop, SmallVectorImpl< omp::ReductionDeclareOp > & reductions) static
Populates reductions with reduction declarations used in the given loop.
Definition at line 369 of file OpenMPToLLVMIRTranslation.cpp.
Referenced by convertOmpWsLoop().
convertAtomicOrdering()
llvm::AtomicOrdering convertAtomicOrdering (Optional< omp::ClauseMemoryOrderKind > ao)
Convert an Atomic Ordering attribute to llvm::AtomicOrdering.
Definition at line 897 of file OpenMPToLLVMIRTranslation.cpp.
Referenced by convertOmpAtomicRead(), and convertOmpAtomicWrite().
convertOmpAtomicRead()
static LogicalResult convertOmpAtomicRead (Operation & opInst, llvm::IRBuilderBase & builder, LLVM::ModuleTranslation & moduleTranslation) static
Convert omp.atomic.read operation to LLVM IR.
Definition at line 918 of file OpenMPToLLVMIRTranslation.cpp.
References convertAtomicOrdering(), mlir::Operation::getLoc(), mlir::LLVM::ModuleTranslation::getOpenMPBuilder(), mlir::LLVM::ModuleTranslation::lookupValue(), mlir::success(), and mlir::LLVM::ModuleTranslation::translateLoc().
Referenced by convertOmpReductionOp().
convertOmpAtomicWrite()
static LogicalResult convertOmpAtomicWrite (Operation & opInst, llvm::IRBuilderBase & builder, LLVM::ModuleTranslation & moduleTranslation) static
Converts an omp.atomic.write operation to LLVM IR.
Definition at line 942 of file OpenMPToLLVMIRTranslation.cpp.
References convertAtomicOrdering(), mlir::Operation::getLoc(), mlir::LLVM::ModuleTranslation::getOpenMPBuilder(), mlir::LLVM::ModuleTranslation::lookupValue(), mlir::success(), and mlir::LLVM::ModuleTranslation::translateLoc().
Referenced by convertOmpReductionOp().
convertOmpCritical()
static LogicalResult convertOmpCritical (Operation & opInst, llvm::IRBuilderBase & builder, LLVM::ModuleTranslation & moduleTranslation) static
Converts an OpenMP 'critical' operation into LLVM IR using OpenMPIRBuilder.
Definition at line 306 of file OpenMPToLLVMIRTranslation.cpp.
References mlir::Constant, convertOmpOpRegions(), mlir::LLVM::ModuleTranslation::getLLVMContext(), mlir::LLVM::ModuleTranslation::getOpenMPBuilder(), and mlir::success().
Referenced by convertOmpReductionOp().
convertOmpMaster()
static LogicalResult convertOmpMaster (Operation & opInst, llvm::IRBuilderBase & builder, LLVM::ModuleTranslation & moduleTranslation) static
Converts an OpenMP 'master' operation into LLVM IR using OpenMPIRBuilder.
Definition at line 277 of file OpenMPToLLVMIRTranslation.cpp.
References convertOmpOpRegions(), mlir::LLVM::ModuleTranslation::getOpenMPBuilder(), and mlir::success().
Referenced by convertOmpReductionOp().
convertOmpOpRegions()
static void convertOmpOpRegions (Region & region, StringRef blockName, llvm::BasicBlock & sourceBlock, llvm::BasicBlock & continuationBlock, llvm::IRBuilderBase & builder, LLVM::ModuleTranslation & moduleTranslation, LogicalResult & bodyGenStatus, SmallVectorImpl< llvm::PHINode *> * continuationBlockPHIs = nullptr) static
Converts the given region that appears within an OpenMP dialect operation to LLVM IR, creating a branch from the sourceBlock to the entry block of the region, and a branch from any block with an successor-less OpenMP terminator to continuationBlock.
Populates continuationBlockPHIs with the PHI nodes of the continuation block if provided.
Definition at line 81 of file OpenMPToLLVMIRTranslation.cpp.
References mlir::LLVM::detail::connectPHINodes(), mlir::LLVM::ModuleTranslation::convertBlock(), mlir::LLVM::ModuleTranslation::convertType(), mlir::failed(), mlir::failure(), mlir::LLVM::ModuleTranslation::forgetMapping(), mlir::Operation::getNumOperands(), mlir::Operation::getOperand(), mlir::LLVM::detail::getTopologicallySortedBlocks(), mlir::LLVM::ModuleTranslation::lookupBlock(), mlir::LLVM::ModuleTranslation::lookupValue(), and mlir::LLVM::ModuleTranslation::mapBlock().
Referenced by convertOmpCritical(), convertOmpMaster(), convertOmpOrderedRegion(), convertOmpParallel(), convertOmpSections(), convertOmpWsLoop(), and inlineConvertOmpRegions().
convertOmpOrdered()
static LogicalResult convertOmpOrdered (Operation & opInst, llvm::IRBuilderBase & builder, LLVM::ModuleTranslation & moduleTranslation) static
Converts an OpenMP 'ordered' operation into LLVM IR using OpenMPIRBuilder.
Definition at line 512 of file OpenMPToLLVMIRTranslation.cpp.
References findAllocaInsertPoint(), mlir::LLVM::ModuleTranslation::getOpenMPBuilder(), mlir::LLVM::ModuleTranslation::lookupValues(), and mlir::success().
Referenced by convertOmpReductionOp().
convertOmpOrderedRegion()
static LogicalResult convertOmpOrderedRegion (Operation & opInst, llvm::IRBuilderBase & builder, LLVM::ModuleTranslation & moduleTranslation) static
Converts an OpenMP 'ordered_region' operation into LLVM IR using OpenMPIRBuilder.
Definition at line 542 of file OpenMPToLLVMIRTranslation.cpp.
References convertOmpOpRegions(), mlir::failure(), mlir::LLVM::ModuleTranslation::getOpenMPBuilder(), and mlir::success().
Referenced by convertOmpReductionOp().
convertOmpParallel()
static LogicalResult convertOmpParallel (omp::ParallelOp opInst, llvm::IRBuilderBase & builder, LLVM::ModuleTranslation & moduleTranslation) static
Converts the OpenMP parallel operation to LLVM IR.
Definition at line 206 of file OpenMPToLLVMIRTranslation.cpp.
References convertOmpOpRegions(), findAllocaInsertPoint(), mlir::LLVM::ModuleTranslation::getOpenMPBuilder(), getProcBindKind(), mlir::LLVM::ModuleTranslation::lookupValue(), and mlir::success().
Referenced by convertOmpReductionOp().
convertOmpReductionOp()
static LogicalResult convertOmpReductionOp (omp::ReductionOp reductionOp, llvm::IRBuilderBase & builder, LLVM::ModuleTranslation & moduleTranslation) static
Converts an OpenMP reduction operation using OpenMPIRBuilder.
Expects the mapping between reduction variables and their private equivalents to have been stored on the ModuleTranslation stack. Currently only supports reduction within WsLoopOp, but can be easily extended.
Definition at line 968 of file OpenMPToLLVMIRTranslation.cpp.
References convertOmpAtomicRead(), convertOmpAtomicWrite(), convertOmpCritical(), convertOmpMaster(), convertOmpOrdered(), convertOmpOrderedRegion(), convertOmpParallel(), convertOmpSections(), convertOmpWsLoop(), mlir::LLVM::ModuleTranslation::convertType(), mlir::Operation::emitError(), mlir::failed(), mlir::failure(), findReductionDecl(), mlir::Region::front(), mlir::Block::getArgument(), mlir::Operation::getName(), mlir::LLVM::ModuleTranslation::getOpenMPBuilder(), inlineConvertOmpRegions(), mlir::WalkResult::interrupt(), mlir::LLVMTranslationDialectInterface::LLVMTranslationDialectInterface(), mlir::LLVM::ModuleTranslation::lookupValue(), mlir::LLVM::ModuleTranslation::mapValue(), mlir::LLVM::ModuleTranslation::stackWalk(), and mlir::success().
convertOmpSections()
static LogicalResult convertOmpSections (Operation & opInst, llvm::IRBuilderBase & builder, LLVM::ModuleTranslation & moduleTranslation) static
Definition at line 577 of file OpenMPToLLVMIRTranslation.cpp.
References convertOmpOpRegions(), mlir::emitError(), findAllocaInsertPoint(), mlir::LLVM::ModuleTranslation::getOpenMPBuilder(), and mlir::success().
Referenced by convertOmpReductionOp().
convertOmpWsLoop()
static LogicalResult convertOmpWsLoop (Operation & opInst, llvm::IRBuilderBase & builder, LLVM::ModuleTranslation & moduleTranslation) static
Converts an OpenMP workshare loop into LLVM IR using OpenMPIRBuilder.
Definition at line 649 of file OpenMPToLLVMIRTranslation.cpp.
References collectReductionDecls(), convertOmpOpRegions(), mlir::LLVM::ModuleTranslation::convertType(), mlir::failed(), mlir::failure(), findAllocaInsertPoint(), mlir::Operation::getLoc(), mlir::LLVM::ModuleTranslation::getOpenMPBuilder(), inlineConvertOmpRegions(), mlir::LLVM::ModuleTranslation::lookupValue(), makeAtomicReductionGen(), makeReductionGen(), mlir::LLVM::ModuleTranslation::mapValue(), mlir::success(), and mlir::LLVM::ModuleTranslation::translateLoc().
Referenced by convertOmpReductionOp().
findAllocaInsertPoint()
static llvm::OpenMPIRBuilder::InsertPointTy findAllocaInsertPoint (llvm::IRBuilderBase & builder, const LLVM::ModuleTranslation & moduleTranslation) static
Find the insertion point for allocas given the current insertion point for normal operations in the builder.
Definition at line 55 of file OpenMPToLLVMIRTranslation.cpp.
References mlir::WalkResult::interrupt(), mlir::LLVM::ModuleTranslation::stackWalk(), and mlir::WalkResult::wasInterrupted().
Referenced by convertOmpOrdered(), convertOmpParallel(), convertOmpSections(), and convertOmpWsLoop().
findReductionDecl()
static omp::ReductionDeclareOp findReductionDecl (omp::WsLoopOp container, omp::ReductionOp reduction) static
Returns a reduction declaration that corresponds to the given reduction operation in the given container.
Currently only supports reductions inside WsLoopOp but can be easily extended.
Definition at line 351 of file OpenMPToLLVMIRTranslation.cpp.
Referenced by convertOmpReductionOp().
getProcBindKind()
static llvm::omp::ProcBindKind getProcBindKind (omp::ClauseProcBindKind kind) static
Convert ProcBindKind from MLIR-generated enum to LLVM enum.
Definition at line 190 of file OpenMPToLLVMIRTranslation.cpp.
Referenced by convertOmpParallel().
inlineConvertOmpRegions()
static LogicalResult inlineConvertOmpRegions (Region & region, StringRef blockName, llvm::IRBuilderBase & builder, LLVM::ModuleTranslation & moduleTranslation, SmallVectorImpl< llvm::Value *> * continuationBlockArgs = nullptr) static
Translates the blocks contained in the given region and appends them to at the current insertion point of builder.
The operations of the entry block are appended to the current insertion block, which is not expected to have a terminator. If set, continuationBlockArgs is populated with translated values that correspond to the values omp.yield'ed from the region.
Definition at line 388 of file OpenMPToLLVMIRTranslation.cpp.
References mlir::Block::back(), mlir::LLVM::ModuleTranslation::convertBlock(), convertOmpOpRegions(), mlir::Region::empty(), mlir::failed(), mlir::failure(), mlir::LLVM::ModuleTranslation::forgetMapping(), mlir::Region::front(), mlir::Operation::getOperands(), mlir::LLVM::ModuleTranslation::lookupValues(), mlir::LLVM::ModuleTranslation::mapBlock(), and mlir::success().
Referenced by convertOmpReductionOp(), and convertOmpWsLoop().
makeAtomicReductionGen()
static OwningAtomicReductionGen makeAtomicReductionGen (omp::ReductionDeclareOp decl, llvm::IRBuilderBase & builder, LLVM::ModuleTranslation & moduleTranslation) static
Create an OpenMPIRBuilder-compatible atomic reduction generator for the given reduction declaration.
The generator uses builder but ignores its insertion point. Returns null if there is no atomic region available in the reduction declaration.
Definition at line 483 of file OpenMPToLLVMIRTranslation.cpp.
Referenced by convertOmpWsLoop().
makeReductionGen()
static OwningReductionGen makeReductionGen (omp::ReductionDeclareOp decl, llvm::IRBuilderBase & builder, LLVM::ModuleTranslation & moduleTranslation) static
Create an OpenMPIRBuilder-compatible reduction generator for the given reduction declaration.
The generator uses builder but ignores its insertion point.
Definition at line 453 of file OpenMPToLLVMIRTranslation.cpp.
Referenced by convertOmpWsLoop().