MLIR: lib/Analysis/Presburger/PresburgerSet.cpp File Reference
PresburgerSet.cpp File Reference
#include "mlir/Analysis/Presburger/PresburgerSet.h"
#include "mlir/Analysis/Presburger/Simplex.h"
#include "mlir/Analysis/Presburger/Utils.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallBitVector.h"
Functions
static void assertDimensionsCompatible (const IntegerPolyhedron &poly, const PresburgerSet &set)
Assert that the IntegerPolyhedron and PresburgerSet live in compatible spaces.
static void assertDimensionsCompatible (const PresburgerSet &setA, const PresburgerSet &setB)
Assert that the two PresburgerSets live in compatible spaces.
static SmallVector< int64_t, 8 > getNegatedCoeffs (ArrayRef< int64_t > coeffs)
Return coeffs with all the elements negated.
static SmallVector< int64_t, 8 > getComplementIneq (ArrayRef< int64_t > ineq)
Return the complement of the given inequality.
static void subtractRecursively (IntegerPolyhedron &b, Simplex &simplex, const PresburgerSet &s, unsigned i, PresburgerSet &result)
Return the set difference b \ s and accumulate the result into result.
Function Documentation
assertDimensionsCompatible() [1/2]
static void assertDimensionsCompatible (const IntegerPolyhedron & poly, const PresburgerSet & set) static
Assert that the IntegerPolyhedron and PresburgerSet live in compatible spaces.
Definition at line 43 of file PresburgerSet.cpp.
References mlir::IntegerPolyhedron::getNumDimIds(), and mlir::IntegerPolyhedron::getNumSymbolIds().
Referenced by mlir::PresburgerSet::intersect(), mlir::PresburgerSet::isEqual(), mlir::PresburgerSet::subtract(), subtractRecursively(), mlir::PresburgerSet::unionPolyInPlace(), mlir::PresburgerSet::unionSet(), and mlir::PresburgerSet::unionSetInPlace().
assertDimensionsCompatible() [2/2]
static void assertDimensionsCompatible (const PresburgerSet & setA, const PresburgerSet & setB) static
Assert that the two PresburgerSets live in compatible spaces.
Definition at line 54 of file PresburgerSet.cpp.
References mlir::PresburgerSet::getNumDimIds(), and mlir::PresburgerSet::getNumSymbolIds().
getComplementIneq()
static SmallVector<int64_t, 8> getComplementIneq (ArrayRef< int64_t > ineq) static
Return the complement of the given inequality.
The complement of a_1 x_1 + ... + a_n x_ + c >= 0 is a_1 x_1 + ... + a_n x_ + c < 0, i.e., -a_1 x_1 - ... - a_n x_ - c - 1 >= 0, since all the variables are constrained to be integers.
Definition at line 143 of file PresburgerSet.cpp.
Referenced by subtractRecursively().
getNegatedCoeffs()
static SmallVector<int64_t, 8> getNegatedCoeffs (ArrayRef< int64_t > coeffs) static
Return coeffs with all the elements negated.
Definition at line 130 of file PresburgerSet.cpp.
Referenced by subtractRecursively().
subtractRecursively()
static void subtractRecursively (IntegerPolyhedron & b, Simplex & simplex, const PresburgerSet & s, unsigned i, PresburgerSet & result) static
Return the set difference b \ s and accumulate the result into result.
simplex must correspond to b.
In the following, U denotes union, ^ denotes intersection, \ denotes set difference and ~ denotes complement. Let b be the IntegerPolyhedron and s = (U_i s_i) be the set. We want b \ (U_i s_i).
Let s_i = ^_j s_ij, where each s_ij is a single inequality. To compute b \ s_i = b ^ ~s_i, we partition s_i based on the first violated inequality: ~s_i = (~s_i1) U (s_i1 ^ ~s_i2) U (s_i1 ^ s_i2 ^ ~s_i3) U ... And the required result is (b ^ ~s_i1) U (b ^ s_i1 ^ ~s_i2) U ... We recurse by subtracting U_{j > i} S_j from each of these parts and returning the union of the results. Each equality is handled as a conjunction of two inequalities.
Note that the same approach works even if an inequality involves a floor division. For example, the complement of x <= 7*floor(x/7) is still x > 7*floor(x/7). Since b \ s_i contains the inequalities of both b and s_i (or the complements of those inequalities), b \ s_i may contain the divisions present in both b and s_i. Therefore, we need to add the local division variables of both b and s_i to each part in the result. This means adding the local variables of both b and s_i, as well as the corresponding division inequalities to each part. Since the division inequalities are added to each part, we can skip the parts where the complement of any division inequality is added, as these parts will become empty anyway.
As a heuristic, we try adding all the constraints and check if simplex says that the intersection is empty. If it is, then subtracting this Poly is a no-op and we just skip it. Also, in the process we find out that some constraints are redundant. These redundant constraints are ignored.
b and simplex are callee saved, i.e., their values on return are semantically equivalent to their values when the function is called.
b ^ s_i is empty, so b \ s_i = b. We move directly to i + 1. We are ignoring level i completely, so we restore the state before going to level i + 1.
Definition at line 186 of file PresburgerSet.cpp.
References mlir::SimplexBase::addInequality(), mlir::IntegerPolyhedron::addInequality(), mlir::SimplexBase::appendVariable(), assertDimensionsCompatible(), mlir::Simplex::detectRedundant(), getComplementIneq(), mlir::PresburgerSet::getEmptySet(), mlir::IntegerPolyhedron::getEquality(), mlir::IntegerPolyhedron::getInequality(), mlir::PresburgerSet::getIntegerPolyhedron(), mlir::IntegerPolyhedron::getLocalReprs(), getNegatedCoeffs(), mlir::SimplexBase::getNumConstraints(), mlir::IntegerPolyhedron::getNumDimIds(), mlir::IntegerPolyhedron::getNumEqualities(), mlir::IntegerPolyhedron::getNumInequalities(), mlir::IntegerPolyhedron::getNumLocalIds(), mlir::PresburgerSet::getNumPolys(), mlir::IntegerPolyhedron::getNumSymbolIds(), mlir::SimplexBase::getSnapshot(), mlir::SimplexBase::intersectIntegerPolyhedron(), mlir::SimplexBase::isEmpty(), mlir::IntegerPolyhedron::isEmptyByGCDTest(), mlir::Simplex::isMarkedRedundant(), mlir::IntegerPolyhedron::mergeLocalIds(), mlir::IntegerPolyhedron::removeEqualityRange(), mlir::IntegerPolyhedron::removeIdRange(), mlir::IntegerPolyhedron::removeInequality(), mlir::IntegerPolyhedron::removeInequalityRange(), mlir::SimplexBase::rollback(), and mlir::PresburgerSet::unionPolyInPlace().