MLIR: lib/Dialect/SparseTensor/IR/SparseTensorDialect.cpp File Reference
SparseTensorDialect.cpp File Reference
#include "mlir/Dialect/SparseTensor/IR/SparseTensor.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/DialectImplementation.h"
#include "mlir/IR/Matchers.h"
#include "mlir/IR/OpImplementation.h"
#include "llvm/ADT/TypeSwitch.h"
#include "mlir/Dialect/SparseTensor/IR/SparseTensorOpsDialect.cpp.inc"
#include "mlir/Dialect/SparseTensor/IR/SparseTensorAttrDefs.cpp.inc"
#include "mlir/Dialect/SparseTensor/IR/SparseTensorOps.cpp.inc"
Macros
#define GET_ATTRDEF_CLASSES
#define GET_ATTRDEF_LIST
#define GET_OP_LIST
#define GET_OP_CLASSES
Functions
static bool acceptBitWidth (unsigned bitWidth)
static LogicalResult isInBounds (Value dim, Value tensor)
static LogicalResult isMatchingWidth (Value result, unsigned width)
static LogicalResult verify (NewOp op)
static LogicalResult verify (InitOp op)
static LogicalResult verify (ConvertOp op)
static LogicalResult verify (ToPointersOp op)
static LogicalResult verify (ToIndicesOp op)
static LogicalResult verify (ToValuesOp op)
static LogicalResult verify (LexInsertOp op)
static LogicalResult verify (ExpandOp op)
static LogicalResult verify (CompressOp op)
static LogicalResult verify (LoadOp op)
static LogicalResult verify (ReleaseOp op)
static LogicalResult verify (OutOp op)
Macro Definition Documentation
GET_ATTRDEF_CLASSES
#define GET_ATTRDEF_CLASSES
Definition at line 25 of file SparseTensorDialect.cpp.
GET_ATTRDEF_LIST
#define GET_ATTRDEF_LIST
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 354 of file SparseTensorDialect.cpp.
GET_OP_LIST
#define GET_OP_LIST
Function Documentation
acceptBitWidth()
static bool acceptBitWidth (unsigned bitWidth) static
Definition at line 28 of file SparseTensorDialect.cpp.
References mlir::AsmParser::emitError(), mlir::emitError(), mlir::failed(), mlir::failure(), mlir::AsmParser::getChecked(), mlir::AsmParser::getContext(), mlir::AsmParser::getNameLoc(), mlir::AffineMap::getNumResults(), mlir::AffineMap::isPermutation(), mlir::AsmParser::parseAttribute(), mlir::AsmParser::parseGreater(), mlir::AsmParser::parseLess(), print(), mlir::success(), mlir::verify(), and verify().
isInBounds()
static LogicalResult isInBounds (Value dim, Value tensor) static
Definition at line 195 of file SparseTensorDialect.cpp.
References mlir::Type::cast(), mlir::failure(), mlir::Value::getType(), mlir::m_Constant(), mlir::matchPattern(), and mlir::success().
Referenced by verify().
isMatchingWidth()
static LogicalResult isMatchingWidth (Value result, unsigned width) static
Definition at line 205 of file SparseTensorDialect.cpp.
References mlir::Type::cast(), mlir::failure(), getElementType(), mlir::Value::getType(), mlir::Type::isIndex(), mlir::Type::isInteger(), and mlir::success().
Referenced by verify().
verify() [1/12]
static LogicalResult verify (NewOp op) static
Definition at line 212 of file SparseTensorDialect.cpp.
References mlir::sparse_tensor::getSparseTensorEncoding(), and mlir::success().
Referenced by acceptBitWidth().
verify() [2/12]
static LogicalResult verify (InitOp op) static
Definition at line 218 of file SparseTensorDialect.cpp.
References mlir::sparse_tensor::getSparseTensorEncoding(), mlir::m_Constant(), mlir::matchPattern(), and mlir::success().
verify() [3/12]
static LogicalResult verify (ConvertOp op) static
Definition at line 240 of file SparseTensorDialect.cpp.
References mlir::success().
verify() [4/12]
static LogicalResult verify (ToPointersOp op) static
Definition at line 267 of file SparseTensorDialect.cpp.
References mlir::failed(), mlir::sparse_tensor::getSparseTensorEncoding(), isInBounds(), isMatchingWidth(), and mlir::success().
verify() [5/12]
static LogicalResult verify (ToIndicesOp op) static
Definition at line 278 of file SparseTensorDialect.cpp.
References mlir::failed(), mlir::sparse_tensor::getSparseTensorEncoding(), isInBounds(), isMatchingWidth(), and mlir::success().
verify() [6/12]
static LogicalResult verify (ToValuesOp op) static
Definition at line 289 of file SparseTensorDialect.cpp.
References mlir::sparse_tensor::getSparseTensorEncoding(), and mlir::success().
verify() [7/12]
static LogicalResult verify (LexInsertOp op) static
Definition at line 303 of file SparseTensorDialect.cpp.
References mlir::sparse_tensor::getSparseTensorEncoding(), and mlir::success().
verify() [8/12]
static LogicalResult verify (ExpandOp op) static
Definition at line 309 of file SparseTensorDialect.cpp.
References mlir::sparse_tensor::getSparseTensorEncoding(), and mlir::success().
verify() [9/12]
static LogicalResult verify (CompressOp op) static
Definition at line 315 of file SparseTensorDialect.cpp.
References mlir::sparse_tensor::getSparseTensorEncoding(), and mlir::success().
verify() [10/12]
static LogicalResult verify (LoadOp op) static
Definition at line 321 of file SparseTensorDialect.cpp.
References mlir::sparse_tensor::getSparseTensorEncoding(), and mlir::success().
verify() [11/12]
static LogicalResult verify (ReleaseOp op) static
Definition at line 327 of file SparseTensorDialect.cpp.
References mlir::sparse_tensor::getSparseTensorEncoding(), and mlir::success().
verify() [12/12]
static LogicalResult verify (OutOp op) static
Definition at line 333 of file SparseTensorDialect.cpp.
References mlir::sparse_tensor::getSparseTensorEncoding(), and mlir::success().