MLIR: mlir::linalg::comprehensive_bufferize::linalg_ext::InitTensorEliminationStep Struct Reference
mlir::linalg::comprehensive_bufferize::linalg_ext::InitTensorEliminationStep Struct Reference
#include "mlir/Dialect/Linalg/ComprehensiveBufferize/LinalgInterfaceImpl.h"
Public Types
using AnchorMatchFn = std::function< bool(OpOperand &)>
A function that matches anchor OpOperands for InitTensorOp elimination.
using RewriteFn = std::function< Value(OpBuilder &, Location, OpOperand &)>
A function that rewrites matched anchors.
Public Member Functions
LogicalResult eliminateInitTensors (Operation *op, bufferization::BufferizationState &state, bufferization::BufferizationAliasInfo &aliasInfo, AnchorMatchFn anchorMatchFunc, RewriteFn rewriteFunc, SmallVector< Operation *> &newOps)
Try to eliminate InitTensorOps inside op.
Public Member Functions inherited from mlir::bufferization::PostAnalysisStep
virtual ~PostAnalysisStep ()=default
virtual LogicalResult run (Operation *op, BufferizationState &state, BufferizationAliasInfo &aliasInfo, SmallVector< Operation *> &newOps)=0
Run the post analysis step.
Detailed Description
Definition at line 21 of file LinalgInterfaceImpl.h.
Member Typedef Documentation
AnchorMatchFn
using mlir::linalg::comprehensive_bufferize::linalg_ext::InitTensorEliminationStep::AnchorMatchFn = std::function<bool(OpOperand &)>
A function that matches anchor OpOperands for InitTensorOp elimination.
Definition at line 23 of file LinalgInterfaceImpl.h.
RewriteFn
using mlir::linalg::comprehensive_bufferize::linalg_ext::InitTensorEliminationStep::RewriteFn = std::function<Value(OpBuilder &, Location, OpOperand &)>
A function that rewrites matched anchors.
Definition at line 26 of file LinalgInterfaceImpl.h.
Member Function Documentation
eliminateInitTensors()
LogicalResult mlir::linalg::comprehensive_bufferize::linalg_ext::InitTensorEliminationStep::eliminateInitTensors (Operation * op, bufferization::BufferizationState & state, bufferization::BufferizationAliasInfo & aliasInfo, AnchorMatchFn anchorMatchFunc, RewriteFn rewriteFunc, SmallVector< Operation *> & newOps)
Try to eliminate InitTensorOps inside op.
rewriteFunc generates the replacement for the InitTensorOp.
Only InitTensorOps that are anchored on a matching OpOperand as per anchorMatchFunc are considered. "Anchored" means that there is a path on the reverse SSA use-def chain, starting from the OpOperand and always following the aliasing OpOperand, that eventually ends at a single InitTensorOp.
The result of rewriteFunc must usually be analyzed for inplacability. This analysis can be skipped with skipAnalysis.
An InitTensorOp is replaced with the the result of rewriteFunc if it is anchored on a matching OpOperand. "Anchored" means that there is a path on the reverse SSA use-def chain, starting from the OpOperand and always following the aliasing OpOperand, that eventually ends at a single InitTensorOp.
Definition at line 454 of file LinalgInterfaceImpl.cpp.
References mlir::WalkResult::advance(), mlir::bufferization::BufferizationAliasInfo::areEquivalentBufferizedValues(), mlir::bufferization::BufferizationAliasInfo::createAliasInfoEntry(), mlir::Value::dyn_cast(), mlir::failure(), mlir::bufferization::BufferizationState::findValueInReverseUseDefChain(), mlir::IROperand< DerivedT, IRValueT >::get(), mlir::bufferization::BufferizationState::getAliasingOpOperand(), mlir::Operation::getContext(), mlir::Value::getDefiningOp(), mlir::Value::getLoc(), mlir::Operation::getOpOperands(), mlir::bufferization::BufferizationAliasInfo::isInPlace(), mlir::Value::replaceAllUsesWith(), mlir::linalg::comprehensive_bufferize::linalg_ext::InsertSliceAnchoredInitTensorEliminationStep::run(), mlir::WalkResult::skip(), mlir::bufferization::BufferizationAliasInfo::unionAliasSets(), mlir::bufferization::BufferizationAliasInfo::unionEquivalenceClasses(), and mlir::Operation::walk().
The documentation for this struct was generated from the following files:
include/mlir/Dialect/Linalg/ComprehensiveBufferize/LinalgInterfaceImpl.h
lib/Dialect/Linalg/ComprehensiveBufferize/LinalgInterfaceImpl.cpp