MLIR: mlir::linalg::comprehensive_bufferize::linalg_ext::InsertSliceAnchoredInitTensorEliminationStep Struct Reference
mlir::linalg::comprehensive_bufferize::linalg_ext::InsertSliceAnchoredInitTensorEliminationStep Struct Reference
Try to eliminate InitTensorOps inside op that are anchored on an InsertSliceOp, i.e., if it is eventually inserted into another tensor (and some other conditions are met).
#include "mlir/Dialect/Linalg/ComprehensiveBufferize/LinalgInterfaceImpl.h"
Public Member Functions
LogicalResult run (Operation *op, bufferization::BufferizationState &state, bufferization::BufferizationAliasInfo &aliasInfo, SmallVector< Operation *> &newOps) override
Try to eliminate InitTensorOps inside op.
Public Member Functions inherited from mlir::linalg::comprehensive_bufferize::linalg_ext::InitTensorEliminationStep
LogicalResult eliminateInitTensors (Operation *op, bufferization::BufferizationState &state, bufferization::BufferizationAliasInfo &aliasInfo, AnchorMatchFn anchorMatchFunc, RewriteFn rewriteFunc, SmallVector< Operation *> &newOps)
Try to eliminate InitTensorOps inside op.
Public Member Functions inherited from mlir::bufferization::PostAnalysisStep
virtual ~PostAnalysisStep ()=default
Additional Inherited Members
Public Types inherited from mlir::linalg::comprehensive_bufferize::linalg_ext::InitTensorEliminationStep
using AnchorMatchFn = std::function< bool(OpOperand &)>
A function that matches anchor OpOperands for InitTensorOp elimination.
using RewriteFn = std::function< Value(OpBuilder &, Location, OpOperand &)>
A function that rewrites matched anchors.
Detailed Description
Try to eliminate InitTensorOps inside op that are anchored on an InsertSliceOp, i.e., if it is eventually inserted into another tensor (and some other conditions are met).
Definition at line 48 of file LinalgInterfaceImpl.h.
Member Function Documentation
run()
LogicalResult mlir::linalg::comprehensive_bufferize::linalg_ext::InsertSliceAnchoredInitTensorEliminationStep::run (Operation * op, bufferization::BufferizationState & state, bufferization::BufferizationAliasInfo & aliasInfo, SmallVector< Operation *> & newOps) override virtual
Try to eliminate InitTensorOps inside op.
An InitTensorOp can be eliminated if it is eventually inserted into another tensor (and some other conditions are met).
E.g.: %0 = linalg.init_tensor %1 = linalg.fill(cst, %0) {inplace = [true]} %2 = tensor.insert_slice %1 into t[10][20][1]
InitTensorOp elimination will try to fill t inplace instead of filling a new allocation %0 and inserting it into t. This is done by replacing the InitTensorOp with:
%0 = tensor.extract_slice t[10][20][1]
The analysis looks for matching ExtractSliceOp/InsertSliceOp pairs and lets those bufferize inplace in the absence of other conflicts.
Starting from an InsertSliceOp, an InitTensorOp at the end of the insert source's reverse use-def chain is eliminated if:
The InsertSliceOp was decided to bufferize inplace.
On the reverse use-def chain path from the InsertSliceOp to the InitTensorOp, all ops were decided to bufferize inplace and the buffer relation is "equivalent" (TODO: can be relaxed if needed).
The reverse use-def chain has exactly one end, which is the InitTensorOp.
Note that the newly inserted ExtractSliceOp may have to bufferize out-of-place due to RaW conflicts.
Implements mlir::bufferization::PostAnalysisStep.
Definition at line 549 of file LinalgInterfaceImpl.cpp.
References mlir::OpBuilder::create(), mlir::Builder::getIndexAttr(), mlir::detail::IROperandBase::getOwner(), mlir::bufferization::BufferizationAliasInfo::isInPlace(), and mlir::linalg::comprehensive_bufferize::linalg_ext::registerBufferizableOpInterfaceExternalModels().
Referenced by mlir::linalg::comprehensive_bufferize::linalg_ext::InitTensorEliminationStep::eliminateInitTensors().
The documentation for this struct was generated from the following files:
include/mlir/Dialect/Linalg/ComprehensiveBufferize/LinalgInterfaceImpl.h
lib/Dialect/Linalg/ComprehensiveBufferize/LinalgInterfaceImpl.cpp