MLIR: mlir::linalg::comprehensive_bufferize::scf_ext::ForOpInterface Struct Reference
mlir::linalg::comprehensive_bufferize::scf_ext::ForOpInterface Struct Reference
Bufferization of scf.for.
Public Member Functions
bool bufferizesToMemoryRead (Operation *op, OpOperand &opOperand, const BufferizationState &state) const
bool bufferizesToMemoryWrite (Operation *op, OpOperand &opOperand, const BufferizationState &state) const
OpResult getAliasingOpResult (Operation *op, OpOperand &opOperand, const BufferizationState &state) const
BufferRelation bufferRelation (Operation *op, OpResult opResult, const BufferizationState &state) const
bool isWritable (Operation *op, Value value, const BufferizationState &state) const
LogicalResult bufferize (Operation *op, RewriterBase &rewriter, const BufferizationState &state) const
Detailed Description
Bufferization of scf.for.
Replace with a new scf.for that operates on memrefs.
Definition at line 260 of file SCFInterfaceImpl.cpp.
Member Function Documentation
bufferize()
LogicalResult mlir::linalg::comprehensive_bufferize::scf_ext::ForOpInterface::bufferize (Operation * op, RewriterBase & rewriter, const BufferizationState & state) const inline
Definition at line 311 of file SCFInterfaceImpl.cpp.
References mlir::OpBuilder::create(), ensureToMemrefOpIsValid(), mlir::detail::enumerate(), mlir::RewriterBase::eraseOp(), mlir::failed(), mlir::failure(), mlir::Block::front(), mlir::bufferization::BufferizationState::getBuffer(), mlir::Value::getLoc(), mlir::Operation::getResults(), mlir::RewriterBase::mergeBlocks(), mlir::bufferization::replaceOpWithBufferizedValues(), mlir::linalg::comprehensive_bufferize::scf_ext::AssertScfForAliasingProperties::run(), mlir::OpBuilder::setInsertionPoint(), mlir::OpBuilder::setInsertionPointToStart(), and mlir::success().
bufferizesToMemoryRead()
bool mlir::linalg::comprehensive_bufferize::scf_ext::ForOpInterface::bufferizesToMemoryRead (Operation * op, OpOperand & opOperand, const BufferizationState & state) const inline
Definition at line 263 of file SCFInterfaceImpl.cpp.
References mlir::bufferization::BufferizationState::isValueRead().
bufferizesToMemoryWrite()
bool mlir::linalg::comprehensive_bufferize::scf_ext::ForOpInterface::bufferizesToMemoryWrite (Operation * op, OpOperand & opOperand, const BufferizationState & state) const inline
Definition at line 271 of file SCFInterfaceImpl.cpp.
bufferRelation()
BufferRelation mlir::linalg::comprehensive_bufferize::scf_ext::ForOpInterface::bufferRelation (Operation * op, OpResult opResult, const BufferizationState & state) const inline
Definition at line 287 of file SCFInterfaceImpl.cpp.
References mlir::bufferization::BufferizationState::areEquivalentBufferizedValues(), mlir::bufferization::Equivalent, mlir::OpResult::getResultNumber(), and mlir::bufferization::None.
getAliasingOpResult()
OpResult mlir::linalg::comprehensive_bufferize::scf_ext::ForOpInterface::getAliasingOpResult (Operation * op, OpOperand & opOperand, const BufferizationState & state) const inline
Definition at line 279 of file SCFInterfaceImpl.cpp.
References mlir::IROperand< DerivedT, IRValueT >::get(), mlir::Value::getType(), and mlir::Type::isa().
isWritable()
bool mlir::linalg::comprehensive_bufferize::scf_ext::ForOpInterface::isWritable (Operation * op, Value value, const BufferizationState & state) const inline
Definition at line 300 of file SCFInterfaceImpl.cpp.
The documentation for this struct was generated from the following file:
lib/Dialect/Linalg/ComprehensiveBufferize/SCFInterfaceImpl.cpp