MLIR: mlir::linalg::comprehensive_bufferize::scf_ext::ExecuteRegionOpInterface Struct Reference
mlir::linalg::comprehensive_bufferize::scf_ext::ExecuteRegionOpInterface Struct Reference
Bufferization of scf.execute_region.
Public Member Functions
SmallVector< OpOperand * > getAliasingOpOperand (Operation *op, OpResult opResult, const BufferizationState &state) const
bool isMemoryWrite (Operation *op, OpResult opResult, const BufferizationState &state) const
LogicalResult bufferize (Operation *op, RewriterBase &rewriter, const BufferizationState &state) const
BufferRelation bufferRelation (Operation *op, OpResult opResult, const BufferizationState &state) const
Detailed Description
Bufferization of scf.execute_region.
Can be analyzed, but bufferization not fully implemented at the moment.
Definition at line 36 of file SCFInterfaceImpl.cpp.
Member Function Documentation
bufferize()
LogicalResult mlir::linalg::comprehensive_bufferize::scf_ext::ExecuteRegionOpInterface::bufferize (Operation * op, RewriterBase & rewriter, const BufferizationState & state) const inline
Definition at line 70 of file SCFInterfaceImpl.cpp.
References mlir::OpBuilder::create(), mlir::detail::enumerate(), mlir::Block::front(), mlir::Operation::getLoc(), mlir::bufferization::getMemRefType(), mlir::bufferization::BufferizationState::getOptions(), mlir::Value::getType(), mlir::Type::isa(), mlir::RewriterBase::replaceOp(), mlir::RewriterBase::replaceOpWithNewOp(), mlir::OpBuilder::setInsertionPoint(), mlir::OpBuilder::setInsertionPointAfter(), and mlir::success().
bufferRelation()
BufferRelation mlir::linalg::comprehensive_bufferize::scf_ext::ExecuteRegionOpInterface::bufferRelation (Operation * op, OpResult opResult, const BufferizationState & state) const inline
Definition at line 125 of file SCFInterfaceImpl.cpp.
References mlir::bufferization::Equivalent.
getAliasingOpOperand()
SmallVector<OpOperand *> mlir::linalg::comprehensive_bufferize::scf_ext::ExecuteRegionOpInterface::getAliasingOpOperand (Operation * op, OpResult opResult, const BufferizationState & state) const inline
Definition at line 40 of file SCFInterfaceImpl.cpp.
References mlir::Operation::getOpResults().
isMemoryWrite()
bool mlir::linalg::comprehensive_bufferize::scf_ext::ExecuteRegionOpInterface::isMemoryWrite (Operation * op, OpResult opResult, const BufferizationState & state) const inline
Definition at line 60 of file SCFInterfaceImpl.cpp.
The documentation for this struct was generated from the following file:
lib/Dialect/Linalg/ComprehensiveBufferize/SCFInterfaceImpl.cpp