MLIR: mlir::linalg::comprehensive_bufferize::scf_ext::AssertScfForAliasingProperties Struct Reference
mlir::linalg::comprehensive_bufferize::scf_ext::AssertScfForAliasingProperties Struct Reference
Assert that yielded values of an scf.for op are aliasing their corresponding bbArgs.
#include "mlir/Dialect/Linalg/ComprehensiveBufferize/SCFInterfaceImpl.h"
Public Member Functions
LogicalResult run (Operation *op, bufferization::BufferizationState &state, bufferization::BufferizationAliasInfo &aliasInfo, SmallVector< Operation *> &newOps) override
Run the post analysis step.
Public Member Functions inherited from mlir::bufferization::PostAnalysisStep
virtual ~PostAnalysisStep ()=default
Detailed Description
Assert that yielded values of an scf.for op are aliasing their corresponding bbArgs.
This is required because the i-th OpResult of an scf.for op is currently assumed to alias with the i-th iter_arg (in the absence of conflicts).
Definition at line 26 of file SCFInterfaceImpl.h.
Member Function Documentation
run()
LogicalResult mlir::linalg::comprehensive_bufferize::scf_ext::AssertScfForAliasingProperties::run (Operation * op, bufferization::BufferizationState & state, bufferization::BufferizationAliasInfo & aliasInfo, SmallVector< Operation *> & newOps) override virtual
Run the post analysis step.
This function may modify the IR, but must keep aliasInfo consistent. Newly created operations and operations that should be re-analyzed must be added to newOps.
Implements mlir::bufferization::PostAnalysisStep.
Definition at line 389 of file SCFInterfaceImpl.cpp.
References mlir::WalkResult::advance(), mlir::bufferization::BufferizationAliasInfo::areEquivalentBufferizedValues(), mlir::WalkResult::interrupt(), mlir::success(), and mlir::Operation::walk().
Referenced by mlir::linalg::comprehensive_bufferize::scf_ext::ForOpInterface::bufferize().
The documentation for this struct was generated from the following files:
include/mlir/Dialect/Linalg/ComprehensiveBufferize/SCFInterfaceImpl.h
lib/Dialect/Linalg/ComprehensiveBufferize/SCFInterfaceImpl.cpp