MLIR: mlir::linalg::comprehensive_bufferize::std_ext::SelectOpInterface Struct Reference
mlir::linalg::comprehensive_bufferize::std_ext::SelectOpInterface Struct Reference
Bufferization of std.select. Just replace the operands.
Public Member Functions
bool bufferizesToMemoryRead (Operation *op, OpOperand &opOperand, const BufferizationState &state) const
bool bufferizesToMemoryWrite (Operation *op, OpOperand &opOperand, const BufferizationState &state) const
OpResult getAliasingOpResult (Operation *op, OpOperand &opOperand, const BufferizationState &state) const
SmallVector< OpOperand * > getAliasingOpOperand (Operation *op, OpResult opResult, const BufferizationState &state) const
LogicalResult bufferize (Operation *op, RewriterBase &rewriter, const BufferizationState &state) const
BufferRelation bufferRelation (Operation *op, OpResult opResult, const BufferizationState &state) const
Detailed Description
Bufferization of std.select. Just replace the operands.
Definition at line 24 of file StdInterfaceImpl.cpp.
Member Function Documentation
bufferize()
LogicalResult mlir::linalg::comprehensive_bufferize::std_ext::SelectOpInterface::bufferize (Operation * op, RewriterBase & rewriter, const BufferizationState & state) const inline
Definition at line 49 of file StdInterfaceImpl.cpp.
References mlir::bufferization::BufferizationState::getBuffer(), and mlir::success().
bufferizesToMemoryRead()
bool mlir::linalg::comprehensive_bufferize::std_ext::SelectOpInterface::bufferizesToMemoryRead (Operation * op, OpOperand & opOperand, const BufferizationState & state) const inline
Definition at line 27 of file StdInterfaceImpl.cpp.
bufferizesToMemoryWrite()
bool mlir::linalg::comprehensive_bufferize::std_ext::SelectOpInterface::bufferizesToMemoryWrite (Operation * op, OpOperand & opOperand, const BufferizationState & state) const inline
Definition at line 32 of file StdInterfaceImpl.cpp.
bufferRelation()
BufferRelation mlir::linalg::comprehensive_bufferize::std_ext::SelectOpInterface::bufferRelation (Operation * op, OpResult opResult, const BufferizationState & state) const inline
Definition at line 66 of file StdInterfaceImpl.cpp.
References mlir::bufferization::None, and mlir::linalg::comprehensive_bufferize::std_ext::registerBufferizableOpInterfaceExternalModels().
getAliasingOpOperand()
SmallVector<OpOperand *> mlir::linalg::comprehensive_bufferize::std_ext::SelectOpInterface::getAliasingOpOperand (Operation * op, OpResult opResult, const BufferizationState & state) const inline
Definition at line 43 of file StdInterfaceImpl.cpp.
References mlir::Operation::getOpOperand().
getAliasingOpResult()
OpResult mlir::linalg::comprehensive_bufferize::std_ext::SelectOpInterface::getAliasingOpResult (Operation * op, OpOperand & opOperand, const BufferizationState & state) const inline
Definition at line 37 of file StdInterfaceImpl.cpp.
References mlir::Operation::getOpResult().
The documentation for this struct was generated from the following file:
lib/Dialect/Linalg/ComprehensiveBufferize/StdInterfaceImpl.cpp