MLIR: mlir::linalg::comprehensive_bufferize::scf_ext::YieldOpInterface Struct Reference
mlir::linalg::comprehensive_bufferize::scf_ext::YieldOpInterface Struct Reference
Bufferization of scf.yield.
Public Member Functions
bool bufferizesToMemoryRead (Operation *op, OpOperand &opOperand, const BufferizationState &state) const
bool bufferizesToMemoryWrite (Operation *op, OpOperand &opOperand, const BufferizationState &state) const
OpResult getAliasingOpResult (Operation *op, OpOperand &opOperand, const BufferizationState &state) const
bool mustBufferizeInPlace (Operation *op, OpOperand &opOperand, const BufferizationState &state) const
LogicalResult bufferize (Operation *op, RewriterBase &rewriter, const BufferizationState &state) const
Detailed Description
Bufferization of scf.yield.
Bufferized as part of their enclosing ops, so this is for analysis only.
Definition at line 425 of file SCFInterfaceImpl.cpp.
Member Function Documentation
bufferize()
LogicalResult mlir::linalg::comprehensive_bufferize::scf_ext::YieldOpInterface::bufferize (Operation * op, RewriterBase & rewriter, const BufferizationState & state) const inline
Definition at line 455 of file SCFInterfaceImpl.cpp.
References mlir::linalg::comprehensive_bufferize::scf_ext::registerBufferizableOpInterfaceExternalModels(), and mlir::success().
bufferizesToMemoryRead()
bool mlir::linalg::comprehensive_bufferize::scf_ext::YieldOpInterface::bufferizesToMemoryRead (Operation * op, OpOperand & opOperand, const BufferizationState & state) const inline
Definition at line 428 of file SCFInterfaceImpl.cpp.
bufferizesToMemoryWrite()
bool mlir::linalg::comprehensive_bufferize::scf_ext::YieldOpInterface::bufferizesToMemoryWrite (Operation * op, OpOperand & opOperand, const BufferizationState & state) const inline
Definition at line 433 of file SCFInterfaceImpl.cpp.
getAliasingOpResult()
OpResult mlir::linalg::comprehensive_bufferize::scf_ext::YieldOpInterface::getAliasingOpResult (Operation * op, OpOperand & opOperand, const BufferizationState & state) const inline
Definition at line 438 of file SCFInterfaceImpl.cpp.
References mlir::OpOperand::getOperandNumber(), mlir::Operation::getParentOp(), and mlir::Operation::getResult().
mustBufferizeInPlace()
bool mlir::linalg::comprehensive_bufferize::scf_ext::YieldOpInterface::mustBufferizeInPlace (Operation * op, OpOperand & opOperand, const BufferizationState & state) const inline
Definition at line 447 of file SCFInterfaceImpl.cpp.
The documentation for this struct was generated from the following file:
lib/Dialect/Linalg/ComprehensiveBufferize/SCFInterfaceImpl.cpp