MLIR: mlir::linalg::comprehensive_bufferize::arith_ext::ConstantOpInterface Struct Reference
mlir::linalg::comprehensive_bufferize::arith_ext::ConstantOpInterface Struct Reference
Bufferization of arith.constant. Replace with memref.get_global.
Public Member Functions
LogicalResult bufferize (Operation *op, RewriterBase &rewriter, const BufferizationState &state) const
bool isWritable (Operation *op, Value value, const BufferizationState &state) const
Detailed Description
Bufferization of arith.constant. Replace with memref.get_global.
Definition at line 26 of file ArithInterfaceImpl.cpp.
Member Function Documentation
bufferize()
LogicalResult mlir::linalg::comprehensive_bufferize::arith_ext::ConstantOpInterface::bufferize (Operation * op, RewriterBase & rewriter, const BufferizationState & state) const inline
Definition at line 29 of file ArithInterfaceImpl.cpp.
References mlir::failure(), mlir::bufferization::GlobalCreator::getGlobalFor(), mlir::Operation::getName(), and mlir::success().
isWritable()
bool mlir::linalg::comprehensive_bufferize::arith_ext::ConstantOpInterface::isWritable (Operation * op, Value value, const BufferizationState & state) const inline
Definition at line 52 of file ArithInterfaceImpl.cpp.
References mlir::Value::isa(), and mlir::linalg::comprehensive_bufferize::arith_ext::registerBufferizableOpInterfaceExternalModels().
The documentation for this struct was generated from the following file:
lib/Dialect/Linalg/ComprehensiveBufferize/ArithInterfaceImpl.cpp