MLIR: mlir::linalg::comprehensive_bufferize::std_ext::CallOpInterface Struct Reference
mlir::linalg::comprehensive_bufferize::std_ext::CallOpInterface Struct Reference
Public Member Functions
bool bufferizesToMemoryRead (Operation *op, OpOperand &opOperand, const BufferizationState &state) const
bool bufferizesToMemoryWrite (Operation *op, OpOperand &opOperand, const BufferizationState &state) const
OpResult getAliasingOpResult (Operation *op, OpOperand &opOperand, const BufferizationState &state) const
SmallVector< OpOperand * > getAliasingOpOperand (Operation *op, OpResult opResult, const BufferizationState &state) const
BufferRelation bufferRelation (Operation *op, OpResult opResult, const BufferizationState &state) const
LogicalResult bufferize (Operation *op, RewriterBase &rewriter, const BufferizationState &state) const
In a first approximation, all the function arguments of a FuncOp are marked inplaceable.
Detailed Description
Definition at line 672 of file ModuleBufferization.cpp.
Member Function Documentation
bufferize()
LogicalResult mlir::linalg::comprehensive_bufferize::std_ext::CallOpInterface::bufferize (Operation * op, RewriterBase & rewriter, const BufferizationState & state) const inline
In a first approximation, all the function arguments of a FuncOp are marked inplaceable.
For now, it is the responsibility of the callOp bufferization to allow FuncOp that are inplaceable to write inPlace.
Definition at line 756 of file ModuleBufferization.cpp.
References mlir::OpBuilder::create(), mlir::detail::enumerate(), mlir::failed(), mlir::failure(), mlir::bufferization::BufferizationState::getBuffer(), getBufferizedFunctionType(), getCalledFunction(), mlir::linalg::comprehensive_bufferize::std_ext::getEquivalentFuncArgIdx(), getModuleBufferizationState(), mlir::bufferization::BufferizationState::getOptions(), mlir::Operation::getResult(), mlir::Value::getType(), mlir::Type::isa(), isaTensor(), mlir::bufferization::replaceOpWithBufferizedValues(), mlir::Operation::setAttrs(), and mlir::success().
bufferizesToMemoryRead()
bool mlir::linalg::comprehensive_bufferize::std_ext::CallOpInterface::bufferizesToMemoryRead (Operation * op, OpOperand & opOperand, const BufferizationState & state) const inline
Definition at line 674 of file ModuleBufferization.cpp.
References getCalledFunction(), getFuncOpAnalysisState(), getModuleBufferizationState(), and mlir::OpOperand::getOperandNumber().
bufferizesToMemoryWrite()
bool mlir::linalg::comprehensive_bufferize::std_ext::CallOpInterface::bufferizesToMemoryWrite (Operation * op, OpOperand & opOperand, const BufferizationState & state) const inline
Definition at line 690 of file ModuleBufferization.cpp.
References getCalledFunction(), getFuncOpAnalysisState(), getModuleBufferizationState(), and mlir::OpOperand::getOperandNumber().
bufferRelation()
BufferRelation mlir::linalg::comprehensive_bufferize::std_ext::CallOpInterface::bufferRelation (Operation * op, OpResult opResult, const BufferizationState & state) const inline
Definition at line 748 of file ModuleBufferization.cpp.
getAliasingOpOperand()
SmallVector<OpOperand *> mlir::linalg::comprehensive_bufferize::std_ext::CallOpInterface::getAliasingOpOperand (Operation * op, OpResult opResult, const BufferizationState & state) const inline
Definition at line 728 of file ModuleBufferization.cpp.
References getCalledFunction(), mlir::linalg::comprehensive_bufferize::std_ext::getEquivalentFuncArgIdx(), getModuleBufferizationState(), mlir::Operation::getOpOperand(), and mlir::OpResult::getResultNumber().
getAliasingOpResult()
OpResult mlir::linalg::comprehensive_bufferize::std_ext::CallOpInterface::getAliasingOpResult (Operation * op, OpOperand & opOperand, const BufferizationState & state) const inline
Definition at line 706 of file ModuleBufferization.cpp.
References getCalledFunction(), mlir::linalg::comprehensive_bufferize::std_ext::getEquivalentFuncArgIdx(), getModuleBufferizationState(), and mlir::OpOperand::getOperandNumber().
The documentation for this struct was generated from the following file:
lib/Dialect/Linalg/ComprehensiveBufferize/ModuleBufferization.cpp