MLIR: mlir::linalg::comprehensive_bufferize::vector_ext::TransferWriteOpInterface Struct Reference
mlir::linalg::comprehensive_bufferize::vector_ext::TransferWriteOpInterface Struct Reference
Bufferization of vector.transfer_write.
Public Member Functions
bool bufferizesToMemoryRead (Operation *op, OpOperand &opOperand, const BufferizationState &state) const
bool bufferizesToMemoryWrite (Operation *op, OpOperand &opOperand, const BufferizationState &state) const
OpResult getAliasingOpResult (Operation *op, OpOperand &opOperand, const BufferizationState &state) const
BufferRelation bufferRelation (Operation *op, OpResult opResult, const BufferizationState &state) const
LogicalResult bufferize (Operation *op, RewriterBase &rewriter, const BufferizationState &state) const
Detailed Description
Bufferization of vector.transfer_write.
Replace with a new vector.transfer_write that operates on a memref.
Definition at line 65 of file VectorInterfaceImpl.cpp.
Member Function Documentation
bufferize()
LogicalResult mlir::linalg::comprehensive_bufferize::vector_ext::TransferWriteOpInterface::bufferize (Operation * op, RewriterBase & rewriter, const BufferizationState & state) const inline
Definition at line 94 of file VectorInterfaceImpl.cpp.
References mlir::OpBuilder::create(), mlir::failed(), mlir::failure(), mlir::bufferization::BufferizationState::getBuffer(), mlir::Operation::getOpOperand(), mlir::linalg::comprehensive_bufferize::vector_ext::registerBufferizableOpInterfaceExternalModels(), mlir::bufferization::replaceOpWithBufferizedValues(), and mlir::success().
bufferizesToMemoryRead()
bool mlir::linalg::comprehensive_bufferize::vector_ext::TransferWriteOpInterface::bufferizesToMemoryRead (Operation * op, OpOperand & opOperand, const BufferizationState & state) const inline
Definition at line 68 of file VectorInterfaceImpl.cpp.
References mlir::IROperand< DerivedT, IRValueT >::get(), mlir::Value::getType(), and mlir::Type::isa().
bufferizesToMemoryWrite()
bool mlir::linalg::comprehensive_bufferize::vector_ext::TransferWriteOpInterface::bufferizesToMemoryWrite (Operation * op, OpOperand & opOperand, const BufferizationState & state) const inline
Definition at line 75 of file VectorInterfaceImpl.cpp.
References mlir::IROperand< DerivedT, IRValueT >::get(), mlir::Value::getType(), and mlir::Type::isa().
bufferRelation()
BufferRelation mlir::linalg::comprehensive_bufferize::vector_ext::TransferWriteOpInterface::bufferRelation (Operation * op, OpResult opResult, const BufferizationState & state) const inline
Definition at line 89 of file VectorInterfaceImpl.cpp.
References mlir::bufferization::Equivalent.
getAliasingOpResult()
OpResult mlir::linalg::comprehensive_bufferize::vector_ext::TransferWriteOpInterface::getAliasingOpResult (Operation * op, OpOperand & opOperand, const BufferizationState & state) const inline
Definition at line 82 of file VectorInterfaceImpl.cpp.
References mlir::IROperand< DerivedT, IRValueT >::get(), mlir::Operation::getOpResult(), mlir::Value::getType(), and mlir::Type::isa().
The documentation for this struct was generated from the following file:
lib/Dialect/Linalg/ComprehensiveBufferize/VectorInterfaceImpl.cpp