MLIR: AssertDestinationPassingStyle Struct Reference
AssertDestinationPassingStyle Struct Reference
Assert that IR is in destination-passing style.
Public Member Functions
LogicalResult run (Operation *op, BufferizationState &state, BufferizationAliasInfo &aliasInfo, SmallVector< Operation *> &newOps) override
Public Member Functions inherited from mlir::bufferization::PostAnalysisStep
virtual ~PostAnalysisStep ()=default
virtual LogicalResult run (Operation *op, BufferizationState &state, BufferizationAliasInfo &aliasInfo, SmallVector< Operation *> &newOps)=0
Run the post analysis step.
Detailed Description
Assert that IR is in destination-passing style.
I.e., every value that is returned or yielded from a block is:
aliasing a bbArg of that block or a parent block, or
aliasing an OpResult of a op in a parent block.
Example:
%0 = "some_op" : tensor<?xf32>
%1 = scf.if %c -> (tensor<?xf32>) {
  scf.yield %0 : tensor<?xf32>
} else {
  %t = linalg.init_tensor : tensor<?xf32>
  scf.yield %t : tensor<?xf32>
}
In the above example, the first scf.yield op satifies destination-passing style because the yielded value %0 is defined in the parent block. The second scf.yield op does not satisfy destination-passing style because the yielded value t is defined in the same block as the scf.yield op.
Definition at line 701 of file OneShotAnalysis.cpp.
Member Function Documentation
run()
LogicalResult AssertDestinationPassingStyle::run (Operation * op, BufferizationState & state, BufferizationAliasInfo & aliasInfo, SmallVector< Operation *> & newOps) inline override
Definition at line 702 of file OneShotAnalysis.cpp.
References mlir::WalkResult::advance(), mlir::bufferization::BufferizationAliasInfo::applyOnEquivalenceClass(), mlir::Value::dyn_cast(), mlir::Operation::emitError(), mlir::Value::getDefiningOp(), mlir::Operation::getOpOperands(), mlir::Operation::getParentOp(), mlir::Value::getType(), happensBefore(), mlir::Type::isa(), mlir::isRegionReturnLike(), mlir::success(), and mlir::Operation::walk().
The documentation for this struct was generated from the following file:
lib/Dialect/Bufferization/Transforms/OneShotAnalysis.cpp