MLIR: mlir::linalg::comprehensive_bufferize::vector_ext::TransferReadOpInterface Struct Reference
mlir::linalg::comprehensive_bufferize::vector_ext::TransferReadOpInterface Struct Reference
Bufferization of vector.transfer_read.
Public Member Functions
bool bufferizesToMemoryRead (Operation *op, OpOperand &opOperand, const BufferizationState &state) const
bool bufferizesToMemoryWrite (Operation *op, OpOperand &opOperand, const BufferizationState &state) const
OpResult getAliasingOpResult (Operation *op, OpOperand &opOperand, const BufferizationState &state) const
LogicalResult bufferize (Operation *op, RewriterBase &rewriter, const BufferizationState &state) const
Detailed Description
Bufferization of vector.transfer_read.
Replaced with a new vector.transfer_read that operates on a memref.
Definition at line 24 of file VectorInterfaceImpl.cpp.
Member Function Documentation
bufferize()
LogicalResult mlir::linalg::comprehensive_bufferize::vector_ext::TransferReadOpInterface::bufferize (Operation * op, RewriterBase & rewriter, const BufferizationState & state) const inline
Definition at line 46 of file VectorInterfaceImpl.cpp.
References mlir::bufferization::BufferizationState::getBuffer(), and mlir::success().
bufferizesToMemoryRead()
bool mlir::linalg::comprehensive_bufferize::vector_ext::TransferReadOpInterface::bufferizesToMemoryRead (Operation * op, OpOperand & opOperand, const BufferizationState & state) const inline
Definition at line 27 of file VectorInterfaceImpl.cpp.
References mlir::IROperand< DerivedT, IRValueT >::get(), mlir::Value::getType(), and mlir::Type::isa().
bufferizesToMemoryWrite()
bool mlir::linalg::comprehensive_bufferize::vector_ext::TransferReadOpInterface::bufferizesToMemoryWrite (Operation * op, OpOperand & opOperand, const BufferizationState & state) const inline
Definition at line 34 of file VectorInterfaceImpl.cpp.
References mlir::IROperand< DerivedT, IRValueT >::get(), mlir::Value::getType(), and mlir::Type::isa().
getAliasingOpResult()
OpResult mlir::linalg::comprehensive_bufferize::vector_ext::TransferReadOpInterface::getAliasingOpResult (Operation * op, OpOperand & opOperand, const BufferizationState & state) const inline
Definition at line 41 of file VectorInterfaceImpl.cpp.
The documentation for this struct was generated from the following file:
lib/Dialect/Linalg/ComprehensiveBufferize/VectorInterfaceImpl.cpp