MLIR: lib/Dialect/Tensor/IR/TensorOps.cpp File Reference
TensorOps.cpp File Reference
#include "mlir/Dialect/Arithmetic/IR/Arithmetic.h"
#include "mlir/Dialect/StandardOps/Utils/Utils.h"
#include "mlir/Dialect/Tensor/IR/Tensor.h"
#include "mlir/Dialect/Utils/ReshapeOpsUtils.h"
#include "mlir/Dialect/Utils/StaticValueUtils.h"
#include "mlir/IR/BlockAndValueMapping.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinAttributeInterfaces.h"
#include "mlir/IR/Matchers.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/IR/TypeUtilities.h"
#include "llvm/ADT/STLExtras.h"
#include "mlir/Dialect/Tensor/IR/TensorOps.cpp.inc"
Classes
struct SliceReturnTypeCanonicalizer
Return the canonical type of the result of an extract_slice op.
struct SliceCanonicalizer
A canonicalizer wrapper to replace ExtractSliceOps.
Macros
#define GET_OP_CLASSES
Functions
static TensorType joinShapes (TensorType one, TensorType two)
Compute a TensorType that has the joined shape knowledge of the two given TensorTypes.
static LogicalResult verify (DimOp op)
static LogicalResult verify (ExtractOp op)
static LogicalResult verify (InsertOp op)
static LogicalResult verify (GenerateOp op)
static int64_t getNumElements (ShapedType type)
static LogicalResult verify (ReshapeOp op)
static void print (OpAsmPrinter &p, ExpandShapeOp op)
static void print (OpAsmPrinter &p, CollapseShapeOp op)
static RankedTensorType computeTensorReshapeCollapsedType (RankedTensorType type, ArrayRef< AffineMap > reassociation)
Compute the RankedTensorType obtained by applying reassociation to type.
template<typename TensorReshapeOp , bool isExpansion = std::is_same< TensorReshapeOp, ExpandShapeOp>::value>
static LogicalResult verifyTensorReshapeOp (TensorReshapeOp op, RankedTensorType expandedType, RankedTensorType collapsedType)
static LogicalResult verify (ExpandShapeOp op)
static LogicalResult verify (CollapseShapeOp op)
template<typename OpTy >
static LogicalResult produceSliceErrorMsg (SliceVerificationResult result, OpTy op, Type expectedType)
static LogicalResult verify (ExtractSliceOp op)
Verifier for ExtractSliceOp.
static RankedTensorType getCanonicalSliceResultType (unsigned resultRank, RankedTensorType sourceType, ArrayRef< OpFoldResult > mixedOffsets, ArrayRef< OpFoldResult > mixedSizes, ArrayRef< OpFoldResult > mixedStrides)
Infer the canonical type of the result of an extract_slice op.
static LogicalResult foldIdentityOffsetSizeAndStrideOpInterface (OffsetSizeAndStrideOpInterface op, ShapedType shapedType)
static Value foldExtractAfterInsertSlice (ExtractSliceOp extractOp)
If we have an ExtractSliceOp consuming an InsertSliceOp with the same slice, we can return the InsertSliceOp's source directly.
static LogicalResult verify (InsertSliceOp op)
Verifier for InsertSliceOp.
static LogicalResult foldInsertAfterInsertSlice (InsertSliceOp insertOp)
If we have two consecutive InsertSliceOp writing to the same slice, we can mutate the second InsertSliceOp's destination to the first one's.
void printInferType (OpAsmPrinter &printer, Operation *op, Value optOperand, Type typeToInfer, Type typeToInferFrom)
ParseResult parseInferType (OpAsmParser &parser, Optional< OpAsmParser::OperandType > optOperand, Type &typeToInfer, Type typeToInferFrom)
static LogicalResult verify (PadOp op)
Macro Definition Documentation
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 1807 of file TensorOps.cpp.
Function Documentation
computeTensorReshapeCollapsedType()
static RankedTensorType computeTensorReshapeCollapsedType (RankedTensorType type, ArrayRef< AffineMap > reassociation) static
Compute the RankedTensorType obtained by applying reassociation to type.
Definition at line 745 of file TensorOps.cpp.
References mlir::OperationState::addAttribute(), mlir::Type::cast(), mlir::convertReassociationIndicesToExprs(), mlir::Builder::getContext(), mlir::getReassociationAttrName(), mlir::getReassociationIndicesAttribute(), mlir::getSymbolLessAffineMaps(), mlir::Value::getType(), mlir::isReassociationValid(), and value.
Referenced by verifyTensorReshapeOp().
foldExtractAfterInsertSlice()
static Value foldExtractAfterInsertSlice (ExtractSliceOp extractOp) static
If we have an ExtractSliceOp consuming an InsertSliceOp with the same slice, we can return the InsertSliceOp's source directly.
Definition at line 1228 of file TensorOps.cpp.
References foldIdentityOffsetSizeAndStrideOpInterface(), mlir::Value::getDefiningOp(), and mlir::succeeded().
foldIdentityOffsetSizeAndStrideOpInterface()
static LogicalResult foldIdentityOffsetSizeAndStrideOpInterface (OffsetSizeAndStrideOpInterface op, ShapedType shapedType) static
Definition at line 1206 of file TensorOps.cpp.
References mlir::failure(), mlir::getConstantIntValue(), and mlir::success().
Referenced by foldExtractAfterInsertSlice(), and foldInsertAfterInsertSlice().
foldInsertAfterInsertSlice()
static LogicalResult foldInsertAfterInsertSlice (InsertSliceOp insertOp) static
If we have two consecutive InsertSliceOp writing to the same slice, we can mutate the second InsertSliceOp's destination to the first one's.
Example:
%0 = tensor.insert_slice %slice0 into %input[0, 0] [64, 64] [1, 1]
%1 = tensor.insert_slice %slice1 into %0[0, 0] [64, 64] [1, 1]
folds into:
%1 = tensor.insert_slice %slice1 into %input[0, 0] [64, 64] [1, 1]
Definition at line 1334 of file TensorOps.cpp.
References mlir::RewritePatternSet::add(), mlir::tensor::canFoldIntoConsumerOp(), mlir::canonicalizeSubViewPart(), mlir::OpBuilder::create(), mlir::OpBuilder::createOrFold(), mlir::failure(), foldIdentityOffsetSizeAndStrideOpInterface(), mlir::getConstantIntValue(), mlir::Value::getType(), mlir::matchConstantIndex(), mlir::matchPattern(), mlir::tensor::preservesStaticInformation(), mlir::RewriterBase::replaceOp(), mlir::RewriterBase::replaceOpWithNewOp(), mlir::succeeded(), and mlir::success().
getCanonicalSliceResultType()
static RankedTensorType getCanonicalSliceResultType (unsigned resultRank, RankedTensorType sourceType, ArrayRef< OpFoldResult > mixedOffsets, ArrayRef< OpFoldResult > mixedSizes, ArrayRef< OpFoldResult > mixedStrides) static
Infer the canonical type of the result of an extract_slice op.
Returns a type with rank resultRank that is either the rank of the rank-reduced type, or the non-rank-reduced type.
Definition at line 1065 of file TensorOps.cpp.
References mlir::tensor::canFoldIntoConsumerOp(), mlir::Location::cast(), mlir::OpBuilder::create(), mlir::detail::enumerate(), mlir::failure(), mlir::getConstantIntValue(), mlir::getMixedSizes(), mlir::matchConstantIndex(), mlir::matchPattern(), mlir::RewriterBase::replaceOpWithNewOp(), and mlir::success().
Referenced by SliceReturnTypeCanonicalizer::operator()().
getNumElements()
static int64_t getNumElements (ShapedType type) static
Definition at line 678 of file TensorOps.cpp.
Referenced by mlir::DenseElementsAttr::complex_float_value_end(), mlir::DenseElementsAttr::complex_value_end(), convertStructType(), mlir::python::PyAffineExpr::createFromCapsule(), mlir::python::PyAffineMap::createFromCapsule(), mlir::Sliceable< Derived, ElementTy >::dunderGetItem(), mlir::DenseIntElementsAttr::end(), mlir::spirv::CompositeType::getCapabilities(), mlir::DenseElementsAttr::getComplexFloatValues(), mlir::DenseElementsAttr::getComplexIntValues(), mlir::spirv::StructType::getElementType(), mlir::spirv::StructType::getElementTypes(), getFirstIntValue(), mlir::spirv::StructType::getMemberDecorations(), mlir::spirv::StructType::getMemberOffset(), getPushConstantVariable(), mlir::spirv::ArrayType::getSizeInBytes(), mlir::DenseElementsAttr::getValues(), isDefinedByCallTo(), mlir::ShapeAdaptor::isDynamicDim(), mlirElementsAttrGetNumElements(), mlir::spirv::StructType::MemberDecorationInfo::operator<(), mlir::AffineDmaStartOp::print(), mlir::AffineDmaWaitOp::print(), mlir::DenseElementsAttr::raw_int_end(), mlir::DenseElementsAttr::size(), mlir::DenseElementsAttr::value_end(), verify(), and mlir::python::PySymbolTable::walkSymbolTables().
joinShapes()
static TensorType joinShapes (TensorType one, TensorType two) static
Compute a TensorType that has the joined shape knowledge of the two given TensorTypes.
The element types need to match.
Definition at line 132 of file TensorOps.cpp.
References mlir::RewritePatternSet::add(), mlir::Type::cast(), mlir::OpBuilder::create(), mlir::failure(), mlir::TensorType::getElementType(), mlir::TensorType::hasRank(), mlir::OperationState::location, mlir::RewriterBase::replaceOpWithNewOp(), and mlir::success().
parseInferType()
ParseResult parseInferType (OpAsmParser & parser, Optional< OpAsmParser::OperandType > optOperand, Type & typeToInfer, Type typeToInferFrom)
Definition at line 1560 of file TensorOps.cpp.
References mlir::success().
print() [1/2]
static void print (OpAsmPrinter & p, ExpandShapeOp op) static
Definition at line 735 of file TensorOps.cpp.
print() [2/2]
static void print (OpAsmPrinter & p, CollapseShapeOp op) static
Definition at line 739 of file TensorOps.cpp.
printInferType()
void printInferType (OpAsmPrinter & printer, Operation * op, Value optOperand, Type typeToInfer, Type typeToInferFrom)
Definition at line 1557 of file TensorOps.cpp.
produceSliceErrorMsg()
template<typename OpTy > static LogicalResult produceSliceErrorMsg (SliceVerificationResult result, OpTy op, Type expectedType) static
Definition at line 1030 of file TensorOps.cpp.
References mlir::Type::cast(), mlir::ElemTypeMismatch, mlir::RankTooLarge, mlir::SizeMismatch, mlir::success(), and mlir::Success.
Referenced by verify().
verify() [1/10]
static LogicalResult verify (DimOp op) static
Definition at line 227 of file TensorOps.cpp.
References mlir::RewritePatternSet::add(), mlir::Type::cast(), mlir::Type::dyn_cast(), mlir::failure(), mlir::tensor::foldTensorCast(), mlir::Value::getDefiningOp(), mlir::Builder::getIndexAttr(), mlir::Operation::getResult(), mlir::Value::getType(), mlir::Type::isa(), mlir::RewriterBase::replaceOpWithNewOp(), mlir::succeeded(), and mlir::success().
verify() [2/10]
static LogicalResult verify (ExtractOp op) static
Definition at line 327 of file TensorOps.cpp.
References mlir::RewritePatternSet::add(), mlir::OperationState::addOperands(), mlir::OperationState::addTypes(), mlir::OpBuilder::create(), mlir::Attribute::dyn_cast(), mlir::failure(), mlir::DenseElementsAttr::get(), mlir::getElementTypeOrSelf(), mlir::ValueRange::getType(), mlir::m_ConstantInt(), mlir::matchPattern(), mlir::RewriterBase::replaceOp(), mlir::RewriterBase::replaceOpWithNewOp(), and mlir::success().
verify() [3/10]
static LogicalResult verify (InsertOp op) static
Definition at line 479 of file TensorOps.cpp.
References mlir::Attribute::dyn_cast(), and mlir::success().
verify() [4/10]
static LogicalResult verify (GenerateOp op) static
Definition at line 501 of file TensorOps.cpp.
References mlir::RewritePatternSet::add(), mlir::Type::cast(), mlir::OpBuilder::clone(), mlir::OpBuilder::create(), mlir::OpBuilder::createBlock(), mlir::Type::dyn_cast(), mlir::Region::end(), mlir::failure(), mlir::Block::getArguments(), mlir::Builder::getIndexType(), mlir::Block::getTerminator(), mlir::RewriterBase::inlineRegionBefore(), mlir::OperationState::location, mlir::BlockAndValueMapping::lookupOrDefault(), mlir::m_ConstantInt(), mlir::BlockAndValueMapping::map(), mlir::matchPattern(), mlir::OperationState::regions, mlir::RewriterBase::replaceOp(), mlir::RewriterBase::replaceOpWithNewOp(), mlir::success(), mlir::Block::without_terminator(), and mlir::wouldOpBeTriviallyDead().
verify() [5/10]
static LogicalResult verify (ReshapeOp op) static
Definition at line 685 of file TensorOps.cpp.
References mlir::Type::cast(), mlir::convertReassociationIndicesToExprs(), mlir::Type::dyn_cast(), mlir::TensorType::getElementType(), getNumElements(), mlir::getSymbolLessAffineMaps(), and mlir::success().
verify() [6/10]
static LogicalResult verify (ExpandShapeOp op) static
Definition at line 813 of file TensorOps.cpp.
References verifyTensorReshapeOp().
verify() [7/10]
static LogicalResult verify (CollapseShapeOp op) static
Definition at line 817 of file TensorOps.cpp.
References mlir::RewritePatternSet::add(), mlir::OperationState::addAttributes(), mlir::Type::cast(), mlir::dispatchIndexOpFoldResults(), mlir::failure(), mlir::DenseElementsAttr::getFromRawBuffer(), mlir::Builder::getI64ArrayAttr(), mlir::getPositionsOfShapeOne(), mlir::DenseElementsAttr::getRawData(), mlir::Value::getType(), mlir::DenseElementsAttr::isSplat(), mlir::m_Constant(), mlir::matchPattern(), mlir::RewriterBase::replaceOpWithNewOp(), mlir::success(), and verifyTensorReshapeOp().
verify() [8/10]
static LogicalResult verify (ExtractSliceOp op) static
Verifier for ExtractSliceOp.
Definition at line 1051 of file TensorOps.cpp.
References mlir::isRankReducedType(), and produceSliceErrorMsg().
verify() [9/10]
static LogicalResult verify (InsertSliceOp op) static
Verifier for InsertSliceOp.
Definition at line 1307 of file TensorOps.cpp.
References mlir::extractFromI64ArrayAttr(), mlir::isRankReducedType(), and produceSliceErrorMsg().
verify() [10/10]
static LogicalResult verify (PadOp op) static
Definition at line 1568 of file TensorOps.cpp.
References mlir::RewritePatternSet::add(), mlir::OperationState::addAttributes(), mlir::tensor::canFoldIntoConsumerOp(), mlir::Type::cast(), mlir::OpBuilder::create(), mlir::dispatchIndexOpFoldResults(), mlir::Operation::emitError(), mlir::detail::enumerate(), mlir::extractFromI64ArrayAttr(), mlir::failure(), mlir::Block::front(), mlir::Block::getArgumentTypes(), getElementType(), mlir::Builder::getI64ArrayAttr(), mlir::Block::getNumArguments(), mlir::Value::getParentBlock(), mlir::Block::getTerminator(), mlir::Value::getType(), mlir::Builder::getUnitAttr(), mlir::Type::isa(), mlir::m_Constant(), mlir::matchPattern(), mlir::tensor::preservesStaticInformation(), mlir::RewriterBase::replaceOp(), mlir::RewriterBase::replaceOpWithNewOp(), mlir::success(), and mlir::RewriterBase::updateRootInPlace().
verifyTensorReshapeOp()
template<typename TensorReshapeOp , bool isExpansion = std::is_same< TensorReshapeOp, ExpandShapeOp>::value> static LogicalResult verifyTensorReshapeOp (TensorReshapeOp op, RankedTensorType expandedType, RankedTensorType collapsedType) static
Definition at line 797 of file TensorOps.cpp.
References computeTensorReshapeCollapsedType(), mlir::failed(), mlir::failure(), mlir::success(), and mlir::verifyReshapeLikeTypes().
Referenced by verify().