MLIR: lib/Dialect/Linalg/Transforms/Tiling.cpp File Reference
Tiling.cpp File Reference
#include <utility>
#include "PassDetail.h"
#include "mlir/Dialect/Linalg/IR/Linalg.h"
#include "mlir/Dialect/Linalg/Passes.h"
#include "mlir/Dialect/Linalg/Transforms/Transforms.h"
#include "mlir/Dialect/Linalg/Utils/Utils.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/SCF/Transforms.h"
#include "mlir/Dialect/Tensor/IR/Tensor.h"
#include "mlir/IR/AffineExpr.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/Transforms/FoldUtils.h"
#include "mlir/Transforms/GreedyPatternRewriteDriver.h"
#include "llvm/Support/CommandLine.h"
#include "mlir/Dialect/Linalg/IR/LinalgStructuredOps.cpp.inc"
Macros
#define DEBUG_TYPE "linalg-tiling"
#define GET_OP_LIST
#define GET_OP_LIST
Typedefs
using LoopIndexToRangeIndexMap = DenseMap< int, int >
Functions
static bool isZero (Value v)
static std::tuple< SmallVector< Range, 4 >, LoopIndexToRangeIndexMap > makeTiledLoopRanges (RewriterBase &b, Location loc, AffineMap map, ValueRange allShapeSizes, ValueRange allTileSizes)
static void transformIndexOps (RewriterBase &b, LinalgOp op, SmallVectorImpl< Value > &ivs, const LoopIndexToRangeIndexMap &loopIndexToRangeIndex)
static Value insertSliceIntoTensor (RewriterBase &b, Location loc, tensor::ExtractSliceOp sliceOp, Value source, Value dest)
template<typename LoopTy >
static FailureOr< TiledLinalgOp > tileLinalgOpImpl (RewriterBase &b, LinalgOp op, ValueRange tileSizes, const LinalgTilingOptions &options)
template<typename LoopTy >
static FailureOr< TiledLinalgOp > tileLinalgOpImpl (RewriterBase &b, LinalgOp op, const LinalgTilingOptions &options)
static LogicalResult tilePadOp (RewriterBase &builder, tensor::PadOp op, tensor::PadOp &newPadOp, LoopNest &loopNest, const LinalgTilingOptions &options)
Generate a loop nest around a given tensor::PadOp (for tiling).
static void insertTilingPatterns (RewritePatternSet &patterns, const LinalgTilingOptions &options)
Populate the given list with patterns that apply Linalg tiling.
static void applyExtractSliceOfPadTensorSwapPattern (FuncOp funcOp)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "linalg-tiling"
Definition at line 34 of file Tiling.cpp.
GET_OP_LIST [1/2]
#define GET_OP_LIST
GET_OP_LIST [2/2]
#define GET_OP_LIST
Typedef Documentation
LoopIndexToRangeIndexMap
using LoopIndexToRangeIndexMap = DenseMap<int, int>
Definition at line 42 of file Tiling.cpp.
Function Documentation
applyExtractSliceOfPadTensorSwapPattern()
static void applyExtractSliceOfPadTensorSwapPattern (FuncOp funcOp) static
Definition at line 504 of file Tiling.cpp.
References mlir::RewritePatternSet::add(), mlir::linalg::AffineLoops, mlir::applyPatternsAndFoldGreedily(), mlir::RewritePatternSet::getContext(), mlir::linalg::getLinalgTilingCanonicalizationPatterns(), insertTilingPatterns(), mlir::linalg::LinalgTransforms::kLinalgTransformMarker, mlir::linalg::Loops, options, mlir::linalg::ParallelLoops, mlir::scf::populateSCFForLoopCanonicalizationPatterns(), mlir::linalg::LinalgTilingOptions::setDistributionTypes(), mlir::linalg::LinalgTilingOptions::setLoopType(), mlir::linalg::LinalgTilingOptions::setTileSizes(), and mlir::linalg::TiledLoops.
insertSliceIntoTensor()
static Value insertSliceIntoTensor (RewriterBase & b, Location loc, tensor::ExtractSliceOp sliceOp, Value source, Value dest) static
Definition at line 147 of file Tiling.cpp.
References mlir::OpBuilder::create().
Referenced by tilePadOp().
insertTilingPatterns()
static void insertTilingPatterns (RewritePatternSet & patterns, const LinalgTilingOptions & options) static
Populate the given list with patterns that apply Linalg tiling.
Definition at line 486 of file Tiling.cpp.
References mlir::RewritePatternSet::add(), mlir::RewritePatternSet::getContext(), and options.
Referenced by applyExtractSliceOfPadTensorSwapPattern().
isZero()
static bool isZero (Value v) static
Definition at line 36 of file Tiling.cpp.
References mlir::Value::getDefiningOp().
Referenced by findAncestorOpInRegion(), makeTiledLoopRanges(), ReduceFolder(), tileLinalgOpImpl(), and tilePadOp().
makeTiledLoopRanges()
static std::tuple<SmallVector<Range, 4>, LoopIndexToRangeIndexMap> makeTiledLoopRanges (RewriterBase & b, Location loc, AffineMap map, ValueRange allShapeSizes, ValueRange allTileSizes) static
Definition at line 54 of file Tiling.cpp.
References mlir::applyMapToValues(), mlir::AffineMap::getNumResults(), and isZero().
Referenced by tileLinalgOpImpl().
tileLinalgOpImpl() [1/2]
template<typename LoopTy > static FailureOr<TiledLinalgOp> tileLinalgOpImpl (RewriterBase & b, LinalgOp op, ValueRange tileSizes, const LinalgTilingOptions & options) static
Definition at line 158 of file Tiling.cpp.
References mlir::linalg::applyPermutationToVector(), mlir::OpBuilder::clone(), mlir::detail::enumerate(), mlir::failure(), mlir::Builder::getContext(), mlir::AffineMap::getMultiDimIdentityMap(), mlir::AffineMap::getPermutationMap(), mlir::linalg::LinalgTilingOptions::interchangeVector, mlir::inversePermutation(), isZero(), makeTiledLoopRanges(), mlir::linalg::TiledLinalgOp::op, and mlir::linalg::TiledLinalgOp::tensorResults.
tileLinalgOpImpl() [2/2]
template<typename LoopTy > static FailureOr<TiledLinalgOp> tileLinalgOpImpl (RewriterBase & b, LinalgOp op, const LinalgTilingOptions & options) static
Definition at line 304 of file Tiling.cpp.
References mlir::OpBuilder::create(), mlir::failure(), options, mlir::OpBuilder::setInsertionPoint(), and mlir::linalg::LinalgTilingOptions::tileSizeComputationFunction.
tilePadOp()
static LogicalResult tilePadOp (RewriterBase & builder, tensor::PadOp op, tensor::PadOp & newPadOp, LoopNest & loopNest, const LinalgTilingOptions & options) static
Generate a loop nest around a given tensor::PadOp (for tiling).
newPadOp and loopNest are output parameters that return the new (tiled) tensor::PadOp and the loop nest.
Definition at line 344 of file Tiling.cpp.
References mlir::scf::buildLoopNest(), mlir::OpBuilder::clone(), mlir::linalg::computeTileOffsets(), mlir::linalg::computeTileSizes(), mlir::OpBuilder::create(), mlir::failed(), mlir::failure(), mlir::Builder::getContext(), mlir::RewritePatternSet::getContext(), mlir::Value::getDefiningOp(), mlir::AffineMap::getMultiDimIdentityMap(), mlir::scf::LoopNest::getResults(), mlir::Builder::getUnitAttr(), insertSliceIntoTensor(), isZero(), mlir::linalg::LinalgTransforms::kLinalgTransformMarker, mlir::linalg::makeTiledShape(), options, mlir::RewriterBase::replaceOp(), mlir::OpBuilder::setInsertionPoint(), mlir::success(), and mlir::linalg::LinalgTilingOptions::tileSizeComputationFunction.
transformIndexOps()
static void transformIndexOps (RewriterBase & b, LinalgOp op, SmallVectorImpl< Value > & ivs, const LoopIndexToRangeIndexMap & loopIndexToRangeIndex) static
Definition at line 132 of file Tiling.cpp.
References mlir::linalg::addTileLoopIvsToIndexOpResults(), and mlir::detail::enumerate().